### ISSUE TITLE
retopology of the panels

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#10]
3D08 - retopology of the panels.

**Comment by Juanvvc** [comment]
And this issue means...

**Comment by gilbertohasnofb** [comment]
Don't ask me, I never understood it either. I believe this was opened by thevirtualfer.

**Comment by gilbertohasnofb** [comment]
Can we close this?

**Comment by Juanvvc** [comment]
Sure
