### ISSUE TITLE
Electric gauges should not move at the speed of light when powered on

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#101]
Electric gauges (fuel quantity etc) now correctly need power to indicate anything.
However, they should not just jump to the indicated value at the speed of light when the main bus is powered :-)

In reality the needles have a slight lag, maybe use an ease-out motion over maybe half second or second duration and it should look more close to the real thing. This could be the same for all electric gauges.

**Comment by gilbertohasnofb** [comment]
> at the speed of light

:)

**Comment by onox** [comment]
You could use a `<filter>` of type `noise-spike` for this using a `<max-rate-of-change>` element.

**Comment by gilbertohasnofb** [comment]
@onox would you be able to implement this yourself? I believe @tigert is not programming anything at all on this project, and nor am I :(

**Comment by Juanvvc** [comment]
Fixed. I didn't use <filter> because I couldn't find any documentation about that tag outside the autopilot configuration. I used the interpolate() Nasal function in electrical.nas

**Comment by gilbertohasnofb** [comment]
@Juanvvc thanks!

**Comment by onox** [comment]
@Juanvvc You can find the documentation on the [wiki](http://wiki.flightgear.org/Autopilot_configuration_reference). However, I think your choice to use `interpolate()` is better here, 12 XML elements would be too verbose in my opinion.
