### ISSUE TITLE
remove taxi light switch?

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#104]
Apparently our c172p does not have a taxi light (at least I can't see it), and this is often the case with real world 172's: http://s21.postimg.org/m340dtzw7/switches.jpg

So maybe should we remove taxi light switch and create a little 3d rectangle where it should be.

**Comment by Juanvvc** [comment]
Yes, the taxi light is uncommon on a C172, and yes, it is implemented. But not in ALS. According to the XML (but I have not checked yet) the taxi light is only visible in Rembrandt.

**Comment by gilbertohasnofb** [comment]
I see, so in that case should we keep it as it is and close this issue, or should we reconsider having the taxi light?

**Comment by wlbragg** [comment]
If some are really retrofit with them, I'm for keeping it and maybe turning it into ALS light.

**Comment by onox** [comment]
Is it possible to have multiple ALS lights? Because the ALS light is already used for the landing light. Does somebody have a photo showing the difference in lighting between taxi and landing light?

**Comment by zlsa** [comment]
onox, if you're using only one ALS light for the landing light, you can
easily use the second for the taxi light. Remember though that you can't
control the vertical position of the light at all.

**Comment by gilbertohasnofb** [comment]
Since we implemented the taxi lights both in Rembrandt and ALS, I think we can clsoe this issue.
