### ISSUE TITLE
Horizontal and vertical stabilizers too thick

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#106]
Horizontal stabilizer is too thick. Compare this real life photograph (and note how thinner the horizontal stabilizer is when compared to the wings)...: http://www.tripleraffordableaircraft.com/img/cessna-172-four.png

...to these screenshots:
http://s9.postimg.org/ji3k4bp2n/fgfs_screen_003.png
http://s22.postimg.org/b86t2ca75/fgfs_screen_002.png

**Comment by gilbertohasnofb** [comment]
The same is true about the vertical stabilizer, which also seem to be very thick.

**Comment by Juanvvc** [comment]
I have fixed this and #7, but I'm afraid it may involve moving a bit the shadow of the stabilizers in all liveries. Is this going to be a problem?

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/684228/7356330/a72316e2-ed27-11e4-8b28-66e4ce6efced.png)

**Comment by gilbertohasnofb** [comment]
@Juanvvc Juan, this looks great! It will affect all textures though, but I can fix them one by one, no problems at all! Please go ahead and commit it.

**Comment by gilbertohasnofb** [comment]
@Juanvvc just one more thing: it's difficult to judge the rudder from the picture above, but it seems to me that its back is still completely straight, while all 172P and similar models seem to have a little surface in the very bottom: http://s3.postimg.org/oy7ao6x6b/image.png

Maybe this picture illustrates it better, see how the light blue part in the bottom of the rudder has a different angle than the white rudder: http://img.planespotters.net/photo/578000/original/JA4173-Cessna-172_PlanespottersNet_578595.jpg

**Comment by Juanvvc** [comment]
Yes, it is the fixed rudder trim tab: http://upload.wikimedia.org/wikipedia/commons/8/86/Cessna_172_trim_tab.jpg

It is installed on all C172 I've seen, but I'm not sure if it is optional. It is slightly bended to one side because it is a trim tab. I can't remember the side, but according to the all mighty internet it is bended to the port ("left").

**Comment by gilbertohasnofb** [comment]
Well, you could then bent it slightly to the left, but anyway I think that the bent will hardly be noticeable from most angles, the important part is the presence of this element since it gives this very characteristic shape for the 172 rudder surface.

**Comment by Juanvvc** [comment]
I believe I have fixed this and #7, including the rudder trim tab and many holes in the area. Please, check if it is ok!

**Comment by gilbertohasnofb** [comment]
It's much better than before! But two comments:

- the sides of the horizontal stabilizer are now not texturized, just plain black.
- the lines of the rudder seem a little bit off to me. Here is the side view of a 172:
http://cdn-www.airliners.net/aviation-photos/middle/8/1/7/0160718.jpg
Here is what I'd make differently: http://s16.postimg.org/klhypxjib/fgfs_screen_001.png

What do you think?

**Comment by Juanvvc** [comment]
Yes, I noticed the black surfaces. In my pc, they also appeared in the
previous version of the model. Since none complained, I assumed it was some
issue with my drivers.

The surfaces are textured. They are only black if a shader is used on them.
Move the shaders to "low quality" and textures appear again. I'll look into
this.

**Comment by gilbertohasnofb** [comment]
@Juanvvc It looks fantastic now, thanks for the remodelling! I will adjust all the textures to fit it now. As for the shader, indeed having a low setting for Model solves the black sides of the horizontal stabilizer, but I guess we should look what is causing this because the plane look much better with the Model shader at high. I created the issue https://github.com/Juanvvc/c172p-detailed/issues/135 for this.
