### ISSUE TITLE
Livery registration bug in default livery

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#107]
![blinking](https://cloud.githubusercontent.com/assets/11069680/6841052/f9d7a578-d351-11e4-8353-07dd769cafd4.jpg)
User supplied immarticulation is incorrect and some letters/numbers blink.

**Comment by gilbertohasnofb** [comment]
See https://github.com/Juanvvc/c172p-detailed/issues/199 for more screenshots. Also, this bug is not only present in the fuselage but also in the callsign text in the panel.

**Comment by wkitty42** [comment]
where would one start to try to find this problem and fix it?

**Comment by onox** [comment]
Is this happening with other liveries as well?

**Comment by wkitty42** [comment]
i'm only aware of the default (plain white) craft having the callsign being shown on the exterior and on the pilots console... the passenger side console has the callsign also but it is not flickering or showing the wrong letters like the external or pilot's side...

**Comment by wkitty42** [comment]
no one can point me in the direction to start trying to trace this down??

**Comment by wlbragg** [comment]
wkitty, start at c172p/Nasal/immat.nas

**Comment by Juanvvc** [comment]
Please, check pull request #244
