### ISSUE TITLE
Amphibious version is very hard to taxi

### ISSUE THREAD

**Issue by tonghuix** [Juanvvc/c172p-detailed#1074]
Due to no nose gear, so the turning is only using difference break. and due to left turning tendecy, the plane is very hard to maintain in a line. and very hard to turning on ground.

**Comment by wlbragg** [comment]
This issue is again being reported. I passed on the information about using the differential braking at the start. But I am wondering if some kind of drag adjustments on the wheels themselves would help. I don't understand why this type of gear behaves do differently from the regular tricycle gear?

**Comment by gilbertohasnofb** [comment]
> I don't understand why this type of gear behaves do differently from the regular tricycle gear?

That's because the amphibious gears do not rotate at all when you press the rudder pedals, unlike the main gear of the tricycle version which does rotate. So in order to move left or right in the ground you *must* use differential brakes, there is no other way.

**Comment by legoboyvdlp** [comment]
> Scotia Seaplanes is operated from Prestwick Flight Centre in Ayrshire, on the west coast of Scotland. Their Cessna 172 is a 1969 FR172F Reims Rocket Floatplane, adapted by substituting Wipline 2350-A floats for the EDO 2440b ‘straight floats’ fitted by the factory (the number is the weight each float displaces in pounds). Each float has a castoring front wheel and a mainwheel behind the aircraft’s C of G.

We could solve this by adding a castering wheel 

I'll need to see if the EDO 2440b floats can steer.

**Comment by legoboyvdlp** [comment]
Notice:

> Steering with four wheels and differential brakes is no problem at all and the aircraft has a considerably tighter turning circle than a standard C172.

**Comment by gilbertohasnofb** [comment]
> We could solve this by adding a castering wheel

Frankly, I don't see the necessity. Our aircraft behaves exactly like most amphibious ones out there. If we implement an obscure modification we will be teaching our users a behaviour that is far from being common. From what I know, amphibious require differential braking and that's it. 

Do our tutorials teach about this? Else we could have a new amphibious taxiing tutorial. And then it would be the user's problem if they don't really bother doing the tutorials or reading about how to fly the aircraft. Our task is to simulate the real thing.

**Comment by dany93** [comment]
@legoboyvdlp wrote
> We could solve this by adding a castering wheel

Both front wheels are (swivel) castering wheels.

**Comment by dany93** [comment]
Steering the aircraft on the ground can be made by:
- differential braking,
- aerial rudder.

At 0 or very low airspeed, the aerial rudder is not sufficient. The propwash effect helps (more at high propeller RPM) but it is not enough.
Which means that at 0 or very low airspeed, the differential braking is the only way.

On the water, after a short while (still at low airspeed, after only a small rotation leftwards), the propwash and the airspeed effects on the aerial rudder become sufficient.

**Comment by wlbragg** [comment]
>Our aircraft behaves exactly like most amphibious ones out there. 
...
Our task is to simulate the real thing.

If the fist line is a true statement, and it appears we do have evidence of this from real pilots, then I agree with the second line whole heartily.


>Do our tutorials teach about this? Else we could have a new amphibious taxiing tutorial. 

That is a good idea!


> We could solve this by adding a castering wheel
>>Both front wheels are (swivel) castering wheels.

@dany93 I wasn't aware of this, is 
~~~
<max_steer unit="DEG">360</max_steer>
~~~
the only thing that determines a caster wheel?
Does JSBSim (in our case) handle the castering action automatically then?

I just payed close attention to the wheels while applying differential braking and it certainly does appear to caster motion wise. But we are not simulating it in the animation of the wheel object, I am going to fix that today as I think that is important to have the visual of the wheel castering.
Differential braking is more than sufficient to steer the aircraft either right or left at slow speed and it does appear to turn on a dime that way. So I think this is an educational issue, as in the OP needs educating.
Thanks for everyones attention to this and all your feedback.

**Comment by dany93** [comment]
@wlbragg wrote
> I wasn't aware of this, is
`<max_steer unit="DEG">360</max_steer>`
the only thing that determines a caster wheel?
Does JSBSim (in our case) handle the castering action automatically then?

In principle, yes. But the response is more difficult _(expect re-edits!)_
In JSBSIm, `<max_steer unit="DEG">360</max_steer>` is enough.
But JSBSim is not perfect on this. IRL, the caster wheel orientation is given by a shift (a lever arm) between the wheel itself and its rotation axis (orientation). The wheel "drags" behind, which makes the self-orientation.
In JSBSim, the wheel rotates round its own axis, and its orientation is given by the relative ground velocity vector from the aircraft. The drawback is that, when the aircraft is stopped (no velocity vector) with the wheel ill-oriented (this happens most of the time), the wheel is very hard to get oriented. One needs a lot of thrust to get the aircraft start to move.
A tweaking (in JSBSim) is to give an almost zero static and dynamic friction to the wheel. Rather, it behaves like a "ball" with no directional effect.
```
            <static_friction> 0.05</static_friction>
            <dynamic_friction>0.05</dynamic_friction>
                 (snip)
            <max_steer unit="DEG">360</max_steer>
```
This idea has been found by Fritz for the DC3.

See these messages
https://github.com/c172p-team/c172p/pull/1039#issuecomment-378998699 ("On the ground")
https://github.com/c172p-team/c172p/pull/1039#issuecomment-381423770
Your commit aa322198 (wlbragg            2018-04-16)

Uneasy to explain. Am I clear enough?

**Comment by wlbragg** [comment]
`fdm/jsbsim/gear/unit[n]/steering-angle-deg`
works really well with a "wheel-speed" conditional. I'll make a new issue for the animation and open a PR.
