### ISSUE TITLE
Foreign object under starboard wheel

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#108]
There is a foreign object under the starboard wheel.
![foreignobject](https://cloud.githubusercontent.com/assets/11069680/6841094/df55e02e-d352-11e4-88e3-3e18a572c2aa.jpg)

**Comment by wlbragg** [comment]
Foreign object under starboard wheel

**Comment by Juanvvc** [comment]
I cannot reproduce this bug. The object is not in the model. Could it be a particle from your new smoke effect that for some reason is not removed?

I really, really love your trees!

**Comment by wlbragg** [comment]
"I cannot reproduce this bug."
Really, OK, I'll take a better look local then.

**Comment by wlbragg** [comment]
It's gone what ever it was so I'm closing this issue.
