### ISSUE TITLE
Remodel the base giving it a better shape. (Is it lower than normal ?)

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#11]
3D09 - Remodel the base giving it a better shape. (Is it lower than normal ?)

**Comment by gilbertohasnofb** [comment]
Remodel the base of what? Original post does not explain what is this about... I can only assume it's talking about the panel, but I am not sure about it at all. Anyone?

**Comment by gilbertohasnofb** [comment]
Can we close this? This issue never made sense to me anyway.

**Comment by onox** [comment]
I think you meant the fuselage? We should first compare the shape with photo's.

**Comment by gilbertohasnofb** [comment]
Hi onox, this issue was not written by me, only created by me. In the early days of this project we kept a TODO file with a list of tasks, and when we moved to GitHub I volunteered to create individual issues for those things. So this is just a copy and paste of what someone (probably thevirtualfer) wrote. I have really no idea what it means, and I think we have already better and more specific issues about fixing the airplane 3D model, such as #216, #6, #10 and others that already have been solved and closed (e.g. fixing the shape of the rudder and its trim tab, fixing the part of the fuselage that connects with the wings, etc.). IMO we can close this as it makes no sense and is not nearly specific enough.

**Comment by onox** [comment]
I have set 3.8 milestones, so they can be kept open.

**Comment by onox** [comment]
@thevirtualfer should probably explain what he meant then :smile:

**Comment by gilbertohasnofb** [comment]
> I have set 3.8 milestones, so they can be kept open.

I don't know, onox. I'd rather close these cryptic issues than keep them opened. I already tried to talk about these things some 3 months ago when I opened these issues but to no avail.

**Comment by thevirtualfer** [comment]
Oh, guys !

The "base" i was thinking, is the central column inside cockpit.

2015-06-16 8:05 GMT-03:00 onox <notifications@github.com>:

**Comment by thevirtualfer** [comment]
To me, it is very low.

And i just write it to not forget to ask.

Still with network problems here. The SKY says that jun/20 it will be ok,
again.

Cheeers, to all of you.

2015-06-17 17:10 GMT-03:00 Fer Virtual <thevirtualfer@gmail.com>:
