### ISSUE TITLE
Variant with no map

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#111]
I would like to add a variant called c172p-detailed-no-map in which you can only view the map while on the ground. Once you're in the air you can no longer open or see the map. The rationale is that you cannot 'cheat' by opening the map to see where you are. Instead you must use (external) charts and radio navigation to find your way to your destination. (Which is of course more challenging than just opening the map)

The regular c172p-detailed variant remains untouched of course.

Is this okay for everyone? :smiley:

**Comment by gilbertohasnofb** [comment]
I mean, it's okay for me but I find it quite unnecessary as I don't lack self control ;)

**Comment by zlsa** [comment]
I don't think this is a good thing to add to an aircraft; many aircraft override the Ctrl-U altitude cheat which makes it much harder to test their FDMs (because you have to manually climb to the altitude you want again and again).

**Comment by onox** [comment]
@zlsa I don't understand what this has to do with Ctrl-U? It would just be a `-set.xml` file that includes `c172p-detailed-set.xml`.

**Comment by onox** [comment]
Okay, maybe not then.

**Comment by gilbertohasnofb** [comment]
I think the Ctrl-U was just an example of trying to forbid something in order to make the experience more realistic but which has other consequences in the end.
