### ISSUE TITLE
make windows in the doors operable

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#116]
Make windows in the doors operable (there is already a 3D lever that could be clickable).

**Comment by onox** [comment]
@wlbragg Would you like to do this?

**Comment by wlbragg** [comment]
I'm not up to speed on translate animations, so it might take me longer than we have. Plus I have some other "bugs" I have to fix first. If I get back to it in time I can try.

**Comment by onox** [comment]
Ok, I'll see if I can fix it.

**Comment by onox** [comment]
`leftwindow`
`leftwindow_interior`
`windlocked_left`

`rightwindow`
`rightwindow_interior`
`windlocked_right`

**Comment by wlbragg** [comment]
I can work on this if you want!

**Comment by onox** [comment]
Sure. I think the windows rotate along their upper edge. They don't slide down like car windows.

**Comment by wlbragg** [comment]
Push out from bottom?

**Comment by onox** [comment]
Yes. See https://www.youtube.com/watch?v=C-yqLXZtkjA

**Comment by wlbragg** [comment]
Hum, have you seen the frame around the window? Are we going to just ignore this lack of a frame for now until we get a new model?
I wonder if this is part of @thevirtualfer's improvements?

**Comment by wlbragg** [comment]
Here is what were looking at, do we still want to proceed? Keep in mind these are the best viewing angles for being able to see the window.
![win1](https://cloud.githubusercontent.com/assets/11069680/11292513/b127c8ec-8f14-11e5-9027-fe9cf0bc4429.jpg)
![win2](https://cloud.githubusercontent.com/assets/11069680/11292515/b1287242-8f14-11e5-8129-f8cba614519d.jpg)
![win3](https://cloud.githubusercontent.com/assets/11069680/11292511/b127a8d0-8f14-11e5-911c-f97ae8e72118.jpg)
![win4](https://cloud.githubusercontent.com/assets/11069680/11292516/b128d57a-8f14-11e5-9dbc-056f24a0b2e0.jpg)
![win5](https://cloud.githubusercontent.com/assets/11069680/11292512/b127b19a-8f14-11e5-89b1-35b7119ec4b3.jpg)
![win6](https://cloud.githubusercontent.com/assets/11069680/11292514/b127faec-8f14-11e5-8351-d634945d564b.jpg)

**Comment by onox** [comment]
Have you also tried opening the door and see if the animation is still correct?

**Comment by onox** [comment]
For now we should ignore the missing frame and hope @thevirtualfer has (or can) added it to the model.

**Comment by wlbragg** [comment]
>Have you also tried opening the door and see if the animation is still correct?

No, I first wanted to make sure we were OK with the visual and that we are going to proceed. I'll continue on. I might be able to add a thin frame that only is visible on opening as a temporary fix. If I do it will be the last thing I do and then we can decide if we want to keep it that way.

**Comment by wlbragg** [comment]
Done see PR #560

Not sure about MP, flight-recorder and the use of door.nas (specifically "aircraft.door.new(...)"). I'm not familiar with what all can be changed in the syntax of this call or if this is a user defined var or a hard coded constant or function?

Also the new "circle latch support" on the windows could look better with a better texture (more convex 3D looking VS concave).

**Comment by onox** [comment]
> And the use of float alias 3 and 4, I thought maybe there was an issue using them.

The issue was not with the floats but with the ints[0 .. 3], because they were used by old version (<= 3.4) for the registration number.
