### ISSUE TITLE
sound of engine and wind should be louder with door opened

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#117]
The sound of engine and wind should be louder with door opened. Also, the same would be true if the opening of the windows is implemented (see: https://github.com/Juanvvc/c172p-detailed/issues/116)

**Comment by Juanvvc** [comment]
Actually, I strongly believe the doors shouldn't be allowed to be opened if the aircraft is flying. You have to push a plain surface (the door) against 100knots of moving air. You'll need a considerable force to open the door more than a couple of centimetres!

I don't know if this behaviour can be satisfactorily modelled. Do we assume the pilot or copilot are strong enough to open the door in mid air against the relative wind? I'm sure I'm not.

**Comment by gilbertohasnofb** [comment]
I thought we could hear the wind while on the ground, it never crossed my mind to open the door in flight!

**Comment by onox** [comment]
We should limit the maximum position of the doors as a function of the KIAS.

**Comment by gilbertohasnofb** [comment]
> We should limit the maximum position of the doors as a function of the KIAS.

That would be great, but as ludomotico wrote the doors will hardly be operable at high speeds. My idea was related to when the aircraft is on the ground. It's a simple detail, but could be very realistic.

Also, I still plan to work on the sounds for our plane, adding better stall sounds, as well as a door banging and other ones, longer loops for the engine (ours are too short and the repetition drives me nuts), etc.. But I am having a huge difficulty finding GPL-friendly recordings, and even though I have great recording equipment from my university (I study music composition and we have quite nice studio equipments I can borrow here) right now I can't afford a flight on a 172. Hopefully soon I will.

**Comment by onox** [comment]
How about a CC-BY-SA 4.0 license? Is compatible with GPL AFAIK.

**Comment by gilbertohasnofb** [comment]
When I wrote GPL-friendly, I also meant those CC licenses. I couldn't find good recordings with any GPL-friendly license, would you know some? If so, then I can try to clean them myself, equalize, create seamless loops, etc.

**Comment by onox** [comment]
You could try to search on [YouTube with CC filter](https://www.youtube.com/results?filters=creativecommons&lclk=creativecommons&search_query=cessna+172p).

**Comment by gilbertohasnofb** [comment]
The quality of youtube sounds is not good enough IMO. I was hoping to have access to some good recordings at least in WAV format. But I will have a look on those youtube links anyway, thanks!

**Comment by onox** [comment]
Have you tried to find anything on [freesound.org](https://www.freesound.org/)?

**Comment by gilbertohasnofb** [comment]
Yep.

**Comment by onox** [comment]
Have you asked a 172p pilot if you can record some sounds while on the ground?

**Comment by gilbertohasnofb** [comment]
Not really. I was thinking about doing that, but the main sound that I'd like to improve is the stall sound (ours is really not realistic at all), so that would be tricky to do on the ground :stuck_out_tongue_winking_eye: But that could at least solve the engine sound as well as other noises (doors, switches, etc.).

**Comment by gilbertohasnofb** [comment]
And since we are at this, @onox, how difficult would it be to add a small conditional such as the wind and the engine sounds get louder by a factor (let's say 25%) when the door is opened? That would solve all three sound issues we have (and I don't plan to work on any more sounds for the 3.6 milestone)

**Comment by onox** [comment]
This is not very difficult, volume should be controlled via a `<filter>` in a `<autopilot>` or `<property-rule>`.

**Comment by wkitty42** [comment]
when this is done, please check that the sound is the same as inside the cockpit when one hits the 'c' key to remove the cockpit from the display... some craft i've flown make the engine sounds like we're sitting on the wing of the craft when we hit 'c' to remove the cockpit... the way i see it is that all i've done is to sit up and put my face in the windshield area so i can see everything... the sound should not act as if i've outside the craft, IMHO...

**Comment by gilbertohasnofb** [comment]
Also, if https://github.com/Juanvvc/c172p-detailed/issues/116 gets implemented, then this should also apply to opened windows.

**Comment by wkitty42** [comment]
agreed... however, i wasn't aware that we could open any windows in this craft... that would sure help with the over heating problem :laughing:

**Comment by gilbertohasnofb** [comment]
> i wasn't aware that we could open any windows in this craft

We currently can't, hence the issue #116

**Comment by dany93** [comment]
>....but the main sound that I'd like to improve is the stall sound (ours is really not realistic at all), so that would be tricky to do on the ground

Are you certain? I have seen stall warning sensors which were merely a metallic blade at the edge of attack, which flips upwards when the AoA is high. If this is true, it must be easy to flip it on the ground by hand. It can even be a checking.

![stall-warn1](https://cloud.githubusercontent.com/assets/11994061/8208504/4317dc60-1508-11e5-881d-c4de84c98af0.png)
![stall-warn2](https://cloud.githubusercontent.com/assets/11994061/8208511/47846b88-1508-11e5-895f-9dbe74d9a3b4.png)

Our c172 pilots should be able to confirm.

**Comment by gilbertohasnofb** [comment]
>  it must be easy to flip it on the ground by hand. It can even be a checking.

But I bet this won't sound the same as it would in a stall situation, although I may be wrong here.

Anyway, there is a huge discussion going on in the forum thread about the stall sound.

**Comment by dany93** [comment]
>But I bet this won't sound the same as it would in a stall situation

Why? I think this is a 0 or 1 device.

Yes, I've seen on the forum.
I'm not convinced that it is modulated vs AoA, velocity,... At least for most of them.

**Comment by gilbertohasnofb** [comment]
> I think this is a 0 or 1 device.

I think that's a simplistic view of a stall horn. What you are saying is that given a constant fingering (i.e. a single note), blowing on an oboe will produce a 0 or 1 sound. In reality, all these sounds are much more complex, depending on the air flow -- which takes some time to enter a non chaotic state. Wind instruments are notorious to have a very important type of spectrum during the initial attack of a note and another during the remaining sound (some experiments show that people have lots of difficulty recognizing a musical instrument if we cut the first 0.5 seconds of a note). This is partially my reason to argue so fervently about using a recording (sampled sound) instead of trying to program one...

> I'm not convinced that it is modulated vs AoA

Me neither. But as for the speed, it may indeed have something to do with it (just like a flute which you can change the pitch by blowing stronger).

**Comment by dany93** [comment]
What I think (but I would prefer the opinion of a c172 pilot) is that it has nothing to do with a wind instrument. It is a simple blade with a spring, which is normally down, and up just before the stall AoA. An **electrical switch**.

**Comment by gilbertohasnofb** [comment]
Dany, AFAIK the stall horn in the 172 is a mechanical device and what produces the sound is a reed, which is the same principle behind some musical instruments such as an oboe or a basson. See: http://www.baltimorerecorders.org/seminstpics/crumhorn6j.jpg

The only "artificial" sounds I can think of in a 172 are the alert beeps from AP and the runway markers. Everything else cannot be called artificial in my view.

**Comment by Juanvvc** [comment]
dany93, gilberto is right. The horn on the c172 is mechanical. During the exterior check, you literally blow (well, not "blowing" but "aspiring") through a hole in the wing to check it the horn works. It is exactly the same than a musical instrument.

Please, check this link for a description of the different systems for stall detection. The one mounted on Cessna is just mechanical, a hole in the wing:

http://aviation.stackexchange.com/questions/14727/how-do-aircraft-stall-warning-systems-work

**Comment by dany93** [comment]
You are right, it is more complicated than I thought.
>STALL WARNING SYSTEM
The airplane is equipped with a pneumatic type stall warning  system consisting of an inlet in the leading edge of the left wing, an air-operated horn near the upper left corner of the windshield, and
associated plumbing. As the airplane approaches a stall, the low pressure on the upper surface of the wings moves forward around the leading edge of the wings. This low pressure creates a differential pressure in the stall warning system which draws air through the warning horn, resulting in an audible warning at 5 to 10 knots above stall in all flight conditions.

**Comment by gilbertohasnofb** [comment]
> It is modulated with AOA, but it does not go from C to B! It is more like from C to D ;)

I don't understand what you mean by that, Juan!

**Comment by wkitty42** [comment]
@gilbertohasnofb i think he's talking about the sound of the note... like on a piano... going upscale in the same octave from C to D... not downscale in the octave from C to B or jumping from C in one octave to B in the next higher octave...

**Comment by gilbertohasnofb** [comment]
@wkitty42 Thanks! :laughing: I thought it was about going from A to B to C as in a route :) Okay, so he means it goes up with angle of attack instead of going down, and that the range is fairly limited (like a minor or major second).

**Comment by wkitty42** [comment]
@gilbertohasnofb yes, i think that's right... i just listened to one on ewwtube... let me see if i can find it again...

**Comment by wkitty42** [comment]
here it is... 20 second video from Sporty's Pilot Shop... "Side View of a Wing Stall, Cessna 172" https://www.youtube.com/watch?v=CbtG8KHeMak

**Comment by gilbertohasnofb** [comment]
> ewwtube

That's funny :smile: 

> here it is

The funny thing is it behaves as a musical scale, that is, with steps. It's not exactly proportional to the AoA, but actually certain ranges of AoA have an almost constant sound. Do you hear this as well?

**Comment by wkitty42** [comment]
yeah... it is kinda like someone said on the forums (i think)... like one of those kids party blower things with the paper that rolls out... i think it sounds more like a kazoo when it is starting up...

in the discussion, that's also where they were talking about tying the pitch into the AoA but i think it is slightly more than just that to make the necessary sounds... there's also the air flow which is based on the air pressure on the leading edge of the wing...

here's another one... you can just hear the stall horn as he is coming in for a landing... https://www.youtube.com/watch?v=8y4KjouqnKQ
start at about 13:50 where they're on final... you can hear the stall horn just starting at about 14:05...

**Comment by Juanvvc** [comment]
Sorry. I meant the sound goes up about a half/full note and not a full scale :)

**Comment by gilbertohasnofb** [comment]
> that's also where they were talking about tying the pitch into the AoA but i think it is slightly more than just that to make the necessary sounds... there's also the air flow which is based on the air pressure on the leading edge of the wing...

That is exactly my point. And now we are almost in need to develop a full Stall Horn Simulator 2015 in order to implement all this. But jokes aside, a possible proposal is to create ranges, such as:

angle of attack between a and b degrees: sound frequency 1
angle of attack between b and c degrees: sound frequency 2
angle of attack between c and d degrees: sound frequency 3
etc.

**Comment by onox** [comment]
:+1: for SHS 2015 :laughing:

**Comment by gilbertohasnofb** [comment]
And then someone will probably re-release it as Stall Horn Pro Simulator and charge 50 bucks for it! :smile:

**Comment by wkitty42** [comment]
hahaha... that's funny... but hey, it is allowed... they have to support it... but yeah, i get the same weird feeling about a lot of my work... i can't make any $$$ with it so i guve it away and someone else comes along and sells it without sharing in the spoils...

**Comment by gilbertohasnofb** [comment]
> but hey, it is allowed...

Yeah, I know...

**Comment by wkitty42** [comment]
so, with all this discussion about the stall horn, i haven't seen anyone mention that it works based on low pressure across the leading edge of the wing... i guess this is where the modeling comes in... from what i've read on the forums, it seems that JSBSim should be able to calculate this low pressure area and the value of the low pressure...

in the research i've been studying, the low pressure causes the higher pressure to enter the stall horn reed or valve area and create the noise... the lower the pressure, the more high pressure air is allowed through the reed or valve which increases the pitch of the sound... from the stall horns i've heard while researching this, the sound seems to start off sounding like a kazoo and then climbing in pitch as the stall gets worse and more high pressure air flows through the reed or valve section...

it is the low air pressure that is the trigger and that's tied to the speed of the air flowing over the wing as measured at two separate points on the wing... low pressure at point A and high pressure at point B where point B is the opening going to the stall horn's reed or valve assembly...

**Comment by gilbertohasnofb** [comment]
I think you are correct.

**Comment by dany93** [comment]
wkitty42 wrote
 >from what i've read on the forums, it seems that JSBSim should be able to calculate this low pressure area and the value of the low pressure...

Not at my knowledge. Where have you seen that?

I rather think you will have to use the AoA. It is the best indicator, admitted by everyone. By making it non-linear if you prefer, you do all that you want.

Anyway, at best imagine you have the pressure, you have to apply a law to transform it into a note. And you ignore the physical law.
The pitch and volume of the note are connected to the pressure by a law that you do not know, and the pressure difference is connected to the AoA, maybe to the velocity too. As the AoA is directly available, better to use the AoA. In any case you have to guess a link. You can add a velocity contribution if you wish, but with no better knowledge of the physical law. All of that is guess, or preferably comparison with IRL if someone can tell.

**Comment by wkitty42** [comment]
@dany93 since it is a simulator, it should be able to calculate these items or maybe the resulting forces of them... my statement is based on "A different perspective on JSBSim" http://forum.flightgear.org/viewtopic.php?f=49&t=26442

**Comment by wkitty42** [comment]
the idea is to find the pressures at the two points on the wing related to the stall horn... point A at the front (where you suck on the stall horn to test it) where the air exits the stall horn and point B where the high pressure enters the stall horn's air scoop to be directed through the reed or valve assembly...

the idea is if we know the pressures at these two points, we can then calculate (or fake) the speed of the air through the reeds or valves... that speed will determine the pitch of the note... so we start with the base bass note (sounds like a kazoo) and then increase its pitch as the air flow through the tube increases...

really all i'm looking for is a number at point A and another number at point B that we can add or subtract to get a flow number we can use for the air flowing through the stall horn's tube...

**Comment by wkitty42** [comment]
this section from the JSBSim reference manual looks extremely interesting... if we can get qbar(??) from the front edge of the wing and from the bottom of the wing where the pressure is higher when in a stall, this might work out... that is, if it does what i think it can do...
~~~~~
3.1.9.1.15   Sensor Component

When the flight control system uses “sensed” values such as qbar or orientation, the sensed
values are taken from the environment model, and are modeled as “perfect sensors”. That is,
the values were taken directly from the equations of motion, without attempting to make them
look as though they had come from a sensing device (gyro, pitot tube, etc.) – with the
associated imperfections that those devices can introduce. Imperfections can include noise,
drift, and truncation of precision, etc. A bias can be introduced; a bias is simply an
offset introduced to the sensor.

The sensor component models imperfections and increases the realism of the control system.
The only required element in the sensor definition is the input element. In that case, no
degradation would be modeled, and the output would simply be the input.

For adding noise, if the type is PERCENT, then the value supplied is understood to be a
percentage variance. That is, if the number given is 0.05, the variance is understood to be
+/- 0.05 percent maximum variance. So, the actual value for the sensor will be any where
from 0.95 to 1.05 of the actual "perfect" value at any time - even varying all the way from
0.95 to 1.05 in adjacent frames - whatever the delta time.

The format of the sensor specification is:
<sensor name=”name” >
<input> prop
erty </input>
<lag> number </lag>
<noise variation={”PERCENT|ABSOLUTE”} 
distribution={“UNIFORM|GAUSSIAN”}> number </noise>
<quantization name="name">
<bits> number </bits>
<min> number </min>
<max> number </max>
</quantization>
<drift_rate> number </drift_rate>
<delay> number </delay>
<bias> number </bias>
</sensor>

Example:
<sensor name=”aero/sensor/qbar” >
<input> aero/qbar </input>
<lag> 0.5 </lag>
<noise variation=”PERCENT”> 2 </noise>
<quantization name="a
ero/sensor/quantized/qbar">
<bits> 12 </bits>
<min> 0 </min>
<max> 400 </max>
</quantization>
<bias> 0.5 </bias>
~~~~~

**Comment by onox** [comment]
Please continue in #85

**Comment by gilbertohasnofb** [comment]
About the original issue here (raising the volume when the doors are opened), I tried fixing this myself but I can't understand how `<volume>` works. For instance, I tried adding this to the `<wind>` block but it makes no effect:

    <volume>
        <property>/sim/model/door-positions/leftDoor/position-norm</property>
        <factor>0.5</factor>
        <offset>1.0</offset>
        <min>1.0</min>
        <max>1.5</max>
    </volume>

Can someone help me understand how does this work? When you have more than one `<volume>` block, how do they affect the volume of the final sound?

**Comment by wkitty42** [comment]
when i was toying with the stall warning stuff, i was never able to increase its volume to a noticeable level... even now, with the latest pull, i have a hard time hearing the stall warning and other sounds over the engine... adjusting the overall sim sounds doesn't help at all since quite many are shoved into one volume control :(

**Comment by gilbertohasnofb** [comment]
What I am not able to understand is how several `<volume>` blocks influence each other. But even with a single block I had so much difficulty dealing with this door issue... let's hope @onox comes back soon to help us out :smile:

**Comment by Juanvvc** [comment]
Most probably, volume goes from 0 to 1. You are defining min=1.0 and max=1.5. I guess the volume is clamped somewhere, and the final value will be always 1.0

Try min=0 and max=1

The official description of the sound system is here: http://sourceforge.net/p/flightgear/fgdata/ci/next/tree/Docs/README.xmlsound I can't understand the system at all, but it may be because I'm seriously hungry :)

**Comment by wkitty42** [comment]
the biggest problem i see is that some additional sounds are all under the same control in settings that the engine is in... i need to turn the engine down so that i can hear other things like the stall warning... the marker alert tones are plenty loud... i have the radios turned up all the way and must turn down the engine which reduces others wrapped in that same control... probably nothing we can do about it in this craft as it likely needs code within fgfs to be altered... perhaps we can make the actual sound files for the stall warning louder? or are the sounds leveled at a certain db before being mixed?

**Comment by gilbertohasnofb** [comment]
@Juanvvc I have seen other volume blocks with numbers higher than 1. I think the idea is that the final volume value is influenced by all individual volume blocks, and so you may need to cross the 1 barrier in some of them to achieve a desirable result between 0 and 1. Also, I had tried the same code above without min and max, so that 0 and 1 is implicit, and it just didn't work at all.... Thanks for that README, I will have a careful look at it later (when I am not hungry myself!).

@wkitty42 Of course I could make the stall warning louder, but there should be a way to control the volume directly on this xml and that is probably a more elegant solution. I really think @onox knows these things well, so let's just see when he comes back.

**Comment by onox** [comment]
@Juanvvc It seems `Docs/README.xmlsound` is wrong. The following:

```javascript
301           value += factor[n] * function(property[n]);
```

should be:

```javascript
301           value *= clamp(min[n], factor[n] * function(property[n]), max[n]);
```

The `+=` on line 297 is correct, but that line doesn't show the clamping either.

So, assuming factor is > 0, you get a sum of offsets and a product of clamped `factor[n] * function(property[n])`. The final `volume` on line 306 is then clamped to be at most 1.0.

So to answer the question:

> I have seen other volume blocks with numbers higher than 1. I think the idea is that the final volume value is influenced by all individual volume blocks, and so you may need to cross the 1 barrier in some of them to achieve a desirable result between 0 and 1.

Yes, you can have volume blocks with numbers that end up being higher than 1 (for example, property multiplied with factor), but it doesn't make sense in the case of the stall horn volume, because its code is:

```xml
256             <volume>
257                 <property>/fdm/jsbsim/sounds/stall-horn-volume-actual</property>
258             </volume>
```

As you can see it's the only volume block and its property fully defines the volume (there's no factor). I have looked at `Sounds/stall2.wav` in Audacity and the amplitude of the sound looks very soft, so I think the amplitude could be increased quite a bit (make the sound louder) (just make sure no clipping occurs). After that I can adjust the volume in `Systems/c172p-sounds.xml`.

@gilbertohasnofb Can you update the sound in branch bug-117?

@wkitty42 I'm wondering why you have trouble hearing the stall horn, I can hear it easily. What kind of speakers are you using? Do you know if the speakers are good/bad at certain frequency ranges?

Anybody else who has trouble hearing the stall horn?

**Comment by gilbertohasnofb** [comment]
@onox 
>  Can you update the sound in branch bug-117?

Do you mean to raise the amplitude of `stall2.wav` in the mentioned branch or do you mean something else with "update"?

**Comment by onox** [comment]
Just to raise the amplitude of the `stall2.wav` file. Its volume in Audacity (or the program you are using) is quite low, isn't it?

**Comment by gilbertohasnofb** [comment]
@onox done, I just created a branch named `bug-117` and added the louder sound to it. I didn't check the sound in the sim though, can you please verify if the volume needs tweaking in that xml file? (it might be too loud right now). I am going to sleep now but tomorrow we can continue :sleepy:

**Comment by wkitty42** [comment]
@onox i have four sets of speakers attached to the surround sound system connected to the outputs of my sound card... quite simply, i cannot easily hear the stall horn and other sounds because the engine sound is too loud... turning down the engine sound also turns down other sounds because the system merges them all together into the same channel controlled by the same volume slider...

the only other thing i can say about the stall horn in particular is that it doesn't start off bass enough like a low tone on a kazoo before rising in pitch as the stall worsens... i can repost the links i posted previously if needed...

**Comment by onox** [comment]
Reopening this issue because we didn't actually fix the engine and wind noise, just the stall horn.
