### ISSUE TITLE
Improve top of the fuselage

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#119]
Currently, the top of the fuselage and the wings are joining in a rather strange way: http://s2.postimg.org/45stm9q1l/fgfs_screen_001.png

Here is how they look in the real plane: http://flighttraining.aopa.org/images/students/presolo/0208ANTENNA01L.jpg

**Comment by dg-505** [comment]
[I corrected it](http://abload.de/img/fuselagerguu7.jpg), but I did it in AC3D, so I don't have the .blend-file.
Could somebody please explain, how I can import the changed objects manually to blender?

**Comment by gilbertohasnofb** [comment]
@dg-505 that looks really good!!

**Comment by dg-505** [comment]
Now I did the modification also in Blender, and I want to export it. [Juanvvc said](https://github.com/Juanvvc/c172p-detailed/pull/188) that not everything of the .blend-file is exportet to the .ac file. How do I export the .ac file with the correct infomation

**Comment by Juanvvc** [comment]
Fixed by dg-505, I think.

**Comment by gilbertohasnofb** [comment]
Confirmed.
