### ISSUE TITLE
Add reflex on the glass

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#12]
3D10 - Add reflex on the glass.

**Comment by Juanvvc** [comment]
Not sure if this reflex means reflex on the instruments (and then, it is #13), or the new glass effect (and then, it is already fixed in #29 ) Anyway, I think this is duplicated.

**Comment by gilbertohasnofb** [comment]
I believe this is a duplicate of the former XML06 https://github.com/Juanvvc/c172p-detailed/issues/29. I will close it and label it as duplicate.
