### ISSUE TITLE
Model Heat and Air knob slider controls and tie heat and air to them.

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#120]

**Comment by gilbertohasnofb** [comment]
Can you tell me which textures will we need exactly? I thought those two knobs were already textured, but I may be wrong. These are the two knobs under the right yoke, right?

**Comment by wlbragg** [comment]
I don't know that they need textures, I think it is currently one piece in the ac file. They need to be split apart into two different independent  controls with their own name. I guess that is all they need? Unless they will need texture work after they are split apart.

**Comment by gilbertohasnofb** [comment]
I just check them and indeed I don't think they need texturing.

**Comment by Juanvvc** [comment]
I have just committed the animation for the cabin heat and air cond knobs. They are mapped to /environment/aircraft-effects/cabin-heat-set and /environment/aircraft-effects/cabin-air-set, as wlbragg suggested in comments for #133

**Comment by wlbragg** [comment]
It's really nice to have this system, thank you!
