### ISSUE TITLE
Fuel: unuseable fuel not defined

### ISSUE THREAD

**Issue by legoboyvdlp** [Juanvvc/c172p-detailed#1243]
![image](https://user-images.githubusercontent.com/10434911/49330918-72cc8500-f58d-11e8-991f-d69fffd16565.png)

3 us gallons of fuel in each tank are unuseable: this is because there is an area at the bottom of the tank into which water or other contaminants will flow. Therefore, this should be defined as unuseable in the -set file. Pull request on its way.

**Comment by gilbertohasnofb** [comment]
b) is definitely the better approach, if coupled with a short email to the dev-list asking for this feature.

**Comment by legoboyvdlp** [comment]
OK - that's definitely fine, although I'll check first to be sure I didn't mess something up :)

Jonathan

**Comment by legoboyvdlp** [comment]
Yes, but I found the engine still runs when the fuel should be unusable. Or else, I made a mistake somewhere.

**Comment by legoboyvdlp** [comment]
@onox
I think some commits in JSBSIM, also now on next (2018.4) if you are self building or using nightlies will make the unusable fuel actually cut off fuel. I'll build and test later this week.
