### ISSUE TITLE
some instruments seem to be in a bit wrong position

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#128]
The user dg-505 has reported in the forum thread: "[...] some instruments seem to be in a bit wrong position: http://abload.de/img/fgfs-screen-0032jxic.png "

I tested on my system and indeed both the vertical speed indicator and the tachometer are above their correct positions.

**Comment by onox** [comment]
@dg-505 Are all instruments in the correct position now? Then this bug can be closed.

**Comment by gilbertohasnofb** [comment]
I can confirm this is fixed.
