### ISSUE TITLE
How can I heat up the wind shield?

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#133]
During certain meteorological conditions I get a lot of ice or fog on the wind shield, even though from the outside the weather and visibility looks OK. Is it possible to heat up the wind shield so I can keep flying?

**Comment by Juanvvc** [comment]
AFAIK, not yet but it is in the TODO list of wlbragg. Before that, we must fix #120

**Comment by wlbragg** [comment]
Yes, HOLD YOUR BREATH :)
in the debug property list
/environment/aircraft-effects/cabin-heat-set (heat slider knob)
double 0 to 1 (0.5 = half open)
/environment/aircraft-effects/cabin-air-set (airflow slider knob)
double 0 to 1 (0.5 = half open)

/environment/aircraft-effects/cabin-dew-setC (I don't think this is active or useful unless or until we decide to put in an aftermarket air conditioner)

**Comment by onox** [comment]
Does the real Cessna 172p have no button by default to control the heating? I spoke to a user who had to stop flying the c172p-detailed because the scenery was no longer visible from inside the cockpit.

**Comment by wlbragg** [comment]
Yes it does, the properties I posted tie to the RL slider controls for heat and air under the yoke.

**Comment by wlbragg** [comment]
onox, the sliders are in and look like they are also tied. If you can remember what conditions you had set to get the fog and ice, you may want to repeat and test this system.

Thank you.

I will eventually, when I get a chance to.

**Comment by wlbragg** [comment]
I've had fog form on my windows today and opened heat slider to about 20% and air slider to 50%, cleaned it right up. I think were done here for now.

**Comment by onox** [comment]
The air slider does the trick! Thanks :+1:
