### ISSUE TITLE
Remodel magneto key starter

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#137]
Instead of having just the key as a 3D model (current situation), we could also have the part which has the key hole as a 3D object (a simple cylinder would do): http://media.chiefaircraft.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/B/D/BDX_10-357290-1.jpg

A new texture for this has been created before (but I had forgotten to open a ticket for the 3D object, sorry...): https://github.com/Juanvvc/c172p-detailed/issues/22

**Comment by gilbertohasnofb** [comment]
The texture is located in the right-hand side of COLOR_panel_parts.png.

**Comment by dg-505** [comment]
Created a pull request with the new magneto switch. If it is merged (and works correctly), you can close this issue.
