### ISSUE TITLE
remap rudder texture

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#138]
The texture on the rudder, as well as in the back of the fuselage, needs to be better mapped. See: http://s10.postimg.org/bwalu0by1/fgfs_screen_002.png

This is particularly easy to spot in the liveries N35799 and PT-IAO, since they have lines in those areas.

**Comment by Juanvvc** [comment]
Done. Please, check

**Comment by gilbertohasnofb** [comment]
Oh, this is way better!! Thanks a lot Juan. I will need to fix a couple of liveries (both older and new ones) as well as correct the Paintkit once again. For this, I created the issue https://github.com/Juanvvc/c172p-detailed/issues/140
