### ISSUE TITLE
Zero Hole Initiative

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#14]
3D12 - Always ZHI

**Comment by gilbertohasnofb** [comment]
see: https://github.com/Juanvvc/c172p-detailed/issues/15

**Comment by gilbertohasnofb** [comment]
Can we close this? I don't think we have any more obvious holes in the fuselage, so this is not really relevant IMO.

**Comment by wkitty42** [comment]
actually, there may be some holes... or maybe what i'm seeing is something else??

fly at night and hit CTRL-C to light up the click spots... now use the heli view to circle about the craft... i know that i can see the left side door pocket click section for the checklists from outside... there are a few other things that appear from out there, as well...

**Comment by gilbertohasnofb** [comment]
@wkitty42 I can't test it now, but probably it would be better if you could take some screen shots and upload them here or on the forum, so then someone with 3D modelling skills can fix them.

**Comment by wkitty42** [comment]
here's one picture i just took... this is in daylight... reproducing this is extremely easy... start fgfs with this craft... don't do anything else when it loads... simply hit CTRL-C to turn on the click spots hilighting and then hit 'v' to get to the heli view so you can move around the craft... it should start in the rear straight behind the craft... you can see the yellow click spot hilights right through the body... move around the craft and you can see more of them as you go... in this picture, i understand seeing the door and baggage compartment click hilights but not all the other ones on the control panel...
![fgfs-screen-015](https://cloud.githubusercontent.com/assets/4641713/7660185/b4318cf0-fb15-11e4-9c49-e9ac65e8fada.png)

hopefully this picture got attached correctly... if not, i'll try again...

**Comment by gilbertohasnofb** [comment]
But wait, isn't this true to all planes? I mean, these are not holes, this are simply the contours of the instruments which can be toggled on and off, and when using an external view there is no point in having them on, right?

**Comment by onox** [comment]
This is true for all planes. The best solution would be if buttons describe whether it's for internal use or not (sometimes aircraft can have clickable doors in the exterior), but that would require changes to flightgear itself, so this issue currently seems like a wontfix.

**Comment by gilbertohasnofb** [comment]
To be honest I see very little benefit from a possible "fix" of the yellow contours when outside. But my point is that this issue here was not about them, but rather about holes in the 3D model: places where you can see through where you shouldn't (for instance, with badly connected 3D objects). So I believe it should be closed but for the reason that we basically fixed a lot of these holes and right now I can't see any of them in our model.

**Comment by wkitty42** [comment]
maybe i'm not understanding... i thought those things were being seen through holes in the 3D model... when i first start, i can see them right through the tail end as if the seams are not fully closed... i've just loaded and zoomed in real close from the rear heli view starting point... i see now that these things are apparently showing right through the skin and paint and seats and bulkheads... some of them i can even click on and move while i'm outside the craft... ok, so i guess this is a flaw in fgfs itself... sorry for the noise...

**Comment by gilbertohasnofb** [comment]
No worries!
