### ISSUE TITLE
Use or lose Systems/crash-detect.xml

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#145]
Reminder to myself.

Evaluate usefulness of crash-detect.xml for damage system. Either use it or delete it.

Also other misc items to use or delete
terrain_survol_loop in c172p-detailed.nas

**Comment by onox** [comment]
@wlbragg Is this file still in use?

**Comment by wlbragg** [comment]
No, I think we can get rid of it.
