### ISSUE TITLE
Livery switch bug

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#147]
When switching liveries, sometimes the interior.png is not properly displayed (that is, the interior of the default D-EEQA livery is displayed instead). I tracked down how to generate the livery bug that is bothering me so much. Actually it affects ALL liveries. Here is how to do:

1) select the livery D-EEQA
2) select any other livery (let's say 4X-CHV (HD livery))
3) select once again D-EEQA
4) select once again the livery of step 2, in this case 4X-CHV (HD livery). What happens now is that the interior colours of 4X-CHV will not be correctly displayed, but rather the colours of D-EEQA.
5) if now one selects a third livery, the bug is reset. But just follow steps 1-4 once again to make it happen once again

**Comment by onox** [comment]
![fgfs-screen-080](https://cloud.githubusercontent.com/assets/3361585/8154417/4101f85e-133a-11e5-96bc-78965b3004b4.png)
![fgfs-screen-082](https://cloud.githubusercontent.com/assets/3361585/8154418/41074ebc-133a-11e5-9f83-6203fe5e380a.png)
![fgfs-screen-083](https://cloud.githubusercontent.com/assets/3361585/8154419/41081ee6-133a-11e5-9f50-20dc59873b88.png)

**Comment by wkitty42** [comment]
i can't duplicate this :disappointed:  every time i select a/the HD livery, there's a 2 to 3 second pause before it loads... i've tried with using different liveries, too... toggling back and forth between any two at the time several times to no avail...

**Comment by gilbertohasnofb** [comment]
@onox I just tested this again and it's still present. Maybe we should move this to the 3.8 release milestone, as nobody has a clue on how to fix it.

**Comment by wkitty42** [comment]
i still cannot reproduce this...

**Comment by gilbertohasnofb** [comment]
@wkitty42 really? That's really strange. For me, I just have to chose any livery, then D-EEQA, then that same livery again.

**Comment by wkitty42** [comment]
i wasn't able to reproduce it previously, either... i'll try again... gimme a few minutes...

**Comment by gilbertohasnofb** [comment]
Sure.

**Comment by onox** [comment]
> I can't duplicate this :disappointed: every time I select a/the HD livery, there's a 2 to 3 second pause before it loads...

How many seconds your system needs to load a livery is not very relevant. Just switch to 4X-CHV, when it has loaded, switch to D-EEQA, when it has loaded, switch back to 4X-CHV. You'll see the problem in the last screenshot.

**Comment by wkitty42** [comment]
>How many seconds your system needs to load a livery is not very relevant.

i only made that comment due to the time it takes to load a HD livery... i was *not* implying that it had anything to do with this bug...

i can report that i do now see this bug now that i'm looking at the interior carpeting stuff on the door, wall and floor instead of looking for a flawed panel as i had been...

in my testing, i note that this only happens when D-EEQA is used as one of the liveries being switched between... switching between two other liveries does not exhibit this flaw...

wanna bet it is because the D-EEQA livery files are in /Models instead of in /Models/D-EEQA ?? get them moved as in the other issue you guys are working on and this bug will probably go away :wink: :wink:

**Comment by gilbertohasnofb** [comment]
> wanna bet it is because the D-EEQA livery files are in /Models instead of in /Models/D-EEQA ?? get them moved as in the other issue you guys are working on and this bug will probably go away

I also think that would be the case (or at least hope!).

**Comment by wkitty42** [comment]
i just got nosy and went looking at the xml files... /Models/Liveries/D-EEQA.xml points to interior-test.png but i don't see that file in /Models or anywhere in /Models/Liveries or anywhere else...

**Comment by gilbertohasnofb** [comment]
Oh, let me check that right away!!

**Comment by gilbertohasnofb** [comment]
@wkitty42 that was it!!! :smiley:

**Comment by onox** [comment]
Hey, I want to test things too :stuck_out_tongue_winking_eye: :sob:

**Comment by gilbertohasnofb** [comment]
Sorry @onox!!! You must hate me for my lack of PR's... okay, so what should I do now? Can you test directly from the master? Here is a promise: anything I want to push which is not texture or sound, even the most minuscule change of line of code, will enter via a PR.

**Comment by wkitty42** [comment]
@gilbertohasnofb i guess these tired old eyes aren't so tired and old as they seem to be some times :laughing:  so just to confirm, if i pull and update right now, i won't see this problem any more?

**Comment by gilbertohasnofb** [comment]
> if i pull and update right now, i won't see this problem any more?

Yes! :smile:
