### ISSUE TITLE
New solid 3D shadow needed

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#148]
We need a new solid 3D shadow. I finally confirmed why our 3D shadow is solid. It requires a bit of trans in the ac. However our shadow displays varying levels or shades of gray depending on the amount and type of object producing shadow. So the simplest one piece 3dshadow model we can make is what is needed. So I am putting it on the todo list.

**Comment by wlbragg** [comment]
In case it wasn't real clear, this is something I don't think I will be able to do:)

**Comment by wlbragg** [comment]
Including animation for the prop.

**Comment by wlbragg** [comment]
Rolled #125 into this issue. It now includes adding shadows custom to bush kits along with  animating the prop.

**Comment by onox** [comment]
I noticed some problems with the current shadow volume:

* The "Shadow volume" option in "Aircraft Options" is always unchecked when starting FG. Is it turned off by some Nasal code?
* The shadow sometimes floats above the ground
* The nose gear of the shadow looks weird:

![nose-gear-shadow](http://i.imgur.com/yfLXfT4.jpg)

**Comment by wlbragg** [comment]
We need a new 3d shadow model. If anyone wants to start making one please talk to me first. There are some things i need to explain.
Really just the following....
Make the following pieces separate objects
prop
nose gear
left gear
right gear.

**Comment by wlbragg** [comment]
"The Shadow volume option in "Aircraft Options" is always unchecked when starting FG"
Mine is persistent, check again, maybe it was fixed. 

"The shadow sometimes floats above the ground"
There is a bug in the ALG prop update. When certain conditions (reset or ALS on/off) it screws up the AGL settings. You may be seeing this.

**Comment by Juanvvc** [comment]
"If anyone wants to start making one please talk to me first."

I'm not sure what a shadow needs, but I'll try to make one. I understood you need some objects separated. Do you need them for the damage support?

**Comment by wlbragg** [comment]
Yes, including, if possible
prop
wing (aileron and flaps can be part of the wing)
nose gear
wheel
left gear
wheel
right gear
wheel

**Comment by wkitty42** [comment]
are we using a 3D shadow now? is that the "shadow volume" selection? that's what i use right now... since we've now also got the pontoons, we need to add them to the shadow as well... i have no idea what it will take to add and remove them when the pontoons are selected and when we switch to wheels only... maybe switching between two different shadows or can the pontoon shadow be done in the same was as the pontoons are?

**Comment by wlbragg** [comment]
"are we using a 3D shadow now? is that the "shadow volume" selection?"
Yes

"we need to add them to the shadow as well"
Yes, most definitely.

"i have no idea what it will take to add and remove them when the pontoons are selected and when we switch to wheels only.."
We'll use a select animation based on bushkit value. We can use the pontoon without the wheels, but may need a new simpler one for the amphibious version.

**Comment by wlbragg** [comment]
OK, I took on this project and cleaned up our 3d shadow volume. I added pontoon, bush26 and bush36 to go along with default. We still need to make amphibious 3d.

We still need to make ALS 2d pontoon, bush26, bush36 and amphibious.

Later we can add some simple animations.

See commit 2133966

**Comment by onox** [comment]
I don't see the point of having a 2D shadow if we already have the better looking 3D shadow.

**Comment by wlbragg** [comment]
Yes, we have all 3d shadows except amphibious, I only did pontoon.

**Comment by wkitty42** [comment]
would the amphibious shadow be that much different from the plain pontoons? i wouldn't think so... at least not from the distances we generally look at them from in the sim ;)

**Comment by wlbragg** [comment]
That's why I left it for last and it was extra effort to add the gear.

**Comment by onox** [comment]
@wlbragg Can we just ditch the whole 2D shadow thing and just add the gears to the 3D shadow of amphibious so we can close this issue?

**Comment by wlbragg** [comment]
Yes, i'll take care of it in the morning.

**Comment by onox** [comment]
Btw, can the 3D shadow handle the retraction of the gear? If not, then we should have a 3D shadow with the gear retracted (in other words, gear not visible) because you'll only notice the shadow near the water and in that case you'll likely have the gear retracted :wink:

**Comment by wlbragg** [comment]
Good point, yes they can be animated. I'll see if I can get this done sometime today also, I'm glad you commented on it because I had forgot about it.

**Comment by onox** [comment]
@wlbragg Is it OK if I remove the 2D shadow (the checkbutton) and always automatically enable the 3D shadow if ALS is turned on? It's not computationally expensive, so there's no reason to turn it off IMO.

**Comment by wlbragg** [comment]
Hum, I would be OK with it if we first asked in the forum if anyone is using the 2D. I don't really see the need for both except the 3D's alpha is not handled as well as it could be and the 2D looks better visually (except it doesn't morph). I don't know that Thorsten will ever get back to improving the 3D though.
But I am not opposed I guess.
Anyone else have an opinion on this?

**Comment by onox** [comment]
Both the 2D and the 3D shadow can show glitches under certain circumstances. I have a patch here that modifies the value (1.0) on line 18 of `Systems/ground-effects.xml` depending on the bushkit that is used, and moves the shadow closer to the ground.

Are the `Models/Effects/shadow/3d*.xml` files those that control the 3D shadow? I see they have a pitch and z offset. Are those still correct and needed?

**Comment by wlbragg** [comment]
Yes, I am pretty sure those are needed. As to how correct they are?

If you need access to those offsets elsewhere, (like in Models/c172p.xml), you might be able to zero those entries out and pass the ones you want when you call the file from Models/c172p.xml like below.

See lines around 5383
...
 
  <model>
    <path>Effects/shadow/3dbushdefshadow.xml</path>
    <offsets>
      <x-m> ??</x-m>
      <y-m> ?? </y-m>
      <z-m> ?? </z-m>
    </offsets>
  </model>
...

I don't know that this is where your going with this?

**Comment by onox** [comment]
What I'm not sure about is why there is an offset defined in the model xml files, and in the `<filter>` in `Systems/ground-effects.xml`. We can define the offsets in `Models/c172p.xml`, but then we need to remove `<reference>1.0</reference>` on line 18 in `Systems/ground-effects.xml`.

**Comment by wlbragg** [comment]
Maybe you will understand the use of the filter better than I did.
I remember it didn't behave as I anticipated (as far as initially positioning the shadow) and I am pretty sure the offset in the shadow.xml (or pass it from c172p.xml) is the proper way to initially position that shadow.

**Comment by onox** [comment]
I'll remove the 2D shadow. Does it use any files that will then become unused?

**Comment by onox** [comment]
@wlbragg Can I remove the `check_required_version()` call in `Nasal/flashlight.nas` since this aircraft will be added to fgdata 3.6 anyway?

**Comment by wlbragg** [comment]
>I'll remove the 2D shadow. Does it use any files that will then become unused? Can I remove the check_required_version()

I assume you already have those answers.
