### ISSUE TITLE
Remove braking from any damaged gear

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#149]
Do not allow the use of brakes on any gear that is damaged.

**Comment by dany93** [comment]
About the brakes and damages, I hope that you have seen my response in the forum
(brake-parking)
    /controls/gear/brake-parking = 1
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=241870#p241870

**Comment by wlbragg** [comment]
Yes, the only comment I am unclear about is the users comment on applying brakes upon crash. Currently during all crashed gear he ground contacts take over and drag bis applied. But with speed the aircraft skids to a stop.
The comment on NOT applying brakes I agree with. If the gear is broke, you shouldn't be able to apply brakes.
I'll remove control of damaged gear's brake.

**Comment by wlbragg** [comment]
In an effort to get this issue closed, all that is needed IMO is "remove control of damaged gear's brake", not apply brake when damaged. The broken gears contact points provides all the necessary friction to slow it down, but what remains intact is the ability to apply the brakes, that shouldn't work if the gear is damaged to the extent that we modeled.
So the question is does anyone know what property/s to control to diss-allow the application of brakes?

**Comment by onox** [comment]
Save the original `controls.applyParkingBrake` and `controls.applyBrakes` functions and override them.

**Comment by onox** [comment]
I'll fix it :smile:
