### ISSUE TITLE
Remove aileron control on catastrophic crash.

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#150]
The aileron animation is incorrect and cuts into other objects after collapsed wing animation so we need to remove control of aileron upon catastrophic crash.

We also need to check broken wing damaged aileron movement and make sure it isn't cutting into other objects and that it looks acceptable during movement.

**Comment by onox** [comment]
Have you checked the model over MP lately? The wings are missing. Even after I removed "Models/" in the model .xml file here locally. (Although it did remove the "Cannot find "Models/bla bla" messages)

**Comment by wlbragg** [comment]
onox, I have made great strides in getting this ready over MP. I will have something to push hopefully tomorrow or the next day. I am doing it in internal-shadow-control VS a new branch. It's getting difficult to traverse through three branches as it is. My third (sudo) branch is one dany and I have for FDM damage model testing. I am going to roll that into internal-shadow-control also here in the not to distant future because that is the branch I first do all my refactoring, testing, debugging and new features on.
It's been working out well that way. So hang tight, I should have an (incomplete) MP test for you by tomorrow night.

**Comment by wlbragg** [comment]
I was early and pushed what I have completed last night, please check it out for me! I want to start putting it into master ASAP!
There is more to do, by about half, I'd say.

**Comment by wlbragg** [comment]
Done
