### ISSUE TITLE
Retexture the door handels

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#155]
See
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=242201#p242199

**Comment by gilbertohasnofb** [comment]
Does anyone know if this concern the L-shaped moving part or the fixed door part? The L-shapped texture was created by thevirtualfer and it doesn't look bad to me, it's a simple metallic texture. The fixed door part where the L-shaped lever is connected uses the wall and ceiling textures, and there is not much to be done about it: I would be against creating a texture just for it (which would have to change with either interior theme as well). Any opinions?

**Comment by wlbragg** [comment]
I only created this issue because of a users post in the forum. We can close this issue as far as I am concerned if it is more trouble than it is worth, or just not needed.

**Comment by gilbertohasnofb** [comment]
Agreed!
