### ISSUE TITLE
Mixture and Throttle levers: control by mouse scroll wheel counter-intuitive

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#156]
As wkitty42 noticed in
 http://forum.flightgear.org/viewtopic.php?f=4&t=25157&sid=7ec255e8c71cf543322693b0bbd910ce&start=1305#p242180
the controls of mixture and throttle by rolling the mouse scroll wheel are counter-intuitive.
I can invert these controls by
(Models/c172p-detailed.xml, lines 2415 and 2370)

```xml
<action>
    <binding>
        <command>property-adjust</command>
        <property>controls/engines/engine[0]/mixture-lever</property>
        <factor>-0.05</factor> <!-- initially 0.05 -->
        <min>0</min>
        <max>1</max>
        <wrap>0</wrap>
    </binding>
</action>  

<action>
    <binding>
        <command>property-adjust</command>
        <property>controls/engines/engine[0]/throttle</property>
        <factor>-0.05</factor> <!-- initially 0.05 -->
        <min>0</min>
        <max>1</max>
        <wrap>0</wrap>
    </binding>
</action>
```

With this, the levers move in the same direction as your finger.
The drawback is that the left and center click actions are inverted too.
They ***would*** become:
Left Click : decrease
Wheel Click (center):  increase

My opinion is that most people rather use the scroll wheel.
1 - What do you prefer?
2 - Are these lines the right ones to modify? (the values still vary in the expected direction!)

**Comment by onox** [comment]
I always use the scroll wheel, so inverting the throttle and mixture is OK for me :+1:

**Comment by gilbertohasnofb** [comment]
Same for me (y)

**Comment by dany93** [comment]
Done.
PR https://github.com/Juanvvc/c172p-detailed/pull/161
