### ISSUE TITLE
Back side of the propeller should be black

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#157]
by tigert:

> The propeller tip stripe and the sticker in the propeller, at least in the OH-CTL livery, only appear in the front side of the blades. The backside is black, to avoid flickering and glare especially when flying away from the sun. The frontside has the stripe, to make the spinning prop more visible for people on the ground when taxiin etc, so people don't accidentally walk into a spinning propeller. So from the cockpit, it should be just black / dark gray blades. When the prop has a lot of hours after maintenance, the paint might have worn out due to rocks marks etc from flying into gravel runways and water splashes. Many times the mechanic seems to have a can of matt black spraypaint around to paint over the dents, so it is not so disturbing in flight.

If all liveries should have a completely black propeller in the back, we have two solutions: we can make the propeller 3D object black and make it untexturized in the cockpit side for all liveries (cheapest and fastest solution), or have two propeller images in the livery files, one for the front and one for the back, for each livery. Personally, I think we can first try the untexturized and cheap solution and to see how it looks. If it doesn't work, then I can do something like this for all liveries: http://s15.postimg.org/qjy4iu17v/fuselage.png

What do you say?

**Comment by onox** [comment]
@gilbertohasnofb What's the best looking solution and can it be fixed this week?

**Comment by gilbertohasnofb** [comment]
@onox this should be a very easy fix for someone who knows Blender. Simply make the whole propeller object black and remove the texture mapping in the back of the propeller. While at it, maybe we could also check #159.

**Comment by gilbertohasnofb** [comment]
@wlbragg do you think you could give us a hand with this? I tried having a look at it myself, but I still can't wrap my head around Blender... :cry:

**Comment by onox** [comment]
Can we just move all this 3D modeling stuff to 3.8 instead?

**Comment by gilbertohasnofb** [comment]
I would still like to leave this one in particular opened. This is really such an easy fix for someone who knows Blender that I still think we can fix this before our deadline. Let's say if until tomorrow we don't have this done then we close it, would that be fine?

**Comment by wlbragg** [comment]
Yes, let me look at it.

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks a lot!

**Comment by gilbertohasnofb** [comment]
and by the way, if you need a texture for the backside of the propeller for any reason, I can prepare it in literally 5 minutes.

**Comment by onox** [comment]
Ok, just make sure the `.ac` file gets properly exported.

**Comment by wlbragg** [comment]
Yes, sir. It may be late tonight before I have anything to show.

**Comment by wlbragg** [comment]
How does the UV map work for all the livery's? Does each livery have it's own UV map that would have to be changed?
Also I went ahead and downloaded the new version of Blender because it was definitely going to be a problem trying to use the older version now that it was saved with a newer version. All modelers need to beware.

**Comment by gilbertohasnofb** [comment]
> This is beyond my current abilities.

No problems, so let's move this to 3.8 release and later we can ask @Juanvvc or @dg-505 if they could give us a hand.

**Comment by gilbertohasnofb** [comment]
@wlbragg I was thinking about this issue and I think it's better to create a black texture and add to the back of the propeller instead of making it untexturized (we already saw the plethora of problems that untexturized objects can cause). So if I create a texture for the back side of the propeller would you give me a hand applying it?

**Comment by gilbertohasnofb** [comment]
I created a new branch `bug-157` and added new textures to all fuselages (and paintkit as well) containing the back of the propeller. See:

![fuselage](https://cloud.githubusercontent.com/assets/5700795/8765700/7b788098-2e1a-11e5-8405-5ad7028758bc.jpg)

**Comment by wlbragg** [comment]
>So if I create a texture for the back side of the propeller would you give me a hand applying it?

I'll see what I can do!

**Comment by wlbragg** [comment]
See  Bug 157 #433
