### ISSUE TITLE
Better texture mapping of the baggage door

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#158]
The fuselage texture shouldn't be shifted in the baggage door (at least not by that much). See: http://s15.postimg.org/c026f7tez/fgfs_screen_005.png

**Comment by dg-505** [comment]
See pull request #188

**Comment by gilbertohasnofb** [comment]
@dg-505 has this correction been lost due to the pull request https://github.com/Juanvvc/c172p-detailed/pull/188 not being accepted?

**Comment by dg-505** [comment]
Unfortunately this fix indeed has been lost. I can correct it again in the c172p-detailed.blend, but because I don't know how to export it properly to the .ac file I would only push the .blend file so that someone with more knowledge about Blender can export it.

**Comment by gilbertohasnofb** [comment]
> I would only push the .blend file so that someone with more knowledge about Blender can export it.

That could work, we could ask @Juanvvc if he can do it. Also, you could try asking about the .ac export in our forum thread, certainly someone there would explain it to you. Thanks a lot!

**Comment by dg-505** [comment]
Okay, I'm gonna do it later today, because at the moment I'm not at home.

**Comment by gilbertohasnofb** [comment]
No rush, Jonathan!

**Comment by dg-505** [comment]
Roger :smiley:

**Comment by gilbertohasnofb** [comment]
I believe this has been corrected, right? I am closing this issue, but let me know if there is still any work to be done on thus UV map.
