### ISSUE TITLE
Propeller does not get darker with overcast sky

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#159]
The model shader full on, the propeller does not get darker in an overcast day. See:

![fgfs_screen_004](https://cloud.githubusercontent.com/assets/3361585/8564420/107ffed2-254c-11e5-9ab4-755e37dfd66e.png)

**Comment by wlbragg** [comment]
I was looking at this and I have some questions.
What is the "Specularity fix"?

Propeller is NOT included, but it didn't help when I tried to include it.


 <animation>
	 <type>material</type>
	 <object-name>LeftWheelStrut</object-name>
........
	 <object-name>elevatorleft</object-name>
........
	 <object-name>wing_1</object-name>
........
	 <shininess>128</shininess>
	 <specular>
		 <r>1</r>
		 <g>1</g>
		 <b>1</b>
	 </specular>
	 <ambient>
		 <r>1</r>
		 <g>1</g>
		 <b>1</b>
	 </ambient>
 </animation>

Towards the end of Models/c172p-detailed.xml
"Materials"

is this a typo/mistake
<texture>fuselage.deeqa.png </texture>
shouldn't it be
<texture>fuselage.png </texture>

<animation>
   <type>material</type>
   
   <object-name>RightWheelStrut</object-name>
 ........
   <object-name>leftdoor</object-name>
 ........
   <property-base>sim/model/livery/</property-base>
   <texture-prop>texture</texture-prop>
   <texture>fuselage.deeqa.png </texture>
 </animation>

And in
Effects/bumpspec-fuselage
Propeller is NOT included, but it didn't help when I tried to include it.
But I read that this effect only works WITHOUT ALS or Rembrandt active.

I looked at normals in ac and they looked NORMAL:)

**Comment by wlbragg** [comment]
"And in Effects/bumpspec-fuselage, Propeller is NOT included, but it didn't help when I tried to include it. But I read that this effect only works WITHOUT ALS or Rembrandt active."
This must have been outdated because bumpspec is working with ALS, in fact, I think ALS is required.
But I still cant figure out where the problem with the shading is.

**Comment by gilbertohasnofb** [comment]
> But I still cant figure out where the problem with the shading is.

In that case, we maybe should move this to the 3.8 release milestone, what do you think @onox?

**Comment by onox** [comment]
Agreed.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/597
