### ISSUE TITLE
Some instrument are poorly positioned

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#160]
Some instrument are poorly positioned. They are:

- the ADF indicator should go slightly down (notice the light grey area in the lower side of the gauge): http://s10.postimg.org/xx79eop55/fgfs_screen_001.png
- fuel and oil gauges are cut (notice how some numbers and words have parts cut, such as the F letter in the word Fuel , or the number 7 in 75 degrees: http://s12.postimg.org/wj8oszqot/fgfs_screen_002.png

**Comment by dg-505** [comment]
Solved. See pull request #187.
