### ISSUE TITLE
Saving switch states implemented as an option

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#164]
Currently all switches are saved from flight to flight. As ludomotico pointed out in the forum, a probably better alternative would be to have this optional (set in the option menu), as some users who quit FG mid-flight would prefer to have an option for "everything off".

**Comment by Juanvvc** [comment]
wkitty42 in the forum:

"if you use the autostart, it tells you to release the brakes via SHIFT-B but the brakes are not set in the automated startup.."

Automatically run the "everything off" command before the autostart.

**Comment by onox** [comment]
Where are these switches saved or registered in our project?

**Comment by gilbertohasnofb** [comment]
Maybe this could be implemented before the feature freeze, what you guys think (what about you, @wlbragg)? I imagine a lot of people will hate that the switches' state is saved, particularly those who tend to quit FG mid-flight. How difficult is this task?

**Comment by onox** [comment]
How about if you properly exit FG while on the ground, the state is saved, otherwise not?

**Comment by onox** [comment]
I've assigned the 3.6 feature freeze milestone. We can always postpone it if necessary.

**Comment by gilbertohasnofb** [comment]
> How about if you properly exit FG while on the ground, the state is saved, otherwise not?

This will be cryptic to most users, I think. They will not be able to recognize this feature and consider it a bug: "why sometimes the state is saved and others not?". The most trivial solution (and the best IMO) is to have a toggle in the aircraft options menu.

**Comment by wlbragg** [comment]
"How about if you properly exit FG while on the ground"
What property is in play here that you can tap into to save these states under this condition?

"Where are these switches saved or registered in our project?"
Where?

**Comment by onox** [comment]
> What property is in play here that you can tap into to save these states under this condition?
> This will be cryptic to most users, I think. They will not be able to recognize this feature and consider it a bug: "why sometimes the state is saved and others not?". 

Maybe yes. Perhaps it's better to have the following buttons in the standard exit-flightgear dialog:

1. "Exit without saving state"

2. "Save state and exit"

3. "Cancel"

To be honest. I hope there's a signal that we can attach a listener to, but I'm not sure.

> Where?

I don't know. Somebody else made sure that you start with the same aircraft state as when you closed FG.

**Comment by gilbertohasnofb** [comment]
> Perhaps it's better to have the following buttons in the standard exit-flightgear dialog

But that will cause some unnecessary  nagging to users. I mean, once you set you preferences you shouldn't have to choose the same thing for the rest of eternity, right? :smile: I still prefer a single toggle in the aircraft option menu (and this toggle should be off by default -- actually, we have to make sure that a lot of these initial states will be correct before FG 3.6 ships, such as lights off, panel lights off, parking break on, etc.).

> I don't know. Somebody else made sure that you start with the same aircraft state as when you closed FG.

This was done in the pre-GitHub days. I can't remember who implemented, but surely this must be somewhere in our forum thread. Maybe @Juanvvc remembers it better than I do.
