### ISSUE TITLE
Strange 3D object above air vent lever

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#179]
See: http://s2.postimg.org/t488b92t5/fgfs_screen_001.png

Was this created on purpose? If so, what is it? It does look a bit strange to me.

**Comment by Juanvvc** [comment]
It is part of the radio panel. I don't know why it is there, but it is like this also in the original c172p. I don't know why it didn't appear until now, probably a z-fighting issue with the right side of the panel.

I'm quite sure it is a bug and I'll remove the object. Thanks.

**Comment by gilbertohasnofb** [comment]
Thanks Juan. I have the impression it appeared when the air vent lever was remodelled, but I may be wrong on that. Anyway, thanks for fixing it!

**Comment by dg-505** [comment]
Solved. See pull request #187
