### ISSUE TITLE
Propeller blades and wing lights do not change their texture when changing liveries and themes

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#18]
3D17 - Propeller blades and wing lights do not change their texture when changing liveries and themes.

**Comment by gilbertohasnofb** [comment]
Could someone that works in Blender do this? Should be just a couple of clicks to make it change according to the livery file instead of always using the textures located in the Model folder.

**Comment by Juanvvc** [comment]
Done. Please, check. Actually, this is not done in blender but it is a very simple change in the XML file :) You have to add the objects Spinner, LeftNavLight and RightNavLIght to the XML animation that manages liveries.

**Comment by gilbertohasnofb** [comment]
Checked, all is working well! I will now add the propeller and the wing lights to all the older liveries (see https://github.com/Juanvvc/c172p-detailed/issues/139).

**Comment by gilbertohasnofb** [comment]
> Actually, this is not done in blender but it is a very simple change in the XML file :) You have to add the objects Spinner, LeftNavLight and RightNavLIght to the XML animation that manages liveries.

I am trying to understand this, Juan. Which xml file is this? Could you point me out which file and which line is the one regarding the spinner, for instance?
