### ISSUE TITLE
float parts in 2d shadow?

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#193]
i've just loaded commit c3fa9fd6a8... in heli view, there's two weird shark fin looking things in the shadow near the tail area... they are not laying flat on the ground but are perpendicular to it... i have not selected floats at this point... just loaded and stepped out to look...

![fgfs-screen-018a](https://cloud.githubusercontent.com/assets/4641713/7708028/086ddd92-fe21-11e4-9fa9-fae19c054c5d.png)

**Comment by wkitty42** [comment]
here's another shot with the ""fins"" lifted all the way up via the use of the 36" bush wheels ;)

![fgfs-screen-019](https://cloud.githubusercontent.com/assets/4641713/7708179/0b0d78c2-fe22-11e4-9a20-a8fe96f1b2c8.png)

**Comment by wlbragg** [comment]
wkitty42, if you noticed the commit right after c3fa9fd. This should have fixed this. Would you please check and close this issue if fixed?

**Comment by wkitty42** [comment]
i just updated to the latest commit at this time [66b6fa6a]... i didn't notice when the "shark fins" were fixed but i can confirm that they are gone now... i'm not sure how to back up to previous commits to test their changes... not that that is a big deal right now ;)
