### ISSUE TITLE
Create float textures for all liveries

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#195]
Create float textures for all liveries

**Comment by gilbertohasnofb** [comment]
List of liveries which will have their own float texture (risked ones are already uploaded):

4X-CHV
EI-MCF
N301DP
N35799
~~OH-CTL~~
~~PT-IAO~~
ZS-MDF

**Comment by wkitty42** [comment]
i've been flying N35799 recently... no special reason but i'll take a look at some of the others in a bit :)

**Comment by gilbertohasnofb** [comment]
Yeah, I also like the N35799 :smile:. I hope tonight I will manage to finish all these float textures

**Comment by wkitty42** [comment]
sounds like a plan... i might drop by and pick up the paint kit and see if i can do one of my charcoal black with no shininess :smiley_cat:

**Comment by gilbertohasnofb** [comment]
Sure, go for it! Let me know if you need any help :smile:

**Comment by gilbertohasnofb** [comment]
Done.
