### ISSUE TITLE
broken or misplaced strut??

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#198]
what's this thing hanging out above the rear pontoon brace right below the passenger side door? there is not one like this on the pilot's side... i don't find anything like it in any c172p pictures, either...

![fgfs-screen-022](https://cloud.githubusercontent.com/assets/4641713/7725528/892bb852-fec9-11e4-9411-c0bdf7a7a02d.png)

**Comment by Juanvvc** [comment]
Oh, my fault! I introduced the error this morning. Will fix asap!

I'm very sorry!

**Comment by wkitty42** [comment]
not a problem... i think i discovered that it is one of the old wheel struts...

**Comment by Juanvvc** [comment]
Yes, it is. I guess I changed the name of the object and it is not marked for deletion when the pontoons are selected.

It is just a few seconds to fix :)

**Comment by wkitty42** [comment]
fix confirmed :smile_cat:
