### ISSUE TITLE
Checklist: Turn on beacon light before starting the engine

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#2]
Correction to the checklist: it is common practise to have the beacon light ON before starting engine, not after (it helps to warn people around that you are about to start the plane)

Should I add this to the "Before Starting Engine" checklist at the end or to "Starting Engine" at the top?

**Comment by gilbertohasnofb** [comment]
I think the best place is on top of "starting engine" (according to this: http://www.birrfeld.ch/fileadmin/user_upload/Flotte/Cessna_172.pdf )

**Comment by onox** [comment]
Okay :+1:

**Comment by gilbertohasnofb** [comment]
Previously, in the TODO file, it was marked as PRC09 - correction to the checklist: it's common practise to have the beacon light ON before starting engine, not after (it helps to warn people around that you are about to start the plane)
