### ISSUE TITLE
create both high resolution (2048x2048) and regular resolution (1024x1024)

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#20]
TEX02 - create both high resolution (2048x2048) and regular resolution (1024x1024) of HD liveries and allow the user to switch among them (such as by using two different liveries, one called "OH-CTL (HD texture)" and the other simply "OH-CTL")

**Comment by wlbragg** [comment]
Can we close this?

**Comment by gilbertohasnofb** [comment]
Yes!
