### ISSUE TITLE
weird behaviour on water landings

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#200]
When landing on water, the airplane will be slingshot back in the air at high speed, in a strange attitude, while spinning and with broken wings.

Here is how to reproduce it:

- start with the pontoons on a regular runway
- position the aircraft in the air (e.g. 2000 ft)
- try landing on the water
- as soon as you touch the water, the plane will go crazy

This does not happen when taking off with regular wheels and changing to pontoon mid-air (that is, switching mid air to pontoon allows me to have a regular water landing as expected!).

**Comment by dg-505** [comment]
I suggest to create a seperate version of the c172p-detailed with floats by using a seperate -set.xml (something like c172p-detailed-floats-set.xml) and remove the "Float" option in the aircraft dialog. It would be more realistic, if you can't switch between wheels and floats during flight. As a side effect, this bug no longer occurs most likely.

**Comment by gilbertohasnofb** [comment]
Sure, that's an option, but you may have misunderstood me: the switch is NOT causing this bug, what is causing it is to position the aircraft in the air.

**Comment by dany93** [comment]
Just an hypothesis: at start, JSBSim does a calculation (sometimes messages with iterations, qdot and trim...).
I rarely see these messages, but when I start in the water I have them. JSBSim searches to stabilize the aircraft taking into account its suspension.
If you start with the pontoons on a regular runway, the iterations may converge on wrong values.
In this case, that would not be a bug.

**Comment by gilbertohasnofb** [comment]
I have seen other aircrafts behave strangely when using the position in the air option, so that may be one more quirk to this option.

**Comment by dg-505** [comment]
@gilbertohasnofb I understood you, but if you have a seperate c172p-float, you can select the undercarriage <i>before</i> the flight and choose an appropriate start-location before launching FG. That way this bug would not be solved, but it would no longer occur.

**Comment by dany93** [comment]
The drawback of having several FDMs is their management (to implement a new feature on each one).
The advantage is that every one is more simple...

If someone switches between wheels and floats during flight, realism is not his concern....

**Comment by gilbertohasnofb** [comment]
@dg-505 currently the selection of wheels or float is persistent, so next time you load the sim it will remain. The bug will still be present even with two -set.xml files because it's solely due to the fact that I positioned the aircraft in the air. At no times I switched to or from wheels, I started the sim with pontoons, and the bug occurs.

**Comment by wkitty42** [comment]
FWIW: in my testing/playing with the pontoons, the only reason i have taken to switching from wheels to pontoons while in flight is for control on the ground... i fully understand that this is a WIP and eagerly await the pontoons with wheels as well as refined FDM(s) to handle them and hopefully provide a little more control than is currently available :smiley_cat:

**Comment by wlbragg** [comment]
First thought, WIP, I think we can iron some of this stuff out, I just haven't had the time since we became aware of some of these bugs.

"warning message for the start location"
I don't remember where I posted the idea, but I think this or something like this may be the way to go. Maybe even not allowing non-amphibious start up on anything but water.

Let me get the amphibious version finished and then we can look at it in more detail. If someone comes up with acceptable fixes in the meantime, that's OK too.

**Comment by wlbragg** [comment]
The slingshot I haven't experienced though. It sounds like the same behavior we had on land when you crashed. I need to reproduce it and then maybe I can figure out what's causing it. Sounds like a needed contact point or adjustment.

**Comment by wlbragg** [comment]
I just experienced something equally bizarre. When starting aircraft in air, with floats checked by default, the aircraft floats stick into the water and you stop with the floats submerged. I ended up with two radio buttons selected at the same time. This obviously has to do with the strange effects of init. All these little bugs are going to need some investigating and we are going to have to isolate all their causes. I think we will find that in most cases it will be tied to switching things on the fly. But I think we can get a handle on it once we know the specifics..

**Comment by gilbertohasnofb** [comment]
> First thought, WIP, I think we can iron out some of this stuff, I just haven't had the time since we became aware of some of these bugs.

That's of course very reasonable, wlbragg! I am reporting here so we don't forget/miss anything, but we all can take our time to solve these things. Please don't feel like I am pushing or complaining, ok? Really not my intention.

**Comment by wkitty42** [comment]
i'm doing the same as gilberto... just making sure we don't lose sight of things... even in a WIP :smile_cat:

**Comment by wlbragg** [comment]
No worries,
I can confirm the "slingshot" is related to the other problem of sinking in the water. See the thread http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1605#p243845
It is happening because your bug/error is "there are no contact points".
THe bug is that the contact points aren't being created. I still haven't isolated the cause.

**Comment by wlbragg** [comment]
I changed metric contacts to match the rest of the imperial. See if this changes anything or fixes your float problem. I'm sure it's wishful thinking on my part.

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pulled the lastest version, and both bugs are still present, including the slingshot bug.

**Comment by gilbertohasnofb** [comment]
Also, I am usually auto-starting the plane for these tests, just in case that information may be handy to diagnose it.

**Comment by wlbragg** [comment]
"and both bugs are still present, including the slingshot bug"
Just know they are one and the same bug. They will both go away once we figure out why your contact points aren't initializing.
Can you rename your
"hidden FG folder on my home at /home/gilberto/.fgfs, which contains some subfolders, autosave files, log files, navdata and terrasync cache files, etc"
and let FG rebuild your user data and see if that fixes this?
I say "rename" so you retain the original settings in case we need to use them to troubleshoot and in case in Linux install you can reverse this if it breaks something.

**Comment by gilbertohasnofb** [comment]
> Just know they are one and the same bug. They will both go away once we figure out why your contact points aren't initializing.

But if they are the same bug, then why am I able to take off on wheels, change to floats, land softly (no slingshot) but still the pontoons get underneath water?

> Can you rename your hidden FG folder

Just did that, still no cigar... the plane was loaded with pontoons under water (started with floats on the seaport SP01)

**Comment by wlbragg** [comment]
In the sim check
Debug/properties/fdm/jsbsim/contact/unit[13]
and tell me how many lines or items are in there.

do the same for
Debug/properties/fdm/jsbsim/contact/unit[17]

**Comment by wlbragg** [comment]
For one, on land your using different contact points now and they may be initializing correctly. That's what you're  checking now.

**Comment by gilbertohasnofb** [comment]
unit[13]:
`.
..
compression-ft = '' (none)
z-position = '0' (double)`

I don't have unit[17].

**Comment by wlbragg** [comment]
Pull the newest commit and try it, then report the  same info.

**Comment by wlbragg** [comment]
You should have 11 data points in that contacts folder, you only have 2. It is because it is not initializing correctly from the FDM, why, I don't know yet.

**Comment by gilbertohasnofb** [comment]
Just pulled it, I have only 2 data points for unit[13] and 1 data point for unit[17].

**Comment by wlbragg** [comment]
Wow, what is the data point on 17?

**Comment by gilbertohasnofb** [comment]
It's `z-position = '0' (double)`

**Comment by wlbragg** [comment]
What have you done that would be different than everyone else, same for me when I fell into this problem?
Why when you clear out your user data it doesn't fix it, yet mine does?
Did you try the dhc2 lately?

**Comment by gilbertohasnofb** [comment]
I was trying to think about this as well, but nothing comes to mind. Tomorrow I will probably have some time to pull the newest version of fgdata and then I will make some more tests. I think I do have the dhc2 installed, but I never really tried it out - I will do it as soon as I can, ok?

**Comment by wlbragg** [comment]
OK, I'll post the question, what can cause the contact points to NOT initialize.

**Comment by onox** [comment]
I just tried the pontoons again and they are very fun (not doing any repositioning, just changing the "tires" in the aircraft options). Although, I cannot get the aircraft to ditch into the water when pushing the yoke at high speed.

But the amphibious does not work so nicely on the water. On the runway it works nicely, but on the water it has a very high resistance/drag. I can land in an extremely short distance, and taking off is impossible. Even with full throttle. If I change back to pontoons, I immediately start moving and I can take off.

**Comment by wlbragg** [comment]
Put up the landing gear "g G" :)

**Comment by gilbertohasnofb** [comment]
> Put up the landing gear "g G" :)

Will we need to add a switch/lever/button for that in the cockpit? How is the amphibious landing gear controlled in RL?

**Comment by wlbragg** [comment]
I don't know, but the same key that controls the regular landing gear works on the amphibious landing gear (purely by accident) I didn't do anything to make it work, it just did. So I didn't check anything out about it either
I assumed whatever lever the default gear uses, (if we even have one, I don't think I ever used it), should work with the amphibious?

**Comment by gilbertohasnofb** [comment]
@wlbragg I don't think any standard 172 have retractable landing gears. About the amphibian, I read that there is a lever in the cockpit, but I can't find images of it. If you are curious, this pdf seems to have some nice info about the system: http://www.wipaire.com/pdf/service_manuals/1002549.pdf

**Comment by wlbragg** [comment]
Duh, I don't know what I was thinking, brain fart I guess :)

**Comment by wlbragg** [comment]
Nice service manual! Very helpful. Now all we have to do is find a picture.

If we add a interior panel for the gear controls, we can use a "select animation" like we do on any other model to remove or show it depending on whether or not the amphibious is selected, right?

**Comment by gilbertohasnofb** [comment]
> If we add a interior panel for the gear controls, we can use a "select animation" like we do on any other model to remove or show it depending on whether or not the amphibious is selected, right?

I guess so. About the lever, since it seems that these systems seem to be installed by the aircraft owners rather than being manufactured like that, my guess is that the lever won't be in the panel itself but rather somewhere else (maybe on the floor or something like that). But this is a completely uneducated guess from my side :wink: 

I am trying to find pictures of an amphibian cockpit for the past 45 minutes, but I can't find anything... let's ask @tigert or @Juanvvc if they ever encountered an aircraft like this in RL and know where the lever is.

**Comment by gilbertohasnofb** [comment]
> I am trying to find pictures of an amphibian cockpit for the past 45 minutes, but I can't find anything...

The irony of life. Just find one, and it seems to be indeed on the floor: http://www.wipaire.com/Wipaire-Dev/piwigo/i.php?/upload/2012/06/18/20120618091859-cfcacdce-sm.jpg

This cockpit above is slightly different than ours, but I guess we can take a "poetic license" and simply add a lever like that where it fits. Remodelling the cockpit for this would be too much trouble for too little gain IMO.

**Comment by wlbragg** [comment]
I agree, it will only show in amphibious, so simple is best.

**Comment by gilbertohasnofb** [comment]
Ok, so basically we need three things:

- a simple 3D lever on the floor of the cockpit
- textures for the lever (could be added to panel_parts.png)
- animation and programming of the lever

I opened the issue https://github.com/Juanvvc/c172p-detailed/issues/206 for this.

**Comment by wkitty42** [comment]
this new lever will still be tied to the g/G key, though, right?? i think that is really as it should be even though gear movement doesn't normally happen without this 3rd party upgrade of the craft...

**Comment by gilbertohasnofb** [comment]
> this new lever will still be tied to the g/G key, though, right??

Yep.

**Comment by wlbragg** [comment]
I think we can close this issue except we have a team member that can't even use the float plane on water. However I am convinced it is a FG core setup issue and not the c172p-detailed. I have reproduced this bug and the only way I was able to correct it was to basically reinstall FG to a clean state. It is for sure that this happens because the contact points do not register in the FDM, it is the WHY we can't figure out, but it appears to have to do with a confused core FG setup.

**Comment by gilbertohasnofb** [comment]
I agree with you, wlbragg. Once I get a chance I will reinstall my FG and see how it behaves, but in the meantime we can close this. If after fixing my installation the problem appears again I will let you know, but I can't believe that will be the case.
