### ISSUE TITLE
Windshield wipers

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#203]
Something we can check into down the road. Do they include wipers in a Cessna? If so, once again,Thorsten has given us the ability to use a wiper overlay effect. It would be nice to add it at some point.

**Comment by gilbertohasnofb** [comment]
I have never seen a picture of a Cessna 172 with wipers, but let's ask @tigert and @Juanvvc about it.

**Comment by tigert** [comment]
No wipers in 172.

**Comment by wlbragg** [comment]
So we close this?
