### ISSUE TITLE
KT-70 legacy instrument

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#204]
i'm seeing the following lines in my fgfs log i don't know the details to fix this but i have seen it mentioned somewhere... maybe not this instrument but a similar "legacy instrument" message...

```
cockpit:3:/home/myuser/flightgear-dev/next/flightgear/src/Instrumentation/instrument_mgr.cxx:76:Reading instruments from /home/myuser/myflightgear/Aircraft/c172p-detailed/Systems/instrumentation.xml
instruments:4:/home/myuser/flightgear-dev/next/flightgear/src/Instrumentation/heading_indicator_dg.cxx:42:Error in DG heading-indicator config logic
instruments:4:/home/myuser/flightgear-dev/next/flightgear/src/Instrumentation/heading_indicator_dg.cxx:44:Section = heading-indicator
instruments:4:/home/myuser/flightgear-dev/next/flightgear/src/Instrumentation/instrument_mgr.cxx:185:KT-70 legacy instrument compatibility. Please update aircraft to use transponder directly
```

**Comment by onox** [comment]
@wkitty42 Does the C172p have a vacuum-based heading indicator or is it electrically powered?

**Comment by tigert** [comment]
The C172P manual is useful for questions like these - and good reading for the general idea of how things work. It's actually easy to find several versions via google, this is one C172P:
http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf

Page 166 states that the artificial horizon and directional gyro (heading indicator) are vacuum-based. Thus I think the turn/bank instrument is electric for redundancy reasons, so you have a working gyro if your vacuum system breaks down.

//Tuomas

**Comment by onox** [comment]
Thanks, I think the heading-indicator-dg needs to be changed to heading-indicator then, because the -dg version is electrically based.
