### ISSUE TITLE
Create landing gear lever for amphibian model

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#206]
Create landing gear lever for amphibian model: http://www.wipaire.com/Wipaire-Dev/piwigo/i.php?/upload/2012/06/18/20120618091859-cfcacdce-sm.jpg

Basically, it needs three things:
- a simple 3D lever on the floor of the cockpit
- textures for the lever (could be added to panel_parts.png)
- animation and programming of the lever

**Comment by wlbragg** [comment]
Different model Cessna but the same concept I think. thttp://www.trade-a-plane.com/jhimage?id=1374753&keywords=1981%20Cessna%20185F%20-%20Listing%20%23%3A%202068369+%2318&width=573&height=430

**Comment by gilbertohasnofb** [comment]
I think the picture I posted above is also from a different model (it's surely not a 172, even though that's what I was searching), and it looks fairly similar to what you posted. Nevertheless, if we don't find any RL information, then this idea of putting a long lever on the floor sounds quite plausible. And if anyone complains this is not realistic because his/hers amphibian 172 has a lever in a different place, we can always argue that this is not any amphibian system but rather "wlbragg's system" :wink:

**Comment by Juanvvc** [comment]
That lever is quite similar to the flaps lever in a Piper PA28. Probably, we can share the model with the Piper Archer CX project.

**Comment by gilbertohasnofb** [comment]
> Probably, we can share the model with the Piper Archer CX project.

That's a clever idea!

**Comment by tigert** [comment]
I think that is the flap lever in those pictures. I would guess very old C172 models had mechanical flaps. Let's research a bit before modelling :-)

**Comment by tigert** [comment]
For the Wipaire amphibious floats, the gear retraction handle and status lights seem to be combined into a round instrument-face it seems: Page 102 and 104: http://www.wipaire.com/pdf/Parts_Manuals/PM_2350_Cessna172.pdf

That has good reference photos for the modelling in any case, also side view for checking measurements and angles etc.. Closeups also for the gear mechanism and such.

**Comment by wkitty42** [comment]
i did some looking to see if i could find some interior panel pictures with one of these controls on it... i didn't find anything, though... i did, however, look through the above linked PDF and another on the same site for the same product (2350 floats) and i found some info in the other one concerning weight... i didn't look close enough to see if there was anything about drag, though...

FWIW: of the two controls shown in the above PDF, perhaps the square one would fit over on the passenger side control panel area where the circular blank spot is located near the radio stack? it is up high enough to be easily seen and easily reached by the pilot to be able to raise and lower the gear... being able to see the green light for land on land and the blue ones for landing on water will be a big help...

one last thing i found in that other PDF that kinda surprised me... it said that steering is done on land with differential breaking... here i've just been using the rudder on land and on water but i guess it makes sense :laughing:

**Comment by tigert** [comment]
http://upload.wikimedia.org/wikipedia/commons/0/0a/7PANEL_03_01_08.jpg

Also, for performance, the amphibious C172's likely won't have the 160hp engine. OH-CTL has 180, and I would guess the C172 Hawk XP variant is one that could go well with floats too, having a constant speed propeller and more power. From wikipedia:

> R172K Hawk XP, a model available from 1977 to 1981 from both Wichita and Reims. This configuration featured a fuel injected, Continental IO-360K (later IO-360KB) derated to 195 hp (145 kW) with a two-bladed, constant-speed propeller. The Hawk XP was capable of a 131-knot (243 km/h) cruise speed.

> Owners claimed that the increased performance of the "XP" didn't compensate for its increased purchase price and the higher operating costs associated with the larger engine. The aircraft was well accepted for use on floats, however, as the standard 172 is not a strong floatplane, even with only two people on board, while the XP's extra power improves water takeoff performance dramatically."

**Comment by gilbertohasnofb** [comment]
@tigert that cockpit you posted above is actually from a Cessna 206 Stationair, more specifically this one: http://cdn-www.airliners.net/aviation-photos/photos/4/6/7/0650764.jpg

**Comment by tigert** [comment]
Yes  I know, I actually even mentioned it above.

But I bet Wipaire has a common "gauge" for the lights + gear switch that is the same for each aircraft model they put the floats in, as there is no real reason to have differences there. So we could perhaps use that as a reference?

**Comment by gilbertohasnofb** [comment]
> Yes I know, I actually even mentioned it above. :-)

Gosh, I am getting demented, I totally oversaw that.

>  So we could perhaps use that as a reference?

Sounds good. If anyone makes a 3D model, just let me know so I can make the textures.

**Comment by Juanvvc** [comment]
Ok, I'll do the model. The only thing is that we must decide its position in the panel.

The aircraft in the reference picture has a HSI and it does not need one of the VORs. But what about our panel? Do you mind losing the ADF? Do you think moving the ADF into the left side of the panel is a good idea? Only if the pontoons are installed, of course.

**Comment by gilbertohasnofb** [comment]
> Do you mind losing the ADF?

I think that would be a big loss as NDB's are a standard part of IFR navigation, right? 

> Do you think moving the ADF into the right side of the panel is a good idea?

Now we are talking :D That could work out well I think.

**Comment by tigert** [comment]
I think it should be close to the place it is in the photo, so it is easy to reach. There are two logical places: the current EGT, and ADF positions.

I think the gear switch / indicator gauge should replace of the current ADF. The EGT position is too close to the yoke, so it might interfere.

We could move the ADF one slot to the left, over the current EGT and move the EGT to the extra gauge hole on up on the right side, closest to the radio stack.

```
( airspeed ) ( attitude ) ( altimetr ) (  vor1     )  |        |  ( egt )
                                                      | radios |
( turnslip ) ( dir-gyro ) ( variomet ) (  vor2     )  |        |
                                                      |        |
(  rpm     ) (  *yoke*  ) (   ADF    ) (  GEAR     )  |        |
```
This might work

**Comment by gilbertohasnofb** [comment]
@tigert I like this idea!

**Comment by wkitty42** [comment]
i could probably work with that... as long as it is easy to see the blue and green gear indicator lights ;)

i'm guessing this item will also tie into one of the electrical breakers?

**Comment by tigert** [comment]
Yeah. You should study the pages 17 and 18 of the Wipline service manual ;-) Less guesswork, more schematics to get it right. There is a hydraulic pump that is operating the gears, each gear has two microswitches (gear up, gear down) that runs the indicator lights logic. I would guess you could also do it so, that if you damage the pontoons in a hard landing but somehow miraculously manage to go around, the gear indication would not work anymore, as the structure might be bent etc..

http://www.wipaire.com/pdf/service_manuals/1002549.pdf

There is also an emergency hand pump to lower the gear, I don't know where that handle is, we need to study more.

//Tuomas

**Comment by Juanvvc** [comment]
Moving the EGT to the right side of the panel is a much better idea, tigert. I'll try to make an initial implementation of this gear control instrument tomorrow.

**Comment by gilbertohasnofb** [comment]
@Juanvvc will we need new textures for the gear lever? If so, can you explain to me how can I help?

**Comment by Juanvvc** [comment]
First the model, then UV-Map and finally the texture :) I'll make a temporal texture for you to run your magic.

**Comment by gilbertohasnofb** [comment]
> I'll make a temporal texture for you to run your magic.

That's how I like it best as well! :smile:

**Comment by onox** [comment]
Is anyone working on this? If not, then we should set the milestone to 3.8 feature freeze.

**Comment by gilbertohasnofb** [comment]
Please have a look at http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=247740#p247740

**Comment by wlbragg** [comment]
I saw that, makes sense to use it until or unless we find or make one that is more realistic to the c172p. The picture someone posted of the add-on switch bank that sits on top of the front edge of the dash is an actual RL working device. I don't know if it was on a c172p or not though.

**Comment by gilbertohasnofb** [comment]
@wlbragg agreed. But if we implement his switch I would still keep this thread opened and update the description according to what you wrote above. So if you merge his contribution, could you please let me know here?

**Comment by wlbragg** [comment]
I agree, I want to eventually end up with a RL replica (I don't know that the one that abassign copied from the DHC6 isn't a real after market product that could have been used for various models of aircraft and even more, it is possible one could be manually cut into the dash like that, I did it in boats before, different instruments)

Speaking of thanks, copyrights, etc.. I don't know that I ever attributed any of the pontoon source I used from the dhc2, do I need to add that somewhere?

**Comment by wlbragg** [comment]
Lets have onox's opinion on using abassign contribution, if he agrees, I'll handle getting it in master and also the select code to make it only show on the amphibious.

**Comment by gilbertohasnofb** [comment]
> a real after market product that could have been used for various models of aircraft

If that's the case, then we would close this after implementing, but while we research we can add his contribution AND keep this issue alive.

> Lets have onox's opinion on using abassign contribution

:+1: 

> Speaking of thanks, copyrights, etc.. I don't know that I ever attributed any of the pontoon source I used from the dhc2, do I need to add that somewhere?

Which kind of license it was? If it was GPL, then we can thank them just out of politeness. If it was CC-BY, we need to see which gladiator comes back alive from the mailing list battle and then see how to handle it. Either way, our Thanks file is the place to do that. I would recommend you to be explicit with the sort of license you are thanking (see the current entries in that file)

**Comment by wlbragg** [comment]
That also reminds me, anytime anyone adds anything internal to the cockpit, they need to be aware of the internal effects inheritance that needs to go with their additions (this is a reminder for me more than anything). :memo:

**Comment by gilbertohasnofb** [comment]
> anytime anyone adds anything internal to the cockpit, they need to be aware of the internal effects inheritance that needs to go with their additions

Probably the only way to handle this is to keep an attentive eye when checking PR's. You are very likely the best person to spot mistakes, but all of us can try to keep this reminder in our minds when it comes to 3D contributions to the interior.

**Comment by wlbragg** [comment]
It is a Syd Adams aircraft and there is no notice of any kind, but it was one of the base aircraft in fgdata/aircraft so I assume it is strictly GPL. What should I attribute to Sid?

**Comment by gilbertohasnofb** [comment]
So in that case it should be strictly GPL. We don't necessary have to thank anyone then, but we can do that out of politeness. In that case, simply add a new entry to the file `Thanks` in our root (see the other entries in that file to see how onox and I have been handling it).

**Comment by wlbragg** [comment]
OK, will do, thanks.

**Comment by onox** [comment]
Note that this issue has a 3.8 feature milestone, so it needs to wait until 17th of July.

**Comment by wlbragg** [comment]
I wasn't aware that had anything left we could do other than bugs (of which I didn't think we had any defined). Are you telling me the amphibious gear and MP effects are 3.6 "bugs"?

**Comment by onox** [comment]
@wlbragg If it has a 3.6 release milestone then it can go into the 3.6 release.

**Comment by wlbragg** [comment]
OK, guess I'd better look at the list again, thanks.

**Comment by wlbragg** [comment]
I want to resurrect this one. In the forum history
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=247740&hilit=amphibious+gear#p247740
I think this would work!

**Comment by gilbertohasnofb** [comment]
Yep, that looks good to me! It's better than having no lever at all, right? And maybe while you are at it, we could think of adding two super simple bars across the cockpit so that the float and amphibian cockpits will look closer to RL (see: #313). I obviously would help with textures and also xml if necessary.

**Comment by wlbragg** [comment]
What are those bars for? Are we even sure they have anything to do with the pontoons?

**Comment by gilbertohasnofb** [comment]
I don't know what they are for, maybe it's structurally needed, but every single image of a float 172 I have seen had those

**Comment by wlbragg** [comment]
OK

**Comment by gilbertohasnofb** [comment]
It could be reaaaally simple, nothing fancy (as we discussed, the 3D model might change, but 'til then...). I guess just two cylinders, and you can use some texture from `float.png` or from `panel_parts.png` for them.

**Comment by wlbragg** [comment]
Yes, this hits on what all is required.
http://www.cessna172club.com/forum/ubbthreads.php?ubb=showflat&Number=72646#Post72646

If you want to make a texture for it I'll see if I can add the supports. I would try to add the texture to the floats.png

**Comment by gilbertohasnofb** [comment]
> If you want to make a texture for it I'll see if I can add the supports. I would try to add the texture to the floats.png

There is very little space there I think... but what about adding it to `panel.png`?

**Comment by wlbragg** [comment]
That's fine, I was just hoping we could use an existing texture file, so that is good with me.

**Comment by gilbertohasnofb** [comment]
Ok, I will prepare it right now.

**Comment by wlbragg** [comment]
No rush, I'm fixing pontoons at the moment, I found the problem and will push a PR shortly.

**Comment by gilbertohasnofb** [comment]
Well, I am done with the texture. To which branch should I push it to? Should I create a branch `bug-206` for this issue and issue #303 ?

**Comment by gilbertohasnofb** [comment]
This is my idea, I added a single rectangle for those structures, and they can be implemented as follows:

![eg](https://cloud.githubusercontent.com/assets/5700795/10955169/31c7511c-8352-11e5-95ee-e8da5270742d.jpg)

Notice that I "applied" the texture flipped by 180 degrees on the right cylinder, so that they don't look identical to each other even though they use the same texture (makes sense?).

So just let me know where to push and I am off for tonight!

**Comment by gilbertohasnofb** [comment]
Okay, it's my time to go to bed, tomorrow i have a long day at my uni. I didn't push that texture because I didn't want to create a new branch in case you are already working on one, so please download it from here: https://www.dropbox.com/s/94mx7t046pbr0x9/panel.png?dl=0

**Comment by wlbragg** [comment]
Thanks sorry for not replying right away, I got busy. I'll create a branch for it.

**Comment by gilbertohasnofb** [comment]
No worries, it's me who has been having too much time for developing this plane :wink: So in that case, use the Dropbox link and it should all be fine. If you need anything else, let me know and tomorrow I can try to help.

**Comment by wlbragg** [comment]
:+1:

**Comment by wlbragg** [comment]
Issue was already created for the cross bars see #313

New branch will be float-enhance and will cover both the crossbars and the gear switches.
