### ISSUE TITLE
better texture for the ceiling

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#21]
TEX03 - better texture for the ceiling
  * Gilberto: what do you mean by better? Right now it has the same texture as the walls. Do you want something different?

**Comment by gilbertohasnofb** [comment]
Ok, now I get it since @Juanvvc  posted these on the forum: 
http://old.executiveflyers.com/wp-content/gallery/current-offerings/n21518-007.jpg
http://i.imgur.com/4jFOh7f.jpg

**Comment by wlbragg** [comment]
Agreed!

**Comment by gilbertohasnofb** [comment]
Question: would it be possible to create a rectangle where the texture of the speaker, lights, etc. would be displayed and leaving the rest of the ceiling as it is (i.e., changing according to the wall colours of each livery) or is that too difficult to accomplish? That way I wouldn't need to correct the liveries individually, I could simply add these textures to the panel parts file. What do you say, @Juanvvc?

**Comment by gilbertohasnofb** [comment]
In case it's difficult to see what I am proposing above, here is what I have in mind: http://s11.postimg.org/5mhl8an0j/fgfs_screen_001.png

**Comment by Juanvvc** [comment]
Of course, is not only  good compromise but a perfect idea. I'll model this.

**Comment by gilbertohasnofb** [comment]
Perfect Juan! On my last commit I added a red rectangle to the bottom right corner of COLOR_panel_parts.png, so once you create this object you can already apply this texture to it. Then let me know and I start working on the texture itself, ok? Thanks!

**Comment by gilbertohasnofb** [comment]
Ok, I finished the texture, see the bottom right corner of COLOR_panel_parts.png. I based it on this image you sent me: http://old.executiveflyers.com/wp-content/gallery/current-offerings/n21518-007.jpg

Let me know if it works or if I should change anything.

**Comment by gilbertohasnofb** [comment]
Added the new ceiling panel texture to all liveries.
