### ISSUE TITLE
Keeping two FDMs?

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#211]
As I reminder, I was contacted by your team for the "alternative" FDM (c172p-fdm-dany93.xml, stall and spin). Logically, I have integrated the changes according to your demands preferably in it (as much as I could). My initial intention has never been to touch the original one (c172p.xml), this FDM is not my affair. When implementing the stall and spin, I tried to respect the behaviour of the original FDM in the domain where it is good  (inside the flight envelope). I hope I have not shifted too much, evaluating this shift is not easy for me. Which would mean, I hope and if I've succeeded, that the original FDM behavior should be contained in my "stall and spin" one. Only, the "alternative" one is less tolerating to pilot errors out of the flight envelope (which does not mean that it is perfect).

After having made my extra changes (your demands, in-flight damages,...) in the alternative FDM I have updated the original one with them. Even if that is not my preference, I can carry on with this updating because I know better than you where my changes are. However I cannot do it well each time on both directions. In particular, if I have to copy into c172p-fdm-dany93.xml the numerous changes made by wlbragg for the bushkits and floats in c1172p.xml, forgetting something or doing an error can easily happen. For these additions you know what you want and how you have done them better than me.

I'll try to do this for this time but, please wlbragg if you can, I will ask you to check that I've not introduced errors or forgot something.

Moreover, this transfer is heavy and a bit risky. No comparison with the huge work you, wlbragg, have made with the bushkits, but do we have to carry on with this management?

Hence the title of this issue.

"Alternative" FDM explanations:  http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1320#p242233
Connected to this issue:  https://github.com/Juanvvc/c172p-detailed/issues/93

**Comment by onox** [comment]
I think your stall/spin changes are a good addition, so compare `c172p.xml` and `c172p-fdm-dany93.xml` and copy your stall/spin changes to `c172p.xml`. And then `git rm c172p-fdm-dany93.xml`.

**Comment by dany93** [comment]
OK, thanks, I'll do this.

**Comment by tigert** [comment]
Yeah, I agree too. I have to test fly a bit (and really, I need pedals and a yoke to get a better opinion), but yeah, lets not have two. The spin is nice as it also gives you a good demonstration of accelerated stall (stall due to high-G turn).

Yet when you fly it with the normal procedures, there is no problem at all.

So yeah, let's use the new one.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by Juanvvc** [comment]
The idea of having an alternate FDM was to keep the original FDM unchanged but we have already changed the original FDM with new systems. It makes no sense maintaining two different FDMs. I also vote for merging both FDM in a single file.

**Comment by tigert** [comment]
@juanvvc, agreed.

**Comment by wlbragg** [comment]
Yea! About time, I've been for this since the first stall/spin I experienced.
