### ISSUE TITLE
Missing file: Effects/pontoon/bow_wave.xml

### ISSUE THREAD

**Issue by Juanvvc** [Juanvvc/c172p-detailed#213]
I guess someone forgot adding this file to git :)

**Comment by wlbragg** [comment]
What is this?
If this was ever commited it was probably by me on accident. This effect, as far as I know, has never been implemented for the pontoons. It is something I was going to experiment with and if it looked good then I was going to add it, but so far I haven't got that far. Did you see this file commited at some point in time and now it's not so you added this issue? If so, you can close it, it was never suppose to be commited.

**Comment by Juanvvc** [comment]
The missing effect prevented the preview to appear in Fgrun and showed a warning when the aircraft was loaded. The line in c172p-detailed.xml that linked to the effect was removed in your last commit, so this issue can be closed.

Thanks!
