### ISSUE TITLE
cutting power while flying

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#215]
when flying, if i cut off both battery and alternator switches, the engine keeps on running and i can still fly but with no working avionics... if the battery and the alternator are cut off, shouldn't the engine stop, too?

**Comment by gilbertohasnofb** [comment]
I don't think it should stop because the battery is necessary only for starting the engine, not running it. Actually it is the engine itself that feeds the alternator, which recharges the battery.

**Comment by wkitty42** [comment]
right... i was thinking that just like in a car, if the alternator goes out the battery is used for the voltage until it is drained... switching off both would be like a bad alternator (generating no voltage) and disconnecting the battery to see if the alternator is good... since both are switched off, there should be no voltage for the spark... right?

**Comment by gilbertohasnofb** [comment]
> if the alternator goes out the battery is used for the voltage until it is drained... switching off both would be like a bad alternator (generating no voltage) and disconnecting the battery to see if the alternator is good... since both are switched off, there should be no voltage for the spark... 

I think this all is correct. But the engine itself will simply keep running regardless of the position of the alternator and battery switches.

**Comment by dany93** [comment]
For aircraft engines, the spark is given by the magnetos. A double magneto and two spark plugs per cylinder, by security (hence the check Nr 1, Nr 2, BOTH). So that the engine can still run without battery (nor alternator). Even with a single magneto, at the price of a small loss of power.

**Comment by gilbertohasnofb** [comment]
> So that the engine can still run without battery (nor alternator).

Sorry Dany, your phrase is unclear. The engine can still run without battery (that's clear), but what about the alternator? Can it run without it or not?

**Comment by dany93** [comment]
Sorry for my approximate English. The engine can still run (without the battery and) **without the alternator**. The magnetos give the high voltage peak, as long as the engine rotates.
Like old Mobylettes.

**Comment by gilbertohasnofb** [comment]
Thanks for the clarification, Dany. English is obviously not my first language either, and often you'll find me posting nonsense in our thread :wink: 

So I guess we can close this issue, right?

**Comment by wkitty42** [comment]
ok... to this 50+ year old mind, an alternator and a magneto are the same thing... one is just AC and the other DC... i'm guessing now that they are two separate items on aircraft and that the alternator is really only used to provide power for electronics instead of burning up the battery...

**Comment by gilbertohasnofb** [comment]
AFAIK, an alternator does not stores energy, its only purpose is to generate electric energy from the kinetic motion of the propeller. If the engine is not running, the alternator produces no current at all.

**Comment by dany93** [comment]
An alternator and a magneto are completely different.

When the engine is running,

The alternator gives: 
- **AC** voltage, e.g **10 to 40 volts AC**, 
- rectified to give about he same voltage (**10 to 30 V DC**) for instruments and battery charging. **Low DC voltage**.

Nowadays, every car has an alternator, a rectifier (diode bridge), a battery and no magneto. However, a short time high voltage peak is needed for the spark plugs. The spark was given by the contact rupture + a coil for the high voltage (I don't know the name in English). Now, an electronic circuit gives this short high voltage.
Aircraft have  an alternator + rectifier for the battery and two magnetos fro the spark.

A magneto gives (possibly combined with a coil transformer) a **high voltage peak** (e.g. **10 or 15 kilo Volts for some milliseconds**) just for the spark when the cylinder is fed with air + fuel, piston high, ready for the "explosion". **Short high voltage peak (kV)** just for the spark time, low power.

The old Mobylettes had a magneto for the spark, and no battery (and of course no dynamo, no alternator). They were started with a kick. The same for an aircraft with alternator and battery disconnected or out of order. Or the old aircraft, started by manually turning the propeller. the engine with magneto is self-sufficient for its spark when it rotates.

**Comment by Juanvvc** [comment]
I was using only the mobile phone the last days, and apparently if I answer an email the message does not appear here but in the user's inbox. Guys, I'm sorry if you received a private message from me, I was trying to post the message here :)

When the engine is running, the spark is not generated by the battery but by the magnetos. Actually, there are two sparks in each cylinder: one generated by the left magneto and the other by the right magneto. The magnetos are totally independent of the battery or the alternator, they are run by the engine itself. The existence of these two magnetos and two sparks is probably the main difference with a car engine. The magnetos are switched on and off (left only/right only/both) with the starter key.

The engine will work flawlessly even with battery and alternator off. Actually, it happened to me once in real life :)

**Comment by wkitty42** [comment]
ok, thanks for the clarifications... i was under the impression that the term magneto was used for historical reasons and that things were much more modern... i was thinking that what's being called magnetos were actually like "coil packs" on cars which the spark plugs are connected to... now that you all have clarified this, i understand that there are three energy sources... battery and alternator for regular electronics and the magnetos for the actual spark in the cylinders...
