### ISSUE TITLE
aircraft options dialog stopped working

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#223]
Latest git for simgear, flightgear and fgdata and also c172p-detailed, at least as far as I know (unless I messed something up syncing my own fork) - I don't get the aircraft options dialog to work at all. Selecting the menu for the aircraft options just does nothing at all.

I cannot really see anything about this on the debug log either, when I tried to look quickly.

Does this happen to anyone else?

**Comment by onox** [comment]
Do you really have the latest commits? Because I reverted a change by @wlbragg that made the dialogs invisible on small screens.

**Comment by wkitty42** [comment]
i haven't noticed any problems with the craft's options dialogue... i updated everything, fgfs, fgdata, fgaddon, this craft some 4 hours ago (i think) and flew several different configurations and missions with no real problems noted...

**Comment by wlbragg** [comment]
tigert, make sure you have the latest commit and it is still doing this, and verify your on "master".
