### ISSUE TITLE
create texture for the cap of the ventube (top left and top right of the panel

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#23]
TEX10 - create texture for the cap of the ventube (top left and top right of the panel, as seen here: http://www.cruik.org/blog/ventubes/ventube-out.jpg)

**Comment by gilbertohasnofb** [comment]
done

**Comment by Juanvvc** [comment]
Where is this texture? I cannot fix #83 or #105 because I cannot identify this texture :)

**Comment by gilbertohasnofb** [comment]
It's in COLOR_panel_parts.png, very close to the circuit breakers (on the right side of them). It's basically a whitish square with a little black rectangle on its left size (the vent hole). I had the idea to wrap it around the object (imagine the object is a cylinder). Let me know if it works :)
