### ISSUE TITLE
Cabin temperature option in the menu

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#230]
A feature request (if it's easy to implement, of course): would it be possible to add a selectable option to the aircraft menu in order to activate/inactivate the cabin temperature control and the cabin temperature variation in general?

The reason behind this is the following: I believe in RL one can obviously tell when the temperatures are dropping too low or raising too high, but in the sim we only find about them when a pop up appears in the screen (and sometimes almost immediately followed by fog). I love these features, but sometimes I just don't want to bother with it, particularly given that right now it seems to me to be a kind of guess work... (as @wkitty42 pointed out in one of his posts, sometimes a small difference of cabin heat/air will cause these large changes to happen)

So would it be easy to implement an option in the menu that when unchecked forced the cabin to a constant, let's say, 25 degrees Celsius?

**Comment by wkitty42** [comment]
an additional part of this request could be to have a/the dialog where we can manually enter the desired percentage of the temperature knob... on my system, rolling with the mouse wheel gives me 10% increments... it would be nice to have 1% increments or to have a box where we can type in the desired value like there is for the heading bug and radio freqs ;)

**Comment by wlbragg** [comment]
Yes to both questions. I can add the "Disable heat and air" to the menu easy enough. The other might be a little more involved but certainly doable.

**Comment by gilbertohasnofb** [comment]
Maybe a compromise then: we can make the levers less sensible to the mouse wheel (thus solving wkitty42's problem without really messing with options) and then create the disable heat and air in the menu.

As much as choice is good, too many options, sliders, toggles and buttons can transform something simple into a huge mess.

**Comment by onox** [comment]
> As much as choice is good, too many options, sliders, toggles and buttons can transform something simple into a huge mess.

I agree with that.

**Comment by wkitty42** [comment]
sounds ok to me...

**Comment by wlbragg** [comment]
Added the menu option and weather.nas logic. Someone may want to change the wording in the menu.

**Comment by gilbertohasnofb** [comment]
> Someone may want to change the wording in the menu.

Well, you are the native speaker :wink: But what about "enable fixed interior temperature" or "enable constant cabin temperature" or something like this?

**Comment by wkitty42** [comment]
i haven't looked at it yet... gotta pull it... but "constant cabin temperature" with a check box?? not sure what's there so i may be talking through my hat...

**Comment by gilbertohasnofb** [comment]
"constant cabin temperature" meaning that the cabin temperature won't change regardless of vent/heat levers position, and regardless of the outside temperature (and therefore it won't fog as well).

**Comment by wkitty42** [comment]
right...

**Comment by wlbragg** [comment]
Yeah, because it is doing several things.

Disable frost and fog
Disable heat and air
Constant cabin temp
No frost or fog

Again, I defer to you all, what ever you decide I think I will be OK with.

**Comment by gilbertohasnofb** [comment]
Done. I decided for "constant cabin temperature", but anyone can improve it. I also standardized the capitalization in all our labels: now only the first letter of a label is capitalized.

**Comment by onox** [comment]
I think "Disable frost and fog" like @wlbragg said is more clear to users.

**Comment by gilbertohasnofb** [comment]
You are right, that's better. I just modified it, thanks!
