### ISSUE TITLE
Confusing options for shadows

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#235]
Currently it's confusing to have an option called "ALS shadow" and another "ALS shadow volume". I know how they work, but most people trying the plane for the first time won't. How can we improve this?

**Comment by wkitty42** [comment]
TBH i'm not sure what the visual differences are... is one the shadow on the ground and the other the one inside the craft?

**Comment by gilbertohasnofb** [comment]
Nope. One is the default ALS shadow that has a fixed size and is simply an image on the floor. The other is created by calculating how a 3D object would be projected in the ground. One way of seeing how they differ: load the plane during sunset. The regular ALS shadow will have the size as if it was midday, while the ALS shadow volume will be very elongated.

**Comment by wkitty42** [comment]
oooohhhhhh... yeah, i have seen that... is there any reason to keep the non-3D one?

**Comment by gilbertohasnofb** [comment]
No idea. What do you think, @wlbragg ?

**Comment by wkitty42** [comment]
if we need to have both, maybe set the first one as "2D shadow" and the volume one as "3D shadow"... i mentioned this in the forum, too...

**Comment by wlbragg** [comment]
I have no issues if you want to change their names, but I do think for now we should keep both. Maybe eventually if the volume shadow get more work on the transparency issues then I might not have a problem with getting rid of the 2d shadow.

**Comment by gilbertohasnofb** [comment]
Ok, for now this has been solved. If the transparency issues on the 3D shadow gets solved then we can discuss removing these options altogether.

**Comment by onox** [comment]
Does this require help from Thorsten?

**Comment by gilbertohasnofb** [comment]
I am not sure reopening this issue is good. This is about the confusing labels inside the options only, not about the effects themselves. I would say it's better to create a new issue if we want to discuss with Thorsten a certain effect -- this way this repo stays better organized.
