### ISSUE TITLE
New Rating

### ISSUE THREAD

**Issue by dg-505** [Juanvvc/c172p-detailed#240]
Good morning everyone 

I suggest to give the c172p a new rating, because much has changed in the last few month.
Here is my suggestion:
- FDM: 4 or 5 stars. I don't exactly know how close to the reality the FDM is, but it seems very reasonable to me. Maybe someone with real flight experience with the c172p can ssy if it's more 4 or more 5 stars.
- Systems: also 4 or 5. There are some failure modes present (e.g. over-G damage), but as far as I know, there are no emergency checklists available.
- Cockpit: 5 Stars. We have a very accurate 3D-cockpit where most of the controls are animated and have hotspots, and the whole interior has photo-realistic texturing.
- External model: 4 Stars. The exterior model is already very detailed, but in my opinion it's not yet a 5-star, because I think 5 stars should be reserved to models which are detailed like the new P-51 Mustang: http://wiki.flightgear.org/North_American_P-51_Mustang.

As an overall status I suggest "production" or "advanced production" depending on how much stars are  achieved after discussing this issue.

For a reference see http://wiki.flightgear.org/Aircraft_rating_system

**Comment by onox** [comment]
1. FDM: Unless the FDM is based on data from actual testing (wind tunnel, etc.), I would say it's (a solid) 4 stars.

2. Systems: I'm not sure what kind of systems we still need to model. Maybe the engine temperature primer stuff, oil, engine damage, etc.? I think 4 stars.

I agree with what you say about the cockpit and the external model.

**Comment by tigert** [comment]
For systems we should test that with each breaker pulled out, nothing that takes power from it works. Also I think not all breakers might be functional yet?

I cannot say anything is wrong with the fdm with my limited c172 experience. I am pretty convinced about the stall/spin too, it recovers with textbook procedures and the aircraft behaves also very realistically when loaded to mtow (try that on hot day in mountains and you end up with an interesting day..)

I will test further, but definitely a 4 for the fdm, we would need to verify performance with flight manual figures to give it a 5 I guess, but it could well be there. 

All in all the cockpit feels very nice. I agree with 5.

**Comment by dg-505** [comment]
@tigert: About the breakers I can say that most of them do their job properly. Only INST (for instrument lights), INT LT (for cabin lights), Turn Coordinator and Radio breaker 1 don't seem to work. (Maybe we could open another issue for that.)
@onox: About the systems maybe we could implement engine damage when overheating or when exeeding RPM limit, or something like this.
Does anyone have acces to a real POH of a Cessna 172? There *must* be some emergency checklists which can be added to the checklist menu. When this is done, I think we can give the systems 5 stars.

**Comment by gilbertohasnofb** [comment]
> Does anyone have acces to a real POH of a Cessna 172? There must be some emergency checklists which can be added to the checklist menu. 

See section 3 of http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf

**Comment by dg-505** [comment]
Thanks, i'll have a look.

**Comment by dg-505** [comment]
Looks good. Shall I add some of these procedures to the checklists menu?

**Comment by onox** [comment]
@dg-505 Yes, that would be cool :smiley:

**Comment by dg-505** [comment]
Almost finished :wink:

**Comment by onox** [comment]
New rating added in PR #257
