### ISSUE TITLE
Water droplets on glass should flow with propwash

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#242]
The propeller maked wind too, it should flow when you start the engine, and the flow should vary with throttle setting.

**Comment by wlbragg** [comment]
This is a bit tricky. If I remember correctly I did add a clamp to keep it from flowing the wrong way at startup (which i was doing at one point). But the flow is driven by a float and it is not user friendly at all. If someone has done this before than then I stand corrected, but  I'm not sure you can get that much control over the flow. Then again I guess you could translate rpm to the float that controls the movement. This could prove to be interesting!

**Comment by tigert** [comment]
The RPM would pretty much be an indication of the wind - since the propeller is fixed pitch. Also airspeed would be another measurement - maybe try to calculate somewhat sensible wind velocity value based on propeller RPM and another value from indicated airspeed, we could then compare them and use the larger value? That might work?

It would be pretty sweet if we could make it work in a sane way.

**Comment by wlbragg** [comment]
OK, I got it in there. I stuck it it in during the broken wing merge because it was the simplest way for me at the time.
Changes were minor in physics.nas
see https://github.com/Juanvvc/c172p-detailed/commit/d74e1749edd598d01052a70ee9eea033a91e1948 for details
