### ISSUE TITLE
Invalid use of 'Aircraft/c172p' in c172p-set.xml

### ISSUE THREAD

**Issue by stuartbuchanan** [Juanvvc/c172p-detailed#243]
Hi,

Because of the use of 'Aircraft/c172p' in various paths in c172p-set.xml, it's not possible to put the aircraft in a separate FG_AIRCRAFT directory.

Straightforward diff to fix below, which simply removes the prefix.

We'll need to fix this for the the fgdata merge.

-Stuart
```
diff --git a/c172p-set.xml b/c172p-set.xml
index 8b60e42..c82ed50 100644
--- a/c172p-set.xml
+++ b/c172p-set.xml
@@ -68,7 +68,7 @@ Many files from the original c172p directory are included in this file.
   <allow-toggle-cockpit type="bool">true</allow-toggle-cockpit>
 
   <model>
-    <path archive="y">Aircraft/c172p/Models/c172p.xml</path>
+    <path archive="y">Models/c172p.xml</path>
 
     <livery>
       <file type="string">D-EEQA</file>
@@ -139,11 +139,11 @@ Many files from the original c172p directory are included in this file.
   </aircraft-data>
 
   <startup>
-         <splash-texture>Aircraft/c172p/splash1.png</splash-texture>
-         <splash-texture>Aircraft/c172p/splash2.png</splash-texture>
-         <splash-texture>Aircraft/c172p/splash3.png</splash-texture>
-         <splash-texture>Aircraft/c172p/splash4.png</splash-texture>
-         <splash-texture>Aircraft/c172p/splash5.png</splash-texture>
+         <splash-texture>splash1.png</splash-texture>
+         <splash-texture>splash2.png</splash-texture>
+         <splash-texture>splash3.png</splash-texture>
+         <splash-texture>splash4.png</splash-texture>
+         <splash-texture>splash5.png</splash-texture>
   </startup>
 
   <!-- hide the 2D panel -->
@@ -181,11 +181,11 @@ Many files from the original c172p directory are included in this file.
 
     <!-- needed by shadows in ALS: http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=75#p232120 -->
     <property-rule n="101">
-      <path>Aircraft/c172p/Systems/gearAGL.xml</path>
+      <path>Systems/gearAGL.xml</path>
     </property-rule>
 
     <property-rule n="102">
-      <path>Aircraft/c172p/Systems/als-lights.xml</path>
+      <path>Systems/als-lights.xml</path>
     </property-rule>
   </systems>
 
```

**Comment by stuartbuchanan** [comment]
Also Nasal/immat.nas

**Comment by stuartbuchanan** [comment]
Also the following files:
Models/Effects/bumpspec-tail.eff:  <name>Aircraft/c172p/Models/Effects/bumpspec-tail</name>
Models/Effects/bumpspec-tail.eff:  <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
Models/Effects/bumpspec-tail.eff:      <image>Aircraft/c172p/Models/Liveries/tail-normal.png</image>
Models/Effects/damage/damage.xml:		<inherits-from>Aircraft/c172p/Models/Effects/bumpspec-wing</inherits-from>
Models/Effects/damage/damage.xml:		<inherits-from>Aircraft/c172p/Models/Effects/bumpspec-fuselage</inherits-from>
Models/Effects/damage/pontoondamage.xml:		<inherits-from>Aircraft/c172p/Models/Effects/bumpspec-fuselage</inherits-from>
Models/Effects/bumpspec-wing.eff:  <name>Aircraft/c172p/Models/Effects/bumpspec-wing</name>
Models/Effects/bumpspec-wing.eff:  <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
Models/Effects/bumpspec-wing.eff:      <image>Aircraft/c172p/Models/Liveries/wing-normal.png</image>
Models/Effects/bumpspec.eff:  <name>Aircraft/c172p/Models/Effects/bumpspec</name>
Models/Effects/bumpspec-fuselage.eff:  <name>Aircraft/c172p/Models/Effects/bumpspec-fuselage</name>
Models/Effects/bumpspec-fuselage.eff:  <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
Models/Effects/bumpspec-fuselage.eff:      <image>Aircraft/c172p/Models/Liveries/fuselage-normal.png</image>
Models/Effects/pontoon/pontoon.xml:		<inherits-from>Aircraft/c172p/Models/Effects/bumpspec-fuselage</inherits-from>
Models/Effects/glass.eff:    <name>Aircraft/c172p/Models/Effects/glass</name>
Models/Effects/bumpspec-pontoon.eff:  <name>Aircraft/c172p/Models/Effects/bumpspec-pontoon</name>
Models/Effects/bumpspec-pontoon.eff:  <inherits-from>Aircraft/c172p/Models/Effects/bumpspec</inherits-from>
Models/Effects/bumpspec-pontoon.eff:      <image>Aircraft/c172p/Models/Liveries/fuselage-normal.png</image>
Binary file Models/c172p-bushkit.blend matches
Binary file Models/Interior/Yoke/yoke.blend matches
Binary file Models/Interior/Panel/Buttons/breakers/breakers.blend matches
Binary file Models/Interior/Panel/Instruments/oat/oat.blend matches
Binary file Models/Interior/Panel/Instruments/AI/AI.blend matches
Binary file Models/Interior/Panel/Instruments/hobbs/hobbs.blend matches
Binary file Models/c172p.blend matches
Nasal/liveries.nas:aircraft.livery.init("/Aircraft/c172p/Models/Liveries", "sim/model/livery/name", "sim/model/liverytail/name", "sim/model/liverywing/name", "sim/model/livery/index");

**Comment by onox** [comment]
Are you sure it's not a problem on your side? I'm using `--fg-aircraft=/home/onox/fg-aircraft` which contains a folder called `c172p`.

**Comment by onox** [comment]
Also, if you remove the prefix in `<model><path>` then people are going to have problems viewing your aircraft.

**Comment by stuartbuchanan** [comment]
Hi Guys,

Good spot - I have the aircraft installed under "Aircraft/c172p-detailed"
rather than "Aircraft/c172p".

However, this fix should allow the aircraft to be installed anywhere.

Don't know if removing the prefix in <model><path> causes a problem over MP
or not.

-Stuart

**Comment by onox** [comment]
Yes, it causes problems.

**Comment by stuartbuchanan** [comment]
Ah well.

OK, then I guess there's no point in removing the prefixes elsewhere if the
<model><path> must have a prefix.

-Stuart

**Comment by onox** [comment]
Correct. I think FlightGear itself should be changed so that aircraft can define a unique identifier representing the aircraft. In that case, paths could be made without the prefix.
