### ISSUE TITLE
Damage repair does not recharge the battery

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#248]
load the craft normally with the engine off... make sure that damage is enabled in the craft's options... press the autostart just to ensure that everything is ready to go... do not press the 's'tart button! also, make sure the instrument lights are turned all the way up to 100%... now, go get lost editing or providing support or whatever... as long as you're away long enough for the battery to run down... now, when you get back, you cannot start the engine but the instrument lights are all still on! if the battery is dead, the instrument lights should be off, too...

so, then click the damage repair button... now try to turn the engine over... no go.

When pressing "Repair" button:
* [x] Recharge battery
* [x] Enable all circuit breakers

**Comment by onox** [comment]
The repair button repairs your gear and wing.

**Comment by onox** [comment]
Maybe there should be a separate button to "Replace battery"?

**Comment by gilbertohasnofb** [comment]
I don't think we should have a different button, else our menu is getting too complicated! Let's just use the same repair button to replace the battery.

**Comment by wkitty42** [comment]
that's my thought's too... i would expect [REPAIR] to repair all damage and problems... even burnt out fuses if/when we get to the point of damaging them for some reason :wink:

**Comment by onox** [comment]
> even burnt out fuses if/when we get to the point of damaging them for some reason

:dizzy_face:  :open_mouth: :scream:

Nice! :smile: Is it really possible for these fuses to irreversibly disconnect/break the electrical wire? (So that you need to replace the fuse instead of simply pushing it?) If yes, then we need to create an issue for this.

**Comment by wkitty42** [comment]
ummm... yeah, you are right... they are circuit breakers instead of fuses... that means that we need to pop the button out and kill that circuit if/when it suffers overvoltage or overamperage for some reason... the only reasons i can think of are mainly related to age (weakening springs and metal fatigue) and possibly the alternator having problems and surging more than desired which might happen if the diodes in the bridge rectifier (converting AC to DC) are breaking down from over heating or loose connection from vibration... it is a slow breakdown process, though... just think about how it happens in a car or truck ;)  yeah, something else to maybe track in the userarchive along with the hobbs time numbers and other similar saved items :wink:  oh! and on the black box tapes, too...

**Comment by wkitty42** [comment]
what has been decided with this? i pulled some 8 or 10 new commits just a little bit ago so this might already be taken care of but previous to those, the repair button doesn't fix the battery... i'm testing the battery drain now to be sure... just wanted to drop a note so we don't forget this before the release...

**Comment by onox** [comment]
There's no PR that refers to this issue, so it hasn't been fixed yet.

**Comment by wlbragg** [comment]
AI can add it to repair function, anyone know what property to add and what value to set it to?

**Comment by wkitty42** [comment]
i'm digging just to see what i can see... i've found /systems/electrical/battery-charge-percent which appears to use 1.0 as 100% charge... so far, rooting with the aid of the phi web interface, i don't find much else that seems related...

i've done no startup procedures at all... just started the sim and it seems to have started with the battery, alternator and avionics switches ON along with the panel lights at 100%... everything else is turned off and i specifically turned everything off and all the way down the last time i started and exited the sim...

**Comment by onox** [comment]
@wkitty42 `/systems/electrical/battery-charge-percent` is read-only. Instead you have to call `battery.apply_load((1.0 - battery.charge_percent) * battery.amp_hours, 3600)`. I'll fix this issue now, it seems rather easy :smile:

**Comment by onox** [comment]
@wkitty42 I have pushed branch bug-248. Do `git fetch` or `git pull` in master branch (I guess that is what you usually do). You should see a new message about branch bug-248. After that you do `git checkout bug-248`

To test in which branch you are, you do `git branch`. To go back to master, you do `git checkout master`.

**Comment by wkitty42** [comment]
@onox i couldn't tell that it was read-only... i was in the sim a little while ago and opened the tree with '/'... i navigated to that node... i was watching it, the amps and the voltage dropping... then i went and turned off all the switches again (see issue #285) and watched the numbers stop dropping... as a test, i set that battery-charge-percent to 1.0 and clicked the [set] button... it was accepted and i left everything sitting for a time while i made dinner... when i came back, i saw it was still at 1.0 and the other numbers were stable... i turned on the battery switch and was kinda surprised that the value dropped immediately to .95xxxxx... it and the other numbers were dropping again and stabilized when i turned the battery switch back off again... i wasn't expecting to see a 5% drop just by turning on the switch but it is what it is :wink:

**Comment by wkitty42** [comment]
@onox ok... i'll make a fetch in a few minutes and check out that branch, copy it over to my live directory i fly the craft from and test it...

**Comment by onox** [comment]
That's because `Nasal/electrical.nas` stores the actual charge in a variable, not in a property. The property is just for your information, it's not the actual state.

Anyway, please test bug-248 branch and report in #290 :smile:

**Comment by wkitty42** [comment]
done :smile_cat:
