### ISSUE TITLE
search for unused textures and delete them

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#25]
TEX12 - search for unused textures and delete them
  * Gilberto: for instance, does our model use the files c172p-02.png, c172p-int-01.png, c172p-int-02.png and UV_cone.png?

**Comment by gilbertohasnofb** [comment]
Can anyone else confirm that these 4 files are not being used? I tried deleting them and I can't see any difference in our aircraft, both outside and inside, HD livery or not. They really seem to be just old unused files to me.

**Comment by Juanvvc** [comment]
No, these files are not used and, in fact, I removed the references from the .blend file some time ago.

Related to this. What you think of renaming files COLOR_***.png to something more descriptive and consistent, like the names you are using in Liveries?

**Comment by gilbertohasnofb** [comment]
Ok, so I removed these files.

> What you think of renaming files COLOR_***.png to something more descriptive and consistent, like the names you are using in Liveries?

I am all up for it! I just didn't do it myself because I didn't know what it would influence. I suggest using the same standard as I used on the liveries, what do you think? This is how I name them: fuselage.png, interior.png, panel.png, panel_parts.png, tail.png and wing.png

**Comment by Juanvvc** [comment]
Files renamed and file .blend updated.

**Comment by gilbertohasnofb** [comment]
Thanks!
