### ISSUE TITLE
Ctrl+C shows wrong names in radio

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#256]
When you press Ctrl+C and look at the radios, some names are wrong:

-  "Autopilot" and "DME" are reversed.
- Com1/Nav1 also shows "ADF receiver"

**Comment by onox** [comment]
It's a bug, not a feature :wink:

**Comment by gilbertohasnofb** [comment]
hahaha my bad :laughing:

**Comment by wkitty42** [comment]
i saw that but missed the reversal... has this just happened? i remember something about a KT70 or some such instrument being removed but i haven't found that log entry and may very well have the number screwed up... i think it has something to do with my other issue about the DME toggle switch...

**Comment by onox** [comment]
Com1/Nav1 also shows "ADF receiver"

**Comment by gilbertohasnofb** [comment]
@onox okay, so I updated the title and description. Thanks!
