### ISSUE TITLE
see what to do with the older liveries

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#26]
TEX13 - see what to do with the older liveries, since they will require some updates if we want to keep them (adding wing lights, propeller, etc. to each one of them)

**Comment by gilbertohasnofb** [comment]
I personally feel that a lot of these older liveries have very low quality (such as n301dp and eimcf which have horrible resolution, but also IVA, HB-CHX and D-ENMU which are plain ugly in my opinion). Should we really keep these older liveries with our plane?

There is also a practical side to this question now: ludo has fixed issues https://github.com/Juanvvc/c172p-detailed/issues/7 and https://github.com/Juanvvc/c172p-detailed/issues/106 but it will involve the rework of all liveries. Also, I'd like to have the some more 3D objects changing their texture according to the livery, such as propeller and wing lights (see issue https://github.com/Juanvvc/c172p-detailed/issues/18). I am just not sure I'd really like to be fixing and dragging these liveries around.

Currently we have 16! liveries, and I would suggest we keep the following 11:

4X-CHV (HD livery)
CAP
D-EEQA
default
G-BEMB
KLM
N35799 (HD livery)
OH-CTL (HD livery)
PT-IAO (HD livery)
ZK-WAX
ZS-MDF (HD livery)

This way we have 5 regular liveries, 5 HD ones and 1 blank for using the custom immatriculation. All regular liveries would use thevirtualfer's default panel.

What do you guys think?

**Comment by onox** [comment]
As long as you keep the KLM livery, I'm fine with removing the 5 ugly liveries :wink:

**Comment by wlbragg** [comment]
Works for me!

**Comment by gilbertohasnofb** [comment]
Ok guys, thanks!

@Juanvvc what about you, Juan? Do you have some request concerning these older liveries?

**Comment by Juanvvc** [comment]
Please, take into account the "ugly" liveries are someone's hard work. In case the c172p-detailed is finally selected as the default aircraft, I strongly believe these liveries should be still downloadable. If we decide to remove these liveries from the package, we should definitely submit them to the livery database.

**Comment by gilbertohasnofb** [comment]
(I already apologize in advance for the long answer! Here we go)

Well, every single texture file, 3D object and line of code in FG is part of someone else's hard work. The problem is that older collaborations may not be up to the same level of quality of current ones. If someone would replace any of my works in the future by better ones I wouldn't feel even slightly angry about it: I really believe quality comes in first place. Heck, even right now when I create a new livery or a new texture I am always asking all of you if you like it or not, and if I would get a "nope" as an answer I'd either rework it or leave it aside. I guess that's part of creating something good, isn't it? If legacy becomes a priority, we then come to the situation where an improved aircraft is full of new features but has a livery list polluted with low resolution textures created 15 years ago that probably most people won't use anyway, just for the sake of not removing someone else's work. And worse, these liveries have to be maintained to be up to date (e.g., adding the wing tip lights, propeller and other new textures to them...).

You also used quotation marks around "ugly", but I don't think it's that subjective in this case, or is it?

Anyway, I am willing to "recreate" these two low resolution liveries if you guys would like (I wouldn't even mind keeping the original 1024x1024 size instead of the typical 2048x2048 files that I normally create), but that would mean that the old files would serve only as a reference for the new ones, just as a layer in the background of GIMP which would later be deleted (so in the end, the work of whomever created those liveries would also be replaced). As for the other three ones, I wouldn't know how to improve them to be honest.

So I leave it up to you all if we should keep them with the plane or not, but I'd rather have them in the livery database as you proposed. Also, let me know what you think about the two low res ones, should I recreate them or not?

**Comment by wlbragg** [comment]
"should keep them with the plane or not"
Maybe  "not".

"but I'd rather have them in the livery database as you proposed"
I think that is a good alternative if we are concerned with legacy.

"I am willing to "recreate" these two low resolution liveries"
Any you are willing to recreate I think could have the original removed completely.

- my 2 cent

**Comment by gilbertohasnofb** [comment]
Ok, so I will recreate those two. And would anyone know who are the authors of those three liveries? We need to know who they are in order to upload them to the livery database.

**Comment by gilbertohasnofb** [comment]
Done, check forum for pictures. We still need to find the authors of the other 3, upload them to the livery database and remove their files from our folder in order to close this issue.

**Comment by gilbertohasnofb** [comment]
Does anyone have any clue on how to find the original authors of those 3 liveries? I tried looking for some mention of them in the forum but I came up empty handed. Without it we can't submit it to the livery database. If we don't find the authors, our options are to either remove the liveries anyway or just to leave them with the plane as they are now. But I repeat, these liveries will have to be maintained, and since we don't have them as a layered xcf file but only a flattened png, it will be quite some work to correct all of them.

**Comment by gilbertohasnofb** [comment]
Ok, let's just forget about this and leave all these liveries there. I reworked all of them (see https://github.com/Juanvvc/c172p-detailed/issues/139 and https://github.com/Juanvvc/c172p-detailed/issues/140), including manually recreating the back of their fuselages. Now all should work well with our plane, even if I still find some of them ugly :)
