### ISSUE TITLE
Sound effect for floats

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#264]
Sound effect for floats: needs the sound itself and then to be programmed.

**Comment by wlbragg** [comment]
Like slapping on water and/or gear retraction?

**Comment by onox** [comment]
I mean the quiet and calm sound of water while you're floating.

**Comment by gilbertohasnofb** [comment]
Okay. I guess we also need then of something moving through water as well, right? Could we implement both?

**Comment by onox** [comment]
That would be nice as well.

**Comment by wlbragg** [comment]
"Could we implement both?"
Yes

**Comment by gilbertohasnofb** [comment]
Okay guys, so I will look for the two sound effects and create a mono seamless loop, hopefully tonight I will have it done. Then I report back to you, onox.

**Comment by onox** [comment]
Sounds like a plan! :smile:  :+1:

**Comment by wkitty42** [comment]
from #238 
> (which begs the question, do things floating still make any sound?)

sure... ever take a metal flat bottom boat (eg: john boat) out on a lake or pond? little waves make small slapping noises against the hull... larger waves make sharper and slightly louder sounds... i would image they are similar to what one would hear with these pontoons...

**Comment by gilbertohasnofb** [comment]
You are right, wkitty, thanks. I am already working on the sounds and I have some ideas here :)

**Comment by onox** [comment]
@wlbragg Are you able to determine (x,y,z) coordinates of objects in the 3D model?

**Comment by wlbragg** [comment]
"(x,y,z) coordinates of objects in the 3D model"
Not sure what you are asking, in what context?

**Comment by onox** [comment]
I would like to know the position of the master, avionics, and beacon switches.

**Comment by onox** [comment]
x positive is aft, y positive is right, z positive is up. For example, the location of the stall speaker is (0.4, 0, 0.4).

**Comment by gilbertohasnofb** [comment]
Ok, it's uplodaded. There are two files:

- `water-still.wav`: should be fairly soft and played every time the pontoon is in contact with the water
- `water-fast.wav`: should be played only when in contact with the water as well, but its volume should be proportional to the speed of the plane (given a range of let's say 0 knots for min volume and 60 knots for max volume. Speeds > 60 knots should then not change the volume any more).

What do you think?

**Comment by onox** [comment]
Sounds good to me.

**Comment by wlbragg** [comment]
No guarantee but

master
x -0.3660
y -0.4142
z -0.2396

avionics
x -0.3660
y -0.3995
z -0.2679

beacon
x -0.3660
y -0.1533
z -0.2679

avionics is a bit of a guess because it's position is not in the aircraft blend file.

**Comment by wlbragg** [comment]
Do you not have blender or a way to check this?
Or am I not understanding what you want.

**Comment by wlbragg** [comment]
The master position is the center between the two master switches.

**Comment by onox** [comment]
Thank you so much @wlbragg :smile: Yes, I have Blender, but I don't really understand it.

**Comment by wkitty42** [comment]
@onox i'm in the same boat... except you understand more than i do ! :laughing:

**Comment by onox** [comment]
I've added the positions. The x coordinate was good, but the y and z needed to be adjusted a bit. It's not really possible to hear any difference in the position, but that might change if we add sounds for the radio stack and the doors.

**Comment by wlbragg** [comment]
No problem, I'm almost shocked though that I am the one someone would come to with a blender question. I knew next to nothing about it less than 6 mo ago, now I guess I can get around somewhat in it.
It's one of those programs though that have so many things and ways to do them that it takes a long time of constant use to learn it all.
Glad I could help.

**Comment by andgi** [comment]
I took a quick stab at adding pontoon/float sounds:
https://github.com/Juanvvc/c172p-detailed/pull/287

**Comment by gilbertohasnofb** [comment]
I just tested it. Here are some thoughts and bugs:

- when I load the plane, the sound is really soft. Once the engine starts and the plane starts to move, there is a huge sudden raise in volume which doesn't sound good
- as soon as the plane is not in touch with the water, the sound stops at once. I would say fading it out (for some 0.5 seconds) would make it sound way better
- are you using both sounds I had uploaded? I couldn't really hear it very well.

Also, I had proposed the following implementation, what do you think?

- `water-still.wav`: should be fairly soft and played every time the pontoon is in contact with the water
- `water-fast.wav`: should be played only when in contact with the water as well, but its volume should be proportional to the speed of the plane (given a range of let's say 0 knots for min volume and 60 knots for max volume. Speeds > 60 knots should then not change the volume any more).

**Comment by andgi** [comment]
I have only used water-fast.wav. The sound should not be audible at all until 2 knots, if it starts too loud I can lower the initial volume (currently 0.2) and possibly the maximum volume (currently 2.0). On my system it is rather weak all the time - I more or less have to pull the mixture to hear it clearly. Fading out a sound is outside my knowledge of FG the sound system so I'll have to leave that for somebody else.

**Comment by gilbertohasnofb** [comment]
@andgi okay then, but it would be great to have both sounds. Also, I believe that fading in and out is quite crucial in this issue. Let's see if @onox can help implement these things.

**Comment by andgi** [comment]
If you want water still played all the time at constant volume while any float is in contact with water that is not so hard to add.

Fading out is harder, but maybe a height AGL property could be used for the condition and to fade out the volume.

**Comment by gilbertohasnofb** [comment]
> If you want water still played all the time at constant volume while any float is in contact with water that is not so hard to add.

Yep, that would do.

> Fading out is harder, but maybe a height AGL property could be used for the condition and to fade out the volume.

Great idea. Could fade it quite quickly (my guess is 8-10 ft AGL). This should apply to both sounds as well.

What do you think?

**Comment by andgi** [comment]
I have added the water-still sound too now. I've realized altitude AGL doesn't work by itself for fading out since it would have to remember that the sound was playing, but the current activation property goes to 0 as soon as the floats leave the water and cannot tell that the previously were in the water.
A specialized property that decays after leaving the water needs to be added.

**Comment by onox** [comment]
@andgi Maybe you could replace the activation property with a [monostable](http://wiki.flightgear.org/Autopilot_configuration_reference#Monostable_flip_flop_.3Cmonostable.3E) filter (in a `<property-rule>` or `<autopilot>`) to delay the deactivation.
