### ISSUE TITLE
correct background of the attitude indicator

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#27]
XML03 - the background of the attitude indicator (just behind the moving part which shows the attitude) is currently grey, but it should be coloured according to the file AI1.rgb
  * Ludomotico: This is a weird bug: the background of the AI depends on the angle of view or the zoom level.
  * Gilberto: I can swear this has already been fixed, or am I seeing things?

**Comment by gilbertohasnofb** [comment]
Can someone confirm this has been fixed? All looks fine for me, but this issue hasn't been moved to the fixed section of our old TODO file...

**Comment by Juanvvc** [comment]
Yes, this was fixed when the object inside the panel was moved sligthly to the bow.
