### ISSUE TITLE
Various multiplayer errors

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#274]
1. Effects:

    ```
Cannot find image file "Models/Effects/interior/black_px.png"
Cannot find image file "Models/Effects/interior/black_nx.png"
Cannot find image file "Models/Effects/interior/black_py.png"
Cannot find image file "Models/Effects/interior/black_ny.png"
Cannot find image file "Models/Effects/interior/black_pz.png"
Cannot find image file "Models/Effects/interior/black_nz.png"
Cannot find image file "Models/Effects/interior/grayscale_px.png"
Cannot find image file "Models/Effects/interior/grayscale_nx.png"
Cannot find image file "Models/Effects/interior/grayscale_py.png"
Cannot find image file "Models/Effects/interior/grayscale_ny.png"
Cannot find image file "Models/Effects/interior/grayscale_pz.png"
Cannot find image file "Models/Effects/interior/grayscale_nz.png"
Cannot find image file "Models/Effects/interior/default_px.png"
Cannot find image file "Models/Effects/interior/default_nx.png"
Cannot find image file "Models/Effects/interior/default_py.png"
Cannot find image file "Models/Effects/interior/default_ny.png"
Cannot find image file "Models/Effects/interior/default_pz.png"
Cannot find image file "Models/Effects/interior/default_nz.png"
```

2. Missing "Aircraft/c172p/" prefix:

    ```
loadxml: Cannot find XML property file 'Models/Liveries/4X-CHV (HD livery).xml'
```

**Comment by wlbragg** [comment]
Did this break with the name change?

**Comment by onox** [comment]
Did we remove the aircraft path prefix during the name change? I think the prefix was never there (not sure though).

**Comment by onox** [comment]
Some user reported the livery update bug on the mailinglist.

**Comment by wkitty42** [comment]
@onox are you speaking of this post by ludovic brenta?
On 06/10/2015 05:43 PM, Ludovic Brenta wrote:
> I just had a similar symptom; another player with a c172p suddenly
> disappeared from my view and pilot list, but remained on the live map.
> At least this time I had an error message in my log window:
> 
> loadxml: Cannot find XML property file 'Aircraft/c172p/Models/Liveries/OH-CTL (HD livery).xml'.
> 
> Spaces and parentheses in file names are a bad idea :/
> 
> Would anyone like to jump in and rename that file in FGAddon?

here's my response to him...
> that file should not be in FGAddon... it is part of the new c127p-detailed... AFAIK, this craft
> has not yet been added to anything in the official distribution...

> i'll pass this back to the rest of the team working on it to ensure that they have seen it... our
> freeze is coming up shortly so that we can have something ready for fgdata...

maybe we should consider his comment about the filenames? obviously we don't seem to be having problems on linux and i guess winwhatever... has anyone tested the craft on mac?

**Comment by onox** [comment]
@wkitty42 Actually we both run Linux and I could reproduce the problem.

**Comment by wkitty42** [comment]
:+1:  yes, i've now seen the merges and just read the del list... i've been down for the last few days with some sort of bleeding lung infection or perforation so i've not been able to be up and spend as much time on anything as i was :disappointed:

**Comment by onox** [comment]
I hope you get better soon :cat:  :worried: :sob:

**Comment by wkitty42** [comment]
me^2 ... the gods and goddesses will have their way with me, one way or another :wink:

**Comment by wlbragg** [comment]
Get well!
