### ISSUE TITLE
console error messages

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#282]
i'm seeing this with the latest... not sure what's caused it... i hate being sick like this :( 

details: started at KMCO with amphibious pontoons... flew north maybe 10 minutes or so to a small lake (slightly east) with an amphibious landing area... landed perfectly and then ""boated"" to the dock area... basically beached the craft and then extended the gear so as to try to drive up on the land... how is that supposed to work now? get the gear down and then beach/drive onto the land?

the first error/warning was already on the console when i looked... not sure when the other (invalid listener id) showed up... i had exited previously with amphibious pontoons already selected...

$ ~/flightgear-dev/next/run_fgfs.sh --launcher
default catalog not found, installing 'org.flightgear.default' from 'http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml'.
catalog download failure:http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml
Enabling ATI viewport hack

In file /home/wkitty42/myflightgear/Aircraft/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.
Nasal runtime error: removelistener() with invalid listener id
  at /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/io.nas, line 391
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/lag_adjust.nas, line 67
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/lag_adjust.nas, line 92
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/globals.nas, line 119
Loading local weather routines...
Animated jetways ... initialized
KMA20 audio panel initialized
Hobbs system stopped
Starter off
KI266 dme indicator #0 initialized
Electrical system initialized
Primer reset to 0
Starter on
Hobbs system started
Starter off
Primer reset to 0
Starting hard-coded terrain presampling
Flap Volts: 28
Flap Volts: 28
Flap Volts: 28
Flap Volts: 28
Flap Volts: 28
Flap Volts: 24.62959660294488
Flap Volts: 24.62917211427198
Flap Volts: 24.62664705089879
Flap Volts: 24.62664705089879
Flap Volts: 24.62480516160373
Flap Volts: 24.62431587118737
Flap Volts: 24.61491266679638
Flap Volts: 24.61444642528362
Flap Volts: 24.60880813798402
Flap Volts: 24.60836222761731
Hobbs system stopped
Segmentation fault (core dumped)

**Comment by onox** [comment]
Have you tried to start FG multiple times?

**Comment by wkitty42** [comment]
no, not at the same time... i have a desktop specifically for running fgfs... i don't run it on any other desktop of the 8 that are configured... when i was testing to see if the battery drain repair had been implemented (before i read your post about it not having a PR) i saw that the messages were all posted at roughly the same time...

just tested again... the first one about line 25 comes up real fast and the next takes about 20 seconds or so... timing not accurate... guessed by ALT-TAB back to the console window after clicking the [run] button in the launcher... i haven't done anything other than start fgfs in this test... my current pull is from commit 43ea6fe1b6f1695a33bd5cffb7c13bdc1627dada... here's the output i got this time from a start and wait to settle out on the runway with an immediate [esc] exit... starting with amphibious pontoons selected if that makes any difference...

$ ~/flightgear-dev/next/run_fgfs.sh --launcher
default catalog not found, installing 'org.flightgear.default' from 'http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml'.
catalog download failure:http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml
Enabling ATI viewport hack

In file /home/wkitty42/myflightgear/Aircraft/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.
Nasal runtime error: removelistener() with invalid listener id
  at /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/io.nas, line 391
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/lag_adjust.nas, line 67
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/lag_adjust.nas, line 92
  called from: /home/wkitty42/flightgear-dev/fgdata-ng/Nasal/globals.nas, line 119
Loading local weather routines...
Animated jetways ... initialized
KMA20 audio panel initialized
Hobbs system stopped
Starter off
KI266 dme indicator #0 initialized
Primer reset to 0
  Trim Results: 
          Altitude AGL:    3.4  wdot:  3.21e+01 Tolerance: 1e-03  Failed
           Pitch Angle:  0.098  qdot:  1.08e-09 Tolerance: 1e-04  Passed
            Roll Angle:     15  pdot: -9.82e-09 Tolerance: 1e-04  Passed

  Trim Statistics: 
    Total Iterations: 61
    Sub-iterations:
    wdot: 0 average: 0  successful:  0  stability: 5.6467
    qdot: 0 average: 0  successful:  0  stability: 2
    pdot: 0 average: 0  successful:  0  stability: 2
    Run Count: 1775
Electrical system initialized
Segmentation fault (core dumped)

**Comment by onox** [comment]
I didn't mean running multiple fgfs instances at the same time, but I meant that you try to restart FG sequentially. I get segfaults too once in a while. I then just try to start FG again and then it works.

**Comment by wkitty42** [comment]
@onox OH! the segfault has nothing to do with this stuff... it happens all the time right now when i exit the sim after using the built in --launcher... i just copied the entire screen of output... the two errors i'm speaking of are at the top between "Enabling ATI viewport hack" and "Loading local weather routines..." :wink:

**Comment by onox** [comment]
Those errors are not caused by the c172p aircraft. They are caused the MP patch in fgdata.

**Comment by wkitty42** [comment]
@onox oh... ok... since i've been out for a few days and only had a few tens of minutes at a time to play, they were a surprise to me when i saw them...
