### ISSUE TITLE
water spray on windshield after roll onto land

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#284]
amphibious pontoons... take off from airport (KMCO in this case) and fly to some water landing area (near cape canaveral in this case)... gear up after takeoff... perfect landing on water... slowed to ~6-8kts and approached the land... lowered gear and increased throttle to roll up onto the land... rolled onto the land pretty easily... backed off power, set brakes, performed full shutdown procedures... location ~10feet from edge of water facing inland (water behind craft)... still getting water splashes on windshield... restarted craft, boosted throttle in an effort to maybe blow the water off the windshield and stop it from continuing to appear... no luck... perform complete shutdown procedures and exit sim with water still splashing on windshield...

**Comment by wlbragg** [comment]
Were the back of your pontoons still in the water? If not I'll try to duplicate.

**Comment by wkitty42** [comment]
i was ~10 feet from the water on the land when i restarted the craft to try to dry the windshield...

**Comment by gilbertohasnofb** [comment]
@wkitty42 if you can, add some labels to your bug reports to help organize them. Also, if it's a pure bug and it's something simple, we can assign it to the FG 3.6 release milestone.

**Comment by wkitty42** [comment]
@gilbertohasnofb i've looked when i create issues or go back to edit those i've made and i don't see anywhere to select labels...

**Comment by gilbertohasnofb** [comment]
Do you have direct push access to this repository? Because if not then I believe you can't select labels yourself. In that case no worries, I don't mind to keep adding them myself.

**Comment by wlbragg** [comment]
I think I have identified the problem and will fix it tonight (hopefully)

**Comment by wkitty42** [comment]
@gilbertohasnofb no, i don't have push access to the repo... that's ok, too... less chance for me to mess something up :wink:
