### ISSUE TITLE
Save and restore state of switches

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#285]
last time i was in the sim, i shut down everything and ensured that all switches were in the OFF state... i'm not sure where this problem is but i just loaded the sim with the same craft and location as last time and the battery, alternator, and avionics switches are all ON instead of OFF where they had been set... the starter switch is also set to BOTH for the magnetos... that was also specifically turned off... additionally, the mixture knob is pushed all the way in to 100% instead of being pulled out to 0% where it was also left...

**Comment by wlbragg** [comment]
This was working?

**Comment by wkitty42** [comment]
i'm not sure what you are asking?

**Comment by wkitty42** [comment]
i just tested again... commit a2e3a5f76db85eac4a415f08971fe1f7d6c6cf28 ... start the sim... ensure that everything is OFF and mixture is at 0%... exit the sim, start the sim with the same command line and options (i use --launcher and just click run because everything is already set or stored as i want it)... battery, alternator, avionics switches are ON, starter is set to BOTH and mixture is 100%... none where they were previously...

TBH, i'm not sure if this is a sim problem or a settings saving and restore problem with the craft... i know that at least one craft forces everything off when loading so that you have to go through its startup sequence properly... i'd just like to see this one restoring the switches to the last state they were in when the sim was exited or reset... note that i'm not testing reset at all even if i do mention it here ;)

**Comment by wlbragg** [comment]
"i'm not sure what you are asking?"
Was it something that used to work but suddenly doesn't anymore?

**Comment by wkitty42** [comment]
@wlbragg honestly, i don't know :/

**Comment by onox** [comment]
I want to save the following additional properties:

`/controls/switches/magnetos`
`/controls/switches/master-bat`
`/controls/switches/master-alt`
`/controls/switches/master-avionics`

`/controls/gear/brake-parking`
`/controls/flight/flaps`
`/controls/flight/elevator-trim`
`/controls/engines/current-engine/throttle`
`/controls/engines/current-engine/mixture`
`/controls/engines/engine[0]/primer-lever`

Fixes #82 as well.

**Comment by gilbertohasnofb** [comment]
Probably you could also add the carburator heater lever as one day we plan to implement carb icing.

**Comment by onox** [comment]
That one is already present (`/controls/anti-ice/engine/carb-heat`).

**Comment by gilbertohasnofb** [comment]
ok, my bad

**Comment by onox** [comment]
@gilbertohasnofb I see that the circuit breaker for the air conditioning hasn't been implemented?

**Comment by gilbertohasnofb** [comment]
No, it hasn't. I think there was some discussion about it before (maybe @Juanvvc remembers it). But does our cessna have air conditioning? (I just checked and the real OH-CTL doesn't have that breaker)

**Comment by onox** [comment]
It has cabin air+heat, or is that not controlled by that circuit breaker?

**Comment by gilbertohasnofb** [comment]
I think carbin air and heat is a different thing than air conditioning, but I'd ask @tigert and @Juanvvc about it.

**Comment by gilbertohasnofb** [comment]
(just as an example: I have seen so many older cars with air vents and some sort if air heat as well but NOT air conditioning)

**Comment by onox** [comment]
Yes, they are different things. But I'm not sure to which "air cond" should refer.

**Comment by gilbertohasnofb** [comment]
I am seeing several pictures of the model P's panel, and some have this air conditioning breaker while most don't. Since we don't have implemented the air conditioning system, maybe we should simply remove this breaker, what do you think? I can remove the labels from the panels if you want, or we can leave the label and the black surround of the breaker, but remove the breaker itself (see: http://s27.postimg.org/zepnx88g3/panel_reference4.jpg).

**Comment by gilbertohasnofb** [comment]
Oh, I just checked our plane in we actually don't have a breaker for the air conditioning, just the panel label. It's exactly as in the picture above. So if we don't ever implement an air conditioning system (which I don't think we need to) then the plane is fine as it is.

**Comment by wkitty42** [comment]
On 07/08/2015 04:35 PM, onox wrote:
> Yes, they are different things. But I'm not sure to which "air cond" should refer.

if there's a breaker, that indicates electrical and that indicates a freon type 
based A/C like in a house, refrigerator, or car... this craft doesn't have that 
in this implementation... there's only open windows (when they get implemented) 
and the air vent up on the corner of the windshield (i think that's where it is)...

**Comment by Juanvvc** [comment]
wkitty42 is right. The A/C is an optional equipment not installed on all c172p. I guess it was not very popular and it is not installed on our c172p, but the breaker hole and the label are there just in case :) Empty (but covered) breaker holes are common, as the picture linked by gilberto shows.
