### ISSUE TITLE
water spray on windshield disappears too suddenly

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#288]
Currently, the water spray on windshield disappears too suddenly after a water take off. As soon as the plane is not touching the water the spray disappears immediately. Would it be possible to fade them out somehow or work on this transition?

**Comment by wlbragg** [comment]
Yeah, I think we can do that.

**Comment by gilbertohasnofb** [comment]
Are you sure this is fixed? Now what happens to me is that after I take off from water, the water spray stays with the plane for a really long time! Like 30 seconds or so. Is that on purpose? Also, I don't see the fading.

**Comment by wlbragg** [comment]
gilbertohasnofb,
I am doing the following
if altitude > 2m or hydro/active-norm = 0
 subtract .005 from ground-splash-norm every loop until ground-splash-norm = 0

It isn't elegant, but it should be slowly removing any water drops from the windshield.

**Comment by wkitty42** [comment]
@wlbragg would there really still be water spray 6 feet off the water? i don't know where 0m is being read from... eye level? bottom of the pontoons? bottom of the craft's belly? maybe reduce from 2m to 1m?

**Comment by wlbragg** [comment]
Funny you mentioned that, the actual prop used is
altitude-agl-m
and that is independent to the particular aircraft as to where exactly that is.
I vaguely remember looking at that number and I think it was somewhere like 1.?? when sitting on the ground so it should be close enough.
Also don't forget I am using 
altitude-agl-m OR  hydro/active-norm = 0
and the whole idea was the "residual" water dissipation, not the start of water splash, that requires
hydro/active-norm > 0, nothing to do with AGL. 
Now I can't even remember why I am using AGL at all.

**Comment by wkitty42** [comment]
i just (finally) found that property... i see one called gear-agl-m but that one seems to be off, too... i don't know what it is calling "gear" if it isn't the landing gear...

wearing the amphibious pontoons, sitting on the runway at KMCO:
altitude-agl-ft: 6.760xxxxxxxx
altitude-agl-m: 1.755xxxxxxxx
gear-agl-m: 2.289xxxxxxxx

wearing the regular pontoons, sitting on the runway at KMCO:
altitude-agl-ft: 6.657xxxxxxxx   (drifting)
altitude-agl-m: 1.726xxxxxxxx   (drifting)
gear-agl-m: 2.257xxxxxxxx   (drifting)

wearing normal landing gear, sitting on the runway at KMCO:
altitude-agl-ft: 4.400xxxxxxxx
altitude-agl-m: 1.036xxxxxxxx
gear-agl-m: 1.569xxxxxxxx

looking at those numbers, something is wrong... the agl in meters and feet should be better matched when converting from one to the other... taking the last set with normal gear, 1.036 meters is 3.399 feet not 4.4 feet... going the other way, 4.4 feet is 1.34112 meters... and i'm still not sure where the "gear-agl-m" is coming from... surely it isn't the actual landing gear position above ground level... these have got to be based off of some other point in the model...

on the second set of numbers wearing the regular pontoons, "(drifting)" means that the numbers are floating up and down in at least the second and third decimal places... they're not steady like the other two sets of readings...

sorry, too, it is 0500 here... i woke up at 0300 and can't get back to sleep :(

**Comment by gilbertohasnofb** [comment]
@wlbragg 

> I felt like the one test I did after coding it worked OK.

I will test it again, and if it fails I will make a video of it, ok?

**Comment by onox** [comment]
Also, have you read #299?
