### ISSUE TITLE
Flaps keep moving to new position after turning off battery

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#294]
If you turn on the battery, then move the flaps to a new position, and then quickly turn off the battery again. Then the flaps keep moving to their new position.

After the flaps have moved to their new position, they can no longer be moved again, which is good :+1:

**Comment by gilbertohasnofb** [comment]
The property we have to freeze is `/surface-positions/flap-pos-norm`, but I can't find where this property is being changed. If anyone can point me in the right direction I can try to fix this.
