### ISSUE TITLE
Sparks not visible in evening and night

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#295]
Sparks are visible during the day, but not in the evening and night. Shouldn't they actually appear brighter during the evening and night than during the day?

Noon (visible):
![fgfs-screen-065](https://cloud.githubusercontent.com/assets/3361585/8147279/de167512-1262-11e5-8c0e-b468a7254d75.png)

Dusk (still a little bit visible):
![fgfs-screen-066](https://cloud.githubusercontent.com/assets/3361585/8147275/c406ea30-1262-11e5-83b0-4ede218011c0.png)

Evening:
![fgfs-screen-068](https://cloud.githubusercontent.com/assets/3361585/8147276/c40a2682-1262-11e5-90f3-584bb99ffc56.png)

**Comment by gilbertohasnofb** [comment]
Bug confirmed.

**Comment by wlbragg** [comment]
I'll try to take a look at thins in the next 24 - 36 hrs.

**Comment by onox** [comment]
@wlbragg Have you tried to see what is causing this problem? I'll branch and tag in about an hour or so.

**Comment by wlbragg** [comment]
Oops, fell through the cracks. I'll look at it in a couple hours, when I get home to my computer.

**Comment by onox** [comment]
@wlbragg I have tagged version/3.6.0 and create a release branch called release/3.6.0, so version 3.6 has been released. This means we can now start working on 3.8! (And party! :smile: :tada: )

**Comment by gilbertohasnofb** [comment]
@wlbragg I believe onox told Stuart in the mailing list to go ahead and merge our plane with fgdata, and so this issue has already been moved to the 3.8 release milestone. In that case I guess you don't have to hurry now to fix it.

**Comment by gilbertohasnofb** [comment]
> This means we can now start working on 3.8! (And party! :smile: :tada: )

Yay! :beers: :cocktail: :tada: :dancer: :wine_glass: 

Really guys, very good job, it has been a pleasure to work with you all. Looking forward to start dealing with the 3.8 issues :smile:

**Comment by onox** [comment]
@wlbragg @gilbertohasnofb FYI, I have renamed the v3.6 tag to `freeze/3.6.0` and tagged your last commit as `version/3.6.0`. This commit is also used by the release branch `release/3.6.0`.

**Comment by onox** [comment]
> Looking forward to start dealing with the 3.8 issues

And adding cool new features like the GPS and the web panel :smile:

**Comment by gilbertohasnofb** [comment]
@onox Yeah, the GPS is really grabbing my attention now, I'd love to work on it!

**Comment by onox** [comment]
Can I give you a link to the code for the OSM map I worked on a little?

**Comment by gilbertohasnofb** [comment]
@onox quick question: now that we are past our 3.6 milestone and that we have `release/3.6.0` branch, should we start working on the 3.8 features and bug fixes via PR's to be merged in the master?

**Comment by onox** [comment]
master branch is now open (via PR's of course) for 3.8 features and bug fixes.

**Comment by gilbertohasnofb** [comment]
:+1:
