### ISSUE TITLE
pink tint - ALS flashlight shadow issue?

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#298]
it this pinkish shadow looking tint on the instrument dials the weird shadow thing that was being looked for with the ALS flashlight? it is easily seen in the instruments in this shot... i haven't seen or noticed it before now but this flight had the sun relatively low back over my right shoulder... i should have zoomed in more to catch it better... this is also an unedited snapshot...

![fgfs-screen-054](https://cloud.githubusercontent.com/assets/4641713/8151192/05824370-12d5-11e5-8abb-6014abce779b.png)

**Comment by wlbragg** [comment]
It is possible, what it is that has the potential for negative (or positive) effects is the internal shadow effect. It is required to have any object that you want to have the flashlight effect also have the interior shadow applied to them. We always had interior shadow applied to the panel, buttons seats., etc., but we never did apply it to all the instruments and gauges until the flashlight code was finished. That is when I added "interior shadow" effect to all the instruments and gauges and all their parts.

**Comment by wkitty42** [comment]
@wlbragg is there some special method that i can use to see if this is related to the flashlight? moving my viewpoint around, maybe? i've lost the sun in real time so i'll have to try to set up something in sim time to simulate what i was seeing if changing my viewpoint is a/the way to test this...

**Comment by wkitty42** [comment]
i just tried to set something up but dusk is too late and afternoon is too early :(  i'll try to remember to test this again before 19:00 EDT by flying the same route again tomorrow...

**Comment by wlbragg** [comment]
You can choose an instrument or gauge that you want to test and edit its xml file. The clock looked like it had a lot of pink.
You can edit c172p\Models\Interior\Panel\Instruments\clock\clock.xml and comment out
```
<effect>
  <inherits-from>../../../../Effects/interior/c172p-interior</inherits-from>
  <object-name>Face</object-name>
  <object-name>SecondHand</object-name>
  <object-name>MinuteHand</object-name>
  <object-name>HourHand</object-name>
 </effect>
```

**Comment by onox** [comment]
Add `<!--` and `-->` around it.

**Comment by wkitty42** [comment]
if/when i can reproduce this, i will try to comment out the effect in one of the instruments and test it... i hate having to exit the sim, edit and reload the sim to try to get back to the same place... especially when time is against me/us... i saw the above while flying but i may be able to do it again while sitting on the ground...

**Comment by onox** [comment]
@wlbragg Did PR #332 fix this?

**Comment by wlbragg** [comment]
Probably

**Comment by wlbragg** [comment]
I'm sure this was the internal shadow on the gauges, if it appears again open a new issue.
