### ISSUE TITLE
Reclaim int[14] to int[19] MP properties

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#299]
The registration number system (immat) uses 6 precious properties. We need to reclaim the properties for the more important effects.

Use Canvas to paint the registration number from `/sim/multiplay/generic/string[0]` on the fuselage. Draw text on the fuselage or use http://wiki.flightgear.org/Howto:Dynamic_Liveries_via_Canvas

`/sim/model/c172p/immat` is true for the livery "default" only. All other liveries do not display the registration number on the wings and fuselage.

Current problem is we need to replace the "textranslate" technique to display the registration number in the cockpit with either Canvas or the old method (`<text>` IIRC). We can use local properties for this since only the white plain ugly "default" livery displays it on the fuselage.

* [x] Use different local properties for displaying the registration number in the cockpit. For example, we could use `/sim/model/c172p/regnum1`, etc. (lets not keep using French). Modify `Models/Immat/immat.xml` and `Nasal/immat.nas`.
* [x] Disable the animations that display the registration number on the fuselage in `Models/Immat/immat.xml`. (If we leave it enabled, we would need to use the same local properties as those used for the cockpit panel, which looks weird over MP. So better just disable it) (All liveries except "default" do not show the registration number on the fuselage anyway)
* [ ] Use int[14] to int[19] to show water spray effects over MP

* ~~Use Canvas to paint the registration number on all liveries. Use custom colors and fonts tailored for the specific liveries.~~

**Comment by onox** [comment]
@wlbragg We can do the first three items today and tomorrow. Canvas stuff should be done later.

**Comment by gilbertohasnofb** [comment]
> Use Canvas to paint the registration number on all liveries. Use custom colors and fonts tailored for the specific liveries.

I am pretty much against this. This will be a lot of work and little gain in my opinion, and the Canvas text does not look as good as a textured text. Really don't see the point. Also, all those HD liveries are based on real life airplanes and I use their real life callsigns as well.

**Comment by wlbragg** [comment]
"all those HD liveries are based on real life airplanes and I use their real life callsigns as well."
I can agree with that, but if we do retain some kind of registration system, it would be nice to have some of those or other HD paint schemes.

"This will be a lot of work and little gain in my opinion, and the Canvas text does not look as good as a textured text."
I was just looking at the existing system and don't understand it well enough to make really informed opinion on it, but on cursory review I don't see why it can't be converted to use string vs int. We need those valuable MP INT's back and I think there has to be a better way than passing (and loosing) 6 INT's for MP.
There are other hard-coded MP vars being passes we can steal if needed, but the immat's were the most logical place to look first IMO.
As far as canvas is concerned, that was a late night brainstorming suggestion as an alternative (all I could here bouncing around in my brain was Hooray saying "Canvas, Canvas, Canvas" :) ), I'm sure if it can't be made to look good we won't do it.

**Comment by wkitty42** [comment]
> (all I could here bouncing around in my brain was Hooray saying "Canvas, Canvas, Canvas" :)

now that's funny! worth posting to the forum's "what made you laugh" topic :angel:

**Comment by gilbertohasnofb** [comment]
@wlbragg check out the discussion at #300 for more arguments. What seems to have been decided is to leave things as they are: one "custom callsign" livery which will receive immat on panel and outside (currently named "default" and completely blank, but I will make it pretty instead of just white) and all other liveries will continue to have hard coded callsigns on the outside and no immat in the panel (as some also have it hard coded in their panel textures). Is that all right with you all?

**Comment by wlbragg** [comment]
I just read  #300 after posting the above. Yes that still fits with my logic :). 

Maybe in the future we might be able to add a couple other color schemes for custom registration.

**Comment by gilbertohasnofb** [comment]
> Maybe in the future we might be able to add a couple other color schemes for custom registration.

Sure, that is possible. I will have a look on the situation now and maybe I can try to add already 2 or 3 options for the custom callsign.

**Comment by wlbragg** [comment]
onox, I am confused as to what you asking in the checkoff list. We have to disable all of it to use 14-19 because the panel is using them also.
So are you saying to ALSO use (create) different props (other than the ones they setup in alias), and why did they set up the alias's if they never used them over MP? Aren't they setup and only used locally?

**Comment by onox** [comment]
The registration number in the cockpit uses the same properties because they already used those properties for MP.

What I'm trying to say is, we modify `immat.xml` to just display the registration number in the cockpit and use local properties for it. Only the local player has see the cockpit anyway. So no need to use MP properties in order to display the registration number on the cockpit panel.

**Comment by wlbragg** [comment]
OK, you wan't me to work on that now so I can have the alias's back?

**Comment by onox** [comment]
If we use local properties for the registration number in the cockpit, we can use the 6 MP properties currently in use for something else.

**Comment by onox** [comment]
You can work on it if you want yeah :smile:

**Comment by wlbragg** [comment]
No, I didn't say I want, but if I want the alias's back I guess I have to :(...

**Comment by onox** [comment]
@wlbragg You can reclaim int[14], int[15], int[16], int[17], int[18], int[19].

**Comment by wlbragg** [comment]
OK, one more question, why are we commenting out the wing and fuselage section and not just using the "new" props on it also?

**Comment by onox** [comment]
Because if you're flying online and I look your aircraft. I see @wlbragg flying with PH-ONOX painted on it :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
OK, now you have really confused me.

I can't reclaim 14-19 until I fix immat.xml and immat.nas?
We aren't going to be sending the immat info across MP anymore are we if we reclaim 14-19, so everything is local now, no one will see anything?
If we do convert MP over to unused string MP's we can also send the info for only showing the immat if using an aircraft that allows it?
You have thoroughly confused me (don't worry, that's not hard to do)...

**Comment by onox** [comment]
> I can't reclaim 14-19 until I fix immat.xml and immat.nas?

Yes.

> We aren't going to be sending the immat info across MP anymore are we if we reclaim 14-19, so everything is local now, no one will see anything?

Yes. But people couldn't see the custom callsign anyway, because @gilbertohasnofb toggled "immat" to false some time ago.

**Comment by onox** [comment]
Shall I modify `immat.xml` and `immat.nas`?

**Comment by wlbragg** [comment]
I think that is a great idea!

**Comment by gilbertohasnofb** [comment]
> because @gilbertohasnofb toggled "immat" to false some time ago.

Just to make it clear, it was off for all liveries except for the "default" one, and this was discussed in the forum thread so it's was not a maverick moment of mine :wink:

**Comment by wlbragg** [comment]
I still don't understand why we are removing "locally" displaying registration on the wing and tail section. It is local only and will never bee seen across MP.
So why remove it?
No worries gilbertohasnofb.

**Comment by onox** [comment]
I know, the ugly white livery is the only exception. But I find that livery so super ugly that I'm just going to act like an ostrich, put my head in sand, and pretend it doesn't exist :laughing:

**Comment by onox** [comment]
@wlbragg If you do display it, the aircraft will paint a callsign on the wings and fuselage. The problem is is that it will be the wrong callsign. The aircraft of player B should draw callsign B on A's computer, but with local properties it will draw A's callsign on B's aircraft on A's computer.

**Comment by onox** [comment]
On B's computer, it will draw B's callsign on A's aircraft.

**Comment by onox** [comment]
I'll create branch bug-299 and modify `immat.xml` and `immat.nas`, and you'll see and understand :smile: Shouldn't take more than a couple of minutes to fix.

**Comment by wlbragg** [comment]
OK, I trust you got that worked out in you mind. I guess I am just not up to speed on this whole MP thing. Best I see it... Thanks for your patience!

**Comment by gilbertohasnofb** [comment]
> I know, the ugly white livery is the only exception. But I find that livery so super ugly that I'm just going to act like an ostrich, put my head in the sand, and pretend it doesn't exist :laughing:

The new "Custom Callsign" liveries are already up. There are 2 of them, please have a look.

**Comment by gilbertohasnofb** [comment]
Images:

http://s15.postimg.org/evta0nci3/fgfs_screen_002.png
http://s15.postimg.org/5mr3qj3m3/fgfs_screen_003.png

**Comment by wlbragg** [comment]
Very nice, thank you!

**Comment by gilbertohasnofb** [comment]
My pleasure!

**Comment by gilbertohasnofb** [comment]
I deliberately created textures with lots of white so there is no worry about the colour and position of the callsigns, but I have the impression the letters are a bit too far apart from each other.

**Comment by onox** [comment]
I'm done, pushing in a minute.

**Comment by onox** [comment]
Pushed branch bug-299.

**Comment by Juanvvc** [comment]
Regarding the color of the letters, they are not yet themable but nothing prevents these letters to be changed with the livery, as any other texture. Currently, the letters are inside Model/immat/immat.png. I also think these letters are too far apart each other but this is very easy to fix.
