### ISSUE TITLE
Change default livery

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#300]
1. The current default in `/sim/model/livery/file` is "D-EEQA". Let's change this to a HD livery. I suggest either "4X-CHV_HD_livery" or "OH-CTL_HD_livery".

2. The "default" livery is plain ugly white:

![fgfs-screen-079](https://cloud.githubusercontent.com/assets/3361585/8154368/aaf7e062-1339-11e5-98be-0f8105ccba6e.png)

~~I propose that we just delete it.~~

**Comment by wkitty42** [comment]
if we're dumping the immat thing, this is/was the only craft really using it... plus the letters weren't following the fuselage contours... it is a nice idea and i've seen and used it on other craft... b1900d or citationX when i did one of my custom liveries and this immat was on the tail...

but having the plain ugly white kinda might give folks something to work with for doing their own liveries... maybe?? just change the name of it from "default" to something else like "plain_ugly_white" :laughing: :wink:

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> but having the plain ugly white kinda might give folks something to work with for doing their own liveries

Nope, that doesn't make sense. We have a paint kit included as a GIMP file in our plane so no need to keep a white texture (also, the paint kit has shadows in different layers which is necessary for any good texturing work. The white texture here is really useless for creating liveries).

> if we're dumping the immat thing

I don't think we should dump the immat thing, just create a better texture for it. I will do that myself.

@onox 

> Let's change this to a HD livery. I suggest either "4X-CHV_HD_livery" or "OH-CTL_HD_livery".

That's fine with me, of course :smile:

**Comment by onox** [comment]
I'll remove the "default" livery then and change the default from "D-EEQA" to "4X-CHV_HD_livery".

**Comment by gilbertohasnofb** [comment]
No, don't remove the default livery, I will adapt its xml file to the new custom immatriculation livery, okay? Just change the default to whatever you like.

**Comment by onox** [comment]
How does the custom registration number livery look like then?

**Comment by onox** [comment]
Also, have you read #299?

**Comment by gilbertohasnofb** [comment]
I will create a new one. Currently it's all white, but I will probably adapt one of the older ones (maybe D-EEQA) but have no text on it.

> Also, have you read #299?

No, just read it now (sorry I was offline the whole day). I am pretty much against this: 'Use Canvas to paint the registration number on all liveries. Use custom colors and fonts tailored for the specific liveries". This will be a lot of work and little gain in my opinion, and the Canvas text does not look as good as a textured text. Really don't see the point. Also, all those HD liveries are based on real life airplanes and I use their real life callsigns as well.

**Comment by onox** [comment]
You can use Canvas to draw textures as well.

**Comment by onox** [comment]
But we need int[14] to int[19] anyway.

**Comment by onox** [comment]
Also, Canvas might give us a way to draw the registration number with the correct font color, etc. Currently the textures are just black for all liveries.

**Comment by gilbertohasnofb** [comment]
> You can use Canvas to draw textures as well.

So then we would need to create 30+ textures for the whole alphabet + numbers for each livery? That's just crazy... 

> But we need int[14] to int[19] anyway. Also, Canvas might give us a way to draw the registration number with the correct font color, etc. Currently the textures are just black for all liveries.

I get onox, but I think this will influence all other liveries, and all this just for the sake to be able to have custom immatriculations on the plane. If those properties are needed then my opinion is to simply remove the possibility of having a custom callsign. One less option = simpler plane, you get 2 extra properties, better looking textures -- all positive things IMO.

**Comment by onox** [comment]
Actually you get 6: int[14], int[15], int[16], int[17], int[18], int[19].

**Comment by onox** [comment]
> So then we would need to create 30+ textures for the whole alphabet + numbers for each livery? That's just crazy... 

I hope/think Canvas can just draw certain parts of textures. Having to create 30+ textures. I didn't say we _must_ use textures. If Canvas has a `drawText("Callsign").fontColor("orange")` function, then we could use that.

**Comment by gilbertohasnofb** [comment]
So what about solving this the easy and better way then? Let's just please forget about this custom callsign thing... who cares if you are flying online as N-00B and in the plane it's actually written OH-CTL. The advantage is negligent IMO. 

I am sorry but I really dislike the look of the text above the fuselage (like what the default livery current looks like), so this together with the amount of work really puts me down....

**Comment by onox** [comment]
@gilbertohasnofb You want to get rid of this whole MP registration number system?

**Comment by gilbertohasnofb** [comment]
> You want to get rid of this whole MP registration number system?

No, I don't want that, but I'd rather get rid of it than to rework all textures and apply custom callsigns to all of them. 

My ideal solution would be to keep things as they are: one special livery for custom callsign, all others with fixed callsign on their exterior. I can improve this custom callsign livery, make it more interesting than simple white. But I am 100% against removing the hard coded text from the HD liveries.

And one more point: I don't have the GIMP files to any of the older liveries, which means that removing their text is not trivial at all. It would either mean deleting all of them or some manual painstaking reconstruction work (which I am also not really up to).

**Comment by onox** [comment]
> My ideal solution would be to keep things as they are: one special livery for custom callsign, all others with fixed callsign on their exterior. I can improve this custom callsign livery, make it more interesting than simple white. But I am 100% against removing the hard coded text from the HD liveries.

OK.

**Comment by gilbertohasnofb** [comment]
Cool, so please don't delete the current "default" livery, I will rework it and upload it soon.

**Comment by wkitty42** [comment]
[quote= @onox ]
> Also, Canvas might give us a way to draw the registration number with the correct font color, etc.
> Currently the textures are just black for all liveries.

on the one craft where i learned about the call sign being used on the craft's exterior, i had to play with the color settings in a file to get the color the way i wanted it to appear for the registration on the outside of the craft when i did one of my first custom liveries... in this case, the craft was completely black and i didn't want a pure blinding white call sign letters giving its location away... i'll try to root out which craft that was and how it was done... i do know that the call sign was placed on the vertical tail and had the ability for lights to shine on it... it was either the b1900d or the citationX... i think the X but apparently i'm rather loopy these days from being sick...

**Comment by onox** [comment]
@gilbertohasnofb Just for your information (I'm not gonna implement it now or in the future), what I meant with Canvas was able to do things like this:

Imagine I'm using the 4X-CHV livery. Now lets assume my custom callsign is "CHVX-4" (same characters, different order). With the black custom callsign it currently looks like (if you manually toggle a property):

![fgfs-screen-089](https://cloud.githubusercontent.com/assets/3361585/8165902/7ccc532a-1394-11e5-9a9f-dbc1155c8408.png)

As you can see the custom callsign doesn't "fit" with the livery. With Canvas we would hopefully be able to do this instead:

![fgfs-screen-090](https://cloud.githubusercontent.com/assets/3361585/8165931/ad425068-1394-11e5-8ee4-52b76be22289.png)

**Comment by onox** [comment]
@gilbertohasnofb Btw, can you rename the white livery "default" to something else? It suggests it's the default, but it isn't.

**Comment by onox** [comment]
I'll create a branch to set the default to 4X-CHV.

**Comment by gilbertohasnofb** [comment]
> Just for your information (I'm not gonna implement it now or in the future), what I meant with Canvas was able to do things like this:

I get it, onox... but that's really besides the point. My main problem is that I don't think the custom call sign looks good. There is a huge difference of quality between a hard coded text and the Canvas text (at least on my system with anti alias off, the immatriculation in the "default" livery does not look good at all). 

> Btw, can you rename the white livery "default" to something else? It suggests it's the default, but it isn't. 

I will do that, probably custom_callsign for the files and "Custom Callsign" in the menu.

> I'll create a branch to set the default to 4X-CHV.

Just a second, what about using OH-CTL? I personally think that's our best looking texture and panel. What do you say? But 4X-CHV is also fine with me.

**Comment by onox** [comment]
> What do you say? But 4X-CHV is also fine with me.

I don't really have a strong preference. So I suggest to do a voting.

Who wants "4X-CHV_HD_livery" and who wants "OH-CTL_HD_livery"?

**Comment by gilbertohasnofb** [comment]
The two new "Custom Registration" liveries are already committed.

**Comment by onox** [comment]
See #304

**Comment by wkitty42** [comment]
i have no preference as to which craft is "the default" when loading the first time... once settings are adjusted and a livery is chosen, that'll be the pilot's default until they change it...

**Comment by gilbertohasnofb** [comment]
@wkitty42 you are right. This will simply change which livery will show when someone fires up FG for the first time (before he or she changes the livery himself).

**Comment by onox** [comment]
Guys, is it ok if I make a poll on the forum for input for a new default (HD) livery?

**Comment by gilbertohasnofb** [comment]
Fine with me.

**Comment by onox** [comment]
![fgfs-screen-095](https://cloud.githubusercontent.com/assets/3361585/8169806/4886b0d4-13ac-11e5-8807-2d3c13d5fe67.png)
![fgfs-screen-096](https://cloud.githubusercontent.com/assets/3361585/8169808/4887737a-13ac-11e5-9e86-10363c07c396.png)
![fgfs-screen-097](https://cloud.githubusercontent.com/assets/3361585/8169809/48883fee-13ac-11e5-901f-3ef4f3e03356.png)
![fgfs-screen-098](https://cloud.githubusercontent.com/assets/3361585/8169810/488ad042-13ac-11e5-9b0f-683e6f87ec42.png)
![fgfs-screen-099](https://cloud.githubusercontent.com/assets/3361585/8169807/4886fb70-13ac-11e5-9a67-4a03848564ed.png)

**Comment by onox** [comment]
![fgfs-screen-108](https://cloud.githubusercontent.com/assets/3361585/8170190/46001258-13af-11e5-9b99-36dac03ececa.png)
![fgfs-screen-109](https://cloud.githubusercontent.com/assets/3361585/8170193/46058cc4-13af-11e5-9224-e36971367149.png)
![fgfs-screen-110](https://cloud.githubusercontent.com/assets/3361585/8170191/46027232-13af-11e5-827d-23553f670806.png)
![fgfs-screen-111](https://cloud.githubusercontent.com/assets/3361585/8170192/4602fd1a-13af-11e5-9232-fc37ffbca3d6.png)
![fgfs-screen-112](https://cloud.githubusercontent.com/assets/3361585/8170194/46074e60-13af-11e5-9004-61806f3f4d1d.png)

**Comment by onox** [comment]
I have added the poll here http://forum.flightgear.org/viewtopic.php?f=4&t=26563

**Comment by wkitty42** [comment]
i don't have any problem with a poll but i don't really see any need for it... having at least one immat capable craft is going to help others design their own craft where they want to allow others folks to place their own call sign (aka registration) on the craft without having to go through the mess of figuring out how to create a livery on their own...

yeah, i'm kinda one of those... i was really excited when i saw that the b1900d or citationX put my call sign on the fuselage... i still need to go back and figure out which craft that was that i discovered this with... sadly the heat in my area and my recovery are thwarting my efforts... especially when the AC is set for 74 and it is really 96+ in the abode :( :( :(

**Comment by gilbertohasnofb** [comment]
@wkitty42 but the poll is about which livery will be the default in FG 3.6, nothing to do with callsigns.

**Comment by wkitty42** [comment]
@gilbertohasnofb i understand that... but i don't really understand why :cry: sure, one craft livery may be selected as the default but what does it really gain any of us? bragging rights? is that really worth the possible pain?? /me says that as a 50+ year old who has been thorough similar too many times

**Comment by onox** [comment]
@wkitty42 I think you're confusing the custom callsign livery "default" (which has now been renamed) with the default livery "D-EEQA". All that is we're going to do is change the default to not be "D-EEQA", but (probably) "4X-CHV_HD_livery".

What it gains for us is that if a completely new player starts FlightGear for the first time ever, he/she will see a nice HD livery instead of the older "D-EEQA" livery.

**Comment by gilbertohasnofb** [comment]
> What it gains for us is that if a completely new player starts FlightGear for the first time ever, he/she will see a nice HD livery instead of the older "D-EEQA" livery.

A better first impression? Which is usually all it takes for someone to form a (completely ignorant) opinion about a subject.

**Comment by onox** [comment]
Agreed. I will set the new default tomorrow.

**Comment by wkitty42** [comment]
@onox no, i wasn't confusing the two... i understand the gains... what i didn't understand was why the need to figure out which HD livery was to be the one selected... just flip a coin! :laughing:

**Comment by onox** [comment]
Changed default livery in 829c649.

**Comment by gilbertohasnofb** [comment]
I just got a message from a guy from South Africa telling me his airclub just bought the real ZS-MDF :smiley: 

https://fgflights.blogspot.de/2015/04/bodensee.html?showComment=1479303066443
