### ISSUE TITLE
Implement external preflight inspection

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#303]
Here is a list of ideas of what we can implement. 

* [x] clicking on the fuel tank door (red circle above each wing) will open the fuel and weight dialogue
* [x] ~~clicking on ailerons, rudder and elevator (if and only if on the ground and with the engine off) causes them to wiggle, as if testing them~~ maybe too silly, one can simply use their joystick/yoke/mouse in control mode to look at the surfaces moving from outside to simulate this
* [x] clicking on the pitot tube will add or remove the pitot cover. If forgotten, the airspeed indicator should be considered as blocked and the airspeed reading should be much lower than normal
* [x] clicking on the wheels (if and only if on the ground and with the engine off) should add or remove a block and the aircraft can't move if the block is on (kind of like parking brakes). Something like this yellow blocks but on all gears: http://www.cessna172club.com/forum/avatars/1314.jpg
* [x] create cords for securing the aircraft to the floor (click to add remove if and only if on the ground with engine off), aircraft can't move if they are on. See: https://upload.wikimedia.org/wikipedia/commons/1/1f/CAP_cadets_secure_a_Cessna_172_%28090317-F-2156C-003%29.jpg
* [x] create option in the aircraft menu to [ ] secure aircraft (add all things above or remove all things)
* [x] ~~also simulate fuel contamination by water? (how it affects the engine)~~ split into #504
* [x] ~~implement oil level. As ludomotico wrote: "You must check the oil level always, and refill about once out of ten flights. I don't know if flighgear implements engine failures if the oil lever is too low, or they must be simulated by the aircraft."~~ split into #499 

* * *

Old issue:

gizmo4487 made a feature request in the forum:

> An external preflight inspection should be added, since the plane supports Walker view. It would add to the realism and be very entertaining for real pilots.

That is a nice idea indeed. I think there was some discussion about it some time ago, but I can't remember where it lead to. Let's leave an opened issue for this (no milestone attributed so far since this has still to be discussed).

**Comment by Juanvvc** [comment]
We need two things for this:

- a working walker :) The walker needs the latitude and longitude of the model to be initialized before switching to the walker view. Currently, you have to switch the walker mode on in the menu and then switch to the walker view, or you spawn in the middle of the ocean. Initializing latitude and longitude is trickier than it seems, and the code is buried somewhere inside the walker nasal code. I tried some weeks ago to fix this, with no success.
- Oil management. Obviously, the aircraft is going to be in perfectly working condition (unless recently crashed, that is!). Hence, checking the oil level and adding/removing oil is going to be the only interesting thing to do in the outside.

**Comment by gilbertohasnofb** [comment]
@Juanvvc do you think it's a problem to leave this issue opened? I mean, it's a long shot but if it's opened we may revisit it in the future.

**Comment by Juanvvc** [comment]
Of course it can be left open! This little issue with the walker must be fixed one day or the other, and the oil system is probably going to be implemented in the future.

The external revision can be done without checklist: just check every single part of the aircraft. The only value to consult in the checklist is the oil level: between 6 and 8 octaves, IIRC. And the oil management is not yet implemented.

**Comment by gilbertohasnofb** [comment]
> Of course it can be left open! 

Oh, so I think you closed this by accident and not on purpose. I will reopen it right now.

**Comment by gilbertohasnofb** [comment]
And so I think #46 is related to this.

**Comment by Juanvvc** [comment]
Oh, sorry, i clicked on the wrong button! Sorry!

**Comment by gilbertohasnofb** [comment]
No worries, I did the same a couple of times already :smile:

**Comment by tigert** [comment]
Oil amount is usually measured in "quarts" (imperial unit pretty close to a liter), minimum 6 in that engine I think (depends on engine size, so the 180hp might have a bigger oil sump, need to verify from the handbook). If you plan for a longer cross country trip, you want to up it close to 8, since the lycoming engine does eat something like a quart in every 10 hours. For this reason you have a bottle or two in the trunk, and if it is much below 7qt when you check you add one quart before the flight.

The maintenance stuff is pretty tricky to do right - on one hand it is part of the preflight and the life as a pilot, but on the other hand, it is not nice if the user interface to do the checks is awkward. I never really learned how the walker works, so there needs to be a lot of improvement (plus it would be nice to actually show what kind of problems you should look for when you do the checks!)

**Comment by gilbertohasnofb** [comment]
Guys, inspired by the new Airfoil Lab Cessna 172 for X-Plane I thought we could implement some nice things related to preflight inspection, and they could work even without the walker (just using any external view):

- clicking on the fuel tank door (red circle above each wing) will open the fuel and weight dialogue
- clicking on ailerons, rudder and elevator (if and only if on the ground and with the engine off) causes them to wiggle, as if testing them
- clicking on the pitot tube (if and only if on the ground and with the engine off) will add or remove the pitot cover. If forgotten, the airspeed indicator should be considered as blocked and the airspeed reading should be much lower than normal
- clicking on the wheels (if and only if on the ground and with the engine off) should add or remove a block and the aircraft can't move if the block is on (kind of like parking brakes). Something like this yellow blocks but on all geras: http://www.cessna172club.com/forum/avatars/1314.jpg
- create cords for securing the aircraft to the floor (click to add remove if and only if on the ground with engine off), aircraft can't move if they are on. See: https://upload.wikimedia.org/wikipedia/commons/1/1f/CAP_cadets_secure_a_Cessna_172_%28090317-F-2156C-003%29.jpg
- ceate option in the aircraft menu to `[ ] secure aircraft` (add all things above or remove all things)

**Comment by legoboyvdlp** [comment]
Also, a fuel test hole would be a good feature - you put a test tube in and check it for water.
If the sim has rain you have to click the test tube hole to remove water or something....
also this should have a checkbox in the options menu

**Comment by onox** [comment]
Also simulate fuel contamination by water? :smile:

**Comment by gilbertohasnofb** [comment]
I copied the list of ideas to the first post to make it easier to find. Also, I implemented the "clicking on fuel caps open fuel dialogue" in the branch `441`

**Comment by onox** [comment]
We should also add these red "remove before flight" things. I think there was one airplane (piper archer) that had them, but not completely sure.

**Comment by gilbertohasnofb** [comment]
Totally. I think those are the pitot tube cover, which I mentioned in the third point. I will check the piper archer for them.

**Comment by onox** [comment]
It's not the archer, but the bonanza: http://forum.flightgear.org/viewtopic.php?f=4&t=22808&start=75#p213700.

**Comment by gilbertohasnofb** [comment]
Found it, and it even has its own .ac file :smile:

**Comment by gilbertohasnofb** [comment]
Okay, so I implemented the pitot tube cover in the branch `bug-303`:

- added pitot tube cover 3D object from the bonanza + improved texture
- click on the cover to remove it, click on pitot tube to put it back
- if left on, airspeed indicator doesn't respond
- state saved between sessions (as well as the airspeed indicator condition)
- hoovering tooltips change if pitot tube cover is there or not

Maybe in the future someone can help me improve this 3D model, I think it should look a bit more like this:

![eg](http://airfactsjournal.com/files/2011/03/pitot-tube.jpg)

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg would one of you check my code to see if I haven't done anything stupid?

**Comment by onox** [comment]
I'll check it in a minute.

**Comment by gilbertohasnofb** [comment]
@onox In the next days I plan to implement the block in front of the main wheels when securing the plane (see fourth idea in the main post). The conditional I have in mind is if the plane has ground speed < 1kts and is at the ground (using AGL altitude), the blocks can be activated by clicking on the wheels. The question I have is how to then force the airplane to not move, regardless of brakes and parking brakes? Would you have any idea which property could I use for that? I tried raising the friction between the gear and the ground but it didn't really work.

**Comment by onox** [comment]
Pfff... good question. Fake parking brake? What kind of solution do other planes use? Try the 787-8 for example.

**Comment by onox** [comment]
@gilbertohasnofb @wlbragg Btw, what should we do with that `skitext` branch?

**Comment by gilbertohasnofb** [comment]
Ok, I will check it in the next days. I will just add the condition that the pitot tube can't be removed if the groundspeed is higher than 5 knots and then call it a day (or rather a night).

> what should we do with that skitext branch?

I have no idea what was going on there any more. But given that we have merged the skis into the `master` and they have textures, I assume that whatever is left there is useless.

**Comment by onox** [comment]
Or use the wow conditions. 'not(wow1 or wow2 or wow3)'

**Comment by gilbertohasnofb** [comment]
Sorry, I don't get it.

**Comment by wlbragg** [comment]
>what should we do with that skitext branch?

Yes, get rid of it.

@gilbertohasnofb wow is a property the gear have that is true when on the ground and false when not on the ground. So (not wow) is the aircraft is off the ground.

**Comment by gilbertohasnofb** [comment]
I get it now. I think only using airspeed would be sufficient though and it would keep the code cleaner (much less lines), since the condition (groundspeed < 5kts) must imply that the plane is on the ground.

**Comment by wkitty42** [comment]
ever flown at 80kts into a 75kts head wind? but seriously, i think the ground contacts should also be taken into account for the best accuracy... ground contact and speed = zero but let's also not forget about drifting in the wind in an amphibious that's not tied up to something or beached...

**Comment by gilbertohasnofb** [comment]
If your true groundspeed is less than 5 knots, I think you have big worries than if your pitot tube cover was left on :wink: 

> let's also not forget about drifting in the wind in an amphibious that's not tied up to something or beached...

That's a valid point. What would be an upper limit groundspeed of drifting in such situations?

**Comment by gilbertohasnofb** [comment]
@wlbragg I created the block for the wheels but when I add power to the plane, the whole fuselage goes a bit down, and so do the blocks: they sink in the scenery. How can I make their position be relative to the front wheel and not to the fuselage??

**Comment by wkitty42** [comment]
@gilbertohasnofb as an aside, i just read, in the last few days, about old WWI or WWII craft specifically flying into strong headwinds to be able to fly backwards over the ground... in other words, they let the wind push them backwards or back and sideways so they could reach their intended destination... sure, with decently powered craft these days, going backwards like this is much harder... especially if the winds don't normally reach the speed of your craft's flight capabilities ;)  now back to our regularly scheduled development and bug hunting ;)

**Comment by gilbertohasnofb** [comment]
@wlbragg tiedowns implemented for all variants except floats and amphibian. Also, I have a little problem which you can help me with: those struts that connect the wing to the fuselage (where the tiedowns are connected to) are actually a single object with the fuselage! Would you be able to create two "hotspots" (don't make them too small) in the top of the struts to use them for the tiedowns? Currently the hotspot to add them is the whole wing, which is very inelegant.

**Comment by wlbragg** [comment]
Let me know if the hot spots on the tiedowns are big enough and at the correct angle, I angled them to match the strut but I am not sure if that is correct.

Great body of work gilbertohasnofb, this is really adding up!

**Comment by gilbertohasnofb** [comment]
:+1: :smile:

**Comment by gilbertohasnofb** [comment]
I am opening a new issue for the fuel contamination by water, so we can then close this one with this PR here: https://github.com/Juanvvc/c172p-detailed/pull/505

**Comment by gilbertohasnofb** [comment]
@onox 

As you rightfully pointed out, today we got the first bug report about using the parking brake property for all the securing aircraft objects: someone's joystick button stopped to control to the parking brakes in our plane. Here is his code:

```
    <button n="12">
       <desc>Parking Brake</desc>
       <binding>
          <command>nasal</command>
          <script>
             brake = !getprop("/controls/gear/brake-parking");
             setprop("/controls/gear/brake-parking", brake);
             if (brake) {
                gui.popupTip("Parking Brake ON");
             } else {
                gui.popupTip("Parking Brake OFF");
             }
             setprop("/controls/gear/brake-left", 0);
             setprop("/controls/gear/brake-right", 0);
          </script>
       </binding>
    </button>
```

I can of course help him solve his particular issue by adapting the code above, but that's a very inelegant solution and we are bond to find more reports of this in the future. So I guess something must be done about it, but what?

**Comment by onox** [comment]
> I can of course help him solve his particular issue by adapting the code above, but that's a very inelegant solution and we are bond to find more reports of this in the future. So I guess something must be done about it, but what?

He shouldn't directly modify `/controls/gear/brake-parking`. See PR #520.
