### ISSUE TITLE
fine tune ALS shadow

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#31]
XML08 - fine tune ALS shadow to translate lower with aircraft on deck and translate higher on altitude gain

**Comment by Juanvvc** [comment]
![fgfs-screen-037](https://cloud.githubusercontent.com/assets/684228/6635503/392d5942-c967-11e4-9646-6a9e11826047.png)

Check this snapshot. The aircraft is just on ground. Our shadows are still 2D, we should probably use the new 3D shadows.

**Comment by wlbragg** [comment]
Added all three shadow possibilities, Non-ALS, ALS-Shadow and ALS-Shadow-Volume.
See forum for details.

**Comment by wlbragg** [comment]
Adjusted the ALS-shadow and ALS-shadow-volume to start out closer to the ground. I consider this issue closed.
