### ISSUE TITLE
Add glass reflection visible from external view

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#314]
Duplicate the glass and give it a very small distance from the interior glass, so that there is no z-fighting. Add an effect based on `Effects/model-combined-transparent`.

Tune the parameters to get something like: http://tigert.1g.fi/kuvat/MIK/2006-07-30-parnu/_DSC2655.jpg

**Comment by gilbertohasnofb** [comment]
Is this possibly related to #13 or not at all?

**Comment by onox** [comment]
This is about the large windshield and the glass in the doors. I just noticed there is already a "glas" object. ("glas_interior" and "glas_interior_sides" are for the interior).

**Comment by onox** [comment]
@wlbragg It seems object "glas", "leftwindow", and "rightwindow" have a `Effects/interior/c172p-interior-glass-shadow` effect applied to them. What does this do? If I remove that effect and try to apply `Effects/glass` to them, I'm not getting any good reflection at all. Are the normals pointing outward?

**Comment by wlbragg** [comment]
>rightwindow.. have a Effects/interior/c172p-interior-glass-shadow effect applied to them. What does this do?

interior-glass-shadow
applies the cubemap shadow to glas, leftwindow and rightwindow.

interior-glass-reflection-front 


interior-glass-reflection-front
applies the cubemap reflection to glas_interior.


glas_interior and  glas are duplicate, offset, front windows (only one effect per window)

leftwindow, rightwindow

glas_interior
leftwindow_interior
rightwindow_interior
glas_interior_sides

**Comment by onox** [comment]
No I mean this:

![fgfs-screen-338](https://cloud.githubusercontent.com/assets/3361585/8259705/de55bb40-16be-11e5-8b1a-2f3777758361.png)

Look at the rainbow reflection on the canopy. That should be handled by `Models/Effects/glass.eff`, but when I tried to apply it to the "glas" object, I didn't see the cool reflection.

**Comment by onox** [comment]
Is this cube map shadow thing an ALS effect to be seen from inside the cockpit or from external views?

**Comment by onox** [comment]
> outside rain effect and sky reflection is already applied through
bumpspec "Effects/model-combined-deferred"

Transparent objects need to use `Effects/model-combined-transparent` (which is used by `Models/Effects/glass.eff`) not `Effects/model-combined-deferred` as far as I know.

**Comment by onox** [comment]
> glas_interior and glas are duplicate, offset, front windows (only one effect per window)

You say they are duplicate, but shouldn't the normals be opposite? Normals pointing inwards for "glas_interior" and outward for "glas".

**Comment by wlbragg** [comment]
Everything I posted except bumpspec is all internal.

**Comment by wlbragg** [comment]
Internal shadows and internal reflection and rain drops.
OK, rainbow, yes I am familiar with it. Give me a second to look at it and see what I know about it.

**Comment by wlbragg** [comment]
I just noticed this
> Any surface using the glass effect will automatically register itself as transparent for use in Rembrandt.

**Comment by onox** [comment]
I don't know much about all these ALS effects, but to me it looks like you need an "interior" glass that uses `Effects/glass` for fancy windshield rain/fog effects + another "interior" glass for `Effects/model-interior" + an "exterior" glass for `Effects/model-combined-transparent`?

I have read on the wiki about needing two glass objects (1x "interior" and 1x "exterior"), but now it seems we need 2x "interior" + 1x "exterior" :confused:

**Comment by wlbragg** [comment]
>The recommended effect for glass surfaces seen from outside is model-combined-transparent.eff. 

Appears so.

**Comment by wlbragg** [comment]
I'm familiar with a lot of it but there is "A LOT OF IT"!

**Comment by onox** [comment]
I'll ask Thorsten if he can check whether we're using all those ALS effects correctly.

**Comment by wlbragg** [comment]
This is the bumpspec
http://wiki.flightgear.org/index.php?title=Howto:Aircraft_reflection_shader&redirect=no

Do you know where the docs for rainbow are?

**Comment by onox** [comment]
Probably here: http://wiki.flightgear.org/ALS_technical_notes

**Comment by wlbragg** [comment]
Unrelated:
http://wiki.flightgear.org/Howto:Glass_reflection_effect_for_instruments

**Comment by wlbragg** [comment]
I thought it was there too but don't see it.

**Comment by onox** [comment]
I've send a PM to Thorsten, hopefully he can tell if we're doing anything wrong.

**Comment by wlbragg** [comment]
Here is the forum thread showing it being used and the threads leading up to it.
http://forum.flightgear.org/viewtopic.php?f=47&t=25456&start=75#p235963

**Comment by wlbragg** [comment]
http://forum.flightgear.org/viewtopic.php?f=47&t=25456&start=90#p236002
Is this what you tried?

**Comment by wlbragg** [comment]
This is similar to bumpspec.eff, I didn't add the bumpspec.eff that already existed and that is where I got deferred instead of transparent.

**Comment by onox** [comment]
It could be that the interior effect (for shading) can be applied to the "glas_interior" object (which has normals pointing inward AFAIK) and then we flip the normals of "glas" (that's the outer glass object) and apply the shiny rainbow reflection effect to it :smile: 

But Thorsten needs answer this because I'm guessing here.

**Comment by wlbragg** [comment]
No glas is for shadows, can't use it.
We have to have two layers for internal effects.

**Comment by wlbragg** [comment]
I just switched the bumpspec to inherit transparent instead of deferred and it still looks to be applying the bumpspec and external reflections correctly. Still lots to look at though. I need to check external rain, etc. and do some image comparisons.

**Comment by wlbragg** [comment]
Yes, I am sure Thorsten can answer this in a few seconds.

**Comment by wlbragg** [comment]
>bumpspec to inherit transparent instead of deferred and it still looks to be applying the bumpspec and external reflections correctly

This is all fuselage objects, not glass. Why use one over the other?
If we can use transparent to fuselage objects, why not just add glass to it. My next test.

**Comment by wlbragg** [comment]
I have a feeling we are going to need another layer for external effects.

**Comment by wlbragg** [comment]
onox, you still there?

**Comment by wlbragg** [comment]
Try adding <object-name>glas</object-name> to line 291 in Models/c172p.xml
>  
 <effect>
     <inherits-from>Effects/model-transparent</inherits-from>

is that what your looking for?

**Comment by onox** [comment]
I'm here again.

**Comment by onox** [comment]
@wlbragg No, that's the `Effects/model-interior` effect. I want "glas" to have the `Models/Effects/glass.eff` effect. But when I tried it, it didn't work.

And now I'm going to watch TV!

**Comment by wlbragg** [comment]
OK

**Comment by wlbragg** [comment]
No, that is model-transparent and it inherits from model-transparent.

glass.eff inherits from model-combined-transparent

**Comment by wlbragg** [comment]
Try it and look at the glass reflection on the outside, I think that is what your looking for and as far as I can tell it isn't breaking anything but I am not sure were suppose to be able to apply two different effects to the same glass unless it is because it is two sided?
But now I have to figure out when and where the internal reflection got broke.

**Comment by wlbragg** [comment]
There is a file in Models/Effects/  called glass.eff, I am not sure where or when that file got put there. It may have been by me, but I think it is not being used by anything. The internal glass reflections inherit directly from fgdata/effects/glass.

**Comment by onox** [comment]
This is what Thorsten said in a PM (I think he would have no problem with this post being public):

> Glass should always be single-sided surfaces anyway to avoid trouble (or so Emilian says).

> So you have one glass layer from outside, one from inside.

> The outside layer for the rainbow should use model-combined-deferred.eff (because that does fogging and all the stuff you see from outside), the inside layer should use glass.eff (because that does the forward light scattering effects which you can only see from inside).

> wlbragg is using model-interior.eff in addition to get the impression of a shadow falling onto the interior glass - something that I had not intended at all, but which looks neat nevertheless. You don't need that though. Eventually, I might also add the support for the interior shadow to the glass effect.

**Comment by onox** [comment]
So if we decide to not have shadow falling onto the interior glass, we should flip the normals of "glass", "leftwindow", and "rightwindow". And then on lines 353 use `Effects/glass`?

**Comment by onox** [comment]
I tried to do it myself and export to `c172p.ac` file, but the whole model became ugly and appeared with the wrong cockpit livery, so better drop this issue if you don't consider yourself a Blender guru :smile:

**Comment by wlbragg** [comment]
Maybe this will help a little.
![effects](https://cloud.githubusercontent.com/assets/11069680/8266541/5dd6ea76-16f9-11e5-8476-bab0954aa149.jpg)
There are other things attached to each of these effects.
Did you try what I posted above?
>Try adding the object glas to line 291

and also add leftwindow and rightwindow
 It worked for me and didn't appear to have side effects although I'm not positive about the side effects. I don't think we want to loose the internal glass shadow.

**Comment by wlbragg** [comment]
>I noticed with the Cessna 172P detailed that the glass dosen't really show.

from
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2055#p247971

onox, please try my suggestion above
>Try adding the object glas, leftwindow and rightwindow to code block around line 291 in Models/c172p.xml
...xml...

and let me know what you think. I don't think this includes the rainbow effect but it does appear to correct this users observation and I don't think there is a negative effect in doing this, (I have to verify this), and it may be that we want the full glass effect with rainbow and the likes. But for now I am really curious what you think about this effect on the glass.

**Comment by onox** [comment]
If I do that I don't see any difference.

**Comment by wlbragg** [comment]
Mine does, it looks like it puts some kind of reflection or noise on it. It is subtle and I can only see it at an angle.

**Comment by onox** [comment]
In Rembrandt? To be honest I only checked for differences under ALS.

**Comment by wlbragg** [comment]
No, in ALS.

**Comment by wlbragg** [comment]
>The outside layer for the rainbow should use model-combined-deferred.eff (because that does fogging and all the stuff you see from outside), the inside layer should use glass.eff (because that does the forward light scattering effects which you can only see from inside).

 Your post from Thorsten. Remember we just switched deferred to transparent. I'm going to keep at this until we get it.

**Comment by onox** [comment]
On the [wiki](http://wiki.flightgear.org/ALS_technical_notes#Why_a_separate_effect_for_glass_seen_from_inside.3F) it recommends `model-combined-transparent`:

> The recommended effect for glass surfaces seen from outside is model-combined-transparent.eff.

**Comment by wlbragg** [comment]
What aircraft is that jet?

**Comment by wlbragg** [comment]
@onox, I really think we have this as good as it can be with the shape of our glass. I studied several aircraft that look good and have tried the settings they used (all slightly different). I made some more adjustments and I think this is done.

![ref1](https://cloud.githubusercontent.com/assets/11069680/11006669/9d874d60-848a-11e5-9ebd-df43a3d528ac.jpg)
![ref2](https://cloud.githubusercontent.com/assets/11069680/11006668/9d87315e-848a-11e5-9c35-634cb31345ca.jpg)
![ref3](https://cloud.githubusercontent.com/assets/11069680/11006671/9d899106-848a-11e5-9808-dfd61e7690a8.jpg)
![ref4](https://cloud.githubusercontent.com/assets/11069680/11006670/9d87a71a-848a-11e5-8c8e-470811ad614b.jpg)
![ref5](https://cloud.githubusercontent.com/assets/11069680/11006672/9d89e3f4-848a-11e5-9ee2-fca17c321dba.jpg)

**Comment by onox** [comment]
It's mainly the lack of reflection on the front window I'm concerned about. See for the V-22 for example:

![fgfs-screen-303](https://cloud.githubusercontent.com/assets/3361585/11007404/e70935ea-84c9-11e5-91ff-e24d43e9ce10.png)
![fgfs-screen-304](https://cloud.githubusercontent.com/assets/3361585/11007405/e709530e-84c9-11e5-9642-3ad53fe21990.png)

**Comment by onox** [comment]
Perhaps we should ask Thorsten on the mailing list to test our aircraft and tell us if we're asking ALS to do the impossible or whether we made some stupid mistake.

**Comment by onox** [comment]
There are still many weird issues with the glass. The glass looks suddenly much different when the angle changes:

![fgfs-screen-312](https://cloud.githubusercontent.com/assets/3361585/11013187/e9855414-8502-11e5-86ef-dcff918970cb.png)
![fgfs-screen-313](https://cloud.githubusercontent.com/assets/3361585/11013188/e9a405a8-8502-11e5-8603-5c98eaad0c9a.png)

**Comment by onox** [comment]
Lets leave the issue open until the issue is properly fixed.

**Comment by wlbragg** [comment]
@onox, I think I figured out the glass issue, check out the changes to the j3cub and let me know if that is what your looking for with the c172p. If so, I think I can do it with the c172p. On your word I'll start on it. It requires specular and diffuse lighting changes to the glass in the blend file.

**Comment by onox** [comment]
J3Cub has a very nice reflection now :smile:

![fgfs-screen-431](https://cloud.githubusercontent.com/assets/3361585/12310386/5d1b9a14-ba50-11e5-99c6-56307cb2a6f4.png)

**Comment by onox** [comment]
I'll move this to a later milestone because I think we have to wait until Thorsten has modified ALS to properly support dual layer glass.
