### ISSUE TITLE
Make screws not clickable (they open checklist)

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#315]
Currently the screws are clickable and they open checklist. This is confusing and unrealistic, and we have three other ways of opening the checklists:

- via the menus
- ~~via a keyboard shortcut~~ (incorrect information)
- by looking down and clicking on the Cessna POH

It has been decided to remove this feature. We also must make sure that when pressing Ctrl+C these screws will not illuminate any longer.

**Comment by onox** [comment]
I've looked in the Blender file a bit:

"bolts" object is part of "LeftBag". If we don't want the bolts we either need to:

1. Use object "Plane.006", which isn't very clear; or:

2. Move "bolts" object in Blender outside "LeftBag". To the same level as "LeftBag" instead of as a child of it.

**Comment by onox** [comment]
@gilbertohasnofb Btw, what's the keyboard shortcut?

**Comment by gilbertohasnofb** [comment]
> If we don't want the bolts we either need to [...]

Just to avoid any misunderstanding, I believe we want the bolts, we just don't want them being clickable. 

> Btw, what's the keyboard shortcut?

Oh my, I think I am mistaken about that! I could swear there was a shortcut for it, but apparently there isn't. Sorry about it, I will remove it from the description.

**Comment by onox** [comment]
@wlbragg @Juanvvc Can one you do this one? Move "bolts" object in Blender outside "LeftBag". To the same level as "LeftBag" instead of as a child of it.

**Comment by wkitty42** [comment]
on this, my main concern is that things that are not really clickable to change them are not shown... like the compass on the top of the dash... you can't change that magnetic item... can you???

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> on this, my main concern is that things that are not really clickable to change them are not shown...

I don't understand, are you talking about the bolts or about other things? I also don't understand what you mean with the phrase, sorry

> like the compass on the top of the dash... you can't change that magnetic item... can you???

Nope, you can't do anything with the compass, and that's why we removed its yellow contour when pressing Ctrl+C and also the tooltip (although putting the tooltip back could be a good idea as some people complained the compass is difficult to read without it).

**Comment by onox** [comment]
> (although putting the tooltip back could be a good idea as some people complained the compass is difficult to read without it)

This can probably also be solved by using FGCamera (once that gets added to 3.8) It would be nice though if tooltips could be shown without a "pick" animation (which gives those yellow contours).

**Comment by wkitty42** [comment]
@gilbertohasnofb yes, that was poorly worded... what i was trying to say is that if you cannot change something, it should not be clickable... IMHO, FWIW...

on the compass, to me it is an ornament as i always have the HUD turned on... it is much easier for me to use the HUD to see my speed, throttle position, heading, altitude and land height below me...

**Comment by wlbragg** [comment]
>@wlbragg @Juanvvc Can one of you do this one? Move "bolts" object in Blender outside "LeftBag". To the same level as "LeftBag" instead of as a child of it.

I just now saw this, you still need this done?

**Comment by Juanvvc** [comment]
@wlbragg, I am looking at this thing right now ;)

Probably, it was my fault. Sometimes, I group some objects together without noticing there are other objects already selected. Hence, it is a bug introduced by me and the screws were never intended to be joined with the LeftBag.

**Comment by Juanvvc** [comment]
Pull request submitted.

@wlbragg, if you are reading this, could you decide about #250 ?
