### ISSUE TITLE
Ctrl+C shouldn't show certain objects as clickable

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#316]
Ctrl+C shouldn't show certain objects as clickable. At most their names, but certainly not as clickable:

- compass
- airspeed gauge's needle
- EGT gauge's red button (currently I believe it does nothing)

**Comment by onox** [comment]
@gilbertohasnofb It seems a pick animation is used for the compass and airspeed in order to show a tooltip. Would you suggest to just remove the pick animations? The other instruments don't have them anyway.

**Comment by gilbertohasnofb** [comment]
I don't know what is a pick animation, but I would suggest removing the yellow contours around the airspeed needle and compass, and maybe even from the EGT button as of now it doesn't do anything (AFAIK).

**Comment by onox** [comment]
Removing the yellow contours means also no more showing the tooltips of the compass and airspeed indicator.

**Comment by onox** [comment]
EGT's red button changes the `/engines/engine[0]/egt-bug-norm`. Click and hold and then drag your mouse up or down.

**Comment by gilbertohasnofb** [comment]
> Removing the yellow contours means also no more showing the tooltips of the compass and airspeed indicator.

I don't think we need a tooltip for the airspeed indicator and compass as virtually no other gauge has it (we don't have it for the altimeter, vertical speed, heading indicator, tachometer, etc.). Or we should add it to all gauges. The point is to be consistent.

Also, are you sure the yellow contour is necessary for showing tooltips? I can see the airspeed tooltip when my mouse is hoovering above the airspeed indicator but NOT above the needle.

> EGT's red button changes the /engines/engine[0]/egt-bug-norm. Click and hold and then drag your mouse up or down.

You are right. In that case, that button should behave identically to a knob and this should be clearer (right now you have to click slightly to the right of the button to go up and slightly to the left to move it down). Also, the cursor should be the same as the other knobs, with two horizontal arrows such as :left_right_arrow:

**Comment by onox** [comment]
It seems I can make the tooltip for the airspeed indicator appear by removing the "Needle" object from the pick animation. (Now it's applied only to the "Face" object)

**Comment by onox** [comment]
I've decided to remove the tooltip for the ASI for the reasons you gave above.

**Comment by gilbertohasnofb** [comment]
Okay onox, I will test the PR.

**Comment by gilbertohasnofb** [comment]
Thanks onox.

**Comment by wlbragg** [comment]
Did anyone see and address the post to the dev-mailing-list about their being no tooltip for the "hide yoke" mouse over position? They also stated there is usually a gui menu choice for the same.

**Comment by onox** [comment]
Do people want a tooltip for the yoke?

**Comment by wkitty42** [comment]
@wlbragg yes, i did and i responded...

@onox wouldn't it be best if all clickables had tool tips? they are helpful for night flights if someone does not know about the flashlight...

there are other craft that i like to fly at night but almost cannot because i can't find the proper switches in the dark... if they would pop up tool tips, then i'd be able to find the switches i was after and get'er done :wink:

**Comment by wlbragg** [comment]
Yes, on the mailing list it was mentioned and a menu entry.

**Comment by wlbragg** [comment]
Keep in mind I am still a week behind in my reading the digest, so there may have been more discussion on it.

**Comment by gilbertohasnofb** [comment]
> Did anyone see and address the post to the dev-mailing-list about their being no tooltip for the "hide yoke" mouse over position? They also stated there is usually a gui menu choice for the same.

I am totally up for both the tooltip as well as the gui menu choice (and NOT inside the options menu, but as a standalone option in the C172P menu, which is typical for most aircraft).

**Comment by onox** [comment]
> I am totally up for both the tooltip as well as the gui menu choice (and NOT inside the options menu, but as a standalone option in the C172P menu, which is typical for most aircraft). 

Could you make a new issue for this?

**Comment by gilbertohasnofb** [comment]
@onox Absolutely, here it is: https://github.com/Juanvvc/c172p-detailed/issues/322

I didn't assign a milestone because I don't know if this qualifies as a bug or a feature. What do you think?

**Comment by onox** [comment]
People have complained about it, so I think it can be qualified as a bug :smile:

**Comment by gilbertohasnofb** [comment]
Decided to reopen because @geoffmcl has reintroduced the tooltips and Ctrl+C label (both of which are very welcome!), but also brought back the yellow contour of the compass. IMO it shouldn't have it as it's not clickable, but the tooltip is useful indeed.

**Comment by wkitty42** [comment]
FWIW and TBH: i've never seen a tool tip on that magnetic compass... certainly never one that showed me the direction i was facing... it might have worked in 3.4 but i only had that for a day and didn't fly the c172p during that time... it wasn't until you guys started working on this project that i actually started working with the craft more and paying more attention to things...

**Comment by onox** [comment]
> but also brought back the yellow contour of the compass. IMO it shouldn't have it as it's not clickable, but the tooltip is useful indeed.

I think that needs changes in FG itself. Since it's only the compass that currently has this problem and the other items are fixed, I'm going to close this issue again otherwise we're never going to reach 0 open issues for 3.6 :wink: (but you're free to create a new issue for the compass with a 3.8 release milestone)
