### ISSUE TITLE
Create tooltip and GUI menu option for removable yoke

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#322]
Create tooltip when hoovering above the removable yoke mount and also a GUI menu option for it. The menu option "Hide/show yoke" should not be inside the aircraft options menu (where we have engine type, repair, wheel type, etc.), but as a standalone option in the C172P drop down menu itself, which is typical for most aircraft in FG.

**Comment by gilbertohasnofb** [comment]
From the mailing list:

Oops, seems at this moment fgdata is a
melange of the old c172p, and the new detailed!

Went to add the 'Show/hide yokes' to the menu
since I know this is just a few lines of xml,
and find we now have TWO(2) c172-menu.xml files!

  Dialogs/c172p-menu.xml
  gui/dialogs/c172p-menu.xml

The first is where the old c172p had its menu,
and the second is the new 'detailed' menu!

Adding this to the second adds the menu item:

	<item>
		 <name>show-hide-yokes</name>
		 <binding>
		     <command>property-toggle</command>
		     <property>sim/model/hide-yoke</property>
		 </binding>
	</item>

**Comment by onox** [comment]
I'll do this.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by onox** [comment]
Which position do you want the item?

**Comment by onox** [comment]
Under Flashlight ok?

**Comment by gilbertohasnofb** [comment]
> Under Flashlight ok?

Sounds good to me.

**Comment by onox** [comment]
@gilbertohasnofb :arrow_up: :smile:

**Comment by gilbertohasnofb** [comment]
Tested, :+1:
