### ISSUE TITLE
Magneto switch has different illumination depending on its position

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#325]
When set to BOTH, the magneto switch looks much brighter than when set to OFF, L, R or START. IMO the brighter starter looks better and is easier to read. See:

http://s28.postimg.org/ab42gk1jh/magneto_switch_bug.jpg

**Comment by wlbragg** [comment]
This could be something to do with interior shadow on the gauges, comment out effects code block in 
Models\Interior\Panel\Instruments\magneto-switch\magneto-switch.xml

```<effect>
   <inherits-from>../../../../Effects/interior/c172p-interior</inherits-from>
   <object-name>key</object-name>
   <object-name>start</object-name>
   <object-name>magsw</object-name>
   <object-name>click-L</object-name>
   <object-name>click-R</object-name>
   <object-name>click-S</object-name>
 </effect>```

**Comment by gilbertohasnofb** [comment]
@wlbragg Do you think you could have a look on it once you get the chance? I don't understand how the effects work in FG :cry:

**Comment by wlbragg** [comment]
Yes, 
hopefully I can duplicate your visuals.

**Comment by gilbertohasnofb** [comment]
> hopefully I can duplicate your visuals.

If you can't, please let me know so I can try to narrow down in which conditions they appear. Right now I can make it consistently appear when I choose the theme "Stormy Monday" using AW, ALS. Also, cloud shadows make no difference here.

**Comment by wlbragg** [comment]
Don't waist any more of your time on this. It is related to the internal shadow and flashlight effect. But there is even more that needs to be addressed. I am preparing a video and explanation so all of us (current developers) can sort this out and come to some kind of consensus.

**Comment by wlbragg** [comment]
Here is the issue...
I added the internal shadow effect to all gauges because it was necessary if we wanted the flashlight to illuminate the gauges and not produce a black void.
Effect Applied
https://dl.dropboxusercontent.com/u/63093453/fg/eapplied.jpg
Effect Not Applied
https://dl.dropboxusercontent.com/u/63093453/fg/enotapplied.jpg
Also because technically a shadow should fall on the gauges.

However, this shadow effect more than likely doesn't account for every detail needed to make it prefect in all cases, it may be that it never can.
Or maybe Thorsten felt it not necessary to take it any farther than he did (gain VS effort).
Either way we have what we have and now need to decide what we are willing to put up with.

Following are two videos, one with the shadow effect applied to every gauge and the second without it applied to every gauge.
Keep in mind, some of the switches and knobs don't necessarily behave as we might expect either and that they are all influenced by the internal shadow effect as well as the flashlight.
Effect Applied
https://dl.dropboxusercontent.com/u/63093453/fg/effect-on-gauges.mp4
Effect Not Applied
https://dl.dropboxusercontent.com/u/63093453/fg/no-effect-on-gauges.mp4

**Comment by gilbertohasnofb** [comment]
Hmm, I see. Should we contact Thorsten and explain the issue we are having? Maybe he is not aware of it.

**Comment by wlbragg** [comment]
I sent him a message, he should respond here in time.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by wlbragg** [comment]
Thorsten was kind enough to explain it to me again (I guess I am getting Oldtimers). I knew we were going to have some trouble if I applied the shadow effect to the gauges but didn't know I could use the flashlight without using the shadow map.
So the answer is to not use the shadow map on the gauges. I will edit all those files and commit a PR, hopefully by tomorrow afternoon.

**Comment by wlbragg** [comment]
Reminder to myself, add yoke and yoke attachment point to flashlight effect and check rudder peddles.

**Comment by wlbragg** [comment]
Done - see #332
There is a fine line between what gets the shadow effect (which includes the flashlight effect) and what only gets the flashlight effect. It is up to us to decide when the shadow effect causes problems on an object.
As it stands now, all internal buttons and knobs and all internal objects in Models/c172p.xml have the shadow and the flashlight applied.
All gauges only have the flashlight effect (unless there was a gauge that is defined locally in Models/c172p.xml and not as an xml link, if there is one of these instances, I missed it and it should only get the flashlight and needs to be changed)

I also added yoke (and mounts), rudder pedals, flap controls (had missed those before) and circuit breakers.
All of these have both the internal shadow and flashlight.

The only thing I couldn't find was the console up on the ceiling, what is that called and is it an object?
If not and it is just part of the textures, why is it not illuminating same as the all the other interior objects?

The reason the shadow doesn't work well on child models is 
>the child models (included xmls) including their offsets and transformations are not in the same coords as the shadow computation

and
>We need to give the transformation matrix between systems to the shader, but that won't happen for 3.6 as it's fairly complicated.

Per Thorsten.

**Comment by gilbertohasnofb** [comment]
> It is up to us to decide when the shadow effect causes problems on an object.

Okay, so let's keep our eyes opened for other potential problems that may appear. I will test your PR right now.

**Comment by wlbragg** [comment]
>The only thing I couldn't find was the console up on the ceiling, what is that called and is it an object?
If not and it is just part of the textures, why is it not illuminating same as the all the other interior objects?

Anyone know the answer to this?

**Comment by gilbertohasnofb** [comment]
The texture is located in the bottom right of panel_parts.png, and the rectangular object in which this texture is applied was created by @Juanvvc on this issue: https://github.com/Juanvvc/c172p-detailed/issues/21

**Comment by wlbragg** [comment]
Thank you!

**Comment by wlbragg** [comment]
One more commit under this see PR  #334
