### ISSUE TITLE
Test the plane once merged with fgdata

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#327]
This is just a remind to us all that we must test the plane in fgdata once it's merged. For instance, Torsten had reported in the mailing list that two livery files were duplicated (one version capitalized, the other not). Obviously all of us are only using our own repository since we are still working on fixing bugs, but I think that it would be good if we check the plane directly from fgdata once it's merged.

**Comment by wkitty42** [comment]
i have been flying both craft... the new one in fgdata and the one in my local development repo... i haven't noted any specific problems with the one in fgdata... i do, however, see the lowercase Models/Liveries/n301dp.xml file of 760 bytes in size dated 9 Mar 2015 07:53AM... it does also show up in the livery list in the sim...

as i always use the --launcher, what i do is to search for 172p and then hover over their description boxes so i can see the path tool tip... then i can select the one i want to fly based on the directory in the tool tip... i assume that there is no crossing of paths in the sim by me doing it this way and that if i select the one in fgdata, that's where everything for that craft comes from... this seems to work properly as i do not see the lowercase n301dp listed in the liveries when i select the craft in my development repo...

**Comment by gilbertohasnofb** [comment]
@wkitty42 Great, so please report here any conflicts you see, okay? Stuart said he will empty the c172p folder before merging our project, so no old files should be conflicting there. Anyhow, let's double check them later, okay?

**Comment by onox** [comment]
I think they didn't get remove all the files before copying the new c172p.

**Comment by gilbertohasnofb** [comment]
That's what it looks like.

**Comment by wkitty42** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@onox please check what Stuart wrote in the list:

> Previously there were 3 other -set.xml files for different variants:
> 
> c172p-2dpanel-set.xml - 2D panel
c172p-panel-only-set.xml - high resolution panel-only display for multi-computer setup
c172p-canvas-set.xml - Canvas demo with a CDMU and Canvas hooks.
> 
> I think we definitely want to keep the c172p-panel-only variant, and probably the c172p-canvas as it provides a good reference on how to use Canvas within an aircraft.
> 
> I think the c172p-2dpanel variant can be removed as the panel isn't particularly nice and I can't imagine anyone uses it anymore.
> 
> How do you want to do this?

**Comment by onox** [comment]
I see that, but I didn't delete those files. Also I wonder if keeping `c172p-canvas-set.xml` is a good idea, because we can always get it back from git. It's probably also very out-of-date.

**Comment by gilbertohasnofb** [comment]
@onox Oh, I didn't mean you yourself deleted them, I am just pointing it out to you that at some point someone deleted them. And I wouldn't know the advantages/disadvantages of having/not having them, so I thought I would share this with someone more knowledgeable :smile:

**Comment by onox** [comment]
Aren't we going to add this nice glass cockpit for 3.8?

**Comment by gilbertohasnofb** [comment]
You mean the one from project Farmin? I think @Juanvvc was interested in doing it (I vaguely remember some post by him about this on the forum thread).

**Comment by onox** [comment]
Yeah.

**Comment by gilbertohasnofb** [comment]
Also, if I am not mistaken, someone was already trying to implement it and posted some images of a functioning c172p-detailed with a Farmin on it, but it was very crudely done (there was no modification to the 3D model, it they just added the glass above the regular cockpit).

**Comment by onox** [comment]
Yeah, I remember those screenshots.
