### ISSUE TITLE
New crash sounds

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#329]
I just added two new sounds to our project to be used when the plane gets damaged:

- `crash.wav` sound (when the plane is completely shattered)
- `damage.wav` for smaller damage (such as damage to the wing only, but not a complete destruction to the plane

A new branch `bug-329` has been created.

**Comment by gilbertohasnofb** [comment]
@onox Would you like to help me implement these? The sounds are already in the new branch, and I can tailor them according to what you'd need.

**Comment by onox** [comment]
> when the plane is completely shattered

@gilbertohasnofb What do you mean with this? When the wings collapse, when one wing breaks, or when both wings are broken?

**Comment by gilbertohasnofb** [comment]
@onox I had in mind to use the `damage.wav` sound for when a wing breaks, and `crash` for when it collapses or when one hits the engine in the floor or when the gear collapse, etc. What do you think? Did you hear the sounds?

**Comment by onox** [comment]
To be honest, no, I'm listening to music right now :smile: :headphones:

**Comment by gilbertohasnofb** [comment]
@onox no worries, but when you have a chance check them out and I think it will make much more sense of what I am trying to achieve with this feature

**Comment by onox** [comment]
@gilbertohasnofb How about using 1:32 to 1:37 and 2:12 to 2:19 from https://www.youtube.com/watch?v=FsRwlr7RDkk ? It's from NASA Langley. I guess that would make it public domain, although YouTube puts its standard license on it. Maybe we could e-mail NASA Langley and ask for permission, public domain version, or a CC-BY licensed version of it? (Or contact via twitter https://twitter.com/NASA_Langley)

**Comment by onox** [comment]
I think `damage.wav` is okay, but I don't really like `crash.wav`. I hear too much glass :confused:

**Comment by gilbertohasnofb** [comment]
> I don't really like crash.wav. I hear too much glass :confused:

I agree with you, particularly after comparing to the video you posted above. 

> Maybe we could e-mail NASA Langley and ask for permission, public domain version, or a CC-BY licensed version of it? (Or contact via twitter https://twitter.com/NASA_Langley)

I think we should do that indeed because as of how that youtube video stands now we really can't use it :cry: Do you have a twitter account to contact them? If not I will try to find some e-mail address to contact them.

**Comment by gilbertohasnofb** [comment]
@onox I contacted NASA about the license of that video, let's hope they answer me. But in the meantime, wouldn't you like to implement these two sounds, and later if we get a green light by them then I will exchange the `crash.wav` for the one from that video?

**Comment by onox** [comment]
Totally forgot about this issue :open_mouth: 

About `crash.wav`: it sounded like breaking glass :confused:?

**Comment by gilbertohasnofb** [comment]
It's from a car crash. I think it's better than no sound, but I will work on finding a replacement for it

**Comment by gilbertohasnofb** [comment]
From NASA:

> Dear Gilberto:
> 
> NASA still images, audio files and video generally are not copyrighted. You may use NASA imagery, video and audio material for educational or informational purposes, including photo collections, textbooks, public exhibits and Internet Web pages. This general permission extends to personal Web pages. This general permission does not extend to use of the NASA insignia logo (the blue "meatball" insignia), the retired NASA logotype (the red "worm" logo) and the NASA seal. These images may not be used by persons who are not NASA employees or on products (including Web pages) that are not NASA sponsored.  If the NASA material is to be used for commercial purposes, especially including advertisements, it must not explicitly or implicitly convey NASA's endorsement of commercial goods or services. If a NASA image includes an identifiable person, using the image for commercial purposes may infringe that person's right of privacy or publicity, and permission should be obtained from the person. Any questions regarding application of any NASA image or emblem should be directed to:  Photo Department NASA Headquarters 300 E St. SW Washington, DC 20546 Tel: (202)358-1900 Fax: (202)358-4333.
> 
> Sincerely,
> The Public Inquiries Office

I guess that's a green light, right? In that case, I will replace the old `crash.wav` by the one from the video. I will do this tomorrow.

**Comment by gilbertohasnofb** [comment]
Actually, I manage to do it now, the new sound is already in this branch. I just applied some noise reduction. It sounds much better than that car crash :wink:

**Comment by onox** [comment]
@gilbertohasnofb Which duration from the video did you use?

**Comment by wkitty42** [comment]
speaking of sounds, i'm not sure where to add this but when switching between the pontoons, amphibious and skis, there's no workshop sounds... yes, this is with my corrected directory structure... i'm not sure about creating a new issue, though...

**Comment by onox** [comment]
> there's no workshop sounds

There's only a workshop sound when switching between the 160 HP and 180 HP engines.

**Comment by onox** [comment]
@gilbertohasnofb Because the branch was very old, I rebased on top of master. So you have reset your branch (`bug-329`) to an old common commit again:

1. Try: `git merge-base bug-329 master`. It should give you a commit from 2015-06-23 (you can find out by doing `git log COMMIT_FROM_MERGE_BASE`)

2. Then do `git reset --hard COMMIT_FROM_MERGE_BASE`.

3. Then do `git pull`.

**Comment by onox** [comment]
@gilbertohasnofb In the mean time I have added the sounds to `c172-sound.xml`. However, FG doesn't like `damage.wav`:

```
AL Error (sound manager): Invalid Enum at buffer add data
No such buffer!
```

I think this is because the file is pcm_s24le instead of pcm_s16le.

**Comment by onox** [comment]
I have fixed it by loading and exporting the file in Audacity.

**Comment by onox** [comment]
@gilbertohasnofb I have already created a PR, but could you use 2:12 to 2:19 to create a new wind sound? The current wind sound is just white noise, which sounds really bad :cry:

**Comment by gilbertohasnofb** [comment]
I will do that!

**Comment by gilbertohasnofb** [comment]
Hmm onox, that sound is not good either, I will try to find a better source. That part of the video has some subtle sounds from the test that are very soft, but once you loop it they become obvious. I will look for a cleaner wind sound now.

**Comment by gilbertohasnofb** [comment]
I would say for us to merge that PR and open a new ticket for improving the wind sound, as I had a quick look on several samples now and I couldn't find anything good, and so it may take some time for that, what do you say?

**Comment by onox** [comment]
> I would say for us to merge that PR

I'm not that happy with `damage-heavy.wav` as I explained in https://github.com/Juanvvc/c172p-detailed/pull/522#issuecomment-154692023. Are you able to find a different sound?

**Comment by onox** [comment]
For the wind we can definitely create a new issue.

**Comment by gilbertohasnofb** [comment]
I just say your other comment. Well, `damage-heavy.wav` sounds similar to `crash.wav` because it's basically a short version of that sound. I understand what you are looking for, but it has been tough to find a good sound for that. I will look for it again later, ok?

> For the wind we can definitely create a new issue.

Ok, I will do that.

**Comment by onox** [comment]
OK. Do you want to merge the PR? If yes, then I'll remove `damage-heavy.wav` and then merge it.

**Comment by gilbertohasnofb** [comment]
I'd say I will give it another go at the heavy damage sound, so let's wait just a little bit longer before merging. I will try to do it still today.

**Comment by onox** [comment]
OK.

**Comment by onox** [comment]
@gilbertohasnofb Could you do the same for `crash.wav`?

**Comment by gilbertohasnofb** [comment]
Not really, that's as loud as it gets without clipping.

**Comment by onox** [comment]
OK. We'll leave it untouched then.
