### ISSUE TITLE
Add back panel only variant

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#338]
Add back the high resolution panel-only display for multi-computer setup from the old c172p.

**Comment by onox** [comment]
@stuartbuchanan @Juanvvc @gilbertohasnofb Do you really want a separate `c172p-panel-only-set.xml` file or can I add `<panel>` to the regular -set.xml file? Basically the only thing it does is define `<panel>`, set a different `<description>`, and change the pitch offset of the cockpit view -8 degree.

**Comment by tigert** [comment]
We should also port the fgpanel panel from the old 172, that is nice if you want a flight training device setup with two monitors.

**Comment by tigert** [comment]
That could be a different issue though, will make one.

**Comment by gilbertohasnofb** [comment]
> Do you really want a separate `c172p-panel-only-set.xml` file or can I add `<panel>` to the regular `-set.xml` file?

Maybe having only one `-set.xml` file would be better. This way there is a single option for this plane when launching FG (those 4 options of the older c172p were very confusing for me when I first started in FG).

**Comment by onox** [comment]
> This way there is a single option for this plane when launching FG (those 4 options of the older c172p were very confusing for me when I first started in FG).

I agree with that as well.

**Comment by onox** [comment]
> We should also port the fgpanel panel from the old 172, that is nice if you want a flight training device setup with two monitors.

I'm not sure how fgpanel works nowadays, I thought it was rewritten/replaced by one of the t(h)orstens.

**Comment by onox** [comment]
Some instruments need to be fixed:

1. Bendix King HSI (column 3 row 2) is electric instead of vacuum based. It's also not a simple Heading Indicator like in the actual cockpit. (It combines HI and NAV1)

2. The ADF instrument (column 2 row 3) doesn't not respond.

3. The RPM instrument (column 4 row 3) works correctly for the 160 HP engine, but not the 180 HP. (This problem can be easily fixed)
