### ISSUE TITLE
amphibious take off from water... bouncing too extreme!??

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#343]
i've been flying master all the time... at some point, recently [during or after my first and only MP session the other day], something has changed... i've posted on the forums about not having any problems taking off with amphibious but now in the last day or so, i have major problems... suddenly theres some sort of bouncing when i reach my previous pull up speed... now i crash every time with wings broken with over G forces... i'm not doing anything any different then i was doing before but now i cannot get off the surface... something major has changed and i don't know how to handle it... flying with the keyboard as that's the only way i can...

**Comment by dany93** [comment]
I do not remember when the hydrpdynamics code was inserted into the master branch.

Did you follow this issue? https://github.com/Juanvvc/c172p-detailed/issues/326#issue-90163385
Particularly https://github.com/Juanvvc/c172p-detailed/issues/326#issuecomment-114252580  and https://github.com/Juanvvc/c172p-detailed/issues/326#issuecomment-114518061
And maybe (not included, just a proposition with no response) https://github.com/Juanvvc/c172p-detailed/issues/326#issuecomment-114821380

**Comment by wkitty42** [comment]
@dany93 i read all issues... they are all sent to me via email and i also go through all of them here on the site by clicking on the notifications button at the very top to the left of my avatar...

i did read about others bouncing but i never experienced it until now... i followed everything in those conversations but as it didn't happen to me, there wasn't much i could say other than to relate my experiences which may now appear to be less than truthful to others... i may have messed up my local repo and that may be why i hadn't seen this locally... i rebuilt my repos, github and local, the other day when i did my first MP with others at the PASN water party... since i forked clean, i do have this bouncing problem now...

i do keep my yoke pulled back one or two notches (key strokes)... i cannot use my mouse to fly with as i do not have enough room to move it and it is much too sensitive to try to fly with... i do everything with the keyboard... trim is back a tick or so (like from autostart and the checklists) and i go full power... when i reach 55kts, i tap the 2 key on the keypad to pull the yoke back "one notch"... the bouncing comes ~10 seconds or so after that... possibly ~70kts i think... i'll have to test again and try to note the speed... i have tried pushing the yoke one notch and pulling it back slightly more but the bouncing is horrendous and breaks my wings after throwing me into the air...

**Comment by wlbragg** [comment]
Sounds like you have been flying the old FDM all this time. This is the issue that has been discussed, however it is way better now than it was just a week or two ago. It still requires a bit of touch though but nothing like it did before, you can actually take a little bit of a lax approach and have a successful outcome.

**Comment by dany93** [comment]
It is almost impossible to have an accurate, reactive control for pitch and roll with the keyboard. The mouse can do, if its sensitivity is "normal". Don't you really have some place to add a joystick?

**Comment by wkitty42** [comment]
@wlbragg yeah, i don't know... i was fetching and merging from the repo every day... some times several times a day when you guys were doing a lot of merges...

@dany93 i can find room... i just don't have the spare resources to purchase a new usb joystick... i have an old one that uses the ancient midi port type connection but there's no port like that on this system...

**Comment by onox** [comment]
Just use the mouse then. That's what I do.

**Comment by wlbragg** [comment]
Me too!

**Comment by onox** [comment]
You're kinda expected to use either mouse or joystick.

**Comment by wkitty42** [comment]
i've tried the mouse and it is very hard to control with... keyboard is much easier... besides, how else would i control the craft if my hand(s) or arm(s) were mangled or missing... toes and mouth-stick are the first things that come to mind...

**Comment by tigert** [comment]
Mouse takes a bit to get used to, but it is actually pretty good compromise with no extra equipment, I even fly with the laptop touchpad just fine. Definitely more accurate than the keyboard, for when you actually hand fly.

It is more "live" though, with keyboard you give a nudge at one control at a time and it is more predictable, but the mouse is more like I remember my first school flights - easy to steer too much and on turn the aileron and elecator are manipulated with the same control (mouse / airplane stick or yoke) so everything changes everything else and your mouse is all over the place when you try to regain the control :-)

Not ideal, but I like the mouse. Definitely true for physical impairment, where cursor keys work much better then.

The mouse yoke sensitivity can be adjusted in props/ by the way.

Still, it is very hard to recover from a spin with even mouse yoke though, as the leftbutton-sideways-drag rudder is so slow to manipulate, so you easily end up in opposite spin when you cannot center it fast enouh. Pressing "5" to center all control works of course but it is very abrupt with that kind of situation..

We have the theustmaster warthog hotas and thrustmaster pedals at the club, We want to hook fg up to them to test the fdm too.
