### ISSUE TITLE
180 engine not registering on HUD

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#354]
The throttle setting in the HUD does not move when in the 180 engine condition, it only moves when using the 160 engine.

**Comment by onox** [comment]
Yeah about that HUD... it's generic, it's default, it's ugly, it's only needed if an aircraft doesn't have a nice cockpit. So... can we not just disable that thing?

**Comment by dany93** [comment]
Even if it doesn't have realistic justification, it easily gives some information (GPS coordinates, ground velocity, altitudes if I recall well). These can be useful in special cases, like development. I people do not like it, they just have to not set it.

**Comment by wlbragg** [comment]
Sorry onox, didn't mean to bring up a sore subject. You know what the only thing I use it for is, checking where the throttle is set at.

**Comment by wkitty42** [comment]
please **don't** disable this generic HUD... i cannot fly very well without it... no matter how detailed the panels are, i have to zoom in to see them but with the HUD i can easily tell what's going on... i'm sure that i'm not the only one doing this, too... i use it with all craft i fly... zooming in and back out and trying to get my view back to normal is a huge PITA...

**Comment by tigert** [comment]
The HUD is likely the thing that everybody has their own favorite use for it. I verify that I have the correct QNH set (since it seems to auto-adjust it!) and also I use it to verify wind direction when practicing the water landings on the c172p float versions, since it shows the groundspeed (I can align myself to the waves and check with groundspeed whether I am going downwind or upwind. Lazy things, yeah. But sometimes handy... :-P

**Comment by wkitty42** [comment]
eagerly awaiting this fix... there's only a few more days (three or four if i'm counting properly) and it definitely needs to be in the 3.6 release or there's gonna be a lot of complaints when folks choose to use the 180HP engine...

**Comment by gilbertohasnofb** [comment]
I found a fix to this, but it's probably not very elegant. See the PR above.

**Comment by onox** [comment]
The fix doesn't work for 160 HP engines and I find it a bit hacky.

How about we just display the throttle and groundspeed on the screen and then just disable the HUD? Like @andgi did in his hydrodynamics branch?

That way we don't have this ugly HUD which people aren't supposed to use (we have a beautiful cockpit) (so far only our keyboard-only user wkitty42 complained about it) but you can still see the throttle and groundspeed.

**Comment by gilbertohasnofb** [comment]
Fixed with PR #407.

**Comment by onox** [comment]
Well, the HUD has been fixed for now, but after we have implemented #392 and @wkitty42 has cleaned up his desk (so that his mouse is no longer boxed in), I hope we can one day remove this ugly HUD.

**Comment by gilbertohasnofb** [comment]
> wkitty42 has cleaned up his desk (so that his mouse is no longer boxed in)

hahaha

>  I hope we can one day remove this ugly HUD.

I still think we can leave it there as this is part of FG, but let's discuss this later when we have a working GPS and we can think about it with fresher minds :smile:
