### ISSUE TITLE
Aircraft wont start up. 

### ISSUE THREAD

**Issue by CaptainLaForest** [Juanvvc/c172p-detailed#359]
The version of this aircraft that I have downloaded is the regression version 3.2. I downloaded this one because I use FlightGear v3.4. When I load the model, all of the circuit breakers are out. And when I run through the startup procedure, the engine doesn't even crank. It just sits there at 0 RPM and the prop not turning when I am holding the key in the start position (And yes, I did try using the "s" key, and yes the mixture was full rich). I tried to use the autostart but that didn't work either. Even when I pushed the circuit breakers back in the Attitude indicator, Turn coordinator and radios were not working, even with the master switch and avionics power switch on. ere is my about FlightGear screenshot in case someone might find it helpful: 
![fgfs-screen-009](https://cloud.githubusercontent.com/assets/12752663/8444603/943af818-1f60-11e5-81b2-300cb5af0332.png)

**Comment by Juanvvc** [comment]
"all of the circuit breakers are out"

It seems electrical.nas is not loaded. This probably means the aircraft is not correctly initialized. My guess is some linked file is missing and flightgear stops loading files. Is there any message in the console?
