### ISSUE TITLE
Operation of dials of KX-165 com/nav radio

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#369]
@tigert @wezzer I have some questions about how the dials on the KX-165 behave:

1. If the NAV1/2 standby frequency is 117.50 and I turn the 1 MHz dial to increase its frequency. Does it change to 108.00 or 108.50?

2. If the NAV1/2 standby frequency is 117.95 and I turn the 50 KHz dial to increase its frequency. Does it change to 108.00 or 117.00?

**Comment by wezzer** [comment]
That's a very good question! :D I can't remember for sure (or access the club airplane right now), but I would say that the logic is following:
1. NAV1 117.50 and Mhz dial is turned to increase the frequency -> 108.50
2. NAV1 117.95 and Khz dial is turned to increase the frequency -> 117.00

Ie. the Mhz and Khz are treated as separately values.

**Comment by tigert** [comment]
This is my memory too. Maybe we can find some youtube to verify or does the silver crown manual say anything?

**Comment by onox** [comment]
For both NAV1 and NAV2 it seems that if the frequency is 117.95 and you use the KHz dial to increase the frequency, the actual frequency switches to 118.00 instead of 117.00. I'll fix this.
