### ISSUE TITLE
Better UV map of the Attitude Indicator

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#373]
I believe we need a better UV map of the Attitude Indicator. For some reason, the straight lines get angled in the corners, see:

![fgfs_screen_001](https://cloud.githubusercontent.com/assets/3361585/12906964/131d2252-cee6-11e5-9675-60ebc0f05291.png)

Could anyone who knows Blender have a quick look at this, please?

**Comment by wlbragg** [comment]
I know why this is doing this and I am trying to fix it now.

**Comment by gilbertohasnofb** [comment]
ok., let me know if I can help with anything
