### ISSUE TITLE
Radio knob bug

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#374]
When switching between the stand by frequency and in use frequency, I believe that the knob that selects the frequency shouldn't move. In our plane, it seems that each position of the knob correspond to a specific frequency (so it moves when the switch happens), but in real life I am almost 100% sure that the knob does not move as it's position is not tied to a frequency (it's only the number of clockwise or counter-clockwise clicks that matter). See: https://vid.me/FSBD

@tigert @Juanvvc could you please confirm if I am correct about the knob's behaviour?
@onox I didn't add a milestone because I am not sure how much work would be to fix this and if we would make it in time for the 3.6 release.

**Comment by tigert** [comment]
Yeah, knob does not move, it just adjusts the MHz or kHz portion of the frequency.

I don't think it is 3.6 critical really, everything works and it is just cosmetical, but yeah, we should fix it eventually.

**Comment by onox** [comment]
@tigert How many clicks per 360 degrees do the KHz and MHz dials have? I have currently set it to 4 deg per click, so that's 90 clicks per one full rotation.
