### ISSUE TITLE
Property floats-enabled-norm is already defined.

### ISSUE THREAD

**Issue by stuartbuchanan** [Juanvvc/c172p-detailed#377]
I'm getting the following error on startup from commit cab40a0af989bf08302836f98e91672920369fa3:

Failed to tie property fcs/ to object methods

In file /home/stuart/FlightGear/fgdata/Aircraft/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.

**Comment by wkitty42** [comment]
i think this has already been taken care of in commit 9935ec8e6c48902e492f37658ff91017bc109b3b

commit 9935ec8e6c48902e492f37658ff91017bc109b3b
Author: onox <denkpadje@gmail.com>
Date:   Fri Jul 3 15:57:16 2015 +0200

    Fix "Failed to tie property fcs/ to object methods" warnings, fixes #351
    
    Signed-off-by: onox <denkpadje@gmail.com>

**Comment by stuartbuchanan** [comment]
It doesn't seem to be for me.  I was running on the latest version from
origin/master, and
the changes from that commit are present.

-Stuart

**Comment by wkitty42** [comment]
@stuartbuchanan: i don't know how you have your setup done but i have the dev directory where i pull from git and then i have another one that i actually fly the craft from... i've forgotten to clean my flying directory and copy over the latest pulls/merges from my dev directory at times...

aside from that, i was seeing those entries on my console until that commit and i haven't seen them since... i'll try to get a load up in a few minutes after i finish toying with this AI 747 craft i'm harassing with the UFO :laughing:

**Comment by wkitty42** [comment]
@stuartbuchanan: yeah, i'm not seeing it... i'm on the latest commit (cab40a0af989bf08302836f98e91672920369fa3)

[commit log]
commit cab40a0af989bf08302836f98e91672920369fa3
Merge: 0f35fab a05ed99
Author: Gilberto Agostinho <gilbertohasnofb@gmail.com>
Date:   Sun Jul 5 19:19:49 2015 +0200

    Merge pull request #375 from geoffmcl/master
    
    Re-add tooltip to magnetic compass.
[end]

[console snapshot sitting on KSFO 19R]
myuser@mymachine:~/flightgear-dev/next$ ~/flightgear-dev/next/run_fgfs.sh --launcher
default catalog not found, installing 'org.flightgear.default' from 'http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml'.
catalog download failure:http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml
Enabling ATI viewport hack
Failed to tie property fcs/ to object methods

In file /home/myuser/myflightgear/Aircraft/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.
Loading local weather routines...
Animated jetways ... initialized
KMA20 audio panel initialized
Hobbs system stopped
Hobbs system stopped
Starter off
KI266 dme indicator #0 initialized
  Trim Results: 
          Altitude AGL:    3.4  wdot:  3.21e+01 Tolerance: 1e-03  Failed
           Pitch Angle:  -0.04  qdot:  3.97e-04 Tolerance: 1e-04  Failed
            Roll Angle:     16  pdot: -1.90e-03 Tolerance: 1e-04  Failed

  Trim Statistics: 
    Total Iterations: 61
    Sub-iterations:
    wdot: 0 average: 0  successful:  0  stability: 2.663
    qdot: 0 average: 0  successful:  0  stability: 2.3315
    pdot: 0 average: 0  successful:  0  stability: 2.3315
    Run Count: 1348
Electrical system initialized
Primer reset to 0
Could not find at least one of the following objects for animation: 'terminal_2'
Could not find at least one of the following objects for animation: 'terminal_2'
Starting hard-coded terrain presampling
0 pa_shoulder_f
0 pa_shoulder
0 pa_threshold
[end]

**Comment by dany93** [comment]
Hi Stuart,

The message
```
Failed to tie property fcs/ to object methods

In file /home/dany/FG/github/c172p/Systems/c172p-hydrodynamics.xml: line 25
      Property floats-enabled-norm is already defined.
```
is still here with the Juanvvc : master pull from 05 july 2015.
Here is is my question to AndersG and his response. https://github.com/Juanvvc/c172p-detailed/pull/365#issuecomment-118294553

**Comment by wkitty42** [comment]
apparently i misread something... i have not been associating the "failed to tie property" messages with the "property floats-enabled-norm" message... previously there were two more "failed to tie property" messages after the "floats-enabled-norm" one... those are gone and i thought the first one, as shown above, was also... are these two messages together or are they separate problems?

i do remember AndersG's response... perhaps there's some sort of reordering of routines needed to handle the situation with the "floats-enabled-norm" property as he described?? depending on the answer to my question above about "failed to tie", fixing that may or may not fix this... i remember bringing both up in an issue previously (that ended up solved and the issue name changed) and at least two were fixed which the "floats-enabled-norm" one remained and apparently the first "failed to tie" message remained, too... or came back??

**Comment by onox** [comment]
I have fixed the last `Failed to tie property fcs/ to object methods` warning in branch [bug-377](https://github.com/Juanvvc/c172p-detailed/tree/bug-377), but @andgi needs to tell us how he wants to remove the `Property floats-enabled-norm is already defined.` warning.

**Comment by andgi** [comment]
It is a warning, or in this case, more of an notification so I'm not sure it needs to be removed.
Should you want to remove it, comment out line 25 in c172p-hydrodynamics.xml:
https://github.com/Juanvvc/c172p-detailed/blob/master/Systems/c172p-hydrodynamics.xml#L25

(There should have been a line comment above: `<!-- Interface property. Are floats present? Range {0,1}. -->` or similar.)
