### ISSUE TITLE
Remove yellow contour of compass when using Ctrl+C

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#378]
Remove yellow contour of compass when using Ctrl+C. Currently, in order to be able to have a tooltip on the compass, we need a pick/knob animation, which also creates a yellow contour around the object. This usually means that the object is clickable, but the compass is not clickable and the yellow contour may confuse people about it. Ideally, we should be able to keep the tooltip (and the label under Ctrl+C as well), but remove the yellow contour.

**Comment by gilbertohasnofb** [comment]
I am closing this because it doesn't make any sense: if we have a pick animation, we will have the yellow contour, end of story. I didn't know better in those days :wink:

**Comment by wkitty42** [comment]
On 11/05/2015 06:25 AM, Gilberto Agostinho wrote:
> I am closing this because it doesn't make any sense: if we have a pick
> animation, we will have the yellow contour, end of story. I didn't know better
> in those days :wink:

yeah, i think we're all learning something each day... the core really should do 
this differently, though... that's something for another place of discussion, 
though :wink: :wink:
