### ISSUE TITLE
Liveries organization

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#380]
1. I want to move `Models/floats.png`, `Models/fuselage.png`, `Models/tail.png`, `Models/wing.png`, `Models/interior.png`, `Models/panel.png`, and `Models/panel_parts.png` to `Models/Liveries/D-EEQA/`.

2. Change `<texture>` in `Models/c172p.xml` to refer to the files in `Models/Liveries/4X-CHV/` if it helps to actually make 4X-CHV the default.

**Comment by gilbertohasnofb** [comment]
Sounds good to me.

**Comment by onox** [comment]
@Juanvvc @wlbragg Is it possible to prefix the .png files you're using in Blender/`.ac` with `Models/Liveries/4X-CHV/`? I would like to move (instead of copy) some of the .png files in `Models/` to `Models/Liveries/D-EEQA/`. For multi player, it will use the "texture" lines in the `.ac` files, which are the .png files from D-EEQA in `Models/`.

So the current situation is that most liveries are in `Models/Liveries/`, except the default (which is still D-EEQA), whose files are in `Models/`. Therefore I would like to have these files moved (`git mv`) to `Models/Liveries/D-EEQA/` and then make sure the Blender and `.ac` file refer to the files in `Models/Liveries/4X-CHV/`. But I can't do the Blender/`.ac` step.

**Comment by onox** [comment]
If anyone of you is able to update the Blender/`.ac` files, please do this in a new branch bug-380, because I'm not sure how the defaults + livery system work together.

**Comment by wlbragg** [comment]
I think I can update the blend file path but I am unclear as to what you want.

>Is it possible to prefix the .png files you're using in Blender/.ac with Models/Liveries/4X-CHV/?
What are these using now?

**Comment by onox** [comment]
What I want is that the blend and ac file refer to the png files in `Liveries/4X-CHV/`. Is that possible or does Blender really want the files in the same directory as the `.blend` file?

**Comment by wlbragg** [comment]
It shouldn't have any problem pointing to files outside the blend location.

**Comment by wlbragg** [comment]
You don't happen to know what all files need looked at do you?

**Comment by onox** [comment]
These are the files in the `.ac` file:

```
texture "fuel-selector.png"
texture "fuselage.png"
texture "interior.png"
texture "interior_windows.png"
texture "panel_parts.png"
texture "panel.png"
texture "prop.png"
texture "tail.png"
texture "transparent2.png"
texture "wing.png"
``

but `fuel-selector.png`, `interior_windows.png`, `prop.png`, `transparent2.png` are not part of the liveries, so these should not be changed.

**Comment by onox** [comment]
So it's basically the files that are used by the liveries whose path in the `.blend` and `.ac` file need to be changed:

`floats.png`
`fuselage.png`
`interior.png`
`panel_parts.png`
`panel.png`
`tail.png`
`wing.png`

**Comment by onox** [comment]
Don't forgot to do this in branch bug-380 @wlbragg :wink:

**Comment by wlbragg** [comment]
@ onox, we need to go slow here and check things step-by-step. I changed paths to Liveries/4X-CHV/ on everything in c172p.blend that pointed to any of the following
floats.png
fuselage.png
interior.png
panel_parts.png
panel.png
tail.png
wing.png
and then exported the .ac

That is all I did, I didn't delete an textures out of Model, I'll leave you to do and test.
Also I have a bit of a problem with the rest of the blend files.
c172p-damage.blend
c172p-damage.blend 
c172p-damage.blend 
c172p-damage.blend

**Comment by onox** [comment]
I grepped through the `.ac` file, but the textures still point to the files in the current directory. `git log` tells me only @Juanvvc  and @thevirtualfer have modified/exported the Blender file. Maybe they have a different version of Blender and use a different AC3D plug-in.

Since I don't want to break anything just days before the release and I managed to fix the single player default (on multi player (other c172p's) it should show the D-EEQA livery until it has loaded the actual livery of the other player), I'm gonna close this issue as "wont fix".

It's not really a big issue, other than that it's ugly that D-EEQA's files are in `Models/` instead of `Models/Liveries/D-EEQA/`.

**Comment by gilbertohasnofb** [comment]
@onox we could also leave this opened and just change the milestone to FG 3.8 release.

**Comment by onox** [comment]
Hmm.. I'll let the Blender guys decide on this one. They have to look at either the 4X-CHV or the D-EEQA livery in Blender :smile:

**Comment by wlbragg** [comment]
>I grepped through the .ac file, but the textures still point to the files in the current directory

Yes, they do. Strange, in the blend they are pointing to 4X-CHV. Maybe an export functionality weakness?

>I'll let the Blender guys decide on this one
OK, by me (and that isn't me :)). I felt it looked rather daunting to correct simply because of the amount of objects, but it really isn't, other than it didn't work. :smile:
