### ISSUE TITLE
Human models not visible over MP

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#386]
Human models are not visible over MP. Their presence (in the seat or not) should be transmitted over MP (4 bits), but whether they are actually displayed should depend on the local setting (show/hide human models) in the Aircraft Options dialog.

**Comment by gilbertohasnofb** [comment]
> but whether they are actually displayed should depend on the local setting (show/hide human models) in the Aircraft Options dialog.

Does this mean that if someone is flying a different plane than the c172p over MP and he sees a c172p, then the presence of the human models should be decided according to his last settings?

**Comment by onox** [comment]
> then the presence of the human models should be decided according to his last settings?

Yes.

**Comment by wkitty42** [comment]
On 07/12/2015 10:31 AM, onox wrote:
>     then the presence of the human models should be decided according to his
>     last settings?
>
> Yes.

so if their craft has no human pilot capability, they will never see our 
pretty/handsome pilot??

perhaps this would be better using the originator's settings for the pilots? if 
i have them turned off on my end, you won't see them in my craft... if i have 
them turned on, then you will see them in my craft...

**Comment by gilbertohasnofb** [comment]
> perhaps this would be better using the originator's settings for the pilots?

This will lead to inconsistencies. The reason some people like human models is because they find silly to have empty planes. Others, like me, are annoyed by the Barbie look of human models. Having half of the Cessnas with and half without them in MP will annoy both groups :smile: 

I like the idea of simply using the user's setting. If I disabled my c172p human models, then regardless of which plane I am flying over MP all c172p will be without human models.

**Comment by onox** [comment]
> > then the presence of the human models should be decided according to his last settings?
> 
> Yes.

@gilbertohasnofb Actually the answer is no, so if someone is flying a different plane we can choose to just show the models. If the player finds them creepy he/she just can fly away until the c172p is out of view.

**Comment by gilbertohasnofb** [comment]
That's a fair solution as well. As long as we have consistency (i.e. all planes having models or all planes having no models or using the user personal setting) then I am fine with it!

> If the player finds them creepy he/she just can fly away until the c172p is out of view.

I will keep my distance from every single c172p then! :smile:
