### ISSUE TITLE
Some knobs have inverted scrolling

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#391]
Some knobs have inverted scrolling when using the mouse wheel. That is, scrolling up should raise their values and __NOT__ diminish them. The problematic knobs are:

* [x] Heading indicator's heading bug
* [x] Heading indicator's heading offset
* [x] Altimeter Hg setting
* [x] Instrument light
* [x] Microphone setting (COM1 COM2 EXT)
* [x] Nav1/Nav2/Com1/Com2/ADF volume knobs
* [x] ADF frequency knob
* [x] Transponder four numbers
* [x] DME setting (N1 HLD N2)

**Comment by onox** [comment]
> Transponder setting (N1 HLD N2)

Do you mean DME setting?

**Comment by gilbertohasnofb** [comment]
Yep, that's what I meant.

**Comment by onox** [comment]
Fixed the DME knob in PR #394 (it used to be non-scrollable)

**Comment by onox** [comment]
@gilbertohasnofb Fixing the scrolling means though that left clicking becomes "decrease" and middle clicking "increase". But I think scrolling knobs is more important.

**Comment by gilbertohasnofb** [comment]
> I think scrolling knobs is more important.

Absolutely!

**Comment by onox** [comment]
@gilbertohasnofb I found a much better solution, setting `/sim/mouse/invert-mouse-wheel` to true.

I just need to fix:

* the dials of the KX-165 and DME instrument
* throttle and mixture
* rotation animation of HDG dial of ADF
* make sure attitude horizon, altimeter, nav1 radial and nav2 radial dials rotate

**Comment by gilbertohasnofb** [comment]
> I found a much better solution

Great! Once this work is done I will test the PR, okay? Thanks a lot for the work, @onox!

**Comment by onox** [comment]
@gilbertohasnofb Sure, shouldn't take too long.

**Comment by onox** [comment]
@gilbertohasnofb Can you find out what the outer and inner dial of the ADF instrument should do? They both currently change the standby KHz frequency.

**Comment by gilbertohasnofb** [comment]
I will have a look on that now.

**Comment by gilbertohasnofb** [comment]
Hmm, it seems that the KR 87 should have the possibility of having decimal numbers for the ADF, and then the outer knob would increment 0.1 Hz. See how the panel should have 4 seven-segment displays for each frequency but ours has only three: http://www.baron58.com/kr87.htm

**Comment by gilbertohasnofb** [comment]
UPDATE: this image above is incorrect, Bendix manual says the range is 200KHz to 1799KHz in 1 KHz increments and so our KR87 is correct. But then I don't know how the dials work. Maybe the outer one increments 1 KHz while the inner increments 10 or 100 KHz (as else to go from 200 to 1000 KHz would take 800 clicks!!).

**Comment by onox** [comment]
I'll make the outer 100 KHz, that's what the `<shift-action>` uses.

**Comment by gilbertohasnofb** [comment]
Sounds good.

**Comment by onox** [comment]
@gilbertohasnofb Can you test branch bug-391? See https://github.com/Juanvvc/c172p-detailed/issues/391#issuecomment-120494711

**Comment by onox** [comment]
I need to make some of the dials rotatable and then I'll create a PR.

**Comment by gilbertohasnofb** [comment]
Checked, all seem to be working perfectly.

**Comment by onox** [comment]
@gilbertohasnofb Fixed knobs of attitude indicator, altimeter, and nav 1 and nav 2 radials.

**Comment by gilbertohasnofb** [comment]
Thanks, all works super well!

**Comment by onox** [comment]
Cool! :smile:
