### ISSUE TITLE
Garmin 196 GPS option

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#392]
We could add the Garmin 196 GPS to our dashboard as an option (default off, to be activated via the menu). This GPS model is already located in fgdata, so it's very easy to add it to our plane. For my tests, I add the following lines to `Models/c172p.xml`:

```xml
<model>
    <path>Aircraft/Instruments-3d/garmin196/garmin196.xml</path>
    <offsets>
            <x-m>-0.4</x-m>
            <y-m>0.16</y-m>
            <z-m>0.205</z-m>
            <heading-deg>-12.0</heading-deg>
    </offsets>
</model>
```

And the following to the `c172p-set.xml` inside the `<nasal>` block:

```xml
<garmin196>
    <file>Aircraft/Instruments-3d/garmin196/garmin196.nas</file>
</garmin196>
```

This is the result, which is quite nice IMO:

![image1](http://s16.postimg.org/jfpbf4fbp/fgfs_screen_002.png)

![image2](http://s16.postimg.org/mb2elzjbp/fgfs_screen_003.png)

![image3](http://s16.postimg.org/aw5xhd6z9/fgfs_screen_004.png)

The good thing about directing to this GPS inside fgdata instead of copying it to our project is that any updates would also be automatically applied to our plane. For instance, I created a better texture for it but I couldn't make it work, and I reported it to the original creator.

**Comment by onox** [comment]
@gilbertohasnofb Could you perhaps upload those images directly to github? (Via the link at the bottom of the text input box) Then they are directly visible in the issue.

**Comment by gilbertohasnofb** [comment]
> Could you perhaps upload those images directly to github?

Well, I left them in the same server as before (postimage) but added them directly to the issue. Next time I add them directly, ok?

> Nice feature for 3.8 btw 

Yes, but there is lots to be fixed on this GPS. I already wrote the original author and I am seeing if he is interested in fixing a couple of bugs I found. I tried creating a more realistic dark texture but I can't add it to the model (his instructions are not working), but more importantly it seems the map is always slightly off position sometimes, but that changes according to the airport (e.g., when at SBRJ, the GPS displays the airport as being 0.15 nm south, when at SBSP it shows the airport some 0.3 nm North, and so on). Let's see how this goes, I will post an update here if I get any answers.

**Comment by gilbertohasnofb** [comment]
Hooray informed me that the original Garmin 196 project is apparently not being developed any longer, but someone was porting it to Canvas: http://wiki.flightgear.org/Garmin_GPSMap_196

I will keep this post updated if I receive any answers.

**Comment by gilbertohasnofb** [comment]
From Hooray:

> The 196 isn't too complex - so as long as you have 1-2 guys familiar with basic coding concepts (maybe even Nasal/Canvas), completing the existing prototype shouldn't be too difficult or time-consuming.
All the mapping stuff (as shown in the screen shot above) is already fully functional and working, because it was done by Gijs, Philosopher and others involved in unrelated MFD efforts, and because the MapStructure framework is sufficiently generic to still be useful.
Making the other pages/features functional will mainly involve editing/creating Inkscape SVG files and animating those via Nasal functions (timers/listeners).
For page handling, one of your coders should understand the concept of a state machine and the benefits of introducing one - which is where/why the GPSMap196 failed basically - even though I did provide corresponding patches, those were never committed by F-JJTH. You may still be able to find them by searching the forum/wiki though.

**Comment by wkitty42** [comment]
i can hardly wait for a fully glass cockpit to be fitted... i know there are some out there in RL as i've seen photos of them... almost leads to wonder about possible weight changes... they probably won't be enough to worry about, though...

**Comment by gilbertohasnofb** [comment]
Yes, the glass cockpit will be nice, but it will involve so much work (we will have to remodel and re-texturize the whole panel I think). But regardless of that, I think having a realistic looking GPS (particularly an old-school one such as the 196) would be great for the regular panel :smile:

**Comment by gilbertohasnofb** [comment]
The Canvas version of the GPS does not turn on on my computer, and I also felt a drop in performance (but this has to be tested, this is merely an impression). Is anyone here familiar with Canvas?

**Comment by onox** [comment]
I did some work on that OSM map on the wiki. Added zooming with scroll wheel and dragging. But the dragging is not consistent yet across zoom levels and there's no double buffering yet.

**Comment by gilbertohasnofb** [comment]
Alternatively, we could also get the non-Canvas 196 and try to develop it ourselves. It's quite functional so far, besides the texture problem and the major bug of the position being sightly off.

**Comment by onox** [comment]
I haven't looked at the instrument yet, currently fixing bugs for 3.6 :smile:

**Comment by gilbertohasnofb** [comment]
I understand that, I am simply brainstorming here, as well as taking notes so I don't forget anything. Right now I have very few things to do in our project (I am basically only testing your PRs and trying to contribute with one or two discussions), so I have plenty of time to mess around with this type of things :wink:

**Comment by tigert** [comment]
The 196 is very fitting option to an older 172 like ours. There are also panel-mounts available that have a clip for easy attachment and removal of the unit.

http://www.airportpilotshop.com/Air-Gizmo-Panel-Mount-for-Garmin-196-296-396-496-p/airgizmo-496.htm
http://www.vicdrive.co.uk/JOHNB1.JPG

It would be nice to do an avionics upgrade option for the Cessna at some point, with maybe a Garmin GNS or GTN set, but developing those moving map gps'es and color display navigators is quite time consuming if you want to model them completely, and I think it is also important to have a complete "steam gauges" and dials & needles set as well, since part of the fun in radio navigation is to learn to model the airspace inside your head, while following a VOR needle and DME readout. The moving map does add a lot of safety and situational awareness, but there is something very different in plain "raw data" radio navigation.

This old website seems to be online still: http://www.navfltsm.addr.com/ - very nicely written tutorial into that world.

I do agree we should try to create shared units, instruments and systems because all small GA planes would benefit from this kind of development and these units, and all of them share the same kind of units in the real life as well.

**Comment by gilbertohasnofb** [comment]
@tigert 

> The 196 is very fitting option to an older 172 like ours

Yes, I also love the look of them together with the model P :smile: 

> There are also panel-mounts available

I would rather have the GPS in some sort of mount like this:

http://www.gpscity.com/gallery_pics/pic01220-1.jpg
https://www.rammount.com/images/ipadminimount4.jpg

This way, we don't need to modify the cockpit for it and the GPS would be an option for the default model, to be activated via the menu. So people who don't want to use it or don't want to lose performance can simply ignore it, and their panel won't have a hole where the GPS would be.

> developing those moving map gps'es and color display navigators is quite time consuming

Indeed. The good thing about these 196 is that they were at least basically developed, so they can be at least a basic simulation of how these work. Right now I am using them only to orient myself, for instance to see where are the airports, high peaks, VOR and NDBs, etc., and for that the 196 looks pretty good.

**Comment by tigert** [comment]
Yeah, the dash mount is just fine too.

http://www.finnairflyingclub.com/flk/asp/images/CAY_panel_1024.jpg

This is a fellow club's 172 with the smaller garmin handheld. The 196 is also very nice, it can have a flight plan with waypoints etc. I need to look into it again :)

This is agood way to revive the project!

**Comment by gilbertohasnofb** [comment]
@tigert That mount in the centre of the dashboard looks great too!

Great to see that a lot of you are interested on this idea, so after the release of FG 3.6 we can really work on it! It would be so much nicer to have an implementation of a RL GPS instead of using FG's map and route manager :)

**Comment by legoboyvdlp** [comment]
One question here,does the GPS affect the autopilot IRL that is will it be able to do nav mode with gps instead of vor? Would it be possible to see this if yes?

**Comment by tigert** [comment]
Not the gpsmap196.

For autopilot guidance you need a certified gps and an approved installation.

**Comment by gilbertohasnofb** [comment]
Hooray on the performance hit I felt when using the Canvas version of this GPS:

> yeah, the original code written by F-JJTH is using a few inefficient techniques, such as the settimer(0) call to constantly update things (unnecessarily), I did actually post patches addressing/fixing this, but F-JJTH never committed those, so you will have to check the corresponding thread.

**Comment by gilbertohasnofb** [comment]
So guys, is anyone really up to develop this GPS or how do you feel about it? The thing is Hooray is offering some help but first we need someone with Nasal and Canvas knowledge and also he would like some help with the wiki for this work. Please see his message at: http://forum.flightgear.org/viewtopic.php?f=14&t=15433&p=253470#p253455

So do any of you feel like embracing this? Maybe @onox or @wlbragg feel like and have the knowledge? As much as I would like to have a GPS I don't have any Nasal or Canvas skills myself, but as always I am willing to help with whatever I can.

**Comment by onox** [comment]
Any existing Nasal code that I can use?

**Comment by gilbertohasnofb** [comment]
I think you'd have to ask Hooray. Since I know you are not in the forum, I'd happily forward any messages to him.

**Comment by onox** [comment]
I'll create `bug-392` with the non-Canvas variant.

**Comment by gilbertohasnofb** [comment]
Okay. Let me know if I can help with this. I personally had crashes all the time with the Canvas version, but the non-Canvas was awfully unreliable and the maps weren't precise enough. Hooray argued against developing the non-Canvas GPS for some reasons in that thread, but I have no horse in this race and no idea if that would be a good decision or not. I'm clueless as always :stuck_out_tongue:

**Comment by wlbragg** [comment]
Is this a GPS addon?

https://upload.wikimedia.org/wikipedia/commons/6/67/Cockpit_of_cessna_172e_g-asss_of_1964_arp.jpg

**Comment by onox** [comment]
```
Nasal runtime error: undefined symbol: ligne
  at Aircraft/Instruments-3d/garmin196/garmin196.nas, line 2872
```

**Comment by onox** [comment]
I can get a nice list of nearby VOR's, NDB's, and fixes :smiley:. Entering airport codes in the route tab is slow though. It affects the autopilot.

**Comment by gilbertohasnofb** [comment]
I don't get that error, @onox. Did you install the gps with the same snippets I posted in the first post here or are you doing something different?

**Comment by onox** [comment]
GPS instruments appears to be working mostly.

**Comment by gilbertohasnofb** [comment]
I created a new branch called simply `gps` to play around with this issue, okay?

**Comment by gilbertohasnofb** [comment]
I wrote ages ago:

> it seems the map is always slightly off position sometimes, but that changes according to the airport (e.g., when at SBRJ, the GPS displays the airport as being 0.15 nm south, when at SBSP it shows the airport some 0.3 nm North, and so on). 

I found the cause of that bug: the reason behind it is that I am a complete idiot! Obviously we are always 0.x nm from the airport when starting at a runway, since the airport GPS position will never coincide with every single end of every single runway! :blush: 

Also, I don't feel the GPS is slow at all. Where did you felt that, @onox? I remember that in the past it used to be slow, but today it is working super well and it's very responsive!

I made some modifications on the branch `gps` and I also want to report a couple of bugs:

- the north arrow does NOT point to the North, it's always stuck in the top left corner:
![fgfs-screen-007](https://cloud.githubusercontent.com/assets/5700795/11610327/e63560ac-9b9f-11e5-88f2-451b49b77176.png)

- sometimes the elements in the screen rotated 180 degrees for a brief time, like few hundreds of a second only (so an airport in the NW would show at SE), but I still didn't have the chance to try to narrow this down and see if it's reproducible or not. Let's just keep the eyes opened for it though.

- some of the GPS screens are displayed slightly offset (one pixel or so) but the effect is very bad: try zooming in the GPS, click MENU then use the arrows up and down. Notice how the screen moves around.

- in the already mentioned branch I moved this garmin to `/Models/Interior/Panel/garmin196` so it's now local, and so we can freely modify it

- I added a better texture for it (replacing the original `coque.png`)

- I created a GUI check box for adding the GPS and made it's state savable (default = off)

- the antenna now starts in the upper position

Question: does the GPS affect performance if it's not visible? Is its Nasal code loaded regardless of the model, for instance?

**Comment by gilbertohasnofb** [comment]
Question no. 2: when turning on the GPS, the default zoom range is always 0.125 nm, which seems awfully zoomed in. Does anyone know if the real model have a default value (and if so, what is it) or does save the last used value? I found its [manual online](http://www.manualslib.com/manual/253205/Garmin-Gpsmap-196.html) but I can't find this answer there, and I also can't find any video of someone turning on a Garmin 196 or equivalent...

**Comment by onox** [comment]
@gilbertohasnofb Is that the Canvas variant? I had already created a non-Canvas variant in branch [`bug-392`](https://github.com/Juanvvc/c172p-detailed/compare/bug-392).

**Comment by gilbertohasnofb** [comment]
@onox no, that's the non-Canvas variant. Sorry but I missed the message where you mentioned the branch `bug-392`. As far as I can see, the only thing you did in that branch was to add the 3D model to the plane (using the FGDATA path). Given that I made it local and already did some few improvements (texture, GUI check button, antenna position), do you think we could simply delete `bug-392` and use the branch `gps` for this work? Alternatively, I can of course add these modifications to the branch you created and delete the newest one. What do you think?

**Comment by gilbertohasnofb** [comment]
Sorry for the mess by the way :confounded:

**Comment by onox** [comment]
> Alternatively, I can of course add these modifications to the branch you created and delete the newest one.

@gilbertohasnofb I think it's better to do that. In the `bug-392` we simply (re-)use the stuff in FGDATA instead of duplicating it. So I suggest to add your fixes to that branch and delete your `gps` branch. In case there are any bugs in the `Aircraft/Instruments-3d/garmin196/` code, then you simply need to patch it and send the patches to the mailing list. That way other people who use the garmin196 can benefit from it as well.

**Comment by gilbertohasnofb** [comment]
@onox 
>  In case there are any bugs in the Aircraft/Instruments-3d/garmin196/ code, then you simply need to patch it and send the patches to the mailing list. That way other people who use the garmin196 can benefit from it as well.

But that will give us much less room to improve things! Why can't we work on improving the GPS here and after the work is done we send a patch to FGDATA, just like we did with the environment sounds? It would be a nightmare to have to send a patch to FGDATA and wait for it to be tested and committed every time we changed that `wind.wav` sound, let alone something as complex as a GPS... 

And then in case we will make the GPS local while working on it, are you sure you don't want me to simply delete branch `bug-392` and keep`gps` as it's much less work? Else I will have to merge them and the result will be _identical_ to the current `gps`, just with a different name.

**Comment by gilbertohasnofb** [comment]
For instance, the garmin196 in FGDATA can't use different textures for some reason, so if I am experimenting with them I'd need to first fix that, then send a patch of my texture every time I want to see it in the sim. Kind of a nightmarish scenario, isn't it?

**Comment by onox** [comment]
If you really want to work on improving the GPS, we should go with the Canvas variant.

**Comment by gilbertohasnofb** [comment]
Well, I don't think I am the person for that as I know nothing about Canvas (and even the non-Canvas is way beyond my programming capacities). But I am trying the best I can to work on it, started with textures, plan to have a look on that buggy North indication. But I'd hope that anyone else would jump in the boat for this as I don't think I can go far by myself :smile:

**Comment by onox** [comment]
We might be able to use `Nasal/canvas/MFD_Generic.nas`.

**Comment by onox** [comment]
Btw, what do you mean with "different textures"?

**Comment by onox** [comment]
Are you talking about the hardware itself (the device) or the screen?

**Comment by gilbertohasnofb** [comment]
I created a darker texture (for the device) that is much closer to the RL model. The one in FGDATA is grey, the real life is plastic black. So what I am saying is that it's easier to have a local copy to play around with it to improve, and then send a patch afterwards when we have something stable or that we are satisfied with. Makes sense?

**Comment by gilbertohasnofb** [comment]
And I also plan to take a look on the screens that move slightly when going up and down in the menu, I have to see if that's a texture, 3D model or programming problem.

**Comment by onox** [comment]
Let's do the following:

**Comment by onox** [comment]
Use `bug-392`. Move the old non-canvas device a bit to the right so I can compare it.

Then add a new .ac file containing just your patched device. Make sure to remove all non-visible objects in that .ac file. Make sure that the screen itself is just a flat rectangle.

I'll add the canvas stuff then.

**Comment by onox** [comment]
Is that ok with you?

**Comment by gilbertohasnofb** [comment]
Sure it is! I will try to modify the .ac file myself, but please know that I am useless on Blender... If I don't manage myself I will shout for help, ok?

(so this means that we will use only the 3D model of the `garmin196` and that we plan to program the GPS itself from scratch?)

**Comment by gilbertohasnofb** [comment]
I will try to do this still tonight

**Comment by onox** [comment]
Yes. That's why you should move the old non-canvas to the right so I can reproduce the behavior in the new canvas variant.

**Comment by gilbertohasnofb** [comment]
Okay!

**Comment by onox** [comment]
Btw, could you test my PR that is currently open? :smile:

**Comment by gilbertohasnofb** [comment]
Yes, sorry for the delay, I will try to do it tonight as well! I am just so clueless about how those things are supposed to work that I have been hoping someone else would test and merge it before me :stuck_out_tongue_winking_eye:

**Comment by onox** [comment]
It's very simple, if EGT is high and cabin heat is open, it gets warmer. If you open cabin air, overhead vents, or windows/doors, you add air from outside. Adding humans will increase temperature a little and increase humidity.

I've been flying with the branch for a while now, and it all works. It's mainly some constants that could be tuned. The fog/frost appears not too fast. I'm not sure humans add enough heat. Maybe it's better to just merge the PR, so that we can later hear if people think fog needs to be appear quicker or not.

**Comment by gilbertohasnofb** [comment]
Sound all right, I will give it a go.

> Maybe it's better to just merge the PR, so that we can later hear if people think fog needs to be appear quicker or not.

We can do that, but I promise you I will get at it still today. If you can wait a couple of hours I can test it and merge it myself. Is that all right?

**Comment by onox** [comment]
That's okay.

**Comment by gilbertohasnofb** [comment]
> Move the old non-canvas device a bit to the right so I can compare it.

@onox, it seems that you already the __non-Canvas__ device in that branch:

```
    <model>
        <path>Aircraft/Instruments-3d/garmin196/garmin196.xml</path>
        <offsets>
            <x-m>-0.4</x-m>
            <y-m>0.16</y-m>
            <z-m>0.205</z-m>
            <heading-deg>-12.0</heading-deg>
        </offsets>
    </model>
```

So basically if I do as you say and add my slightly modified Garmin, we will have two non-Canvas devices, one grey and one black, one remote and one local. Is that what you want?

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/11615228/ae2a4044-9c5b-11e5-8896-58172465a4c5.png)

**Comment by onox** [comment]
Well, the new black one should just have an empty screen. Don't add every single file (like docs, etc.) as you did in `gps`. That's not really necessary because the empty screen (simple rectangle in Blender) will be painted by canvas eventually.

**Comment by gilbertohasnofb** [comment]
I see, so we will have a grey non-Canvas GPS and a black non working GPS. I will do it as you say.

**Comment by onox** [comment]
Yes. So just add the minimal amount of files to see the device itself. It shouldn't function until we add the actual canvas code later.

**Comment by gilbertohasnofb** [comment]
Ok.

**Comment by gilbertohasnofb** [comment]
Okay, I pushed it. Remember that I added the GUI option to show/hide the GPS, so the first time you load this branch you will have to activate it in the Aircraft Dialog. I created a .blend file and I deleted all the screens objects but one. The problem is that I get an error when I try to export the model as a .ac file, so could you or someone else with more Blender experience check what is going on? The file is located at `/Models/Interior/Panel/garmin196`. This means that the current .ac file is the default one with several screens one above the others, ok?

**Comment by gilbertohasnofb** [comment]
Also, branch `gps` should have been deleted.

**Comment by onox** [comment]
@gilbertohasnofb I have deleted the `gps` branch. Have you done more work on the `bug-392` branch? I want to rebase it on top of latest master, because the branch is already quite old (1 month).

**Comment by gilbertohasnofb** [comment]
> I have deleted the gps branch

Ops, I had deleted it only locally! Thanks then :smile: 

> Have you done more work on the bug-392 branch

Nope, just that single commit. Feel free to rebase it.

**Comment by onox** [comment]
@gilbertohasnofb Pushed. In the `bug-392` branch you can reset to two commits ago with `git reset --hard HEAD~2`. After that use `git pull`.

**Comment by gilbertohasnofb** [comment]
Done :+1:

**Comment by onox** [comment]
Btw, to get rid of the screen objects, they should be removed in Blender, but in the mean you could try to create a temporary select animation with a condition that is always false (`<false/>`) and then add all those (useless) screen objects.

**Comment by onox** [comment]
That way we also gather a list for whoever can properly export .ac files to know which objects can be safely deleted in Blender.

**Comment by gilbertohasnofb** [comment]
> Btw, to get rid of the screen objects, they should be removed in Blender
> [...]
> That way we also gather a list for whoever can properly export .ac files to know which objects can be safely deleted in Blender.

Well I already did that, it was pretty obvious which objects could be deleted and so I did that. I am just having troubles exporting the .ac file, but I believe that .blend is ready to go. Could you give it a try maybe?

**Comment by onox** [comment]
Oh, it's already present, didn't notice the file. I'll check.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by onox** [comment]
I get an error too. It goes away when I delete the "screen" object.

**Comment by gilbertohasnofb** [comment]
Can you check if that object isn't set to any texture? That could be the issue. If not then would you be able to delete it and create a new rectangle object as a new screen?

**Comment by onox** [comment]
Maybe, but it's too late now. Need to sleep :wink: :sleeping:

**Comment by gilbertohasnofb** [comment]
No worries, we do it some other time. Here is also very late as well... have a good night, onox!

**Comment by onox** [comment]
@gilbertohasnofb Is this how it's supposed to look? The exported `.ac` file has different materials:

```diff
-MATERIAL "ac3dmat0" rgb 0 0 0  amb 0.2 0.2 0.2  emis 0 0 0  spec 0.2 0.2 0.2  shi 128  trans 0
-MATERIAL "ac3dmat1" rgb 1 1 1  amb 0.2 0.2 0.2  emis 0 0 0  spec 0.2 0.2 0.2  shi 128  trans 0
-MATERIAL "DefaultWhite" rgb 1 1 1  amb 1 1 1  emis 0 0 0  spec 1 1 1  shi 50  trans 0
+MATERIAL "DefaultWhite" rgb 1.0000 1.0000 1.0000  amb 0.2000 0.2000 0.2000  emis 0.0000 0.0000 0.0000  spec 0.5000 0.5000 0.5000  shi 10 trans 0.0000
+MATERIAL "DefaultWhite.002" rgb 1.0000 1.0000 1.0000  amb 1.0000 1.0000 1.0000  emis 1.0000 1.0000 1.0000  spec 0.5000 0.5000 0.5000  shi 12 trans 0.0000
```

![fgfs-screen-405](https://cloud.githubusercontent.com/assets/3361585/11768039/e4ba8de8-a1c0-11e5-9548-0309aacf4dd1.png)

**Comment by onox** [comment]
If I manually modify `emis` to zero then it looks alright. Not sure about `spec` and `shi` though.

**Comment by gilbertohasnofb** [comment]
> Is this how it's supposed to look?

Regarding what, exactly? Texture-wise? If so, then yes, it looks fine to me.

> If I manually modify emis to zero then it looks alright (during day and night). Not sure about spec and shi though.

I am not familiar with these sort of properties as they are normally done in Blender :cry:

**Comment by wlbragg** [comment]
Anything I can do to help on this, let me know!

**Comment by onox** [comment]
On the forum/wiki you can find screenshots of an older Canvas implementation. It would be nice if you could find the code and the `.svg` files :smile:

**Comment by onox** [comment]
And delete the `screens.png` material from the `screen` object in Blender. If you then export the `.ac` file. Is it much different according to `git diff`?

**Comment by wlbragg** [comment]
I'm not the person to find things in our wiki or forum (or I am and nothing is ever there :smile: )
I found mostly what you already reference here.
http://wiki.flightgear.org/Garmin_GPSMap_196
http://forum.flightgear.org/viewtopic.php?f=71&t=23047&hilit=gps&start=15
http://forum.flightgear.org/viewtopic.php?f=14&t=15433&p=253470#p253455
http://forum.flightgear.org/viewtopic.php?f=71&t=23644&hilit=gps

> code and the .svg files

Look where?

>Is it much different according to git diff?

Is this what you looking for?
@ -1,13118 +1,12894 @@

**Comment by onox** [comment]
> Is this what you looking for?
@ -1,13118 +1,12894 @@

No, what I meant to ask is how many lines are added/deleted when you simply delete the material reference in the screen object.

**Comment by onox** [comment]
> Look where? Is it in our c172p history?

No, but on the forum they said they made use of some colored SVG files.

**Comment by onox** [comment]
[This](http://forum.flightgear.org/viewtopic.php?f=71&t=23047&hilit=gps&start=15#p209575) is what I mean:

![GPSmap196 with SVG images](http://wiki.flightgear.org/images/a/a9/Gpsmap196-svg-instruments.png)

I was hoping that we could still find the code that generates that picture somewhere on the internet.

**Comment by wlbragg** [comment]
Do you have any idea what plane that is in in the background?

**Comment by wlbragg** [comment]
That is what 1,13118 +1,12894  is

It went from 13118 to 12894 = 224 less lines.

**Comment by onox** [comment]
Ah, OK, didn't recognize it as diff stats. I thought it was the usual output from the .ac file. It still modifies over 10_000 lines it seems. I guess the .ac exporter plug-in finds that necessary.

Could you add the fixed Blender and .ac file? Make sure to set `emis` in the .ac file to 0 if it is 1. Here I always have to manually adjust it :confused:

**Comment by onox** [comment]
> Do you have any idea what plane that is in in the background?

Don't know. Ask Hooray.

**Comment by wlbragg** [comment]
The one in this branch (Bug-392) is already had the material removed?
Did you want me to take the one from "master" and edit it and then save it to this branch?

**Comment by gilbertohasnofb** [comment]
> Do you have any idea what plane that is in in the background?

@wlbragg that's the dr400-dauphin

**Comment by onox** [comment]
@wlbragg No, just checkout `bug-392`, edit the Blender file, and export to the .ac file.

**Comment by wlbragg** [comment]
>@wlbragg No, just checkout bug-392, edit the Blender file, and export to the .ac file.

Wow, I had jsut check and I'm telling you it did have the material removed. :open_mouth:
I'll look again!

**Comment by wlbragg** [comment]
OK, you were right, it was still there.
Done.

**Comment by onox** [comment]
@wlbragg What's the "test" commit?

**Comment by onox** [comment]
I'll squash last two commits into one and force push.

**Comment by onox** [comment]
Done.

**Comment by wlbragg** [comment]
Sorry, it was something I was was doing prior. I didn't realize it was still a part of my local branch.

Is this what your looking for?
![page-panel](https://cloud.githubusercontent.com/assets/11069680/11829114/c469fe3e-a35f-11e5-90bc-f3fbd88fc847.jpg)

**Comment by wlbragg** [comment]
No, that doesn't look like it.

**Comment by onox** [comment]
Ehh... I'm not sure why you come up with that picture? O_o That's not an SVG.

Could you perhaps just ask Hooray if he still has the code? I deleted my forum account.

**Comment by wlbragg** [comment]
I did ask Hooray on the Forum and that was .svg, I couldn't post it as .svg, I had to change it to jpg to post it here.

**Comment by wlbragg** [comment]
Found reference to the image in a few unexpected places, haven't found the code yet.

https://commons.wikimedia.org/wiki/Category:Flight_instruments
https://commons.wikimedia.org/wiki/Category:SVG_aircraft_instruments
From here
http://forum.flightgear.org/viewtopic.php?f=71&t=23047#p209470

This was a surprise.
http://www.clickindia.com/detail.php?id=137806476
http://www.latostadora.com/camisetas/combustible

**Comment by wlbragg** [comment]
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=269021#p268972

**Comment by onox** [comment]
I lost interest in Canvas a bit, so we might just as well hide the Canvas version (the black one) and just show the old white one.

**Comment by gilbertohasnofb** [comment]
@onox no problems at all, but if we don't plan to work on the Canvas version, wouldn't it be better to remove it instead of hiding it, so that the non-Canvas GPS may one day make it to the master? My plan before was to add a checkbox to the aircraft menu to show/hide the GPS, and I can do that in this branch. (BTW sorry for my late reply, I have been super busy lately)

**Comment by onox** [comment]
> wouldn't it be better to remove it instead of hiding it, so that the non-Canvas GPS may one day make it to the master

If you remove it, someone needs to recreate the black GPS device. But since we already have it, simply hiding it is much easier. (It's also easier to unhide it later)

> add a checkbox to the aircraft menu to show/hide the GPS

I'm a bit confused, that checkbox already exists in `bug-392`.

**Comment by gilbertohasnofb** [comment]
Okay, so I will simply hide it then. 

> I'm a bit confused, that checkbox already exists in bug-392.

Oh, I forgot I already had added it! :tired_face:

**Comment by onox** [comment]
I'm working on it right now :smile:

**Comment by gilbertohasnofb** [comment]
Okay then, thanks onox!

**Comment by onox** [comment]
You can merge the PR in a minute :wink:

**Comment by gilbertohasnofb** [comment]
Hmm, wait a second, are you then planning to merge a hidden Canvas GPS and a non-hidden non-Canvas GPS? Isn't that a bit messy?

**Comment by onox** [comment]
Not really, it's just a bunch of files that aren't being used.

**Comment by gilbertohasnofb** [comment]
Okay, I see, so there won't be any mentions of the Canvas version in any of the plane's XML files, but the Canvas GPS itself will be there somewhere in some subdirectory, is that correct? If so, then I guess it's harmless. I thought you meant "hiding" by making it invisible, but leaving the XML code there or something like this.

**Comment by onox** [comment]
I have just commented the XML code.

**Comment by onox** [comment]
Or should I make a comment that the path to .xml file just needs to be modified?

**Comment by onox** [comment]
That seems cleaner.

**Comment by onox** [comment]
Well... I'll just leave it as it is currently (commented the XML code) so that whoever implements the Canvas, can look at both devices side-by-side.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
If you create a PR, I can take a look at it now and merge it.

**Comment by onox** [comment]
@gilbertohasnofb PR has been created.
