### ISSUE TITLE
New thumbnail

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#396]
@gilbertohasnofb Could you create a nice new `thumbnail.jpg` using the new default livery (4X-CHV)?

ALS, detailed weather, etc. Perhaps add 2 people in the cockpit. Post the thumbnail here first so we can decide whether we like it :smile:

**Comment by gilbertohasnofb** [comment]
Sure! I just posted this image in the forum, what do you think about it?

![image](http://s14.postimg.org/4di6v0fc1/fgfs_screen_001.png)

If not, then I can create a new one for us.

**Comment by onox** [comment]
That one looks nice, but can you create one that shows the front? Also, I think the size should be 172x128. That's what the current thumbnail is, don't know what the limits are that the new launcher can handle.

**Comment by gilbertohasnofb** [comment]
> That one looks nice, but can you create one that shows the front?

Sure, I will do that.

> Also, I think the size should be 172x128.

Oh, I was thinking we were talking about a new splash screen, but of course you mean thumbnail. Sure, I will create a nice one for that. But isn't 172x128 extremely small??

**Comment by onox** [comment]
Yes, it is. Can it be larger? I have never used any of those GUI launchers.

**Comment by gilbertohasnofb** [comment]
I use fgrun and I don't think there is any limitation for size. Let's create a large image and then if necessary we shrink it.

**Comment by gilbertohasnofb** [comment]
What about these ones?:

![image1](http://s30.postimg.org/zc9zlqdwh/fgfs_screen_002.png)

![image2](http://s30.postimg.org/gl82bkjc1/fgfs_screen_003.png)

**Comment by onox** [comment]
I like the bottom one :smile:

**Comment by gilbertohasnofb** [comment]
Cool, so how should I name the file and to which folder should I upload? `thumbnail.png` on the root?

**Comment by gilbertohasnofb** [comment]
BTW, fgrun uses the splash screen as thumbnail, but I know that fgrun will stop to exists from FG 3.6 onwards. And I never used nor do I know how to use the new Qt launcher.

**Comment by onox** [comment]
I think `fgfs --launcher` if you have Qt 5 installed.

**Comment by gilbertohasnofb** [comment]
Yep, and it seems the new launcher indeed uses only 172x128 thumbnails (fgrun could use any size). I will work on this right now.

**Comment by onox** [comment]
Doesn't the new launcher automatically resize it? :open_mouth:

**Comment by gilbertohasnofb** [comment]
I don't know. Actually, when I start FG via the Qt5 launcher, I see a very old thumbnail for our cessna (it's not even the thumbnail.jpg that we have in our directory). Anyway, I will work on the 172x128 image (I will save a high resolution version just in case, and then we test if it's resized automatically).

**Comment by onox** [comment]
Have you removed the old c172p?

**Comment by gilbertohasnofb** [comment]
Yep, I actually deleted the c172p from fgdata and tried replacing it with ours.

**Comment by onox** [comment]
Have you tried to rename `.fgfs` to `.fgfs-backup`?

**Comment by gilbertohasnofb** [comment]
I will check right now. By the way, this is the small thumbnail looks like:

![thumbnail](https://cloud.githubusercontent.com/assets/5700795/8634699/c6f8b74e-2803-11e5-839c-3604ff1ed6ab.jpg)

**Comment by gilbertohasnofb** [comment]
> Have you tried to rename .fgfs to .fgfs-backup?

Yep, that didn't work for me. Anyway, I pushed the new thumbnail.jpg to the root directory, so now we have to find a way of making it work with the Qt5 launcher. Is anyone here using this launcher?

**Comment by gilbertohasnofb** [comment]
And by the way, I added the image shown in the comment https://github.com/Juanvvc/c172p-detailed/issues/396#issuecomment-120522530 as a new splash screen, as we didn't have a single one showing the default livery! Hope that's all right.

**Comment by onox** [comment]
Fixed in 7b5979e

**Comment by onox** [comment]
> Hope that's all right.

All your screenshots look very nice :smile:

**Comment by gilbertohasnofb** [comment]
Thanks, onox!
