### ISSUE TITLE
Consistent line endings and formatting

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#400]
It seems we use a mixture of LF line endings (Linux and OS X) and CRLF (Windows). We also use a mixture of tabs, 1, 2, 3, and 4 spaces. This makes the code chaotic and uglier than it needs to be. It also creates ugly diffs making reviewing changes more difficult. Tabs also look very wide on Github.

I suggest we go with just LF and 4 spaces. Editors like notepad++ are able to use LF and insert spaces when you press the tab key. For the line endings I would like to add the following `.gitattributes` file:

```
* text eol=lf

*.png binary
*.jpg binary
*.rgb binary
*.wav binary
*.blend binary
*.xcf binary
*.zip binary
```

I can fix the `.xml` files with `XMLLINT_INDENT="4 spaces here" xmllint --format --output FILE FILE`. I won't change the `.nas` files because that needs to be done manually and is just too much work for now.

**Comment by onox** [comment]
Only 5 files will have its line endings replaced:

```
	modified:   Nasal/c172p.nas
	modified:   Nasal/weather.nas
	modified:   Systems/bushkit.xml
	modified:   Systems/fuel.xml
	modified:   gui/dialogs/aircraft-dialog.xml
```

**Comment by wkitty42** [comment]
if you can get that .gitattributes file uploaded to github like the .gitignore file is, then this should cover everyone using this repo... right?

**Comment by onox** [comment]
Yes, it's a file in the repository.

**Comment by wkitty42** [comment]
i will look for it to be downloaded on my next update :wink:

**Comment by wkitty42** [comment]
FWIW: i have not seen this .gitattributes file yet... i'm guessing it has not been released as an update in the repo on its own??

**Comment by onox** [comment]
It's in the repository: https://github.com/Juanvvc/c172p-detailed/blob/master/.gitattributes

**Comment by wkitty42** [comment]
On 07/12/2015 04:37 AM, onox wrote:
> It's in the repository:

confirmed... it came in with the update i just pulled ;)
