### ISSUE TITLE
ADF frequency cannot be changed while the sim is paused

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#401]
Unlike the NAV and COM knobs, the ADF frequency cannot be changed while the sim is paused.

**Comment by gilbertohasnofb** [comment]
@onox Do you have any idea why is this so? This is really a minor bug of course, but since I think it was introduced since our last work in the radios I thought I'd bring it up. As always, feel free to move it to the 3.8 release milestone.

**Comment by onox** [comment]
I can reproduce it here, but I'm not interested in fixing it right now, so I'll move it to 3.8 release.

**Comment by gilbertohasnofb** [comment]
> I'll move it to 3.8 release.

Absolutely fine!

**Comment by gilbertohasnofb** [comment]
Does anyone have any idea what causes this issue? I tried looking at those xml files but can't see anything obvious, the pick animations seem similarly implemented in the ADF radio as the VOR/NAV radios.
