### ISSUE TITLE
Create Co-Pilot View

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#416]
Create Co-Pilot View

**Comment by onox** [comment]
We can also add views for the passengers.

Do we want to enable the views always or only if there's weight on the seat?

**Comment by gilbertohasnofb** [comment]
> We can also add views for the passengers.

That is a nice idea!

> Do we want to enable the views always or only if there's weight on the seat?

I wouldn't do that because some people (like me) don't use the models and then it would be very cryptic to understand why some views are being offered sometimes or not. I think we should offer all 4 views all the time and simply hide the model in case a specific view is selected (as I did for the co-pilot).

I will have a look on the code now and create these other views.

**Comment by onox** [comment]
OK.
