### ISSUE TITLE
Seat mounts need to be 3D objects

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#418]
We had removed the alpha channel of the `interior.png` due to some problems with visibility through the windows, but then the seat mounts (all 4 seats) lost their transparency. See:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/8675172/b1ac4d60-2a42-11e5-8fb6-ca6672e73459.jpg)

The solution is to 3D model the seat mounts (so instead of the current rectangle, we could roughly model this surface as to fit the texture, still keeping it as a 2D surface).

**Comment by gilbertohasnofb** [comment]
@Juanvvc do you think you can give me some advice here? Is there some adverse effect I should expect if I once again add an alpha channel to these textures?

**Comment by Juanvvc** [comment]
There could be the usual issues with the alpha channel and textures in ALS and Rembrandt. Check this thread: http://forum.flightgear.org/viewtopic.php?f=5&t=22707

These issues do not have an easy fix, especially if we want to offer support both in ALS and Rembrandt. But these mounts looked ok in the past. Just recover the alpha channel and we'll see :) At the end of the day, we can always model these seat mounts.

**Comment by gilbertohasnofb** [comment]
@Juanvvc 
> Just recover the alpha channel and we'll see :) At the end of the day, we can always model these seat mounts.

Okay! Let's try the alpha channel solution first, and if someone finds a problem we can just revert it back.

**Comment by gilbertohasnofb** [comment]
@Juanvvc Okay, so I tried adding back the alpha channel (just around the seat mount area in the png file) and then I found out why we removed it in the first place: the interior of the plane isn't visible at all through the windows if there is even a single pixel with alpha channel in that file! 

So now we need solution number two: model the seat mounts in Blender. I am updating the description of the issue now.

**Comment by legoboyvdlp** [comment]
Hmm... may be difficult. Will see what can be done.
I wish Blender worked like WED - point and click to add vertices...

**Comment by wlbragg** [comment]
You'll pick it up quick enough. My main issue with using it was the shear amount of features and not having a clue about its capabilities. But I found a quick Google search almost always gave me the info I needed. Applying that info was another thing.

**Comment by legoboyvdlp** [comment]
Right... I'll see what I can do with this! 
Looks simple enough...

**Comment by legoboyvdlp** [comment]
@gilbertohasnofb @Juanvvc @tigert any ideas about the size of the item in question?

**Comment by gilbertohasnofb** [comment]
Try having a look at tigert's website, he has several pictures of the real thing. See http://tigert.1g.fi/kuvat/Simulators/Flightgear/

**Comment by legoboyvdlp** [comment]
Thanks :)

**Comment by legoboyvdlp** [comment]
I'm not really confident enough to do this; if nobody else gets it done before I look at it, I'll do it, but right now, I'm not sure. I'm still at basic structures:
http://i67.tinypic.com/20kocg6.png

**Comment by gilbertohasnofb** [comment]
No pressure, lego.
