### ISSUE TITLE
Some radio panels are dark under ALS flashlight

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#421]
Some radio panels are dark under ALS flashlight. See:

Flashlight only:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/8697640/ff122958-2af6-11e5-94af-f7aebc059477.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/8697642/040b095c-2af7-11e5-91e6-56f113b1368c.png)

Flashlight + Avionics switch:

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/8697644/08d53ec6-2af7-11e5-9bbe-a05d7cb18492.png)

![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/8697646/0e808baa-2af7-11e5-8d38-de958947faee.png)

Flashlight + Avionics switch + instrument lightning at 100%:

![fgfs-screen-005](https://cloud.githubusercontent.com/assets/5700795/8697649/14bb3f6a-2af7-11e5-9115-2c4a7b3b4650.png)

![fgfs-screen-006](https://cloud.githubusercontent.com/assets/5700795/8697651/19d89a60-2af7-11e5-874b-d998d0a02b29.png)

**Comment by gilbertohasnofb** [comment]
Also notice how the knobs and buttons of the NAV and COM panels are only shown with instrument lightning on, and how the Transponder knobs and numbers are never shown.

**Comment by wlbragg** [comment]
I must be blind, I do see what your taking about now. But my airspeed indicator is correct.
Let me look at the radio stack components. I need to identify all object names that do not have the flashlight effect applied to them and where in the xml they are located?

**Comment by wlbragg** [comment]
OK, AdjustKnob" and the "CageKnob of the AI and "Trim Wheel" I have fixed locally.
![effect](https://cloud.githubusercontent.com/assets/11069680/8707143/9c2e6ad8-2af9-11e5-8b2e-789093b26439.jpg)
I need help identifying the xml location of everything else mentioned in this post.

**Comment by onox** [comment]
The object is called "rect". You can find it if you import `Models/Interior/Panel/Flaps/flaps.ac`. It doesn't seem to be part of `c172p.blend`.

**Comment by onox** [comment]
I'm not really a big fan of making those knobs and trim wheel all white, can't you make it like the CageKnob?

**Comment by gilbertohasnofb** [comment]
@wlbragg look at the 1st and 2nd pictures: the ADF radio is off and and has no instrument illumination, and yet all buttons and knobs are illuminated by the lantern. Now look on top of it, you have a black square! That's where the NAV and COM radios should be. The lantern should illuminate their buttons and knobs. Now look below the autopilot in the 2nd picture: the transponder is completely black.

Turning the instrument illumination on (5th and 6th pictures) work on the buttons and knobs of NAV and COM radios but not on the transponder, which is always black.

The flaps are indeed missing their background label.

> I'm not really a big fan of making those knobs and trim wheel all white

Me neither!

**Comment by wlbragg** [comment]
>I'm not really a big fan of making those knobs and trim wheel all white, 

That is why I posted the comment
>I guess this is an improvement?

>can't you make it like the CageKnob?

I can't, I can only apply the effect or not. I wonder though if there is some other setting or effect that is not being applied to a few of these knobs that are so white.

**Comment by wlbragg** [comment]
OK, I think I got it all
![rad](https://cloud.githubusercontent.com/assets/11069680/8716089/9d710722-2b51-11e5-8922-cc93238514ee.jpg)

**Comment by gilbertohasnofb** [comment]
> OK, I think I got it all

Yes!!! I will check your PR now :smile:
