### ISSUE TITLE
Strange bug with shadows on gauges

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#428]
While working on https://github.com/Juanvvc/c172p-detailed/pull/425 with @wlbragg I came across the following strange bug related to the shadows on the gauges: https://youtu.be/MNkuBGVcNq8

I tried but I couldn't reproduce it. Maybe it was  due to a very specific combination of weather and lightning. If anyone comes across this, please try to find a way of reproducing it.

**Comment by gilbertohasnofb** [comment]
This problem still appears from time to time, but only under certain conditions and I can't reproduce it consistently. It's really a tricky one....

**Comment by onox** [comment]
There's also the problem that needles and instruments get strange pink/green colors:

![fgfs-screen-398](https://cloud.githubusercontent.com/assets/3361585/11754523/2593c4d6-a04c-11e5-8450-af919312e4e4.png)

See altimeter and magnetos.

**Comment by gilbertohasnofb** [comment]
The greenish hue in the magneto switch is indeed present very often. As for the pink colours in the instruments, I have never seen that except when the instrument lightning is higher than 0%, in which case that would be a feature :wink: You are sure that's not the case, right?

**Comment by onox** [comment]
But some of the needles are white instead of pink. They should either be all pink or all white.

**Comment by gilbertohasnofb** [comment]
Agreed. Would you open a new issue for the colour problem or do you want me to do it?

**Comment by onox** [comment]
You can do it :wink:

**Comment by gilbertohasnofb** [comment]
:+1: https://github.com/Juanvvc/c172p-detailed/issues/614

**Comment by wlbragg** [comment]
I'm pretty sure the green is a side effect of the flashlight effect. We ran across it in the shuttle but on a larger scale. Requires a "fake" white cube map to fix. The effect inherited fro flashlight expects a cube and without one uses a default that has green grass on it.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/618
