### ISSUE TITLE
add dust effect during off-pavement landing and take-off

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#43]
PRC03 - add dust effect during off-pavement landing and take-off.

**Comment by wlbragg** [comment]
Finished, added groundspeed limit of 20 kt, rolling_friction-factor > 1 and wow = true. Extended existing smoke code. Consider 3 new dust.xml files using different color smoke (dust color instead of white/gray burning rubber smoke). Leave open until consensus.

**Comment by gilbertohasnofb** [comment]
Can we close this?

**Comment by wlbragg** [comment]
Yes, sorry I took so long to see it.
