### ISSUE TITLE
Spinning propeller sometimes disappear

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#434]
Spinning propeller (the blurred circle) sometimes disappear, although I couldn't narrow down in which conditions this happen.

@wlbragg also wrote:

> I notice it when I flipped upside down and it started to kill the engine, then I saw the prop blur and realized it must be missing from other conditions. I'll take a look at it and see if it is something obvious.

**Comment by wlbragg** [comment]
Does
~~~xml
alias="/params/engine/rpm
~~~
account for both (all) engines or would it be just a single engine?

**Comment by onox** [comment]
@wlbragg It is the RPM of the current engine that you have selected.

**Comment by onox** [comment]
@gilbertohasnofb Can you still reproduce this? I think we need to stop rotating the spinner (that thing to which the propellers are attached to) when the engine is crashed. The propellers correctly stop rotating, but the spinner does not.

**Comment by gilbertohasnofb** [comment]
> Can you still reproduce this?

I will check later today, but this was one of those heisenbugs that appear once in a blue moon.

**Comment by gilbertohasnofb** [comment]
Yes, I can still reproduce this, but it's difficult to narrow down to what is causing it. Sometimes the propeller disk is simply not there!

>  I think we need to stop rotating the spinner (that thing to which the propellers are attached to) when the engine is crashed. The propellers correctly stop rotating, but the spinner does not.

Confirmed. I opened a new issue for this, see: https://github.com/Juanvvc/c172p-detailed/issues/595

**Comment by gilbertohasnofb** [comment]
So, it looks like my propeller disk disappears depending on the speed/RPM! I took off from the external view and it slowly faded away. When I pulled the throttle back is started to appear again. Does anyone else experience this?

**Comment by wlbragg** [comment]
Yes, I just noticed it. So what, at high speed it should still be blurred, correct?

**Comment by gilbertohasnofb** [comment]
I don't know if I understand what you mean by blurred. The disk is always blurred isn't it? I think the problem is that the disk gets more and more transparent with the speed of the propeller (which is correct), but it should never get so transparent that it disappears completely. So basically I think we need somehow to set an upper limit for this.

**Comment by wlbragg** [comment]
OK

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/598
