### ISSUE TITLE
Problem with the tutorial involving the walker and also primer messages

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#439]
In our thread, Thorsten wrote:

> Gentlemen, it seems the C-172p has the walker added by default - and this now interferes with the tutorial system which starts in walker orbit view. Which is a problem, see [here](http://forum.flightgear.org/viewtopic.php?f=18&t=27044).

> I'm not in deep enough in tutorials and the walker to tell what component needs to be fixed or whether something easy can be done aircraft side, so I will cross-post this to the list, but please take a look.

> Also, there's recurring 'Use the primer!' messages when running a tutorial - unterminated Nasal script surviving the reset to a different location perhaps?

Can someone who has knowledge about these things have a look on these reports? Maybe @onox?

As for the milestone, I didn't add any (yet) as this could be fixed still during the FG 3.6 release candidates if I am not mistaken.

**Comment by gilbertohasnofb** [comment]
Further discussions. Thorsten wrote about fixing this for the FG 3.6 RC:
> The tutorial is a 'must-have' since the C-172p is the flight instruction bird of the sim - so either this can be fixed or the walker has to go, but something needs to be pushed to FGData, both 3.6 and 3.7 before the release.

@Juanvvc added:
> My guess is the tutorial is requesting a view index reserved for the walker. If a fix is not available soon, I understand the importance of the tutorials and removing the walker is quite easy: just remove the import in the beginning of the -set.xml file.

**Comment by gilbertohasnofb** [comment]
In the forum, DFaber posted a possible solution (which he also sent to the mailing list):

> I guess I found it. Please try commenting out line 782 in Aircraft/Generic/Human/Nasal/walk.nas. That fixed the Tutorial Problem for me.

**Comment by aplund** [comment]
I tried this out, and it does seem to help greatly.  Now getting a lot of "check the throttle" messages when the engine is meant to be started at the beginning of the tutorial.  But the view problem is now fixed.

PS which forum are you talking about?  I didn't see anything on this in http://forum.flightgear.org/viewtopic.php?f=18&t=27044

**Comment by gilbertohasnofb** [comment]
@aplund Nope, I meant our thread here: http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2250#p253586

**Comment by onox** [comment]
Can we consider this bug to be fixed? (by a commit in fgdata)

**Comment by gilbertohasnofb** [comment]
Has this been solved when @dg-505 made the modifications to the Tutorials or is this still a problem?

**Comment by aplund** [comment]
I have been using the beta version for a while now and I haven't had this crop up.  I think it is fixed.

**Comment by gilbertohasnofb** [comment]
@onox what do you think, shall we close this?

**Comment by onox** [comment]
You don't have to ask my permission for everything :stuck_out_tongue_winking_eye: Can you reproduce it yourself? I see in FGDATA that Thorsten added a small patch "Fix for walker/reposition interference suggested by DFaber" on 2015-08-10. So that may be the fix for this issue.

**Comment by gilbertohasnofb** [comment]
Ok, sorry.

**Comment by gilbertohasnofb** [comment]
I can't reproduce this so I am closing it.

**Comment by wlbragg** [comment]
>You don't have to ask my permission for everything :stuck_out_tongue_winking_eye:

Yes we do! :stuck_out_tongue_winking_eye:
