### ISSUE TITLE
3D Luggage

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#441]
* [x] clicking on the luggage door and opening it could also open the dialogue in which luggage can be added
* [x] similar to the passengers, we can add some very simple 3D luggage to that compartment in case the luggage weight is above a certain threshold

**Comment by legoboyvdlp** [comment]
Also, a canvas payload dialog similar to the Extra 500 one would be nice though totally not necessary!

**Comment by gilbertohasnofb** [comment]
Okay! So I created a branch `bug-441` and I implemented:

- clicking on the luggage door while it is closed also opens the Payload and Weight dialogue

And I can of course create textures for the 3D luggages if anyone volunteers to model them. Could be something __really__ simple.

**Comment by gilbertohasnofb** [comment]
Also, see #486 and #487

**Comment by onox** [comment]
> And I can of course create textures for the 3D luggages if anyone volunteers to model them. Could be something really simple.

I think one of the civilian helicopters (ec-130b I think) has luggage that you could use.

**Comment by gilbertohasnofb** [comment]
I will check it out. Do you think those pieces of luggage have their own .ac model file or do I need to extract them via Blender? Because if I need to extract them from the main model, that's a job that I'd need help with. I will check that tonight.

**Comment by onox** [comment]
I don't know. I can extract them from the main model if necessary.

**Comment by gilbertohasnofb** [comment]
I just checked and I believe the luggage belongs to the `ec130b4.ac` file, so can you give me a hand with this? If the luggage model is incorporated in ours, then I can do the conditionals of how much weight activates the 3D model. Also, if you'd like, you could add more than one piece of luggage with different labels, so that I can do something like this in the conditional: if the weight is between 0 and A nothing is shown, between A and B one piece of luggage is shown, between B and C two pieces, etc.

**Comment by onox** [comment]
I'll check it in a minute.

**Comment by onox** [comment]
I can't really find the luggage in `ec130b4.ac`.

**Comment by gilbertohasnofb** [comment]
I just opened the .ac file in a text editor and I found a lot of objects starting with `luggage`, but maybe that's related to the compartment then.

**Comment by onox** [comment]
Yes.

**Comment by onox** [comment]
I'm trying to find out how the luggage is triggered in Nasal, maybe that way I can find out the names of the objects.

**Comment by onox** [comment]
I cannot spawn luggage in FG. I can set luggage sliders, but nothing appears.

**Comment by gilbertohasnofb** [comment]
I tried the same and it also doesn't spawn to me. Are you sure the ec130 has them?

**Comment by onox** [comment]
No, I don't remember exactly which model had actual luggage.

**Comment by gilbertohasnofb** [comment]
Hmm. I also checked the ec135 and it also doesn't have any luggage.

**Comment by onox** [comment]
Argh! I can't remember :laughing: :sob: Maybe scan the wiki?

**Comment by gilbertohasnofb** [comment]
I just found that the dh6 has a single piece of luggage (not very pretty, but acceptable). We could add two instances of that model to ours.

**Comment by gilbertohasnofb** [comment]
It belongs to `Models/Cabin/cabin.ac` and I belive it's called "baggage". Then I would also have to copy its texture somewhere (probably top right corner of our interior.png) and then we apply it again. What do you say?

**Comment by gilbertohasnofb** [comment]
If you give me green light, I can prepare the texture in no time.

**Comment by onox** [comment]
`baggage` is just a container again I think.

**Comment by gilbertohasnofb** [comment]
I am not sure, but I checked in the sim and it does have a green baggage inside the compartment. And the texture for it is inside that folder, so I guess the model must be in that .ac file.

**Comment by onox** [comment]
I think you have to ask on the forum if there is a model which has some nice luggage objects :worried:

**Comment by gilbertohasnofb** [comment]
I imported it into Blender and I found out the problem: the luggage isn't a different object than the rest of the compartment! The whole thing is one gigantic 3D object, and the texture is applied in a certain way that makes us think those are two objects.

> I think you have to ask on the forum

I will do that.

**Comment by gilbertohasnofb** [comment]
What about these? They are all CC-BY-3.0:

http://www.blendswap.com/blends/view/66594
http://www.blendswap.com/blends/view/77871
http://www.blendswap.com/blends/view/72652

**Comment by onox** [comment]
We could use those, but the textures may need to be replaced because they the textures from elsewhere.

**Comment by gilbertohasnofb** [comment]
Actually those models are extremely hi-poly and full of detail, we really don't need that. I will ask in the forum then.

**Comment by onox** [comment]
You can just remove polygons.

**Comment by gilbertohasnofb** [comment]
I don't think it's that simple, there is just too much detail in general, not only too many vertices. Let's just see if someone recommends something interesting in the forum.

**Comment by gilbertohasnofb** [comment]
The Diamond-Da42 has four different luggages located at `Models/Interior/bagages`. I think that if I improve their texture a bit they could look decent enough.
