### ISSUE TITLE
bug in the straight-in landing tutorial

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#442]
Report by Thorsten:

> Would you kindly take another look at the in-air tutorial start (straight-in landing)?

> It seems the tutorial starts the engine in a weird state - throttle is set to go, but I needed to press 's' once to actually make RPM respond to it. It seems the starter is somehow still on and the tooltip cries for the primer, and after pressing 's' again I get a 'starter off' message and everything runs fine.

**Comment by gilbertohasnofb** [comment]
@Juanvvc @onox @wlbragg Guys, probably we should try to fix this during the RC period. Can any of you have a look at this?

**Comment by onox** [comment]
I did some testing a while ago; when I start the tutorial, the throttle is set to 40 % (like it should) but then quickly after that it gets restored to its persistent value (just like FG restores properties for you when you start FG normally). Also we set /controls/switches/starter to true which means the starter is on all the time, but it doesn't do the pre-autostart (turning on battery, avionics, etc.) if "complex" is on.

Does the property tree contain a property somewhere that indicates that there's a tutorial running _and_ does it have a property that tells in which phase the tutorial is? (the init phase)

**Comment by wlbragg** [comment]
Was working on this last night and I got it to take the primer = 4 using a prop set in init, which did get rid of the "use primer" But like you said, it then kept overriding whatever I used for throttle. I think your on the correct path, I think we need to figure out how to override the throttle.

**Comment by wlbragg** [comment]
Ran out of time to work on it last night, will pick it up this "late" afternoon.

**Comment by wlbragg** [comment]
I think I got it working correctly. Tthe following "set" items are all that was required. I tested it using "Complex Startup". Will push a to 3.7 in  a little bit.
~~xml
<init>
        <set>
            <property>/controls/flight/flaps</property>
            <value>0.0</value>
        </set>
        <set>
            <property>/controls/switches/magnetos</property>
            <value>3</value>
        </set>		
        <set>
            <property>/controls/switches/starter</property>
            <value>true</value>
        </set>
        <set>
            <property>/engines/active-engine/running</property>
            <value>true</value>
        </set>
		<set>
            <property>/controls/engines/engine/use-primer</property>
            <value>false</value>
		</set>
        <set>
            <property>/instrumentation/adf/frequencies/selected-khz</property>
            <value>340</value>
        </set>
        <set>
            <property>/environment/weather-scenario</property>
            <value>Fair weather</value>
        </set>
    </init>

**Comment by Juanvvc** [comment]
I don't know if we are on time for the 3.6 release or not. Unless this issue must be fixed as soon as possible (under days), I will be enhancing the tutorials and missions during these weeks.

**Comment by onox** [comment]
Let us first fix it for 3.7, after that we can decide whether to backport it to 3.6. Sounds OK?
