### ISSUE TITLE
Inverted scroll wheel command

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#444]
I see that the scroll wheel effect on instrument settings has been inverted.

Last logic is: when one pushes (move ~~upwards~~ forward) the scroll wheel, the values increases.
But for me, this direction is counter-intuitive, I preferred the initial one. I link **pulling** (~~downwards~~ backwards) the scroll wheel with turning a knob **rightwards** (clockwise). Thus, I expect the values to increase (radio frequencies, needle turning rightwards).
I admit that this is probably because I'm right-handed, when I look at my scroll wheel: pulling ~~downwards~~ backwards = turning rightwards.

Am I a rare example?

**Exception**: on every (real) altimeter I've seen, **turning the knob rightwards decreases** the indicated altitude and atmospheric pressure.

**Comment by gilbertohasnofb** [comment]
> when one pushes (move upwards)

I am confused with what you mean. Better use forwards and backwards, as a mouse wheel is normally in a levelled plane. Scrolling forwards seems like pushing to me (so that would increase the throttle for instance) while scrolling backwards feels like pulling (decreasing throttle).

**Comment by dany93** [comment]
You are right for the terms: I should have used forwards for pushing instead of upwards, backwards for pulling instead of downwards.
Sorry.

**Comment by gilbertohasnofb** [comment]
And so about knobs: pulling (moving backwards) the scroll wheel normally diminishes a value (think of scrolling a number field in some application), and therefore it should diminish the value of a knob (i.e., turn counter-clockwise). Pushing (forwards) increases a value, and so equals to turning a knob clockwise.

Is this the behaviour you have problems with?

**Comment by gilbertohasnofb** [comment]
Also:

> Exception: on every (real) altimeter I've seen, turning the knob rightwards decreases the indicated altitude and atmospheric pressure.

Did you test if our altimeter knob is inverted (regardless of the mouse wheel discussion)? If so, we should open an issue to fix it.

**Comment by dany93** [comment]
@gilbertohasnofb  wrote:
>Is this the behaviour you have problems with?

Yes.
I do not think firstly in terms of increasing or decreasing a number, but in terms of movement. With an autopilot, I expect pulling the scroll wheel will do a right turning (like by turning a knob clockwise).
From the same logic, on a radio I expect the frequencies to increase.

Notice that gedit or geany have this logic: when you enter a text line which is longer than the window you have access to the **right** side of your text with the horizontal slider, or by **pulling** your scroll wheel above this slider.

>Did you test if our altimeter knob is inverted?

It is not (which makes for me it is the only one with moves in the right direction!! :smile: )

**Comment by gilbertohasnofb** [comment]
@dany93 Well Dany, unless you are using your mouse sideways I really wouldn't argue in terms of clockwise or counter-clockwise. Also, as you yourself noticed, left handed people will see it inverted anyway (I am not one of them, by the way). 

I personally think that changing this behaviour would make it confusing to most people, to be honest. But let's see what the others in our team have to say about it.

> Did you test if our altimeter knob is inverted?

>> It is not (which makes for me it is the only one with moves in the right direction!!

Oh, so I am so sorry but I must open a new issue for it! So in the end they will be all (consistently) wrong to you :wink:

**Comment by onox** [comment]
I associate pulling with decreasing a value, so for me the current behavior is intuitive. But this is mostly a thing that should be configurable in FlightGear's generic configuration screens.

For now, you can try --prop:bool:/sim/mouse/invert-mouse-wheel=false

**Comment by dany93** [comment]
Thanks onox for your indication via the --prop.
But it was not only for me, it was also (and rather) in case other people would have the same preference.
