### ISSUE TITLE
Altimeter knob is inverted

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#445]
@dany93 wrote:

> on every (real) altimeter I've seen, turning the knob rightwards decreases the indicated altitude and atmospheric pressure.

Apparently ours is inverted, both regarding the animation as well as the mouse wheel movement.

**Comment by dany93** [comment]
I've seen this on 4 or 5 (real) Ultralight Aircraft.
Before inverting it, if someone on an aircraft can observe and confirm.... :question:

**Comment by onox** [comment]
Pulling the scroll wheel decreases the altimeter, so that's good I would say. We can change the animation though.

@tigert Do you know whether turning the knob clockwise increases or decreases the altimeter?

**Comment by tigert** [comment]
My gut feeling is that turning the knob clockwise adjusts the altimeter dial value higher - and the altimeter needle moves the opposite direction but I need to verify when I see a real aircraft.

I think the QNH setting is a compensation for the air pressure at the airfield, thus increasing the QNH makes the altimeter show a lower altitude.

Or maybe I am thinking this all backwards, I'll check this once I have slept the night :-)

**Comment by tigert** [comment]
Hm, I guess those instruments may vary too:

https://www.youtube.com/watch?v=X5cy03agfjQ

The logical thing for us to do is to increase QNH when you scroll "up" I guess.

Hmm. These seem to vary by instrument model and make. I guess it is a matter of how things are geared internally in the instrument. Also if you have a dual qnh scale (inHg and HPa) either scale is moving "backwards" no matter what. We should implement a dual-unit altimeter btw, thats something for the future to ponder about.

**Comment by gilbertohasnofb** [comment]
So in that case let's leave things as they are, okay?

**Comment by dany93** [comment]
The altimeters I've seen on Ultralights rather looked liked those from @tigert 's link.
https://www.youtube.com/watch?v=X5cy03agfjQ

Yes, it can be closed. Anyway, that's a minor issue.
