### ISSUE TITLE
Inconsistent damage reporting to user

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#453]
Not sure if this is worth mentioning but I noticed we popup pontoon and wing damage but not gear.

**Comment by gilbertohasnofb** [comment]
I think it is worth mentioning it indeed :+1:

**Comment by onox** [comment]
Do we really want to display tooltips for gear damage as well? I find it a bit annoying during landing, and it is noticeable/expected (during landing) anyway. (Although it's a bit inconsistent though when you don't have them for gear damage)

**Comment by wlbragg** [comment]
Yeah, I don't know. I just happened to notice it was inconsistent. It would be nice if there was a way to indicate damage without a popup or words, maybe a sound or something visual?

**Comment by wlbragg** [comment]
Thinking a bit more about this, if you broke a gear in RL I would imagine one of two "sound" events happening. A tire screeching or metal on pavement (or dirt) scraping. The screeching or sound should happen as long as WOW and groundspeed > 0. This might be the best way to notify the user of the event. Really the same hold true for wing or tail scrap, damaging a wing could simply cause a louder wind signature (sound).

**Comment by onox** [comment]
> A tire screeching or metal on pavement (or dirt) scraping. The screeching or sound should happen as long as WOW and groundspeed > 0. This might be the best way to notify the user of the event.

Yeah, we should enable sounds for damaged gear

Do you still want tooltips for wing damage?

**Comment by gilbertohasnofb** [comment]
As for the sound, what about using the file `damage.wav` for the moment the gear collapses, and then I can create a loop with a scratching metal sound (see: http://freesound.org/people/machine_831/sounds/257302/ ) which should be played while broken, WOW and speed > 0?

**Comment by wlbragg** [comment]
>Do you still want to keep tooltips for wing damage?

I guess it depends on your logic about it. In RL you might hear a nasty sound and feel something (maybe even a pitch change) and you would have to get out of the aircraft and examine the gear (or whatever damage), no one is going to be there to tell you what the heck just happened. So I guess it really isn't completely necessary to notify textually of the event, especially in light of the sound event. One step more (if it wasn't too difficult to implement) would be to cause some "shudder" (like shaking or something).

@gilbertohasnofb , that's not any king of a sound I want to hear coming from any part of my aircraft :fearful: I think that would work well.

**Comment by gilbertohasnofb** [comment]
@wlbragg I would still change the sound a bit, but the idea is that after the gear collapses there will be a lot of metal scrapping the ground. I think I can transform that sound into something good, let me try here :smile:

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg just one thing, which branch is this one here?

**Comment by gilbertohasnofb** [comment]
I see that there was no work so far, only discussions, so I created a branch named `bug-453` and I pushed the new sound file to `/Sounds`. The file is called `scratch.wav`.

**Comment by wlbragg** [comment]
:+1:
