### ISSUE TITLE
landinglight2 object not visible in the landing light recess

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#458]
I can't figure out why the landinglight2 object is not visible in the landing light recess. It is visible in the damaged wing select animation.

I need another pair of eyes on this one.

**Comment by onox** [comment]
What's a landing light recess?

> It is visible in the damaged wing select animation.

Which animation exactly? There are many landinglight* objects it seems. Each of them being used in certain animations.

**Comment by wlbragg** [comment]
Look in the blend file, it is the object "landinglight2". I think it is meant to simulate the landing light bulb. It should be visible in the recessed cutout on the leading edge of the left wing, just past the strut.
Damage (not break) that wing and then it is visible. I know it was working when I was adding the damage because I specifically remember how much of a pain that extra little piece of plane damage was to position in all the damage configurations. Looking at the code, I don't see why it disappear.

**Comment by wlbragg** [comment]
I looked at this in depth and I have determined it is not suppose to be visible unless the light is on. So I'm closing this issue.
