### ISSUE TITLE
Convert splash screen font

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#459]
Convert font from all splash screens from Helvetica to Sans.

**Comment by onox** [comment]
Is there a particular reason for changing the font?

**Comment by gilbertohasnofb** [comment]
Yes: Helvetica is a proprietary font that costs money and therefore not many people have it. I think it's better to have a completely open font so that in the future anyone can modify these images without spending a penny.

**Comment by onox** [comment]
Have you tried the Roboto font?

**Comment by gilbertohasnofb** [comment]
Nope, I don't know it. Do you think that would be a better choice? Do you dislike the results with Sans?

**Comment by gilbertohasnofb** [comment]
The point about Sans is also that it normally comes with every Linux distribution making it a good choice for compatibility.

**Comment by onox** [comment]
I think this new "Sans" font is very basic and ugly. How about one of the fonts from http://blog.spoongraphics.co.uk/articles/20-high-quality-free-fonts-every-design-should-own ?

**Comment by onox** [comment]
This is the Roboto (v1.2) font: https://raw.githubusercontent.com/onox/CVN-70/master/splash1.png I get some small blue pixel artifacts though in Gimp. But that could be specific to my computer.

**Comment by gilbertohasnofb** [comment]
All right, I will convert them to Roboto and commit it back to the PR.

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by onox** [comment]
You have the new version of Roboto? :open_mouth: The dot on the 'i' is round in the new files.

**Comment by gilbertohasnofb** [comment]
I just downloaded it from their website, so I guess it's the newest version.

**Comment by onox** [comment]
Is it OK if I do a rebasing, to remove the second commit?

**Comment by gilbertohasnofb** [comment]
I don't know, what that will do exactly? If it's only for the sake of organization and nothing changes then go for it I guess.

**Comment by onox** [comment]
Just to keep the repository a bit smaller.

**Comment by gilbertohasnofb** [comment]
Sure, so go for it!

**Comment by onox** [comment]
Updated. You can do a `git pull --force`

**Comment by gilbertohasnofb** [comment]
Done it. Thanks a lot, @onox. Now if you can merge that PR we can close this branch.

**Comment by onox** [comment]
Let's wait if some of the other contributors like the font as well?

**Comment by gilbertohasnofb** [comment]
Sure, I just don't think it's that big of a deal. Plus, if two people already like it then I guess it can just be accepted. It's not as if we are tweaking the FDM :wink: But it's up to you.

**Comment by wlbragg** [comment]
It's wonderful! Now you have a quorum. :smile:

**Comment by TeXnicer** [comment]
Font-ideas:
Ubuntu-Font (https://www.youtube.com/watch?v=BG-Q7hTKCws)
TeX Gyre Font Collection: http://www.gust.org.pl/projects/e-foundry/tex-gyre/ (see em at: http://www.fontsquirrel.com/fonts/list/find_fonts?q[term]=tex+gyre&q[search_check]=Y)

**Comment by gilbertohasnofb** [comment]
@wlbragg cool! :smile: 

@TeXnicer these are very nice, I particularly like the Ubuntu-font, but I would still stick to the Roboto font

**Comment by gilbertohasnofb** [comment]
@onox I just couldn't contain myself and I created one more splash screen, what do you think? Would it be all right if I commit it? I just love that screenshot :smile: 

![1](http://s11.postimg.org/6rjp4v0xf/splash10.png)

**Comment by onox** [comment]
You can, but please edit `c172p-set.xml` in the same commit.

**Comment by gilbertohasnofb** [comment]
Sure, sorry about last time.

**Comment by gilbertohasnofb** [comment]
Hmm, I am having some troubles here. After doing a `git pull` on the `master` branch to ensure everything is up-to-date, I tried `git add -A`, `git commit -m "new splash screen no. 10"` and `git push`, for which I receive the following error:

```
Username for 'https://github.com': gilbertohasnofb
Password for 'https://gilbertohasnofb@github.com': 
To https://github.com/Juanvvc/c172p-detailed
 ! [rejected]        heat-air-refactor -> heat-air-refactor (non-fast-forward)
error: failed to push some refs to 'https://github.com/Juanvvc/c172p-detailed'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you did not intend to push that branch, you may want to
hint: specify branches to push or set the 'push.default' configuration variable
hint: to 'simple', 'current' or 'upstream' to push only the current branch.
```
Any ideas?

**Comment by onox** [comment]
You're in the `heat-air-refactor` branch?

**Comment by gilbertohasnofb** [comment]
No, I am in the `master` branch

**Comment by gilbertohasnofb** [comment]
I never even used the `heat-air-refactor` branch

**Comment by onox** [comment]
What does `git status` say?

**Comment by gilbertohasnofb** [comment]
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

Apparently my commit did go through, but I don't get the reason for that error message.

**Comment by onox** [comment]
And you did just `git push` without any arguments?

**Comment by gilbertohasnofb** [comment]
Yep.

**Comment by onox** [comment]
What does `git branch` say?

**Comment by gilbertohasnofb** [comment]
It says I am in the `master` branch (I always check before committing). Here is the whole history:

```
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git pull
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 30 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (30/30), done.
From https://github.com/Juanvvc/c172p-detailed
   1d6d732..446f3be  master     -> origin/master
 * [new branch]      cleanup    -> origin/cleanup
Updating 1d6d732..446f3be
Fast-forward
 Models/Effects/interior/c172p-interior-light.eff | 10 ++++++++++
 Models/c172p.xml                                 | 12 ++++++++++++
 c172p.xml                                        |  2 +-
 3 files changed, 23 insertions(+), 1 deletion(-)
 create mode 100644 Models/Effects/interior/c172p-interior-light.eff
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git add -A
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git commit -m "new splash screen no. 10"
[master 0a1a38e] new splash screen no. 10
 2 files changed, 1 insertion(+)
 create mode 100644 splash10.png
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behaviour now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': gilbertohasnofb
Password for 'https://gilbertohasnofb@github.com': 
Counting objects: 21, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 774.37 KiB | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
To https://github.com/Juanvvc/c172p-detailed
   446f3be..0a1a38e  master -> master
 ! [rejected]        heat-air-refactor -> heat-air-refactor (non-fast-forward)
error: failed to push some refs to 'https://github.com/Juanvvc/c172p-detailed'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you did not intend to push that branch, you may want to
hint: specify branches to push or set the 'push.default' configuration variable
hint: to 'simple', 'current' or 'upstream' to push only the current branch.
```

**Comment by gilbertohasnofb** [comment]
Apparently it's saying that the commit went to the `master` but  got rejected by the `heat-air-refactor`.

**Comment by onox** [comment]
I think you should set `push.default`. I have apparently set it to `simple` here.

**Comment by gilbertohasnofb** [comment]
Ok, I did `git config --global push.default simple`. Let's see how it will behave next time I try to push something. Thanks for the help, onox!

**Comment by onox** [comment]
Also, before you do `git add -A` and `git commit -m`, I suggest to run `git status` to verify the files that you're going to add and commit. I usually call `git commit` without the `-m` argument so that Git drops me into an editor and I can see the files that Git wants to commit.

**Comment by gilbertohasnofb** [comment]
Ok!
