### ISSUE TITLE
Volt-meter constantly at red line/max rather than in green area

### ISSUE THREAD

**Issue by TeXnicer** [Juanvvc/c172p-detailed#463]
![volt-max](https://cloud.githubusercontent.com/assets/15046612/10389399/63a07966-6e71-11e5-8476-809c4f744094.png)

During my test flight I discovered that the voltmeter continously peaks to the max. allowed value ~32V while the PT shows only 28.
So I guess it's about an animation forgotten/unlinked/wrong set up.

**Comment by gilbertohasnofb** [comment]
Thanks for the report, someone will have a look at this.

**Comment by legoboyvdlp** [comment]
I'd like to work on this, if someone could give me a hint to what folder the instrument sits in?

**Comment by wlbragg** [comment]
It's in c172p/Models/Interior/Panel/Instruments/BatteryGauge.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp I just played around with the values, this seems to fix the problem, can you please test it and confirm?

```
 <animation> 
  <type>rotate</type>
  <object-name>PtrR</object-name>
  <object-name>PtrTipR</object-name>
  <property>systems/electrical/volts</property>
  <interpolation>
   <entry><ind>0</ind><dep>2</dep></entry>
   <entry><ind>20</ind><dep>22</dep></entry>
   <entry><ind>30</ind><dep>41</dep></entry>
   <entry><ind>40</ind><dep>60</dep></entry>
  </interpolation>
  <axis> 
   <x>-1</x>
   <y>0</y>
   <z>0</z>
  </axis>
  <center>
   <x-m>0</x-m>
   <y-m>0.02</y-m>
   <z-m>0</z-m>  
  </center>
 </animation>   
```
