### ISSUE TITLE
Rearrange files on the tree

### ISSUE THREAD

**Issue by thevirtualfer** [Juanvvc/c172p-detailed#465]
I started testing some changes into the export script and need to edit each blend file one by one.

The temporary proposed result is under https:/github.com/thevirtualfer/c172p-detailed.git

The branch is "reorder".

The problem i see is that a lot of textures are in the Models/ folder, with blender files, etc, etc, etc.

Moved blender files to a proper folder, and the textures too.

I flyed and all appears ok, to me.

The README.txt inside Models/BlendFiles/ needs a review, because my english is really poor.

**Comment by onox** [comment]
Is this really necessary? The branch looks a bit chaotic.

Just for your information, you can move files in git with `git mv`.

You can clean up a branch by squashing / fixing up commits (meld multiple commits into one) via interactive rebasing. For example, `git rebase -i HEAD~4` if you want to edit the last 4 commits. You should do this first in a test repository (Create a new folder somewhere on your system and then do `git init`. Add and commit some random files and play with the repository). You can learn about interactive rebasing [here](https://www.atlassian.com/git/tutorials/merging-vs-rebasing/).

**Comment by onox** [comment]
Or make a backup of the new `.blend` files and put them in a new and clean branch. Whatever you find easier.

**Comment by thevirtualfer** [comment]
Oh, @Onox !

Thanks to the tuts.

By the way, it is only a proposal of file distribution, and not to be merged. 

I lost files, lost the entire tree, bogus a lot, etc, etc, etc.

It is not to be merged.

Thanks, bro.
