### ISSUE TITLE
check failures

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#47]
PRC08 - check failures
  Gilberto: tested all failures individually (all instruments, all systems, engine, flaps, etc.) and they all seem to work perfectly as expected. Maybe someone else would like to double check this before marking it as solved, but I guess it's all well here. But see some suggestions concerning failures on items PRC07, PRC10, PRC11 and PRC12

**Comment by gilbertohasnofb** [comment]
See also:
https://github.com/Juanvvc/c172p-detailed/issues/46
https://github.com/Juanvvc/c172p-detailed/issues/48
https://github.com/Juanvvc/c172p-detailed/issues/49
https://github.com/Juanvvc/c172p-detailed/issues/50

**Comment by onox** [comment]
We should use `FailureMgr` for failures.

**Comment by gilbertohasnofb** [comment]
> We should use FailureMgr for failures.

Can you explain to me what is `FailureMgr` and how do I use it? Then I assign this to myself and test it again (as I wrote in the description, I had tested all failures individually, but this was in the very beginning of this project)

**Comment by onox** [comment]
It's a framework to model failures. Read http://wiki.flightgear.org/Failure_Manager

**Comment by gilbertohasnofb** [comment]
I tested all instrumental and system failures via the menu in FlightGear and every single one of them seems to be working as expected. I just don't know exactly everything which is influenced by a vacuum and static system failures. And as for a pitot failure, does it only affect the airspeed indicator or some other instrument/system?

> It's a framework to model failures. Read http://wiki.flightgear.org/Failure_Manager

I am so sorry onox but this seems to be above my capacity :cry:

**Comment by gilbertohasnofb** [comment]
Okay, so after some research I found that:

- vacuum system failure: the vacuum gauge should read 0, and the affected instruments are the Attitude Indicator and the Heading Indicator, both of which will slowly start to process and behave erratically.
- static system failure: airspeed indicator, altimeter and vertical speed indicator become unreliable.
- pitot failure: airspeed indicator becomes unreliable.

All this is exactly how our plane behaved on the sim, so I'd say all the failures are working perfectly well. So if you want to check them using `FailreMgr`, go ahead @onox, but else we can close this as they seem to be fine.

**Comment by gilbertohasnofb** [comment]
Just one more comment: the System Failures dialogue show the following possible failures that do not concern out plane:

- Landing Gear
- Speedbrake
- Engine 2

Is there a way to omit these for our plane or this is hard coded in FG?

**Comment by onox** [comment]
I'm not sure. I think FlightGear currently already uses this `FailureMgr` framework, but it loads a compatibility script.

If you read http://wiki.flightgear.org/Failure_Manager#Roadmap, you see: "Replace the hardcoded dialogs with a dynamic one that reflects the set of supported failure modes."

**Comment by onox** [comment]
Btw, that little hook under the left wing, is that the pitot tube? We could fail that if the left wing brakes, for example.

**Comment by gilbertohasnofb** [comment]
Ok, so in that case we leave these dialogues as they are. As for testing the failures, would you like to do some more tests or should I close this issue after my results above?

> Btw, that little hook under the left wing, is that the pitot tube? We could fail that if the left wing brakes, for example.

Yep, that's the pitot tube. We could certainly fail it if the wing breaks, but a faulty airspeed indicator would be a minor problem for a pilot in that situation :wink:

**Comment by onox** [comment]
Yes, that's true :laughing:

**Comment by onox** [comment]
I have never used that failure dialogue, and I'm a bit tired now :sleepy:

**Comment by gilbertohasnofb** [comment]
No problems, onox. We can leave this issue opened then and you decide in the next days what you want to do.

**Comment by onox** [comment]
Well, you tested and concluded that the failures work, so this issue can be closed IMO.

**Comment by gilbertohasnofb** [comment]
Ok then!
