### ISSUE TITLE
Engine dies when changing landing gear type

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#470]
The landing gear types are separated into two groups: A) regular wheels, 26" and 31" bush wheels and B) pontoons, amphibian and skis.

If the engine is running and one tries to change the landing gear type from group A into another from group B, or vice-versa, the engine dies. If one changes the landing gear type within a same group, the engine keeps running.

This behaviour is inconsistent. I would propose to either let the engine keep running for any change, or kill the engine for all changes.

**Comment by onox** [comment]
Isn't this because the engine changes to 180hp when you switch to group B?

**Comment by gilbertohasnofb** [comment]
Does the engine changes automatically to 180hp? If so, that's likely the reason, I just didn't realise it. I will test it again.

**Comment by onox** [comment]
Yes, if you choose pontoons for example, it automatically switches the engine to 180hp. That's by design.

**Comment by gilbertohasnofb** [comment]
@onox yep, you are completely right. So no bug here.

**Comment by wlbragg** [comment]
Yeah, that's a feature :smile:

**Comment by gilbertohasnofb** [comment]
> Yeah, that's a feature :smile:

Yep, it completely makes sense to automatically change the engine for those types of landing gears :smile:

**Comment by wkitty42** [comment]
i guess this means that we should block changing gear types while in the air? either that or restrict changing them to only the ones in the current "class" so the engine does not get changed out while flying...
