### ISSUE TITLE
Add grain and lightmap effect to interior

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#472]
I think we need to get this added. I just added an implicit light map and it looks good. We may not need an explicit one unless we have a really good light person that wants to make a map.

Also the grainMap, I am not sure exactly how the grain texture is suppose to look so I asked Thorsten for the example he used in his documentation.His c172p example actually looked really good.

Here is the implicit lightmap effect.
![lmap](https://cloud.githubusercontent.com/assets/11069680/10714429/4f8c2670-7abd-11e5-9283-bf087d6e777d.jpg)

**Comment by wlbragg** [comment]
Same thing with a bit heavier lightmap setting and a quick and dirty grain effect.
Obviously we can do much better.
![gmap](https://cloud.githubusercontent.com/assets/11069680/10714545/de3f0366-7ac1-11e5-82ed-ef78ef7d371c.jpg)

**Comment by onox** [comment]
What about that irradiance map?

**Comment by gilbertohasnofb** [comment]
@wlbragg In the second picture, the interior texture is missing (note how the door is texturized, but not the other "walls").

**Comment by wlbragg** [comment]
@onox, the first picture is the Irradiance. It is only to additional lines of code, We can add that right now.

The second picture is using a grain overlay (and the Irradiance) on the "chassis" only, I hadn't applied it to the door yet.
I don't fully understand how to create the grain texture yet, in other words It isn't set correctly and it may not be made correctly. It should add detail to what is already there and in my case it basically replaced it (we can do much better).
