### ISSUE TITLE
Suggestion/Proposal: New splash screen(s)

### ISSUE THREAD

**Issue by dg-505** [Juanvvc/c172p-detailed#479]
Hi guys :smirk: 

here I've collected some of my screenshots of the C172P

If you think that ten splash screens are still not enough :stuck_out_tongue_winking_eye: , it would be a pleasure, if you could add the one or other of these pics to the splash screen collection.

![cessna 172p in swiss alps 2](https://cloud.githubusercontent.com/assets/12293276/10854587/eb0d3322-7f3c-11e5-96a8-3137827f7aad.png)
![cessna 172p in swiss alps 1](https://cloud.githubusercontent.com/assets/12293276/10854588/eb0eebea-7f3c-11e5-9306-02a17ac938b3.png)
![cessna 172p floats](https://cloud.githubusercontent.com/assets/12293276/10854589/eb123e1c-7f3c-11e5-9598-f61d218eddf8.png)
![cessna 172p in swiss alps 3](https://cloud.githubusercontent.com/assets/12293276/10854590/eb134cd0-7f3c-11e5-9688-8b5bcc9e4652.png)
![cessna 172p - cool sky](https://cloud.githubusercontent.com/assets/12293276/10854596/fa1fada4-7f3c-11e5-91f9-97007cedffdb.png)

And following Gilberto's request, they are 100 percent original...

**Comment by onox** [comment]
The painting looks heavily damaged :worried:

**Comment by dg-505** [comment]
> Otherwise we have 50 splash screens next year

Hehe, this could be :wink:

What do you mean with damaged? I've got an ATI Mobility Radeon HD5470 with 1GB VRAM in my Laptop. And my Hardware Manager says the drivers were up to date.
Nevertheless there are several issues with it like FlightGear crashes when setting the water shader to max, or the system crashes when combining ALS and Random trees. Well, I think it's high time for a new computer...

**Comment by gilbertohasnofb** [comment]
@dg-505 I think you are using texture compression (using fgrun, on the last page click on Advanced..., then Rendering then untick the option Texture Compression). It improves performance but makes textures look ugly, particularly from oblique angles (like when looking the fuselage from the back of the plane).

**Comment by dg-505** [comment]
Oh, I didn't know that. Thanks for the tip.

**Comment by onox** [comment]
I meant to say that it looked like your livery wasn't painted in over 20 years, but they are artifacts as @gilbertohasnofb said :smile: 

I'll close this issue as won't fix to indicate we have enough splash screens for now.

Anyway, we do have a lot of [new features to be implemented](https://github.com/Juanvvc/c172p-detailed/milestones/FlightGear%203.8%20feature%20freeze) and [bugs to be fixed](https://github.com/Juanvvc/c172p-detailed/milestones/FlightGear%203.8%20release). So choose an issue if you like :smiley:
