### ISSUE TITLE
Strange shadow of a line

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#482]
Yesterday I realized that there is some strange shadow of a line which si much darker than any other shadow in our cockpit. See:

![line](https://cloud.githubusercontent.com/assets/5700795/10868935/9948c75a-809e-11e5-9499-26984038b87a.jpg)

Is this a bug or a feature?

**Comment by dany93** [comment]
I wonder if this would not be a bug, same kind as https://github.com/Juanvvc/c172p-detailed/issues/428
ALS shadows in the cockpit are pleasant at first view, but I feel they are sometimes weird, not easily correlated with the upstream objects and the light source direction.

**Comment by gilbertohasnofb** [comment]
I don't know, Dany, but I don't think it's related to #428. This artifact appeared some short time ago and it's always present as far as I can tell.

I also think the ALS shadows in the cockpit are one of the most immersive effects we have, so if you spot something that is weird try telling @wlbragg about it so we can try to improve it. But IMO the effect is fantastic right now!

**Comment by wlbragg** [comment]
I'll see if I can at least figure out what it is that is causing it.

**Comment by gilbertohasnofb** [comment]
@wlbragg one more thing: it seems to appear when the sun is behind the plane

**Comment by dany93** [comment]
> I also think the ALS shadows in the cockpit are one of the most immersive effects we have,...
...IMO the effect is fantastic right now!

I agree. And I'm pleased with it, whatever.



> so if you spot something that is weird try telling @wlbragg about it so we can try to improve it.

Same place (LFML), same orientation (90 deg), same time (11:30).

**With Rembrandt:**
![rembrant-shadows-lfml](https://cloud.githubusercontent.com/assets/11994061/10869839/a4f2098c-80bb-11e5-8001-7a032d89ce9d.png)

**with ALS:**
![als-shadows--lfml](https://cloud.githubusercontent.com/assets/11994061/10869841/c0a340ce-80bb-11e5-8b67-9aa193155638.png)

Not a critic, I do not like criticizing when I cannot help to get a solution. So, thanks for the work done and the result, anyway.

**Comment by wlbragg** [comment]
Interesting @dany93, that could be my poor excuse of a cube map. Good comparison though to try to make it better.

I don't know if we are capable of getting the yoke to shadow like Rembrandt.
I think not, because we are only using images and not real objects, we just get solid/not solid (no 3d definition).

**Comment by dany93** [comment]
The yoke is subsidiary, but even the other shadows are not the same. I can't understand which object they come from (the sun is from the right side). *On this image*, it looks like a mirror effect of the upright (window frame above). ???

**Comment by onox** [comment]
They come from `Models/Effects/interior/black_*.png`. See `c172p-interior.eff` in that folder. Rembrandt does deferred rendering, meaning it does geometry and lighting (shadows) in separate passes. This allows it to process arbitrary amounts of lights. Having said that, deferred rendering also has its share of problems (needs lots of bandwidth + no hardware anti-aliasing). But in FG we only have (usually) one light source (the sun) and you can limit the number of objects for which it needs to compute the lighting to just aircraft itself. So I guess (but I don't know that much about this topic) we could have realistic lighting in a forward renderer (basic or ALS) as well. There are also new techniques like clustered forward rendering which allows many lights in a forward renderer.

**Comment by gilbertohasnofb** [comment]
> So I guess (but I don't know that much about this topic) we could have realistic lighting in a forward renderer (basic or ALS) as well.

Gosh, that would be cool! I have always been so jealous of the shadows of Rembrandt.

**Comment by onox** [comment]
Yes, but in a standard forward renderer it would be more limited. Just for the sun, not for other light sources.

**Comment by gilbertohasnofb** [comment]
I understand that, but as you pointed out in FG the most important light source is only the sun, so that could be a fair approach.

**Comment by wlbragg** [comment]
> but even the other shadows are not the same. I can't understand which object they come from (the sun is from the right side).

Again, this is possibly my poor attempt at a cube map. It could be I have the wrong layout. Although I thought I tested it enough to be reasonably sure it was correct.

**Comment by wlbragg** [comment]
I just pushed a new branch to correct the irradiance map addition which broke the interior shadow. Please check it out and see if that cleared any of this issue up.

**Comment by dany93** [comment]
For this point https://github.com/Juanvvc/c172p-detailed/issues/482#issuecomment-152841480, I feel there is no difference. e.g., I can see the same image as above with ALS.
Identifying the objects cause of the shadows is uneasy and I am unsure to check correctly, double-checking by someone else would be better.

Anyway, as @gilbertohasnofb wrote in https://github.com/Juanvvc/c172p-detailed/issues/482#issuecomment-152834830
>I also think the ALS shadows in the cockpit are one of the most immersive effects we have,...

So, it is pleasant as long as one does not try to identify the objects...

**Comment by wlbragg** [comment]
I know the shadow cast from the back of the plane to the dashboard, when the sun is at the back of the aircraft is correct and identifiable. You can see the vertical and horizontal stabilizers shadow. Sun casting a shadow from either side also produces a representation of the side of the aircraft, perfectly, probably not.
I did have to somewhat identify what I was seeing when I added the cube. At the time I was OK with what I was seeing, that it was the correct cube element.
The change I just made was because I was using the same objects in two different effect code blocks I was getting what looked like the "outside" cube map. I could see shades of green, blue and white shadow being cast on the inside of the aircraft. At one point I even saw the ground and some trees reflecting on the interior chassis.
That might be cool on the glass but not the solid interior.
