### ISSUE TITLE
Opening doors and baggage door from outside

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#487]
Currently we don't have a 3D model for door handles for the main doors (from outside) nor for the baggage doors, and someone changed the area in which the pick animation can be activated. This makes it very tricky to open them from the exterior view! I'd suggest reimplementing the previous behaviour (whole doors activate pick animation) until we have a 3D model for the handles.

**Comment by legoboyvdlp** [comment]
Tested yesterday, works as expected, all seems good.
Thanks!

**Comment by wkitty42** [comment]
i am not seeing the baggage in the compartment... when i open the baggage door, the payload window does not appear... i can move the slider to 150 pounds and see the craft settle back but there's no baggage showing... i thought with #441 being merged this would be done but i also see #488? has it not been merged yet?  i have fa8c17d944239ea6b60c1fbb6d88670af1f26f88...

**Comment by wlbragg** [comment]
I'm having some issues also, what is really weird is it appears to be related to the view angle. Some angles everything works and other angles nothing works.

**Comment by onox** [comment]
I can confirm this. From some angles, you do get a different cursor and popup, but clicking does not execute the bindings. My guess is this is something in flightgear/simgear.

![fgfs-screen-302](https://cloud.githubusercontent.com/assets/3361585/11003297/e0e75434-84b1-11e5-83e8-0ed140d0d268.png)

**Comment by gilbertohasnofb** [comment]
it's not about angles, it's because you are below the ground! You can't click through an object :wink:

**Comment by gilbertohasnofb** [comment]
And therefore this is something to maybe solve with the core devs, not with our plane. I also would much prefer to be able to click on things even if the camera is below the ground.

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> I am not seeing the baggage in the compartment. When I open the baggage door, the payload window does not appear. I can move the slider to 150 pounds and see the craft settle back but there's no baggage showing.

Are you sure you are on master? The luggage is appearing just fine for me, is anyone else having troubles with that? If you are on master, can you please check if you get some error messages in the console when you add some 70 pounds of luggage (which should activate both black and brown pieces of luggage)?

**Comment by wlbragg** [comment]
Is that what it is, I'll be! You know I was thinking just the other day, the sim should have a "no clipping" or "clipping on" setting where you can't go below ground. That is a standard in many programs and I always wondered why we don't have the ability to limit the view to the "real flight sim world".

**Comment by gilbertohasnofb** [comment]
@wlbragg Yep, it also bothers me a lot. Some things are tricky to click, such as the baggage door and the tie downs. I am now working on implementing testing for fuel contamination, and that will require a hot spot below the wings, which will cause lots of headache for those who don't know about this ground limitation.

**Comment by onox** [comment]
> Some things are tricky to click

It may help to know you can always zoom in and out with the mouse scroll wheel in helicopter view.

**Comment by gilbertohasnofb** [comment]
But I think that zoom would still make the view point stay put below the ground, right? Zoom != moving forwards

**Comment by onox** [comment]
No, you actually move your camera position.

**Comment by onox** [comment]
![fgfs-screen-305](https://cloud.githubusercontent.com/assets/3361585/11007576/230537fa-84cb-11e5-9c85-e22b9b67f215.png)
![fgfs-screen-307](https://cloud.githubusercontent.com/assets/3361585/11007577/23075490-84cb-11e5-8a29-ee6a4ed72e4b.png)

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wkitty42** [comment]
@gilbertohasnofb yes, i'm absolutely sure i'm on master...

myuser@mymachine:~/myflightgear/c172p-detailed-dev$ git branch
* master
  regression-version-to-3.2
  release/3.6.0

however, i forgot that i wasn't flying out of that directory but had been copying the files to ~/myflightgear/Aircraft/c172p after updating them from the repo... no wonder i wasn't seeing what i was looking :disappointed:  :embarrassed:  :embarrassed:  :embarrassed: 

now i'm hearing the thunder when seeing the lightening... i'm able to see the pitot tube cover (but only one half of the dangling part shows), the skis, the luggage, the chocks, the tie downs (which are working GREAT in a nasty storm to keep the craft on the ground)... it is all there now...

yes, i've moved my local repo so that i'm now flying out of it instead of having to try to remember to copy the files over...

**Comment by gilbertohasnofb** [comment]
@wkitty42 Great, so no problem with those things then :smile:
