### ISSUE TITLE
Improve pitot tube cover model

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#492]
It could look like this:

![cover](http://airfactsjournal.com/files/2011/03/pitot-tube.jpg)

**Comment by onox** [comment]
@gilbertohasnofb Perhaps you could ask D-ECHO to adjust his model to be more like in the picture in https://github.com/Juanvvc/c172p-detailed/issues/492#issue-114692971?

**Comment by gilbertohasnofb** [comment]
I will ask him.

**Comment by gilbertohasnofb** [comment]
I sent him a PM, I will let you know once I get a reply.

**Comment by gilbertohasnofb** [comment]
He told me he will have a look at it.

**Comment by onox** [comment]
@gilbertohasnofb Did D-ECHO respond?

**Comment by gilbertohasnofb** [comment]
Not really. I will write him again.

**Comment by D-ECHO** [comment]
I've redone it:
[img]http://i.imgur.com/eLPD708.png[/img]

**Comment by gilbertohasnofb** [comment]
@D-ECHO looks very good, thanks for your work! But the very top of the red plastic (the pointy triangle in the top) seems to be missing the red texture.

**Comment by D-ECHO** [comment]
You mean the white top of the pitot tube?
Well, in your image, this part is also white...
;)

Am 10.01.2016 um 10:47 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
> You mean the white top of the pitot tube? 

Yep!

> Well, in your image, this part is also white... ;)

Well, I don't see it at all, do you mean this image here?

![](https://camo.githubusercontent.com/6841a175ce4a054fc4f3d31ede2c47ab507c9df0/687474703a2f2f61697266616374736a6f75726e616c2e636f6d2f66696c65732f323031312f30332f7069746f742d747562652e6a7067)

Looks all red to me...

**Comment by D-ECHO** [comment]
I mean this image:
https://camo.githubusercontent.com/6841a175ce4a054fc4f3d31ede2c47ab507c9df0/687474703a2f2f61697266616374736a6f75726e616c2e636f6d2f66696c65732f323031312f30332f7069746f742d747562652e6a7067
Just before the pitot meets the wing, there is a white part

Am 10.01.2016 um 11:10 schrieb Gilberto Agostinho:

**Comment by onox** [comment]
@D-ECHO I think @gilbertohasnofb meant this:

![687474703a2f2f692e696d6775722e636f6d2f654c50443730382e706e67](https://cloud.githubusercontent.com/assets/3361585/12221142/06d7ae28-b78e-11e5-9f03-40bfc1ba76d7.png)

**Comment by D-ECHO** [comment]
ah, okay, thanks, my mistake

**Comment by onox** [comment]
Also please put the pitot tube cover in a separate .blend file and position it at 0,0,0. We will set the offset in XML to position it correctly.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by D-ECHO** [comment]
Better like this? ;)

Am 10.01.2016 um 13:35 schrieb Gilberto Agostinho:

**Comment by onox** [comment]
Is there a picture or .blend file available somewhere?

**Comment by D-ECHO** [comment]
Hi, I've now exported it to .ac and changed the c172p.xml, so the rbf fits the pitot.
Where/How can I upload it?
![Pitot Tube](http://i.imgur.com/KXP2Tye.jpg)

**Comment by gilbertohasnofb** [comment]
Looks really good, @D-ECHO! Thanks for the work :+1: 

Do you know how to create a Pull Request (aka "PR") here on GitHub? If so, just create one and we will review and then merge your work.

If you do so, please note that we keep the `.blend` files separated in the `dev` folder, while the `.ac` file should go somewhere in the `/Models/Exterior` I suppose.

**Comment by D-ECHO** [comment]
Done

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/657
