### ISSUE TITLE
Add oil management, fuel contamination and securing aircraft to checklist and tutorial

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#493]
Add:
- pitot tube cover
- wheel chock
- wing tie-down strap
- oil management
- test for fuel contamination

To:

- [x] checklists
- [x] tutorials

**Comment by dg-505** [comment]
I'll do it.
Shall I also write a "Preflight Check" tutorial/checklist?

**Comment by gilbertohasnofb** [comment]
@dg-505 Thanks, that would be a great addition! But maybe it would be better if you wait just a bit longer to start working on this, because we have some new features concerning this coming in the next days: right now there is a PR waiting to be merged which will divide the tie-downs into two objects, then by today or tomorrow I will create a PR for the fuel inspection (water contamination), and hopefully in a couple of days at most I will have the oil management implemented. As soon as I have all this I will report here, how that sounds?

Some other things:

- when creating the tutorial, I'd recommend using the walker for pre-flight inspection
- we can adapt the 1982 POH for the checklist and tutorial, see pages 54-57 in the link: http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf
- I'd say we should also add this pre-flight checklist to our c172p wiki page, see: #437
- when all this is implemented, I plan to create a youtube video to post in our thread, as well as in the wiki page and newsletter, showing how this inspection could be done

**Comment by dg-505** [comment]
Sounds good. Nevertheless I'll start working, and when you add the new things, I'll ad them to the checklists/tutorial.

I had the same idea about the walker:
Checklist item:
`Name:Walker`
`Value:STEP OUT OF AIRCRAFT`

I'll take the original POH into account when creating the checklists. When the checklists are finished, I can add them to the wiki page. About the video: That's a very good idea!

**Comment by gilbertohasnofb** [comment]
Sounds perfect! Thanks a lot!

**Comment by gilbertohasnofb** [comment]
Updated title and description.

**Comment by dg-505** [comment]
For now I've added the first version of the Preflight Inspection checklist to my fork. I'll create a pull request when all checklists and tutorials are finished.
For those who want to test: It's enough to replace the c172-checklists.xml in your aircraft folder with the one from my fork. I already tested it, but I may have missed some things... Further testing is highly appreciated! :point_up::heavy_exclamation_mark::smile:

**Comment by gilbertohasnofb** [comment]
:+1: Great! I will have a look on it soon. Also, see this comment here: https://github.com/Juanvvc/c172p-detailed/issues/437#issuecomment-156854921

**Comment by dg-505** [comment]
Thanks!

**Comment by onox** [comment]
The `carb-heat` property was changed in the checklists.

**Comment by dg-505** [comment]
See #549

**Comment by dg-505** [comment]
If no one has objections, IMHO this can be closed. Or is there still something missing?

**Comment by gilbertohasnofb** [comment]
@dg-505 Sorry for using this page to contact you for something else than the c172p, but I don't have your e-mail address nor do I sue the forum any longer. Anyway, I wanted to ask you if you would be interested in implementing this for the c182 project: https://github.com/HHS81/c182/issues/121
