### ISSUE TITLE
Failed to open file at /Interior/Baggages/suitcase1.xml

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#494]
I'm not sure it this is something wrong on my end or what. I and getting this error in FGRun when I select the c172p.

**Comment by gilbertohasnofb** [comment]
I will check it now, maybe something went wrong with the manual merge.

**Comment by wlbragg** [comment]
looked at the files and they look like it is all there and spelled correct. I don't see anything in the sim either, no GUI about it. Did you add a GUI menu choice for it?

**Comment by gilbertohasnofb** [comment]
Hmm, I don't see any error. Are you sure your `master` branch is up-to-date? And if you open the baggage compartment and add weight, do you see two suitcases being added (one at 35 pounds and the other at 70 pounds of weight)?

**Comment by wlbragg** [comment]
Let me check.

**Comment by gilbertohasnofb** [comment]
When the error appears? I am also using `fgrun` and I see nothing.

> Did you add a GUI menu choice for it?

Nope. There is only a special baggage dialog which is opened when the baggage compartment door is opened.

**Comment by wlbragg** [comment]
Yeah, that works.

**Comment by wlbragg** [comment]
I meant for the chocks and pitot cover? I don't see any of that. Is that merged also?

**Comment by wlbragg** [comment]
Hold on, let me check something.

**Comment by gilbertohasnofb** [comment]
Yes, it is all merged already. I just checked using my `master`, tested again the pitot cover, chocks and baggage and I get no error messages nor any strange behaviour.

**Comment by wlbragg** [comment]
I'm doing a fresh clone now.

**Comment by wlbragg** [comment]
oops, wrong button

**Comment by gilbertohasnofb** [comment]
Ok, let me know how it goes. If you see no error any more then we can close this, else we troubleshoot

**Comment by wlbragg** [comment]
Well I'm loading the sim now, FGRun error is gone, so that is a good sign.

**Comment by wlbragg** [comment]
Sorry for the scare, it's all there! I guess my merge failed to pick it all up. Case closed, Good job!

**Comment by wlbragg** [comment]
Just out of curiosity, why no chocks for 26" and 36" wheels?

**Comment by gilbertohasnofb** [comment]
> Sorry for the scare, it's all there! 

No worries!

> why no chocks for 26" and 36" wheels?

We can implement them as well. The thing is that since the tires are larger, I'd have to create 4 other chock objects, and given how much trouble it was to get only a pair working I thought it was better to leave it for later, when everything is working. But also the chocks looked a bit funny with the gigantic tires IMO :smile:

**Comment by gilbertohasnofb** [comment]
See #495

**Comment by wkitty42** [comment]
we can use larger chocks for the larger wheels, right? :wink:

**Comment by gilbertohasnofb** [comment]
Sure, although the few images of bush planes with chocks I found have tiny chocks anyway, so maybe that wouldn't even be necessary:

![](http://www.bush-planes.com/images/468xNxCessna170PolishedMetal.jpg.pagespeed.ic.Ik03DrPKJ7.jpg)

**Comment by wlbragg** [comment]
Wow, they are small. I guess we need to see if the ones we have now would work as is without any re-positioning. I had big blocks of wood in mind, something you might see in the bush up in Alaska fish camp or something. Maybe I'll make some later and add it.

**Comment by gilbertohasnofb** [comment]
> we need to see if the ones we have now would work as is without any re-positioning.

I did that and they don't work at all. On top of that, even though both bush kits have the same size of front tire, the position of the blocks would have to be individual for them. 

> I had big blocks of wood in mind, something you might see in the bush up in Alaska fish camp or something. Maybe I'll make some later and add it.

That could be really cool! Some ideas as well:

![](http://shaunlunt.typepad.com/shootings/images/2007/07/25/img_811836.jpg)

![](http://www.sefco-export.com/chocks.jpg)

And I can make textures for you if you need.

**Comment by wlbragg** [comment]
OK, make textures for the bottom style and I'll make the models, no hurry, when ever you get time. If you can, make them look older and weathered! :smile:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg done, see `Models/Exterior/wooden-chock/wooden-chock.png` on `bug-303` branch and let me know if that suits you. Also, do you think you could give me a hand creating a 3D object for the tie-down strap? It's basically a single thin double-sided rectangle connecting the ground to the wing strut (something like a seatbelt):

![](https://upload.wikimedia.org/wikipedia/commons/1/1f/CAP_cadets_secure_a_Cessna_172_%28090317-F-2156C-003%29.jpg)

![](http://3.bp.blogspot.com/-aQdHQAHWbj4/VRjLDodqm-I/AAAAAAAAZk4/rIVfklvjsgU/s1600/MAR%2BHK%2B30-03-15%2BBen%2BPatterson.JPG)

**Comment by wlbragg** [comment]
Yeah, I can do that, give me a day or so.

**Comment by gilbertohasnofb** [comment]
Thanks a lot, and no rush! I will create a texture for it at `Models/Exterior/strap`, then you take your time for the 3D model. Once it's done, I can do the xml code :smile:

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg I uploaded the texture for the strap as `Models/Exterior/strap/strap.png` in the same branch (`bug-303`). What I had in mind is something like this:

![](http://store.ceebaileys.com/v/vspfiles/photos/TIE%20DOWNS-4.jpg)

So more or less like a car seatbelt, with a black rectangle for adjustments and a metallic loop for connecting to the wing. 

Thanks a lot for the help!

**Comment by gilbertohasnofb** [comment]
A close up of yet another model:

![](http://www.sportys.com/media/catalog/product/9/6/9623_5.jpg)

**Comment by wkitty42** [comment]
i know i'm late and you guys are working fast on this but i wanted to add that most of the wheel chocks i see seem to be made out of 4x4 (inch) lumbar with the top corners trimmed off... like the small image in the above post by @gilbertohasnofb that has the one with the snow/ice chunks... i'm not sure what the military uses but they are also fairly large like the 4x4s... i'm sure, however, that there are various sizes used... especially if someone decides to make their own like they might do for their ground vehicle (aka car or truck) for chocking the wheels when they have the vehicle jacked up to repair a flat tire...
