### ISSUE TITLE
repair damage doesn't set craft to upright position...

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#497]
while testing the lightening and storm stuff, i came over to write issue #496... while i was doing that, i left the sim running... imagine my surprise when i heard the stall warning starting to buzz... so i switched back over to the sim task only to find myself flipped upside down on the tarmac... those winds were certainly strong!

since i couldn't flip the craft back over with the damage repair, i exited the sim before i thought about saving a flight tape... so i went back in and recreated the situation as best i could... KSFO in the second A1 parking space (as displayed in the --launcher)... set the weather to "stormy monday" at noon and waited... wow! those winds are strong!

i tried to attached the flight tape... but github doesn't accept that file type so here's a link to in in my dropbox... fast forward to about 8:13 and watch what happens :wink: 

https://www.dropbox.com/s/gen7jsy9hqv63dp/c172p-20151102-184840.fgtape?dl=0

just to reiterate, the issue is that damage repair doesn't set the craft back upright (and on the tarmac if that's possible since this flight tape shows the craft up on the wall of the terminal)... the first incident just flipped the craft over... it didn't blow it up on the wall like this flight tape shows...

**Comment by wlbragg** [comment]
This one will be fun, we talked about it a while back and I thought we had add an issue for it. I guess not, so now we have to figure this out. No guarantees this is possible, but we'll certainly take a look at it.
Yes, those storm winds are strong. It would make a great mission to have to try to fly from point A to point B in that kind of weather.

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/308
