### ISSUE TITLE
Allowing/disabling securing aircraft objects

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#498]
I think we need a general toggle to allow/disable the securing aircraft objects (chocks, pitot cover, tie-down strap), as suggested by @wkitty42 

We can either:

- tie this option to the complex startup procedures so that toggle becomes the "advanced user" toggle
- create a new toggle for it

What do you guys prefer, @onox, @wlbragg ? If the second option, can you help me come up with a label better than "Allow securing aircraft objects"?

**Comment by wkitty42** [comment]
On 11/03/2015 04:40 AM, Gilberto Agostinho wrote:
> I think we need a general toggle to allow/disable the securing aircraft objects
> (chocks, pitot cover, tie-down strap), as suggested by @wkitty42
>
> We can either:
>
>   * tie this option to the complex startup procedures so that toggle becomes the
>     "advanced user" toggle
>   * create a new toggle for it
>
> What do you guys prefer, @onox, @wlbragg? If the second option, can you help
> me come up with a label better than "Allow securing aircraft objects"?

how about just "secure the craft"? or maybe leave out "the" to shorten it 
further if needed? then when the yoke lock bar (or whatever that thing is 
called) is created, it can also be added to the same toggle group...

question: i'm on master and fully updated... i'm guessing that these chocks and 
pitot flag are not yet active? i don't see their hot spots showing up with 
CTRL-C and clicking the front tire and/or pitot don't do anything... wheel pants 
don't/won't get in the way of the chocks or the clicky hot spot, right?

**Comment by gilbertohasnofb** [comment]
> how about just "secure the craft"?

This has been discussed and I don't think it's a good thing. The idea is that those wanting to secure have to do it step by step, and the aircraft menu already have individual toggles for that. The point here is to add yet another toggle as a master bypass, that's all.

> i'm on master and fully updated... i'm guessing that these chocks and pitot flag are not yet active? i don't see their hot spots showing up

They are on master. The hot spot for chocks is the main wheel and for the pitot tube cover is, well, the pitot tube. Maybe try erasing your c172p.xml from `~/.fgfs/aircraft-data`

**Comment by wkitty42** [comment]
On 11/03/2015 05:51 AM, Gilberto Agostinho wrote:
>     how about just "secure the craft"?
>
> This has been discussed and I don't think it's a good thing.

hunh?? that's a suggestion for the short name for the menu item you asked about ;)

> The idea is that those wanting to secure have to do it step by step, and the
> aircraft menu already have individual toggles for that. The point here is to
> add yet another toggle as a master bypass, that's all.

right, yeah, i understand that... it "secure craft" is checked then they have to 
go do the steps... if it is unchecked then they are not necessary at all... like 
the damage check box, ya know?

>
>     i'm on master and fully updated... i'm guessing that these chocks and pitot
>     flag are not yet active? i don't see their hot spots showing up
>
> They are on master. The hot spot for chocks is the main wheel and for the pitot
> tube cover is, well, the pitot tube.

they don't have yellow hot spots yet, right?

> Maybe try erasing your c172p.xml from |~/.fgfs/aircraft-data|

hummm... ok... kinda hate losing my hobbs time again but i'll give it a try...

**Comment by gilbertohasnofb** [comment]
> hunh?? that's a suggestion for the short name for the menu item you asked about ;)

So then it's confusing, it sounds like "click here to secure the plane" instead of "click here to allow securing the plane"

> they don't have yellow hot spots yet, right?

They do and they should show up with Ctrl+C.

> hummm... ok... kinda hate losing my hobbs time again but i'll give it a try...

Well, you can probably edit your xml file manually then. Just save your hobbs data and then paste it back in the newly created one. That's the price to pay for using a craft in constant development.

**Comment by wkitty42** [comment]
On 11/03/2015 06:40 AM, Gilberto Agostinho wrote:
>     hunh?? that's a suggestion for the short name for the menu item you asked
>     about ;)
>
> So then it's confusing, it sounds like "click here to secure the plane" instead
> of "click here to allow securing the plane"

oh... well, i was seeing is as the box with the 'X' like damages... not a button 
to click to cause the action :)

>
>     they don't have yellow hot spots yet, right?
>
> They do and they should show up with Ctrl+C.

i'll look again...

>     hummm... ok... kinda hate losing my hobbs time again but i'll give it a try...
>
> Well, you can probably edit your xml file manually then. Just save your hobbs
> data and then paste it back in the newly created one. That's the price to pay
> for using a craft in constant development.

hahahaha... yeah, i missed saving it one time and lost a couple hundred hours... 
if i knew how the number was translated, i could set it to what it should be 
instead of starting over each time... it isn't anything all that big, anyway...

it would be nice to have separate hobbs meters for each variant [grin, duck & 
run for the hills] :lol:

alright! back to this issue instead of this topic drift :smile_cat:

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> yeah, i missed saving it one time and lost a couple hundred hours... if i knew how the number was translated, i could set it to what it should be instead of starting over each time...

look for this type of code exmapled below in your `~\.fgfs\aircraft-data\c172p.xml`, copy it somewhere and after you run FG again and a new xml file is created you replace the code back to it:

```
    <time>
      <hobbs>
        <engine type="double">425.7416666</engine>
        <engine n="1" type="double">114.8333333</engine>
      </hobbs>
    </time>
```

**Comment by wkitty42** [comment]
yeah, thanks... that's what i forgot to do that time i lost what i had...

**Comment by gilbertohasnofb** [comment]
Okay, this has been implemented in branch `bug-303` as a toggle "Allow securing aircraft". I think this makes it clear that the toggle doesn't secure the plane, only allows those items. I am closing this issue now, but if better suggestions for this label appear I can exchange it later, ok?

**Comment by onox** [comment]
@gilbertohasnofb About your xml question on the mailing list: use a table and put both `<text>` elements on the same row and column.

**Comment by gilbertohasnofb** [comment]
@onox thanks, I will try it later today!
