### ISSUE TITLE
Implement oil level management

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#499]
Implement oil level management (splitting issue from #303, which is getting too large already)

@Juanvvc wrote:

>You must check the oil level always, and refill about once out of ten flights. I don't know if flighgear implements engine failures if the oil lever is too low, or they must be simulated by the aircraft.

@tigert wrote:

> Oil amount is usually measured in "quarts" (imperial unit pretty close to a liter), minimum 6 in that engine I think (depends on engine size, so the 180hp might have a bigger oil sump, need to verify from the handbook). If you plan for a longer cross country trip, you want to up it close to 8, since the lycoming engine does eat something like a quart in every 10 hours. For this reason you have a bottle or two in the trunk, and if it is much below 7qt when you check you add one quart before the flight.

**Comment by gilbertohasnofb** [comment]
A couple of questions for you all:
- tigert writes that a 160HP eats about 1 quart every 10h. Can someone help me find the figure for the 180HP?
- tigert wrote that the capacity of a 160HP is about 8 quarts, minimal safe is 6 quarts. Are these figures the same for the 180 HP? Help please.
- what are the failures that low oil level can cause? A "simple" engine failure or something else as well?
- does the oil level influence the oil temperature as well or not really?
- does the oil level influence the oil pressure?

I am thinking about the following strategy:
- oil level will be a persistent property between sessions
- actually, make that two properties, one for the 160 HP and one for the 180 HP
- create a hotspot above the oil tank cap in the nose of the plane
- to avoid complications with the 3D model, I can create the oil tank cap via textures (using our overlay texture)
- clicking there would open a small dialog which shows you the oil level in a slider.
- you could then drag the slider to add or remove oil
- oil level goes constantly down if engine is running
- if oil level < threshold and engine is on => engine fails

What do you all think about this? @onox, @wlbragg, @dany93, any opinions?

**Comment by gilbertohasnofb** [comment]
Some more info I found of things to take into consideration:

> Oil pressure: After engine start the first and most important item to check is the oil pressure, it must register within 30 seconds (60 seconds when in cold to freezing conditions). 
> Low pressure [m]ay be caused by a low level [of oil]

**Comment by Juanvvc** [comment]
I agree with your strategy. Your last point (if oil level < threshold and engine is on => engine fails) it is going to be by far the most difficult to implement. I'd say lets focus on the other points and, once they are working, we can try to implement engine failure.

Regarding the oil cap, it is not really a cap but a small door. In any case, remember we can use a transparent/hidden object only to receive inputs from the user. Most gauge knobs are implemented like this. I think it is enough to define such an object in the starboard side of the engine and it could be much bigger than the real "door" for usability reasons.

http://www.weekendcfii.com/photos/c172preflt/C172_oil_dipstick.jpg
http://i.imgur.com/M2gXSLi.jpg

**Comment by gilbertohasnofb** [comment]
> Your last point (if oil level < threshold and engine is on => engine fails) is going to be by far the most difficult to implement. I'd say let's focus on the other points and, once they are working, we can try to implement engine failure.

Why do you think that would be difficult? Also, I think we should ideally have an engine coughing for some short time before completely failing, right?

>  In any case, remember we can use a transparent/hidden object only to receive inputs from the user.

Yeah, that's what I meant by "hotspot" :smile: But on top of that, I volunteer to redo the textures and add the door to the plane. I have always seen that door on top of the nose, never on the side and I don't know what the object circled in red in your second image is supposed to represent

**Comment by dany93** [comment]
Your strategy seems good.

Like every engine (cars included), low oil level can give:
- heating,
- oil pressure drop,
- jammed engine (broken).

To stop (kill) the engine, you can use the float chamber. But that will immediately stop the engine without make it cough. In fact, I would say that a jammed engine slows then stops without coughing.

**Comment by gilbertohasnofb** [comment]
So one more idea here:
- we can map the lowest point of the green arc in the oil pressure gauge to 6 quarts and the highest to 8 quarts. That way if the gauge is reading less (low oil pressure) it means there is too few oil inside
- after turning the engine on, there is a delay of the needle of the oil pressure that we need to take into account. Probably also taking into account temperature (I read that in regular weather one can wait up to 30s for the oil pressure to normalize, and in cold weather up to 60 seconds). Any ideas if these values are reasonable?

Finally, I will try to at least come up with some concrete pseudo-code for this, but it may be too much for my skills right now. I will give it a try, but at least I would like to gather some information here and make a concrete plan, so that if I am not able to do it alone, someone else can pick up the work. Sounds good?

**Comment by gilbertohasnofb** [comment]
> To stop (kill) the engine, you can use the float chamber. But that will immediately stop the engine without make it cough. In fact, I would say that a jammed engine slows then stops without coughing.

In that case, let's use the float chamber.

**Comment by dany93** [comment]
Now, since 160 and 180 hp engines, it seems that the property to use is
(see c172p/systems/fuel.xml)
`/engines/active-engine/killed = true`

**Comment by gilbertohasnofb** [comment]
Yes, I discovered that property already. Actually, my oil level management is starting to work well. I already created a dialog to control the oil level, and I can kill the engine if level < 6.0 quarts. Now I am trying to figure it out how to handle the oil consumption (I guess I will need Nasal for that).

**Comment by wkitty42** [comment]
On 11/03/2015 06:27 PM, Gilberto Agostinho wrote:
> Yes, I discovered that property already. Actually, my oil level management is
> starting to work well. I already created a dialog to control the oil level, and
> I can kill the engine if level < 6.0 quarts. Now I am trying to figure it out
> how to handle the oil consumption (I guess I will need Nasal for that).

you should be able to model it in the FDM with some sort of consumption 
formula... i would try to introduce some sort of randomness that maybe gets 
worse over the long run... that might include the hobbs runtime in the 
calculation... i suspect that a brand new engine would use very little oil in X 
hours of engine runtime... as that count of hours gets larger, then a bit more 
oil would be used as more and more runtime elapsed...

how often (hours of runtime) does a 160HP and 180HP engine need to be rebuilt?

it really is better to stay off of nasal scripting for everything possible... 
specifically because of the frame rate execution mentioned elsewhere 
previously... the trick is to understand the way to code it in xml so that the 
FDM can handle it properly :smile_cat:

**Comment by onox** [comment]
@gilbertohasnofb You can try to use a `<pid>` to control the amount of oil depending on the oil rate (how fast you lose oil). See `Systems/bushkit.xml` at the bottom. Use ki = 1 and set kp and kd to 0.

If you want to use the regular XML autopilot system, you can use an integrator filter:

```xml
<filter>
    <name>Oil Volume Integrator</name>
    <type>integrator</type>
    <gain>1.0</gain>
    <input>
        <property>/my/oil/rate</property>
    </input>
    <output>
        <property>/my/oil/volume</property>
    </output>
    <u_min>0.0</u_min>
    <u_max>8.0</u_max>
</filter>
```

I don't know how to reset the integrator to 0 though. Might need to ask JSBSim developers on the mailing list because @andgi would like to see it too for the hydrodynamics.

**Comment by gilbertohasnofb** [comment]
@onox Sounds good. I actually had it implemented and kind of working yesterday but using Nasal (I don't get why would using the Hobbs meter property outside Nasal would be any good idea given that the Hobbs function is a Nasal function!). I didn't create a new branch nor push because of those issues we were experiencing yesterday with the repo, so I was just playing around in another folder. Later today I will show you what I have, but your `<filter>` idea may be more interesting indeed.

**Comment by wkitty42** [comment]
On 11/04/2015 05:35 AM, Gilberto Agostinho wrote:
> @onox <https://github.com/onox> Sounds good. I actually had it implemented and
> kind of working yesterday but using Nasal (I don't get why would using the Hobbs
> meter property outside Nasal would be any good idea given that the Hobbs
> function is a Nasal function!).

i mentioned using the hobbs because it is the time that the engine has been 
running... the randomness i mentioned was because engines don't always use oil 
(and other fluids) at the same rate... i was also thinking, without actually 
looking, that you might have saved the hobbs in a property where it would be 
easily accessible to the FDM...

**Comment by tigert** [comment]
Okay, some references:

  * The 180HP upgrades for C172 generally use some variant of Lycoming O-360 engine. The Penn Yann Superhawk upgrade that was installed on OH-CTL uses a Lycoming 0-360-A4M engine  variant, I found an operating manual for the engine via google. Page 3-13 says the oil sump capacity is 8 quarts. Basically there is no real way to measure that for the pilot, as all you really see is the dipstick markings of "max" and "min".
    * http://www.aceflyingclub.com/manuals/lycoming-O360-A4M-operator-guide.pdf
    * This might be interesting reading when you think of implementing the maintenance / preflight stuff, as it contains some operational guidelines etc.

  * The C172P (the new "Skyhawk SP") that is 180HP from the factory has Lycoming IO-360-L2A which is fuel-injected, but otherwise more or less those engines are the same with differences in equipment and configuration. So I guess it's safe to use data from C172SP manual for our purposes. 
    * **MAX Oil 8qt**: Linked POH says sump capacity is 8 quarts and total oil capacity is 9 quarts (page 1-6)
      * I guess some oil is left in the engine covering the parts due to the viscosity and 8 quarts is what you'll find in the sump? In any case, for our use, I think it is safe to assume the max is 8 quarts. 
    * **MIN Oil 5qt, 8 for cross country flying**: The operating handbook page 4-10 (preflight check) says "Do not operate with less than five quarts. Fill to eight quarts for extended flight.
    * http://bvfs.net/uploads/files/N212BS_POH.pdf

**Comment by gilbertohasnofb** [comment]
@tigert Thanks for all the info!

**Comment by onox** [comment]
>  the randomness I mentioned was because engines don't always use oil (and other fluids) at the same rate.

[JSBSim](http://jsbsim.sourceforge.net/JSBSim/classJSBSim_1_1FGFunction.html) has `<random>` (gaussian) and `<urandom>` (uniform) that you can use in functions.

**Comment by gilbertohasnofb** [comment]
My first attempts do not use randomness, but the RPM affects the oil consumption. This should give a "random" feel for the consumption rate within a certain margin.

**Comment by dany93** [comment]
My opinion is that it is sufficient.
I feel that no aircraft in FG has gone so far in the details towards realism.

**Comment by legoboyvdlp** [comment]
Another thing to consider is that oil can be contaminated; ie, if it is anything like my Dad's car, it should be changed every so often.
Thoughts?

**Comment by Juanvvc** [comment]
Oil must be changed often, but I think this is a task for the regular (and mandatory) inspections done by professional engineers.

I believe changing oil or performing a regular inspection is something that must be simulated by a virtual airline company and not the aircraft.

**Comment by onox** [comment]
[This YouTube video](https://www.youtube.com/watch?v=dqCqHlAn3b0&t=303) shows how the oil cap moves.

**Comment by gilbertohasnofb** [comment]
I think that oil contamination is waaaay too specific already. Also, exchanging oil is something beyond what I planed, I just want to implement a simple pre-flight inspection. What I did so far (and I will push soon) is:

- oil is consumed if engine is on, RPM affects its (so it's not constant)
- if oil less then a threshold, engine fails
- created a dialog to check and refill oil

I think that's pretty much it, it's just a matter of refining the code now. I will push this to a new branch soon so you can all comment the code, but today I won't have time for that

**Comment by gilbertohasnofb** [comment]
@onox that would be a 3D model issue, but I think that for now I will just create a hotspot above the normal map oil cap.

**Comment by onox** [comment]
Yes, we should leave the 3D modeling of the oil cap to @thevirtualfer.

**Comment by gilbertohasnofb** [comment]
Okay, so I started working on this on a branch called `oil-management`, where a first implementation is already pushed. @wlbragg similarly to what happened to the fuel tank sumps, the oil door is not displaying the yellow contour when I hit Ctrl+C. Could you please have a look on it using this branch and try to fix it? You don't have to worry about any kind of conflicts with what I am doing because I won't touch the `.ac` nor the `.blend` models myself.

**Comment by wlbragg** [comment]
OK

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by wlbragg** [comment]
It's done. Sorry for the delay.

**Comment by gilbertohasnofb** [comment]
No worries, thanks a lot!
