### ISSUE TITLE
Move normal map files from /Model/Liveries to /Model

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#502]
I think we should move normal map files from `/Model/Liveries` to `/Model` as that makes much more sense. The files are:

`fuselage-normal.png`
`tail-normal.png`
`wing-normal.png`

**Comment by wlbragg** [comment]
I'm OK with it.

**Comment by gilbertohasnofb** [comment]
The thing is that just moving won't work, we have to check all the paths. Do you know which files need the path for those pngs? Does the .ac model need them?

**Comment by wlbragg** [comment]
I don't think the .ac needs them. I can do a search with notepad++ to see what files call them.

**Comment by gilbertohasnofb** [comment]
I forgot that the .ac file is actually a textfile and can be searched! So don't bother, I can take care of that

**Comment by gilbertohasnofb** [comment]
It's only the `bumpspec-*.eff` files. I will fix them now.

**Comment by gilbertohasnofb** [comment]
@wlbragg But before I do that, just for the sake of simplicity, could you please have a look and merge the PR https://github.com/Juanvvc/c172p-detailed/pull/501 as it also affects the normal map?
