### ISSUE TITLE
Simulate fuel contamination by water

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#504]
Simulate fuel contamination by water and how it affects the engine.

Split from #303.

**Comment by Juanvvc** [comment]
This is a very unlikely event: I've never found water in the fuel deposits after about 150 flights. You must check always if there is some water in the deposit, of course, but I think this issue must be of a very, very low priority for the project :)

If you want to educate pilots, we can define a hotspot on the valve. If the user clicks on the valve, a message will appear on the screen "Fuel tank checked: no water"

**Comment by gilbertohasnofb** [comment]
> This is a very unlikely event: I've never found water in the fuel deposits after about 150 flights.

I was thinking about trying to find how unlikely it is and trying to randomize it around that chance. And then if the fuel is contaminated, just clicking on a button would fix it. But if it is really that unlikely then maybe I'd focus on other stuff. Nevertheless, I am reading about it now and then I will see, as if I do get the a reasonable value for the chance of contamination, it would be very easy to implement anyway

> As a first approach and if you want to educate pilots, we can define a hotspot on the valve. If the user clicks on the valve, a message will appear on the screen "Fuel tank checked: no water"

That's kind of cool :smile: I think I will work on that

**Comment by gilbertohasnofb** [comment]
@Juanvvc little question: if contamination is detected, what is the procedure to follow?

**Comment by gilbertohasnofb** [comment]
Also, one more question ludo: from which places under the wings can one take fuel samples? How many holes on which wing for this?

**Comment by Juanvvc** [comment]
To detect water in the tanks, you get a sample of the liquid inside the tank (about 50ml). If it is blue, then it is all fuel. If it is transparent, then there is water at the bottom of the tank. Remember water is more dense than fuel and it goes to the bottom. If you get water, you just continue draining the tank until you get a blue liquid.

There are many draining valves at the bottom of the wings and engine. Check this video: https://www.youtube.com/watch?v=dqCqHlAn3b0 (minute 8:50) In the video, they say you must get samples from all the valves but I sincerely think that is too much trouble... at least, in an aircraft that flies frequently. I guess if an aircraft is landed for a long time, a big amount of water condensation in the tanks is much more likely. The valves in the wings allow checking for water in the fuel tanks, and the valves in the engine are for checking the carburetor.

**Comment by onox** [comment]
Even though unlikely, I think this is still a cool (low priority) feature :smile:

**Comment by gilbertohasnofb** [comment]
I am already working on a simple implementation of this and it's looking kind of cool (I am pushing it to a new branch very soon), but could you guys help me with an educated guess of how often should water be observed? 1 in 100 flights? 1 in 200 flights?

**Comment by gilbertohasnofb** [comment]
Hey guys,

So I started implementing this on branch `bug-504`, and although I am practically done I need some help creating the hotspots for the fuel sumps. I would like to have two distinct hotspots named `LeftSumpHotSpot` and `RightSumpHotSpot` right below each wing:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/11021369/79ac30ca-863f-11e5-95e4-1de61b1a48e1.png)

@wlbragg do you think you could give me a hand with this? If so, be generous with the size of the hotspots as they are already below the wing and we don't want to make this too much awkward.

Then for testing, one can raise the chance of contamination at `/Nasal/c172p.nas`, line 48, or set the contamination for each fuel tank separately using the properties `/consumables/fuel/tank[0]/water-contamination` and `/consumables/fuel/tank[1]/water-contamination`. If either of them is higher than 0.0, the engine won't start. Currently the chance is of contamination is 1 in 100, but for testing one can exchange that line 48 line for something like this, which should give a 90% of chance of contamination:

```
if ((getprop("/consumables/fuel/contamination_allowed")) and (chance < 0.9)) {
```

So as soon as the hotspots are ready, this is ready to be made into a PR and testing :smile:

**Comment by gilbertohasnofb** [comment]
And while you are at it, would you be able to already create a new hot spot just above the oil door in the nose? The oil door is now visible in the normal map in case you need to see where it is.

**Comment by gilbertohasnofb** [comment]
Something like this:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/11029732/3d1d63b0-86c9-11e5-9f24-6e030cb3bb64.png)

**Comment by wlbragg** [comment]
I'm on it!

**Comment by gilbertohasnofb** [comment]
Thank you so much!!

**Comment by wlbragg** [comment]
Sorry, I have to finish the LeftSumpHotSpot and RightSumpHotSpot later (a couple hours) but the OilDoorHotSpot is pushed.

**Comment by gilbertohasnofb** [comment]
Okay! Thanks :+1:

**Comment by wlbragg** [comment]
https://github.com/Juanvvc/c172p-detailed/tree/bug-504

**Comment by wlbragg** [comment]
SumpHotSpotLeft and SumpHotSpotRight are done. I named them starting with Sump to keep them together in Blender. I hope that doesn't mess you up!

**Comment by gilbertohasnofb** [comment]
No problems at all, thanks for the work! I will make a PR for the water contamination in some minutes and then start to work on the oil management :smile:

**Comment by wlbragg** [comment]
I'm not sure about the the order of merging some of these bug fix pr's. I say this because in this particular case the pr contains the "still joined" version of the tiedownhotspots. Just beware when you finally do merge that this pr still has them joined. They are separate in the other pr (#528).

**Comment by gilbertohasnofb** [comment]
Yeah, I am aware of that, it will need to be manually merged. That's not a problem from the point of view of the `.xml` files, but I have no clue how that works for the `.ac` and `.blend. files. I will ask onox about it.

**Comment by wlbragg** [comment]
I can easily bring over the blend changes from #528 to to this on and push if you wold like me to.
Is so just let me know when and I will pull any changes you've made and append the changes from the other blend to this one and push it back.

**Comment by gilbertohasnofb** [comment]
> I can easily bring over the blend changes from #528 to to this one and push if you would like me to.

Yes, please do that. Then I will cancel that PR for the tie-downs and I will create a single PR for all of this. So if you can take care of the `.blend` and `.ac` files, I can take rest of the rest.

**Comment by wlbragg** [comment]
OK, I'll do it now. I'm just bringing over the split  tiedowns to this pr, correct?

**Comment by gilbertohasnofb** [comment]
Yep, it's just the split tiedowns (and their hotspots). Then there is some xml code which I will do it myself. I am going to push some modifications to that branch now (only xml stuff), then I will wait for you in order to start the manual merge, ok?

**Comment by gilbertohasnofb** [comment]
Done. So just do a `git pull` and let me know once you push the modifications. Thank you so much for all the help!

**Comment by wlbragg** [comment]
OK, done!

**Comment by gilbertohasnofb** [comment]
:smile: :+1: :airplane:

**Comment by gilbertohasnofb** [comment]
@wlbragg I finished the manual merge and we are almost ready to go, but there is just one little thing I am still unhappy with: when I press Ctrl+C, I can't see the hotspots for the sumps. I believe they are "inside" the wing. Would it be too much trouble for you to bring them a little bit down, so that Ctrl+C show them? After that, we are ready for a PR :smile:

**Comment by Juanvvc** [comment]
We already have may sources for an engine failure: lack of fuel, water in the deposits, oil management... Emergency procedures says that (after controlling the aircraft, identifying a field suitable for an emergency landing and with enough altitude), you must try restarting the engine. There is going to be a similar situation if, just for the laughs or for training purposes, you switch the engine off and then you try to switch the engine on again.

I believe the current state of the logic to start the engine does not consider a hot-engine situation, only normal start-ups.

If the engine is hot, it means it was used not long ago and (1) using the primer could flood the engine and it must be avoided and (2) there is no time for water to condensate in the tanks.

I agree we can consider only normal start-ups at the moment, but if we get seriously on engine failures we must take this into account.

**Comment by gilbertohasnofb** [comment]
@Juanvvc for now, at least, any presence of water in the fuel will force the engine to shut down, regardless of the quantity. Since the water quantity in the fuel tanks is randomly created at start up, this means it will never happen mid-flight. I would love to implement this in a different way though: instead of causing an engine failure, a quantity of water in the tank (currently ranging from 0.0 to 1.0, no units) would be equivalent to leaning the mixture. So if you have just a bit of water, the engine will feel weaker, but still work. I tried checking some properties for that but I couldn't find (yet) a solution, and I decided to go ahead with a simpler first implementation so that this branch do not get too much behind and require too much manual merging. Also, creating a non-random algorithm for the water in the tanks is a bit tricky, as it depends not only in the humidity but also in the _variation_ of temperature (for instance, an aircraft stored in a hot hangar then moved to a cold outdoors), but when loading the sim we don't have a "previous cold night". I think that the random attribution is fair enough though.

As you say, in the future we can look on what to improve on these things. Same will go for the oil management: oil is consumed at a rate depending only on RPM, and when the oil quantity is below a threshold the engine simply fails, no coughing. Later we can fancy this up, and I would appreciate all the input you may have :smile:

**Comment by wlbragg** [comment]
I just saw this. I'm pretty sure they aren't in the wings. But I will look at it now and see if I can get them to show up.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
@gilbertohasnofb, am I to use master and make a new branch to fix this?

**Comment by wlbragg** [comment]
There are issues with these. I'm not sure how you want to resolve it?
First, this shot shows it is not hidden in the wing. Left wing I moved down, right wing is how it is originally, it can be seen at just the right angle.
![fgfs-screen-002](https://cloud.githubusercontent.com/assets/11069680/11046523/91ac015a-86f3-11e5-8e89-8c67d20d0506.png)
Next, because I moved it down you can see it easier and from more angles.
![fgfs-screen-003](https://cloud.githubusercontent.com/assets/11069680/11046521/91a95be4-86f3-11e5-8d8d-820115b01f36.png)
But, shift it slightly and you still can't see it.
![fgfs-screen-004](https://cloud.githubusercontent.com/assets/11069680/11046522/91aa7ede-86f3-11e5-9258-22c427544531.png)
Thus, we still have issues. You still just want me to move it down?

**Comment by wlbragg** [comment]
![wtr4](https://cloud.githubusercontent.com/assets/11069680/11046872/406f808a-86f5-11e5-9174-a2dacd92ce4a.jpg)
Will this work?
I extruded flaps that hang down on the front and back edge.
Below, right side is the original position of the right wing hotspot which you could not see except for the "perfect" angle (because of the extruded flaps you can see it from virtually every angle). The left side is the "fixed" side that I moved down which still disappears at certain angles.
![wtr5](https://cloud.githubusercontent.com/assets/11069680/11046875/42471850-86f5-11e5-970c-f57ce2bc9f77.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg what about using a very thin cuboid instead of a plane? that might solve the issue:

![](http://res.cloudinary.com/dk-find-out/image/upload/q_80,w_960/cuboid_y2hgis.jpg)

Your solution above is fine (better than the original), but I think it might make not much sense of what it's supposed to represent.

And please use the branch `bug-504`.

**Comment by wlbragg** [comment]
bug-504 branch, right, I was looking at PR's and didn't see any.

OK but instead of a cube I think I will do it my way except inverted, so it is a cube without the top (because you can't see the top anyway), just like the ones over the tiedown hardware on the wings.

I can pull 504 now, fix and push?

**Comment by gilbertohasnofb** [comment]
> so it is a cube without the top

Sounds good!

> I can pull 504 now, fix and push?

Yep, I have no work to be committed, go ahead!

**Comment by gilbertohasnofb** [comment]
@wlbragg did you push it?

**Comment by wlbragg** [comment]
No, going in too many directions at the moment. Give me a sec, I'm checking something on it now.

**Comment by gilbertohasnofb** [comment]
Ok!

**Comment by wlbragg** [comment]
Sorry, I was trying to see what works best and the cube is much better so I am making them now, almost done.

**Comment by gilbertohasnofb** [comment]
No worries, take it easy. I actually have to go now, so I will test and make the PR in the morning.

**Comment by wlbragg** [comment]
OK, it's done, sorry for the delay. Maybe I should do the tiedown hardware hotspots under the wing the same way. They show up much better.

**Comment by gilbertohasnofb** [comment]
@wlbragg Very good job, thanks a lot!
