### ISSUE TITLE
Tutorials are currently not working. They crash the simulator

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#51]
TUT01 - Tutorials are currently not working. They crash the simulator

**Comment by onox** [comment]
@gilbertohasnofb Is this still valid? I tried most of the tutorials and they don't crash the simulator. Although the scenery of KHAF is broken because there's water on the runway.

**Comment by gilbertohasnofb** [comment]
Hi @onox, I don't know who reported this (came from that old TODO file we use to have). If you tested the tutorials and they run fine, then I guess we can close this. x
