### ISSUE TITLE
Problem with shadows on fuel selector and seats

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#514]
Problem with shadows on fuel selector and seats: they are completely untexturized when under shadows:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/10979740/84d770b0-83fe-11e5-8326-8fdcbf640360.png)

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/10979884/555bb4e4-83ff-11e5-9714-3e25e18df6bf.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg I think this is for you :wink:

**Comment by wlbragg** [comment]
When did that happen, arrrrrrggggg!

**Comment by gilbertohasnofb** [comment]
I don't know, but that's on `master` as well

**Comment by wlbragg** [comment]
OK, that is the radiance effect causing this, so I will remove it for the time being until I can figure this out.

**Comment by wlbragg** [comment]
OK pushed this fix and it should be a permanent fix and not just temporary.  Please test and see what you think. I don't think we can apply irradiance to certain objects that we also want shadows on. It was working but was too dark, maybe though some adjustments we can add more objects to the irradiance.

**Comment by wlbragg** [comment]
See #516

**Comment by wlbragg** [comment]
I'm out of here until later tonight.

**Comment by gilbertohasnofb** [comment]
I will check that PR straight away, thanks for the help! Today I am signing off early as well, and I will be travelling in the next days, but I think I will still have some free time for developing here :smile: Cheers!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/516
