### ISSUE TITLE
Amphibian pulling to the left on runway

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#515]
When using the amphibian variant on a runway (and gears down, of course), as soon as it starts to move it turns sharply to the left, regardless of any rudder input. This also happens regardless of the water rudder position.

**Comment by dany93** [comment]
As much as I understand, the nose wheels are free to rotate (360°). The rudder pedals have no action on them.
At *very* low airspeed, the only way to steer the amphibious on the runway is differential braking. But the air rudder quickly becomes efficient enough even at small airspeed to steer the aircraft with the rudder pedals.

**Comment by wlbragg** [comment]
So are you saying that what we are experiencing would be the correct, normal behavior?

**Comment by dany93** [comment]
I'd say yes, that's the normal behavior. Steering the front wheels with the pedals seems technically difficult.
But I do not not know at all this kind of aircraft IRL, better to have a connoisseur's opinion.

**Comment by gilbertohasnofb** [comment]
> At very low airspeed, the only way to steer the amphibious on the runway is differential braking.

That would explain it. 

> self-centering free-castering wheels

So does this means that after a little movement forward would make the nose wheel centred again?

**Comment by dany93** [comment]
No. I think that the spring is here to center the wheel when it leaves the ground, for flying. With a caster wheel, the main cause to center the wheel in forward movement is the movement itself.
But it may help a bit to limit the sidewards movement when the rudder is not efficient yet. Just a guess and I do not know if it is enough...
That would temper my response to @wlbragg's question:
>So are you saying that what we are experiencing would be the correct, normal behavior?

But I still think that the front wheels are free and you need differential braking to steer the aircraft at very low speed on the ground

**Comment by gilbertohasnofb** [comment]
> But I still think that the front wheels are free and you need differential braking to steer the aircraft at very low speed on the ground

That makes sense. So in that case, there is absolutely nothing wrong with this variant, and I'd say we can close this issue. Should we still ask for someone else's opinion or can we just go ahead and close this? Maybe @tigert can give his 2 cents as well.

**Comment by dany93** [comment]
Having no IRL knowledge of this, I'd prefer someone else's opinion.
I think that the behavior is qualitatively correct, only we can wonder about its steepness at start (very low speed). Anyway, it is easy to control.

That makes sense. I've practised an tricycle ultralight aircraft with a caster front wheel: steering was done by differential braking.

**Comment by wkitty42** [comment]
On 11/07/2015 04:50 AM, Gilberto Agostinho wrote:
>     But I still think that the front wheels are free and you need differential
>     braking to steer the aircraft at very low speed on the ground
>
> That makes sense. So in that case, there is absolutely nothing wrong with this
> variant, and I'd say we can close this issue. Should we still ask for someone
> else's opinion or can we just go ahead and close this? Maybe @tigert
> can give his 2 cents as well.

since i have fixed my directory structure and tested this again, it seems to be 
working... i don't know what revision i had been using but in that one the 
differential braking wasn't working... hitting one brake was like hitting both 
so you couldn't turn but it is all working now with the latest... i've been able 
to taxi all the way around KSFO from parking G95 (i think) to RWY 28R following 
AIs all the way... no problems...

even the bit of AIATC works ok as long as you stick to the exact procedure but 
push back can't be done with this craft so i just pivot in place using a brake 
and then follow the ground net from there ;)

**Comment by tigert** [comment]
What was the weather like?

I have no memory of extreme drift with the amphibious floats when flying, it is freely rotating front wheels, so braking will help like mentioned above, but I don'd remember any "turning abruptly to left" -beahvious either. It was all something that you need a bit of right rudder to correct, but nothing dramatic.

If it happens again in zero wind, then it might be something that the dev's are interested in.

**Comment by gilbertohasnofb** [comment]
The weather was good, no remarkable wind. Would you try the amphibian on fair weather and see what you think about the strength of the pull?

**Comment by onox** [comment]
I just tried it and it seems to depend on the wind direction.

**Comment by dany93** [comment]
I think that it is, at least partly, due to the propwash effect. It may be a bit too strong when the aircraft is almost stopped. With a tricycle aircraft, the nose wheel is there to counter it but on the amphibian the nose wheel is castered (free to rotate). At moderately higher speed, the rudder becomes efficient enough to counter it.
As far as I know, the propwash effect is hard-coded (I do not know neither how nor where) and it is globally correct.
Of course, a crosswind will add or subtract to this effect by weather-vane effect on the tail.

**Comment by onox** [comment]
Do we consider this a bug, a won'tfix or not a bug (invalid)?

**Comment by wlbragg** [comment]
I'm questioning why the amphibian is the only configuration that pulls so hard?

**Comment by dany93** [comment]
I keep my previous response:
>With a tricycle aircraft, the nose wheel is there to counter it but on the amphibian the nose wheel is castered (free to rotate)

Differently from a from a tricycle aircraft, the nose wheels have no directional effect. Only the rudder has one, from a moderate airspeed.
I do not know how the real one behaves. The tendency may be too strong at the very beginning of rolling, but considering this as a bug is too much.
Anyway, if it is too strong, I do not know what to do. A won'tfix? Unless someone else better than me has an idea...
The spiralling propwash effect is clearly a real one, always felt, very strong on some aircraft..

**Comment by wlbragg** [comment]
It took me reading it twice for it to sink in, I guess. That is sufficient enough for me to close this issue for now unless someone has proof or knowledge that is is too strong compared to RL.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@dany93 wrote:

> Anyway, if it is too strong, I do not know what to do. A won'tfix? Unless someone else better than me has an idea... Springs on the nose wheels which keep their rotating angle backwards?

@wlbragg wrote:

> That is sufficient enough for me to close this issue for now unless someone has proof or knowledge that is is too strong compared to RL.

I think this is enough to close this.
