### ISSUE TITLE
Issue with parking brakes and joysticks

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#517]
Reported by someguy in the forum:

> A problem with today's build: the parking brake no longer responds properly to my joystick button. Here's my joystick code, which has always worked with every aircraft:

```xml
        <button n="12">
           <desc>Parking Brake</desc>
           <binding>
              <command>nasal</command>
              <script>
                 brake = !getprop("/controls/gear/brake-parking");
                 setprop("/controls/gear/brake-parking", brake);
                 if (brake) {
                    gui.popupTip("Parking Brake ON");
                 } else {
                    gui.popupTip("Parking Brake OFF");
                 }
                 setprop("/controls/gear/brake-left", 0);
                 setprop("/controls/gear/brake-right", 0);
              </script>
           </binding>
        </button>
```

**Comment by gilbertohasnofb** [comment]
@onox

As you rightfully pointed out, today we got the first bug report about using the parking brake property for all the securing aircraft objects: someone's joystick button stopped to control to the parking brakes in our plane. See his code above.

Of course we could help him solve his particular issue by adapting the code above to also respond to our new parking brake property, but that's a very inelegant solution and we are bond to find more reports on this in the future. So I guess something must be done about it, but what?

I got two suggestions from the list today. Thorsten wrote:

> Not sure if JSBSim allows this, but you could try to null the rates by 
setting p, q and r explicitly to zero via a <switch> element if the 
property is active. Or only allow to switch the property on if the rates 
are below a certain value (in reality, you also need to wait for your 
aircraft to be at rest before getting out and tying it up...).
> 
> I think the most elegant way would be the external force - you can make 
them directly physical. Define a set of reference points on the aircraft 
and on the ground, make forces proportional to the difference between 
reference on aircraft and ground - the aircraft will be tied to a 
location. Add some force proportional to the derivative of the reference 
difference (a PID element will do this very nicely) and you get harmonic 
damping of the oscillations around the equilibrium position - all the 
dynamics a real strap will give you in probably less than 100 lines of 
xml.

His idea of using external forces to simulate a real strap is an overkill in my opinion, as this is just a tiny feature of our plane. But maybe using the `<switch>` he mentions could be an option, would you know how to implement it?

Another answer, this time by TeXnicer:

> a) Blocking tires is like giving them (almost) infinite friction.
b) tying down the wings is like having more gravity (or more mass) but 
it needs to be located in the center or balanced on each ground 
connection (aka gear)

I had tried playing around with friction, but somehow it didn't work out. We could have a look on it again though.

**Comment by onox** [comment]
I think an external force is the best solution, but it might be more work/time than anyone of us wants to do (PD tuning).

@gilbertohasnofb Shouldn't `controls.applyParkingBrake(1)` be called instead to toggle parking brake? Also, we're still using `/sim/model/c172p/brake-parking` in `controls.applyParkingBrake` in `Nasal/c172p.nas`. I wonder if it isn't better to extend the "Parking Brake And Chock" `<logic>` element in `Systems/ground-effects.xml`.

@dany93 Btw, is it possible to have points with configurable friction? I see in `Nasal/c172p.nas` that `/fdm/jsbsim/gear/unit[1]/broken` and `/fdm/jsbsim/gear/unit[2]/broken` are being (mis)used as parking brakes.

**Comment by onox** [comment]
@gilbertohasnofb Point someguy to `bug-517` branch.

Note: I think it's not very good that joystick files contain so much logic. This issue is another example that shows there's too much code assuming it can write to `/controls/gear/brake-parking` and other code assuming it can read from it again. But that's more a general problem that FG has.

**Comment by dany93** [comment]
@onox wrote:
>Btw, is it possible to have points with configurable friction? I see in Nasal/c172p.nas that /fdm/jsbsim/gear/unit[1]/broken and /fdm/jsbsim/gear/unit[2]/broken are being (mis)used as parking brakes.

I guess that you mean *contacts* with configurable friction.

Static and dynamic friction coefficients appear in `fdm/jsbsim/contact/unit[N)`
Which suggests that they should be configurable. But I've never done it. At first thought, the risk is of being immediately overwritten by the values given in the FDM, but @wlbragg did that well with the Z-values for the gears, contact type="BOGEY" (in physics.nas). I didn't know that we could do that.

**Comment by gilbertohasnofb** [comment]
someguy wrote in the forum:

> Nose dip = creeping forward on the runway, the aircraft pitches forward, compressing the front suspension. Using controls.applyParkingBrake(1) does not pull the cockpit brake handle out. In the prop browser, the parking brake conditiion blinks once from 0 to 1 for a fraction of a second, then back to 0. Like a short jab on the brakes.
> 
> Am I the only one who's seeing this? Have you guys tried binding one of the parking brake scripts to a button or key for testing on your own machines?

**Comment by onox** [comment]
> the parking brake conditiion blinks once from 0 to 1 for a fraction of a second, then back to 0

In that case something else is resetting the property back to 0. If he actually is using the latest `bug-517` branch, then it I guess it is a user configuration problem.
