### ISSUE TITLE
pitot tube cover can't be seen from the right

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#524]
I don't know how this happened but since yesterday night I noticed that part of the pitot tube cover can't be seen from its right side:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/11014862/a0ffce68-8548-11e5-8c4a-801d54a6d3f0.png)

From the left it's all good:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/11014866/b34b22c0-8548-11e5-944e-ff6c2e99fe6f.png)

I am sure that this wasn't the case when I first introduced this feature, as I was often adding and removing the cover from within the cockpit (i.e. right side of the tube). @onox @wlbragg do you guys have any idea what happened here?

**Comment by onox** [comment]
Either UV problem or mesh isn't double-sided.

**Comment by gilbertohasnofb** [comment]
> mesh isn't double-sided.

Can't be that because I didn't change the model (and I assume no one else did, what would be the point?) and I am 100% sure it was displayed properly before.

**Comment by onox** [comment]
I would say UV unwrapping problem then.

**Comment by gilbertohasnofb** [comment]
No, I don't know how to do that. This model isn't mine, I simply copied the .ac from another plane. But frankly anything related to the model itself doesn't make sense as the source of this problem, it was working before so if no one changed the .ac model then it should be fine, right? (at least that's what I think)

**Comment by onox** [comment]
Object looks ok in Blender.

**Comment by gilbertohasnofb** [comment]
Could it be because of the glass in the window?

**Comment by Juanvvc** [comment]
The model seems weird: there are two one side-planes, but they show the wrong face: the left plane shows the face to the right, and the right panel to the left. Maybe this arrangement confuses the glass shader.

**Comment by gilbertohasnofb** [comment]
Hmm, it's not related to the glass, that side of the cover isn't visible from the outside model either...

**Comment by onox** [comment]
It also happens in external view.

**Comment by gilbertohasnofb** [comment]
Exactly. So it seems to be related to the model itself, but how this happened is beyond me. Could any of you with Blender knowledge have a quick look at it? @Juanvvc said the model seems weird, so maybe we could try a quick fix of those faces?

**Comment by wkitty42** [comment]
On 11/07/2015 06:41 AM, Gilberto Agostinho wrote:
> Could it be because of the glass in the window?

i saw only the left side when i was in the heli view... when i circled to the 
right side, the right side of the dangling part was not shown... i don't see how 
glass would have any affect when one is in an external view like heli unless one 
is looking through the glass and i was not when i first mentioned the problem 
yesterday...

**Comment by gilbertohasnofb** [comment]
@wkitty42 Yep, see what we wrote before:

> Hmm, it's not related to the glass, that side of the cover isn't visible from the outside model either...

> It also happens in external view.

**Comment by wkitty42** [comment]
On 11/07/2015 06:50 AM, Gilberto Agostinho wrote:
> @wkitty42 Yep, see what we wrote before:
>
>     Hmm, it's not related to the glass, that side of the cover isn't visible
>     from the outside model either...
>
>     It also happens in external view.

yeah, i saw it after my post was sent from my email client :wink: just see mine 
as confirmation :smile_cat:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
Do those white dots mean there's no face?

![remove-before-flight-uv-problem](https://cloud.githubusercontent.com/assets/3361585/11015027/66cd7406-854e-11e5-960e-ff9f3ba63cc8.png)

**Comment by onox** [comment]
In Blender there's no UV white box on the texture for `Plane.001`.

**Comment by gilbertohasnofb** [comment]
So am I going crazy and the model wasn't ever displayed from the right side?? I honestly don't think so, but anyway... do you think you could try to fix that? Blender and I don't get along very well...

**Comment by onox** [comment]
I'll try to fix it this weekend.

**Comment by onox** [comment]
Also the normals are wrong as @Juanvvc already said.

**Comment by gilbertohasnofb** [comment]
Thanks @onox :+1:

**Comment by onox** [comment]
We should also shorten the cylinder a bit, I think it's too long for the pitot tube of the 172p.

**Comment by gilbertohasnofb** [comment]
Yeah, that would be great.

**Comment by wlbragg** [comment]
I've just finished this. Pushing now.

**Comment by gilbertohasnofb** [comment]
Oh, thank you! I will test and merge as soon as you do that

**Comment by wlbragg** [comment]
I basically redid it, I don't even know what was wrong. Nothing that made any sense. But I think this is good.
