### ISSUE TITLE
Improve wind sound

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#525]
Improve wind sound

**Comment by onox** [comment]
Not using 2:12 to 2:19 from https://www.youtube.com/watch?v=FsRwlr7RDkk because of https://github.com/Juanvvc/c172p-detailed/issues/329#issuecomment-154685886

**Comment by gilbertohasnofb** [comment]
What about this?: http://freesound.org/people/Zixem/sounds/69509/

**Comment by onox** [comment]
I'm going to be AFK for a few hours now, so I'll leave the decision up to you :wink:. Just temporarily replace `Sounds/wind.wav` to hear if it sounds OK in a loop.
