### ISSUE TITLE
Separate left and right tiedowns and their hotspots into different objects

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#528]
Separate left and right tiedowns and their hotspots into different objects

**Comment by gilbertohasnofb** [comment]
Almost done on branch `bug-528`, I just need help breaking the object `TiedownHotSpot` into two: `TiedownHotSpotRight` and `TiedownHotSpotLeft`. If it's not too much abuse already, @wlbragg could you have a look at this for me? I had managed to break the objects into two in Blender, but when I exported the `.ac` file the textures of a lot of objects were messed up (cockpit wouldn't change according to livery, baggage door belonged to D-EEQA, etc.).

**Comment by wlbragg** [comment]
No problem, I'll try to get it done tonight.

**Comment by wlbragg** [comment]
OK, should be good to go.

**Comment by gilbertohasnofb** [comment]
Thank you so much! :+1:

**Comment by wlbragg** [comment]
@gilbertohasnofb, is this at a point I can pull, fix and push?
