### ISSUE TITLE
the default's c172p FDM is rated at only 3 stars

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#53]
FDM01 - the default's c172p FDM is rated at only 3 stars. Any ideas on how to improve ths would be great!

**Comment by tigert** [comment]
The default one is not really bad at all either, could well be rated higher too? :-) Very subjective though, but I don't really see anything *wrong* in it. I can test fly some to get a better idea though.

**Comment by gilbertohasnofb** [comment]
Hi Tuomas, I also think it could be rated higher, but maybe we could also incorporate some of the improvements of Dany93. For instance, Dany93 added more data to the tables for lift and drag: the original tables would go only up to 20 degrees of angle of attack, and his tables go up to 90. My point is: if we don't want to completely replace the FDM, we can at least cherry pick and copy what we find interesting from the other FDM, right?

BTW: since you have a GitHub account, feel free to post your bug reports directly here, although I don't mind to repost them myself, ok?

**Comment by gilbertohasnofb** [comment]
>  I can test fly some to get a better idea though

Sounds good, you already became the official test pilot of this project :)

**Comment by gilbertohasnofb** [comment]
Maybe we can close this one as well, as I think the rating of this aircraft will change completely after all our work, not only related to the FDM.

**Comment by dany93** [comment]
I agree.

**Comment by onox** [comment]
FDM is now rated 4 stars since #257
