### ISSUE TITLE
No indicated airspeed

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#530]
Pulled "Latest commit 4358ae0"

Indicated airspeed remains at 0 on the instrument.
`instrumentation/airspeed-indicator/indicated-speed-kt` is (none) or nil

Not so important, but I'd like to know:
I wished to come back to my previous version, but I could not.
My local branch is with this bugged version.
[My remote](https://github.com/dany93/c172p-detailed) is still with the previous one (ebb386b)
Attempts: I did
`git merge --abort`
then 
`git reset -- hard`
then
`git pull' (from origin/master, which is my dany93 remote)
With no success ("Your branch is ahead from 'origin/master' by 89 commits")

I did **no git push**. My remote branch is still with my previous version.
[EDIT] After gilbertohasnofb response, **I did a git push** to my remote (dany93). Everything is OK.
But if you can (thank you) I'm still interested in the easiest procedure to come back to the previous version in case of a bugged one. I guess there is an immediate way.

How can I recover to my previous version (or one which works) by the easiest way?
`git reset --hard ebb386b` ??

I hope that my attempts did not do too much mess and I do not dare to go farther...

**Comment by gilbertohasnofb** [comment]
Maybe you have forgotten the pitot tube cover on? You can disable it indefinitely in the aircraft menu as well.

**Comment by dany93** [comment]
Thanks, @gilbertohasnofb 
Good suggestion, but **yes and no**. "Allow securing aircraft" and Put pitot tube cover" where unchecked. By fiddling with them, I got the airspeed.
However, there is some anomaly: 
- If I uncheck "Allow securing aircraft" without unchecking "Put pitot cover", I have no airspeed (although pitot cover unchecks by itself).
- With checking / unchecking like this in  bad order, I can have the airspeed indicated with the pitot cover ON. And no airspeed with Pitot cover OFF.

**Comment by gilbertohasnofb** [comment]
Thanks for the report, @dany93, I will check what is going on and try to fix this bug.

**Comment by gilbertohasnofb** [comment]
Okay @dany93, I found the bug. I will create a PR implementing a lot of things today, and it will also fix this issue. Thanks for pointing this out!

**Comment by onox** [comment]
> My remote is still with the previous one (ebb386b)
Attempts: I did
git merge --abort
then
git reset -- hard
then
`git pull' (from origin/master, which is my dany93 remote)
With no success ("Your branch is ahead from 'origin/master' by 89 commits")

If your remote is at an older revision (ebb386b as you said), then you need to do `git reset --hard ebb386b` to reset your local repository to that particular commit. If you forget the commit id and simply do `git reset --hard`, then you reset to the latest revision (but your tree is already on the latest revision), cleaning the stage and your working copy. The end result is simply that your `git status` will be clean.

So if your git remote tree is A->B and your local git tree is A->B->C, then if you do `git reset --hard` you simply go back to C. So doing a reset without a commit id is only useful if your `git status` shows a total mess.

**Comment by dany93** [comment]
Thank you, @onox.
