### ISSUE TITLE
Gear lights of amphibious do not depend on electrical system

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#533]
Gear lights of amphibious do not depend on electrical system. Even if battery or alternator is turned off:

![fgfs-screen-320](https://cloud.githubusercontent.com/assets/3361585/11045425/a99831f6-8727-11e5-8028-e445949cd52e.png)
![fgfs-screen-321](https://cloud.githubusercontent.com/assets/3361585/11045424/a99056c0-8727-11e5-8364-ad67d8098c30.png)

I see `Model/c172p.xml` has multiple animations that need to be adjusted, so I suggest to do this:

1. Modify `Systems/als-lights.xml` to add a `<logic>` element

2. Add the output property from the `<logic>` element to the parameter list (around line 259) in `Models/c172p.xml`. Something like:

    ```xml
    <cockpit>
        <electrical>
            <gear-amphibious>/local/output/property/of/new/logic/element</gear-amphibious>
        <electrical>
    </cockpit>
```

    It seems `sim/model/material/instruments/factor` is another local property that is not yet in the parameter list.

    Note that the reason to add it to the property list (even though it is a local property) is so that it becomes very easy to modify the plane when we get to use a new free MP property in the future (+ dual-control). (It seems at the moment we cannot use int[0] .. int[3] until most 3.4 users have upgraded to 3.6)

3. Add `<property alias="/params/cockpit/electrical/gear-amphibious"/>` to the animations

**Comment by onox** [comment]
@wlbragg Would you like to do this? Add the commits to branch `bug-533`.

**Comment by wlbragg** [comment]
Yes, I can finish it.

**Comment by onox** [comment]
I can do this issue if you're already too busy with other issues.

**Comment by wlbragg** [comment]
I'd let you! :smile:

**Comment by wlbragg** [comment]
I'll work on it.

**Comment by wlbragg** [comment]
I already have it all in except to tie to the alt and batt. I'll finish it and push later this morning.

**Comment by wlbragg** [comment]
I guess it is tied directly to master power and no switch inline?

**Comment by onox** [comment]
> I guess it is tied directly to master power alt and/or batt and no switch inline?

You mean whether it depens on a circuit breaker? I don't know. @Juanvvc @tigert @wezzer Do you know this?

**Comment by wlbragg** [comment]
I didn't think about that, I would imagine if done right you would absolutely add a circuit breaker to the system for it. But what I was actually asking about was a master power switch for it. I guess regular landing gear don't have a power switch but I think they too would have a circuit breaker.

**Comment by gilbertohasnofb** [comment]
@wlbragg I was looking for some images of how the gear lever in a 172 amphibious would look like and I found this, but I don't know if the lever is for the gear or for the water rudder: http://austingwatson.com/yahoo_site_admin1/assets/docs/Cessna172FloatplanePOH.32573617.pdf

Anyway, I think we need a lever for the water rudder, don't you think?

**Comment by wlbragg** [comment]
Yeah, I like that. It looks like it is a handle attached to a cable. And the tension on the cable and handle keep it seated in the holder.
I wonder though what the pole looking object is for?

Something else, not related to the rudder but to the gear panel. I looked at several conversion of the c172/180 amphibian and they all had the same type of gear control panel as what we used.
![amph](https://cloud.githubusercontent.com/assets/11069680/11199451/4e21ce24-8c93-11e5-8024-5a0ae5f239d0.jpg)
The only thing ours doesn't have is that black "hockey puck" looking thing. I think that is the retract/deploy handle. I'm not sure why they make it so big though. Maybe a safety feature so you can easily tell if they are deployed?

**Comment by wlbragg** [comment]
I'm not sure where we would put it. maybe between the seats?
Here it is in front of the pilot. This is un-textured and no handle.
![rudder](https://cloud.githubusercontent.com/assets/11069680/11202130/7f84560a-8caa-11e5-9161-24207c7561ef.jpg)

**Comment by onox** [comment]
> I'm not sure where we would put it. maybe between the seats?

Put what? The black hockey puck? Why put it between the seats? :confused: Why not attach it to the handle that we have right now?

About the circuit breaker, we could use the one for the interior lights (`/systems/electrical/outputs/instrument-lights`)?

**Comment by wlbragg** [comment]
@ onox sorry for the confusion. I posted the image of our panel out of context with the discussion we were having (I don't necessarily think we need the hockey puck thing).
We were discussing the device they use for releasing the rudder. It looks like a simple cable that is under tension by the spring on the rudder. It has two available setting, deployed or not, I'm not sure which is which. The cable is moved (or released) by removing it from the metal bracket catch and the tension of the spring on the rudder causes the cable to travel forwards until the handle attached to the cable comes into contact with the cable tube that goes through the fuselage. Quite simple but requires some room for the travel. Almost looks like a homemade setup,

**Comment by gilbertohasnofb** [comment]
In between the seats look good to me. And what about that lever in between the seats that can be seen in the pdf I posted, what is that for? Is that some other method of lowering the gear as opposed to a switch in the panel, or does that lever do anything else?

**Comment by wlbragg** [comment]
I don't know what that is for.
@gilbertohasnofb if onox agrees we should add this, we should make a new issue.

**Comment by wlbragg** [comment]
Can you make a texture for any of it. I know it is small detail.The bracket that the handle sits in needs a  couple screw heads. The handle could be wood or plastic and the tube that passes through the fuselage is probably metal of some sort.

**Comment by wlbragg** [comment]
I'm not sure we can get this detailed but the tube through the fuselage would be threaded on the end that passes through the fuselage and then a nut on both the exterior and interior to hold it in place on the fuselage.

**Comment by gilbertohasnofb** [comment]
> if onox agrees we should add this, we should make a new issue.

By this you mean the unknown lever or do you mean the water rudder control?

As for the texture, I will prepare something. To which branch should I push it? I will probably add them to `panel.png` as it is the texture with most empty space (and anyway I am afraid we will have to redo all textures once @thevirtualfer's new model arrives...)

**Comment by gilbertohasnofb** [comment]
One more thing: would you have a photo of the mechanism for me to base the textures? I only have seen that illustration in the pdf file.

**Comment by wlbragg** [comment]
I meant adding the rudder deploy device. but that is OK lets just do it, I'm sure he'd be OK with it.
Do you mind making a new issue for this? 

panel.png is good and the branch could be something like rudder-deploy-device.

No I have no picture but can gestimate by what this thing is doing that it has very simple parts to it

**Comment by wlbragg** [comment]
>Do you mind making a new issue for this?

I'm not trying to put anything off on you. If you saw how I am typing and sitting, you'd be rolling on the floor laughing. I have a very determined dog that insists on sitting with me.

If we have a new issue, is there an easy way for me to copy or move all this discussion to the new issue and keep the authorship?

**Comment by wlbragg** [comment]
@onox, I changed the gear panel to use "/systems/electrical/outputs/instrument-lights" which work good.
One thing I noticed though while testing was that this is not set up to "rely" on power to operate. The gear still work without power, only the lights don't work. I guess I should go ahead and make the gear deploy dependent on power also?

**Comment by gilbertohasnofb** [comment]
> I meant adding the rudder deploy device. but that is OK lets just do it, I'm sure he'd be OK with it.
Do you mind making a new issue for this?
> panel.png is good and the branch could be something like rudder-deploy-device.

Sure, I don't mind doing it myself at all! And I will work on the textures as you say.

> ... and keep the authorship?

Do you mean the assignee? I don't think we can have two assignees, but I don't really care for that. I just assign things for myself so that other people know that I am already working on something, as to avoid common efforts on a same problem :wink:

**Comment by wlbragg** [comment]
> and keep the authorship?

No, I meant copying any of this discussion over the the new issue and who said what. What you did is fine. Well just go from there. Thanks.

**Comment by wlbragg** [comment]
@onox, I changed the gear panel to use "/systems/electrical/outputs/instrument-lights" which work well.
One thing I noticed though while testing was that the gear deploy/retract is not set up to "rely" on power to operate. The gear still work without power, only the lights don't work. I guess I should go ahead and make the gear deploy dependent on power also?

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
@onox, I see the rudders have a key assigned to them but not the gear, where do I stop the gear from deploying if there is no electrical to them?

**Comment by onox** [comment]
@wlbragg Does the landing gear need electricity to move? Perhaps we should also support gravity assist for gear down movement.

**Comment by onox** [comment]
See https://github.com/Juanvvc/c172p-detailed/blob/amphibious-gear-panel-electrical/c172p.xml#L899-L912

**Comment by onox** [comment]
@wlbragg See this trick for how to nuke a `<kinematic>`: https://github.com/Juanvvc/c172p-detailed/blob/amphibious-gear-panel-electrical/c172p.xml#L800-L810

**Comment by wlbragg** [comment]
>Does the landing gear need electricity to move?

Technically yes, at least if using the panel switch. If the panel has no power then the switch shouldn't deploy the gear.
As far as a backup (gravity assist), I can't see how they would have engineered one in those pontoons.

**Comment by onox** [comment]
Hmm... ok, lets do electricity only then.

**Comment by wlbragg** [comment]
Probably, but I'll ask in the forum just in case they have some ingenious way to emergency deploy.

**Comment by onox** [comment]
@wlbragg You want to implement this in the same branch?

**Comment by onox** [comment]
We can keep PR #550 open in that case.

**Comment by wlbragg** [comment]
Yes, we can keep it here.

**Comment by wlbragg** [comment]
I forgot about this next step. I am going to finish this in #551 and keep everything together.
