### ISSUE TITLE
moving sounds to FGDATA

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#542]
Thorsten wrote in the forum thread:

> Gentlemen, with regard to the environment sounds (thunder certainly, is there more?) you have used:
> 
> I think conceptually the best way would be to have those not residing with the aircraft but in the system-wide sound directory and being referenced by the aircraft. In such way, anyone who likes can use the same environment sounds, and we manage diskspace more efficiently.
> 
> Would you be okay with this solution?

From my side, this is absolutely fine, what do you guys think? What about you, @onox? I will suggest that they also copy another sounds from our plane into that directory:

- `thunder1.wav`
- `thunder2.wav`
- `thunder3.wav`
- `rain.wav`
- `rain-windshield.wav`

And also maybe the new `wind.wav` sound, which may be merged via https://github.com/Juanvvc/c172p-detailed/pull/522

**Comment by gilbertohasnofb** [comment]
Also, if these sounds are copied to $FGDATA/Sounds, we can simply remove them from our repository and the code will continue to work without a single alteration, correct?

**Comment by wlbragg** [comment]
Sounds like a plan!

**Comment by onox** [comment]
Do all the sounds have the maximum volume they can have without any clipping? Once they are moved to FGData, we have no longer control over it.

**Comment by gilbertohasnofb** [comment]
So I will check that and then give Thorsten green light.

**Comment by gilbertohasnofb** [comment]
@onox I have re-uploaded 4 files to the branch `bug-329`:

- `thunder2.wav` is now a tiny weeny bit louder, but no need to change the code for it at all (it now has the max amplitude just like the other two thunders)
- `rain.wav`, `rain-windshield.wav` and `wind.wav` all have been really amplified, so can you have a look on the code and adjust their volumes as you wish?

So then I propose the following: we fix our code for these new volumes in this PR here https://github.com/Juanvvc/c172p-detailed/pull/522 and after merging it I will tell Thorsten that he can add those files to FGDATA. Once we see his commit there then we can remove them from our repo in another PR. Sounds good? :loud_sound:
