### ISSUE TITLE
Fuel and luggage GUI sliders shouldn't be available in-flight

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#543]
Similarly to how the oil and fuel sump GUI become inactive if the airplane is moving, the fuel and luggage dialogs should do the same (I am not referring to the Fuel and Payload dialog but rather the new ones that open when clicking on the fuel caps and baggage door).

**Comment by wkitty42** [comment]
i was going to report that, too... you beat me to it :smile_cat: 

i'm also able to open both side doors and the baggage compartment at 100+ kts...

**Comment by gilbertohasnofb** [comment]
:smile: 

> i'm also able to open both side doors and the baggage compartment at 100+ kts...

Thanks, I opened this: https://github.com/Juanvvc/c172p-detailed/issues/544

**Comment by wkitty42** [comment]
:+1:
