### ISSUE TITLE
"Neither a condition nor a property specified" in console output

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#545]
I don't remember when this started showing up but I thought to finally create an issue for it:

> Reading systems from /home/myuser/myflightgear/Aircraft/c172p/Systems/systems.xml
Initializing HUD Instrument
  AI Model Manager
Reading sound sound from /home/myuser/myflightgear/Aircraft/c172p/c172-sound.xml
  Neither a condition nor a property specified
Creating subsystems took:1291
Splash screen progress binding-subsystems

Apparently it doesn't like something in the `c172p-sound.xml` file. That or something hasn't been set yet.

**Comment by onox** [comment]
This is just the wind sound which doesn't have a property or condition because it is always played. Will silence the warning in PR #522.
