### ISSUE TITLE
Create water rudder lever

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#551]
Create water rudder lever for float and amphibian models

Reference: http://austingwatson.com/yahoo_site_admin1/assets/docs/Cessna172FloatplanePOH.32573617.pdf

**Comment by gilbertohasnofb** [comment]
See discussion from https://github.com/Juanvvc/c172p-detailed/issues/533#issuecomment-157194797 onwards. 

@wlbragg I will add the textures to `panel.png` on branch `bug-551` and let you know about it.

**Comment by wlbragg** [comment]
Actually reading the documentation that @gilbertohasnofb provided answered some of my questions.

First off some other potential additions we might want to think about on the amphibious configuration.
1) "standard propeller is replaced by a propeller of larger diameter and flatter pitch."
2) "an oil radiator is installed in the engine rear vertical cooling baffle."
3) "hoisting provisions are added to the top of the fuselage."
4) "a floatplane placard is added."
5) "stainless steel cables."
6) "rudder peddles move the water rudders" 
I know ours move but do they enhance steering in the water?

@gilbertohasnofb , as far as the bar or rod we see, it actually has the word "flap" on it. It is and earlier method for deploying flaps. You can see the flap setting notches in the wheel next to it.

The device we are working on consists of
"water rudder retraction handle".
"water rudder retraction handle hook."
cable housing tube extending through fuselage.
"stainless steel cables."

The "on hook' position of the handle is "rudders up", used for takeoff, in flight and landing.
The "off hook" position is used during taxiing.

**Comment by gilbertohasnofb** [comment]
>  as far as the bar or rod we see, it actually has the word "flap"

Oh, I couldn't read it, so then it makes it clear, thanks!

I will try to prepare these textures still tonight.

**Comment by wlbragg** [comment]
One other thing, when we get this addition working, the speed of the deploy animation should be sped  up. I say this because the rudders are mechanical not electrical and they will deploy or retract at the speed of the pilots arm movement in releasing the handle. Probably pretty quick.

**Comment by gilbertohasnofb** [comment]
You had previously written:

> Can you make a texture for any of it. I know it is small detail.The bracket that the handle sits in needs a couple screw heads that anchor it to the floor. The handle could be wood or plastic and the tube that passes through the fuselage is probably metal of some sort.

So, I decided to add the textures to `panel_parts.png` rather than `panel.png`, as it makes more sense and there is still some empty space there. That file already had a screw head that you can use, so now I added:

- a generic plastic texture
- a generic wood texture

It also already had a metallic texture that can be used. See:

![eg](https://cloud.githubusercontent.com/assets/5700795/11223911/9c0aeabe-8d72-11e5-92b0-7b6eb4056d32.jpg)

Let me know if this suits you or not. I am probably off for today and in the next two days I will be quite busy, but then I am back.

**Comment by wlbragg** [comment]
Perfect, thank you!

**Comment by wlbragg** [comment]
I created the water rudder retraction hardware and positioned it in between the seats. Let 
me know what you think and please be kind. Maybe @thevirtualfer can make a more professional version of it in the future.
Next up is to animate it in the down position.

**Comment by gilbertohasnofb** [comment]
@wlbragg No need to feel humble about it, it is looking pretty good! :smile: But notice that right now you are showing it on all models and not only on the float and amphibian variants.

**Comment by wlbragg** [comment]
Thanks, your too kind.

@gilbertohasnofb, @onox, I've consolidated all float model items into c172p-pontoon.blend, everything except the gear panel. 
@gilbertohasnofb, I am getting an error 'no such member: autostart' in Nasal/engine.nas line 171.
Can you check your local copy before you pull this latest push?

**Comment by wlbragg** [comment]
I don't get the error in master or amphibious branches.

**Comment by gilbertohasnofb** [comment]
It seems related to the PR which already has been merged into master, when I moved the autostart from `engine.nas` to `c172p.nas`. That said, it shouldn't affect this branch at all...

Before pulling anything (so the last commit on my branch `bug-551` is my texture addition from yesterday) gives me no such error message. I will pull and test it again now.

**Comment by gilbertohasnofb** [comment]
After pulling I got no error either. Both times I started the engine with autostart and all went well.

**Comment by wlbragg** [comment]
Hum, let me pull a new copy and see if it went away.

**Comment by wlbragg** [comment]
Try exiting the sim with "complex start up" and "start with engine running" NOT checked, then start it up again.

**Comment by wlbragg** [comment]
This is really frustrating. Not only do I still have the error, but when I switch from floats to bush gear options the cross-bracing and the rudder deploy system don't disappear. This last commit was the select animations that got that part working (at least for the rudder system). The cross-bracing was already working.

Would you please see if the rudder deploy system and the cross-braces disappear when you switch to anything except the pontoon or amphibian?

**Comment by wlbragg** [comment]
I'm not sure what happened but I got it worked it out. I am merging "amphibious-gear-panel-electrical" into this branch and pushing it. It's to difficult working on this separate. Everything should be done except the animation for rudder deploy position of the rudder deploy system. I'll probably do that in the morning.

**Comment by wlbragg** [comment]
#550 and #553 continued here.

**Comment by gilbertohasnofb** [comment]
> Try exiting the sim with "complex start up" and "start with engine running" NOT checked, then start it up again.

That is exactly what I was doing and I was not seeing any error or whatsoever.

**Comment by gilbertohasnofb** [comment]
>  I've consolidated all float model items into c172p-pontoon.blend, everything except the gear panel. 

Were the two branches mergeable? If one branch was created before the modifications to `engine.nas` and the other after, then that file would have been different between them. Could that have caused your problem?

**Comment by wlbragg** [comment]
I think I merged them afterwords. If you have the time pull this and see if the error is still absent for you.
If you remember, what commit modified engine.nas?

**Comment by wlbragg** [comment]
I just checked the autostart code and the one call to it, it is correct. It there maybe another place calling autostart?

**Comment by wlbragg** [comment]
You know what I think this error is originating from, I think it may be related to an old saved state?

**Comment by wlbragg** [comment]
I was right, I had to delete aircraft-data/c172p.xml in .fgfs to get rif of the error. I searched that file for "autostart" and found nothing but deleting it fixed this issue.

**Comment by wlbragg** [comment]
OK, all done, ready to merge unless I made a mistake or forgot something.
@onox, nice trick with the kinetic. I don't think I would have figured that out on my own.

The only outstanding question was
>systems/electrical/outputs/instrument-lights
or
systems/electrical/outputs/instr

on the circuit breaker
systems/electrical/outputs/instrument-lights is labeled interior-lights
systems/electrical/outputs/instr is labeled instr-breakers

I now have it tied to "instrument-lights", (interior-lights)
Would "instr", (instr-breakers) be more appropriate?

I guess it's OK as is.

**Comment by gilbertohasnofb** [comment]
> I was right, I had to delete aircraft-data/c172p.xml in .fgfs to get rid of the error. 

Yeah, I have been messing around a lot with saved states, so almost every recent PR I proposed would involve changes in that file. It didn't cross my mind this could be the issue here though, but great you found the solution :smile:
