### ISSUE TITLE
Refactor object description animations

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#552]
I am not sure this is even an issue that is worth doing but I ask the question here.
When using animations where there are many pieces you can make a single word name that encompass all the separate objects. There are many objects that we are animating that might benefit from this type of refactoring.
Is it something we should or should not bother with?

Example, the amphibious brakes are doing this very thing with

~~~xml
   <!-- MOD: Pontoon Gear -->
    <animation>
        <name>LeftFrontGear</name>
        <object-name>Lstrut.001</object-name>
        <object-name>Ldamper</object-name>
        <object-name>LAxle</object-name>
        <object-name>LFrontWheel</object-name>
    </animation>
    <animation>
        <name>RightFrontGear</name>
        <object-name>Rstrut.001</object-name>
        <object-name>Rdamper</object-name>
        <object-name>RAxle</object-name>
        <object-name>RFrontWheel</object-name>
    </animation>

    <!-- Retractable Gear -->
    <animation>
        <type>rotate</type>
        <object-name>Ldamper</object-name>
        <object-name>LAxle</object-name>
        <object-name>LFrontWheel</object-name>
~~~

If there is no real gain in doing this then we can delete this issue. Until it is decided I have assigned no labels.

**Comment by onox** [comment]
I'm not sure I fully understand. You want to change it to for example:

* gear-front-right-damper

* gear-front-right-wheel

etc.?

**Comment by onox** [comment]
Or do you mean grouping? If you mean grouping, shouldn't it be done in the `.blend` file?

**Comment by wlbragg** [comment]
I know that there is a bunch in all the damage code, other than that I haven't really inventoried it, I just know there is room for improvement there.

**Comment by wlbragg** [comment]
I went through the code and don't see any advantage in this. There was only one block of object names that were being used twice (one rotate ans one translate). All other groupings of object names were different from one another.

So I'm closing it.
