### ISSUE TITLE
Better UV mapping to baggages

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#555]
Better UV mapping to both baggages. Currently, the slim sides of the baggage look strange, they are mapped to a single pixel row of the texture which creates a strange effect:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/11272257/dafd2fa2-8ecb-11e5-8847-8402b9ed8aee.png)

**Comment by wlbragg** [comment]
Just added this to #551

**Comment by onox** [comment]
@wlbragg  Uhh... why is this added to an issue about water rudders? :confused:

**Comment by wlbragg** [comment]
I just wanted to get rid of it and not have to make a new branch or pull one. Was there a branch for this?

**Comment by wlbragg** [comment]
In otherword I just fixed it and pushed it to #551 which is ready to be merged, hopefully!

**Comment by onox** [comment]
You mean PR #554?

**Comment by wlbragg** [comment]
Yes.

**Comment by gilbertohasnofb** [comment]
@wlbragg Thanks for fixing this!

> I just wanted to get rid of it and not have to make a new branch or pull one. Was there a branch for this?

No, there was not. But I think onox is right, we could have created one just for this. Makes the PR's more organized.
