### ISSUE TITLE
Strange polygons inside cockpits of pontoon and amphibian models

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#556]
I just noticed that both the pontoon and the amphibian models have two strange polygons showing inside the cockpit, see:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/11298579/7578dbd0-8f80-11e5-8c9b-012b2d6d02c3.jpg)

To better view them, simply switch from the default to float in the sim and you will see those polygons popping up into existence.

**Comment by wlbragg** [comment]
Uh' oh, I'll check it out and see what happened.

**Comment by gilbertohasnofb** [comment]
I believe it's from the structure which connects the floats to the fuselage: they are "entering" the cockpit from outside, if you know what I mean.
