### ISSUE TITLE
Tie-downs and two sets of chocks showing in fgrun model view.

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#557]
What do we want showing in the fgrun model view, the tiedowns, pitot cover, chocks? As of now all of it is showing including both sets of chocks. So at the minimum we need to "nopreview" at least one set of chocks.

**Comment by gilbertohasnofb** [comment]
Probably the best is to show just the plane, no chocks, no tie-downs, no pitot covers, no pilot inside either.

**Comment by onox** [comment]
> Probably the best is to show just the plane, no chocks, no tie-downs, no pitot covers, no pilot inside either.

I agree with that.

**Comment by dg-505** [comment]
Maybe a ```<nopreview/>```-Tag  in one of the .xml-files would do it. I'm not sure in which file this should be placed. Maybe in the ```chock.xml``` resp. ```rbf.xml``` resp. ```tiedownL/R.xml```? Or in the ```c172p.xml```?

**Comment by wlbragg** [comment]
How do you hide the strobes or whatever this is?

![preview](https://cloud.githubusercontent.com/assets/11069680/11319711/962362b8-9045-11e5-83f4-c278e75b2a33.jpg)

**Comment by wlbragg** [comment]
@gilbertohasnofb, I was going to make a new issue but thought I would ask here first. 

Would it be OK in you opinion to add the tiedown capability to amphibious only (not floats) and only on airport or land (not on water)? If you need another longer set of tiedowns for it, I'd make them for you!

**Comment by gilbertohasnofb** [comment]
Yeah, we could do that. Probably we don't need another set of tiedowns, we can use the same trick of burying them under the ground. But how can we detect if the amphibious in not on water?

**Comment by gilbertohasnofb** [comment]
We could also create a tail tie-down for all these variations, given that it is quite standard as well and is mentioned in the POH:

![](http://fischeraviation.com/wp-content/uploads/sites/10/2014/04/n811jd.jpg)

**Comment by wlbragg** [comment]
>But how can we detect if the amphibious in not on water?

I think this following property is true if on the water
/fdm/jsbsim/hydro/active-norm

**Comment by wlbragg** [comment]
@gilbertohasnofb, I added the tail tiedown in PR Add tail tiedown #565

I ended up putting in all the code for it as it was just as easy to copy and edit all your work than to just add a select animation to see it while I worked on it.

In addition to adding tiedown ability to the amphibious, we should also add it to the ski version (if it is not already).

The amphibious is pretty high of the ground so if it turns out we need longer tiedowns, let me know.

**Comment by dg-505** [comment]
The property ```/gear/gear[~i~]/ground-is-solid``` is set to false, when the respective wheel is over water.

**Comment by gilbertohasnofb** [comment]
@wlbragg Thanks a lot! I will test that PR.

> In addition to adding tiedown ability to the amphibious, we should also add it to the ski version (if it is not already).

It's already there, as the ski has the same height as one of the bush variations, so it was easy to add it. So let's first merge that tail tie-down PR, then we create a new issue for the amphibious tie-downs, okay?

**Comment by gilbertohasnofb** [comment]
@dg-505 thanks for the info! We will use that

**Comment by gilbertohasnofb** [comment]
PR merged, so I created https://github.com/Juanvvc/c172p-detailed/issues/566
