### ISSUE TITLE
wind tunnel data

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#561]
Here is some wind tunnel data posted by erik in the forum thread: http://etd.auburn.edu/bitstream/handle/10415/1135/Recktenwald_Bryan_48.pdf?sequence=1

Maybe @dany93 and others would find some use for it. If not, feel free to close this issue.

**Comment by dany93** [comment]
Thanks @gilbertohasnofb.
Although this thesis subject is disk shaped wings, some measurements on C172 are given for comparison.
I keep it in my documentation.

**Comment by gilbertohasnofb** [comment]
Okay @dany93, in that case I will close this issue. If we ever decide to implement something related to this paper, we can reopen it.
