### ISSUE TITLE
Allow tie-downs to amphibian model if on solid ground

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#566]
Allow tie-downs to amphibian model if on solid ground.

We can use the property `/gear/gear[~i~]/ground-is-solid` (thanks @dg-505!)

Probably we will have to prolong all tie-down models, @wlbragg

**Comment by onox** [comment]
@gilbertohasnofb Has this been implemented?

**Comment by gilbertohasnofb** [comment]
Yes it has.

**Comment by onox** [comment]
Fixed in PR #580. See https://github.com/Juanvvc/c172p-detailed/pull/573#issuecomment-160266736
