### ISSUE TITLE
Add metal plate to floor texture

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#567]
Add metal plate to floor texture. See: http://tigert.1g.fi/kuvat/Simulators/Flightgear/C172-dimensions/aar.jpg

**Comment by onox** [comment]
Do we really want this? IMO it looks kinda ugly.

@gilbertohasnofb Could you do `git commit --amend` and replace the commit message with something like "Added metal plate to floor texture"?

**Comment by onox** [comment]
Hmm... I see on google that there is some sort of plate on the floor, but sometimes it is covered by the carpet.

**Comment by gilbertohasnofb** [comment]
> IMO it looks kinda ugly.

Really? I think it looks good! It's quite common I think

**Comment by gilbertohasnofb** [comment]
It's up to you, but I think it looks good and I also think it's typical for these older models like ours.

**Comment by onox** [comment]
@gilbertohasnofb In that case can you rewrite the commit message as I said in the PR? (I accidentally added the comments to this issue pages, but I meant them to be on the PR page.

**Comment by gilbertohasnofb** [comment]
I will do that.

**Comment by gilbertohasnofb** [comment]
Okay, I did that. Do I need to push it or something?

**Comment by onox** [comment]
Yes, otherwise I don't see it here on Github :wink:

**Comment by onox** [comment]
You are in the correct branch, right?

**Comment by gilbertohasnofb** [comment]
Hmm, not really working. See:

```
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git status
On branch floor-texture
Your branch and 'origin/floor-texture' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
gilberto@gilberto-Inspiron-7520 ~/WorkingFG/c172p/c172p $ git push
Username for 'https://github.com': gilbertohasnofb
Password for 'https://gilbertohasnofb@github.com': 
To https://github.com/Juanvvc/c172p-detailed.git
 ! [rejected]        floor-texture -> floor-texture (non-fast-forward)
error: failed to push some refs to 'https://github.com/Juanvvc/c172p-detailed.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by gilbertohasnofb** [comment]
This is after the commit name was changed locally.

**Comment by onox** [comment]
You need to use `--force`

**Comment by wlbragg** [comment]
Are we going to make it an option?

**Comment by gilbertohasnofb** [comment]
> Are we going to make it an option?

What do you mean? Make this metal plate optional? No, it's hard coded in the textures.

**Comment by onox** [comment]
I think adding yet another check button is a bit too much :worried:

**Comment by gilbertohasnofb** [comment]
I wouldn't see the point either, it's just an "aesthetic" detail. No need for more check buttons indeed. I think buttons should be only for functional things.

**Comment by gilbertohasnofb** [comment]
Ok, I pushed with `--force` but I still see the old commit name here on GitHub

**Comment by onox** [comment]
Refresh.

**Comment by gilbertohasnofb** [comment]
same

**Comment by gilbertohasnofb** [comment]
anyway, on the PR the commit has the correct name, just not here in this issue

**Comment by wlbragg** [comment]
If it is an after market addon, it should be optional. What was it for, to limit wear from your heal?

**Comment by gilbertohasnofb** [comment]
> If it is an after market addon, it should be optional. 

I think it's unrealistic to make this argument. A lot of the textures I created were by using reference pictures only. I can't possibly research every single plate and bolt in the cockpit to see what's from the factory or not, and as long as the cockpit "feels" like a P model (which I think ours do) then I am satisfied :wink:

**Comment by onox** [comment]
> anyway, on the PR the commit has the correct name, just not here in this issue

I see. Just something you have to ignore then I guess.

**Comment by wlbragg** [comment]
My only thought was if we had "several" after market addon that are fairly common we could put them in a separate sub- menu. 
Beings this is just a texture, (I thought it was going to be modeled), I guess it would be difficult to make it selectable.
@gilbertohasnofb, I wasn't asking you to research anything, just asking a simple question.
It is not s simple nut or bolt, it is a decent sized metal plate that may not be appropriate in all configurations, just saying.
But in the end  I am OK with the addition, just making possible suggestions.
I'm typing on a tablet at the moment and am somewhat handicapped.

**Comment by gilbertohasnofb** [comment]
@wlbragg I see you are only making suggestions, no worries about it, I understood you weren't telling me to do anything, just raising a possibility. Communicating via text is complicated, it's often difficult to tell people's tone, and that's why I like to add emojis as often as possible :smile_cat: 

But my opinion is that if something isn't functional, it should be made as optional and so it's up to us to either implement it for all variants or not. I think we should keep our GUIs as clean and small as possible. 

As for the plate itself, my impression is that 2/3 of these older models seem to have them but I really don't know if that's from the factory or not. But given how widespread they seem to be, my guess is that it comes from the factory indeed. Maybe @tigert or @Juanvvc would know something more about it.

**Comment by wlbragg** [comment]
We're good then! :smile:
I just pulled a new master and don't see the plate, did it get merged?

**Comment by gilbertohasnofb** [comment]
:+1: :smile: 

As for the modifications, I just tested the `master` branch and they are showing up on all liveries. Are you sure something isn't wrong with your local repo?

**Comment by wlbragg** [comment]
My mistake, I got it.

**Comment by wlbragg** [comment]
Looks good!
Those have to be for wear from your heal, It would make sense that they are on older models more than new.
