### ISSUE TITLE
Synchronize environment sounds with FGDATA

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#577]
Thorsten has just pushed some of our sounds to FGDATA, specifically the environment ones:

`thunder1.wav`
`thunder2.wav`
`thunder3.wav`
`rain.wav`
`rain-windshield.wav`
`wind.wav`

He had to rename `wind.wav` into `wind1.wav` because of the older file present there. So I guess we must:

- remove our wav files
- rename `wind.wav` into `wind1.wav` in our sound xml file

Here is his commit: https://sourceforge.net/p/flightgear/fgdata/ci/87421c8dabef01ea662902bbf0250ed2b4a4a361/

**Comment by gilbertohasnofb** [comment]
> So I guess we must:
>
> - remove our wav files
> - rename wind.wav into wind1.wav in our sound xml file

@onox can you confirm this is the only things to do? If so, I can do it myself.

**Comment by onox** [comment]
AFAIK that's the only thing you have to do, so you can do it yourself :+1: :smile:

**Comment by gilbertohasnofb** [comment]
Ok!
