### ISSUE TITLE
Add tail tie-down to checklist

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#585]
All securing aircraft properties have now been moved to `/sim/model/c172/securing/`. Also please make sure the PR https://github.com/Juanvvc/c172p-detailed/pull/580 has been merged before, as it will affect the checklists.

@dg-505 do you think you can take care of this one?

**Comment by gilbertohasnofb** [comment]
Sorry, invalid report: I was checking it in an older branch and I wasn't aware of recent modifications to the `master`.

**Comment by onox** [comment]
Usually you can keep these labels (handy when searching/sorting issues), just remove the milestone (otherwise it looks like it was a bug that got fixed in that milestone) and add the "invalid" label (which you already did).

**Comment by gilbertohasnofb** [comment]
Ooops
