### ISSUE TITLE
Stop propeller spinner after engine crash

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#595]
@onox wrote:

> I think we need to stop rotating the spinner (that thing to which the propellers are attached to) when the engine is crashed. The propellers correctly stop rotating, but the spinner does not.

**Comment by wlbragg** [comment]
I'm confused about this one. I checked the code and the spinner is tied to RPM same as the propeller? It should follow what the propeller does.

**Comment by wlbragg** [comment]
OK, I see what's wrong. The damaged prop isn't tied to the spin animation, the spinner is. I'll fix it.

**Comment by gilbertohasnofb** [comment]
Thanks! :+1:

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/597
