### ISSUE TITLE
Change regression version link in forum pg1.

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#596]
@gilbertohasnofb, would you mind updating the link to the "new" regression version on the information page of the c172p-detailed forum at http://forum.flightgear.org/viewtopic.php?f=4&t=25157#p229807

The new link is https://github.com/Juanvvc/c172p-detailed/archive/regression-to-3.2.zip

This is the old (outdated) link https://github.com/Juanvvc/c172p-detailed/archive/regression-version-to-3.2.zip

I'll delete the old branch after the forum update.

Thank you!

**Comment by gilbertohasnofb** [comment]
I will do it right away!

**Comment by wlbragg** [comment]
Thank you!

**Comment by gilbertohasnofb** [comment]
Done.
