### ISSUE TITLE
Improve yoke model

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#606]
Improve yoke model. Currently our model is very simplistic, from a frontal view it is basically a simple rectangle while the typical yoke for these old 172 models would look more like this:

![](http://www.aviationexplorer.com/Commercial_Airliners-Military_Aircraft_Pictures/cessna_172_cockpit.jpg)

Another image, by @tigert: 
![aag](https://cloud.githubusercontent.com/assets/5700795/11674807/7bf32c74-9e24-11e5-94f4-66bf4fe6fa42.jpg)

**Comment by gilbertohasnofb** [comment]
This was actually solved via https://github.com/Juanvvc/c172p-detailed/pull/605

**Comment by gilbertohasnofb** [comment]
Hmm, not really, my bad. That PR only changed the texture, not the 3D model. Sorry!

**Comment by wlbragg** [comment]
We need to map the new texture in the model?

**Comment by gilbertohasnofb** [comment]
No, the texture is mapped properly, it's just our yoke 3D model which is ugly. The texture we now have is for this type of model: 

![](http://www.aviationexplorer.com/Commercial_Airliners-Military_Aircraft_Pictures/cessna_172_cockpit.jpg)

It has much rounder corners, as well as being a trapezium rather than a rectangle, if you know what I mean.
