### ISSUE TITLE
Stop propeller if aircraft is upside down

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#607]
Stop propeller if aircraft is upside down. Currently it keeps spinning.

![fgfs-screen-402](https://cloud.githubusercontent.com/assets/3361585/11684765/333bfaba-9e74-11e5-99ff-150acf9cde91.png)

Can probably be fixed by calling `killengine()` in `upsidedown` function in `Nasal/physics.nas`.

**Comment by dany93** [comment]
It should stop on its own from `Systems/Fuel.xml`
`accelerations/Nz GE 0`

**Comment by onox** [comment]
This is not about gravity (you're right about that), but about the propeller still happily ploughing the ground :smile: It shouldn't do that.

**Comment by dany93** [comment]
Good thing to make a propeller happy :smile:

But more realistically, does the engine stop as expected when upside down ? It should, 
and the propeller should stop too, as a mere consequence of the engine stop... And with the code already done.
Depending on the engine which stops or not, or the propeller animation, something does not work or is not logic.

You wrote
>Can probably be fixed by calling `killengine()`

Which made me understand that the engine does not stop?

**Comment by wlbragg** [comment]
I thought we accounted for that, but maybe it was just the crash flag. In which case we can set the crash flag conditioned upon contact 9, 11 or 12. They are all suppose to be the topside of the aircraft. Those contact points were a bit buggy so verify they are WOW when upside down.

**Comment by wlbragg** [comment]
I would maybe add contact 10 (nose) as anytime the nose touches the ground I think one way or another the prop is going to stop. Unless the actual point is not visually where you might think it should be.

**Comment by onox** [comment]
Wouldn't it be sufficient to call `killengine()` in `upsidedown` function in `Nasal/physics.nas`?

**Comment by wlbragg** [comment]
That sound right.

I wonder if we shouldn't add 9, 11, 12 to
~~~xml
 if (getprop(contact~"unit[12]/WOW"))
            upsidedown();
~~~
and
10 (nose) WOW as a killengine() condition.

**Comment by onox** [comment]
10 is the nose? Yeah, then we should kill the engine as well.

But you might wanna wait a little, I'm busy in `Systems/c172p-ground-effects.xml` and `Nasal/physics.nas`.

**Comment by wlbragg** [comment]
:+1:

**Comment by onox** [comment]
@wlbragg See my comments and questions in PR #615
