### ISSUE TITLE
Engine should be killed if propeller is broken

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#608]
Engine should be killed if propeller has stopped (broken). This should also happen if you for example break the propeller by collapsing the nose gear.

Can be fixed by using `/engines/active-engine/killed`. It seems it is currently used in the animations (that is good), but not by the FDM or engine systems (because if I set full throttle, I still get RPM). Engine is still running in this screenshot:

![fgfs-screen-403](https://cloud.githubusercontent.com/assets/3361585/11684904/3c096a28-9e75-11e5-9413-78daee4e07af.png)

**Comment by dany93** [comment]
The reference should be  `Systems/fuel.xml`. But there is an extra layer above `/engines/active-engine/killed`, which prevents from stopping the engine by directly setting this property to true. I don't know neither why nor where.

**Comment by wlbragg** [comment]
Can you bust a pin or spin it off the shaft?

**Comment by wlbragg** [comment]
> This should also happen if you for example break the propeller by collapsing the nose gear.

This for shue used to be in place, I set it up myself. So it must have got removed accidentally?

**Comment by onox** [comment]
If I print something in `killengine` it gets printed, but `/engines/active-engine/killed` remains false.

**Comment by onox** [comment]
It seems it might be `Systems/engine.xml` that is resetting it.

**Comment by onox** [comment]
I have fixed it.

**Comment by onox** [comment]
@gilbertohasnofb What's the purpose of the `settimer()` in `engine_coughing` in `Nasal/engine.nas`? Is it 1) to just make a coughing sound; or 2) make coughing sound + *temporarily* kill engine?
