### ISSUE TITLE
Colour problems in the cockpit gauges

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#614]
Colour problems in the cockpit gauges: 
- very often the magneto switch looks green under certain light conditions
- the instrument illumination isn't consistent among all instruments. Some needles are whiter and some other are pinker. They should be all pink IMO:
![](https://cloud.githubusercontent.com/assets/3361585/11754523/2593c4d6-a04c-11e5-8450-af919312e4e4.png)

**Comment by gilbertohasnofb** [comment]
For whomever will volunteer to work on this: maybe you could also tackle the issue here https://github.com/Juanvvc/c172p-detailed/issues/35 which is related in a way.

**Comment by wlbragg** [comment]
>very often the magneto switch looks green under certain light conditions

I think I know what this is and have a fix for it, so I will take the assignment.

**Comment by gilbertohasnofb** [comment]
Great! :smile:

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/618
