### ISSUE TITLE
Drag direction of flaps should be vertical instead of horizontal

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#616]
Drag direction of flaps should be vertical instead of horizontal.

**Comment by gilbertohasnofb** [comment]
Also, when scrolling above the flaps with the mouse wheel, forwards lowers the flap while backwards raises the flap. I think that it should be the opposite, right? Backwards should move the flaps down.

**Comment by wkitty42** [comment]
On 12/11/2015 06:23 PM, Gilberto Agostinho wrote:
> Also, when scrolling above the flaps with the mouse wheel, forwards lowers the
> flap while backwards raises the flap. I think that it should be the opposite,
> right? Backwards should move the flaps down.

yes, this is consistent with my view of how the mouse wheel should act...

**Comment by gilbertohasnofb** [comment]
hehe "consistent with my view" isn't the same as "consistent with the other switches", right? You mean that you'd like all others to behave as the flaps, while I think we just need to fix the flaps and then everything is perfect.

**Comment by wkitty42** [comment]
On 12/11/2015 07:21 PM, Gilberto Agostinho wrote:
> hehe "consistent with my view" isn't the same as "consistent with the other
> switches", right? You mean that you'd like all others to behave as the flaps,
> while I think we just need to fix the flaps and then everything is perfect.

then perhaps the throttle and mixture should be reversed, too?
