### ISSUE TITLE
Push/pull levers texturing...

### ISSUE THREAD

**Issue by legoboyvdlp** [Juanvvc/c172p-detailed#624]
http://www.biopatent.com/numbered.jpg

See 42 and 18. They should have a black circle, like the instrument lighting.

Also, there should be a handset style cable under the yoke.

Finnaly, does the 1981 have rudder trim, like the 83? See 29.
Cheers!

**Comment by gilbertohasnofb** [comment]
To clarify: @legoboyvdlp is referring to the the primer and cabin air and heat levers, all of which should look like the instrument lightning. I think this isn't a matter of texture but rather of 3D modelling. What do you think, @wlbragg, would you be interested in adapting the instrument lightning knob for those objects?

This is lego's image:

![](http://www.biopatent.com/numbered.jpg)

@legoboyvdlp no, we don't have a rudder trim in our model

**Comment by wlbragg** [comment]
I might take a look at it. Are we sure the knobs don't come both ways? What is 42 in this image?
In other RL images I've seen, the heat and air knobs are the same look but are smaller.

**Comment by legoboyvdlp** [comment]
Thank you!

And 42 is the cabin heat/air levers.

**Comment by gilbertohasnofb** [comment]
> Are we sure the knobs don't come both ways?

No, I am not sure, but if you google "cessna 172 primer" all results look something like this:

![](http://cyclenetparts.com/images/items2/c13/SAM_9940_e93db9.JPG)

So I think lego may have a point.

**Comment by wlbragg** [comment]
>And 42 is the cabin heat/air levers.

It looks like just one lever?

No matter, I'll just copy one of the example knobs (instrument lighting) and re-size it for the heat and air.

**Comment by legoboyvdlp** [comment]
I think the other one is missing or hidden ;) Perhaps it is in a warm country!

**Comment by legoboyvdlp** [comment]
Good job, @wlbragg

**Comment by wlbragg** [comment]
Thanks!
Good idea! :wink:
