### ISSUE TITLE
Problems with the start-up tutorial

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#628]
Problems with the start-up tutorial:

- aircraft starts with tie-downs, so I guess we must force tie-downs and chocks off as well as pitot tube cover, as well as check for oil and fuel contamination (that is, the aircraft should be in the state after pre-flight inspection). This may affect other tutorials as well but I haven't checked them all.
- I would also force the switches to the correct pre-start position: avionics and master off, all lights off, circuit breakers all on. 
- the tutorial asks me to prime the engine quite a lot, around 6 times. I thought that anything greater or equal to 3 would be fine.
- this tutorial asks me to set the throttle to "around" 10%, but several values (including 10% exactly) aren't accepted. I think anything between 10-20% should be fine right?

**Comment by gilbertohasnofb** [comment]
@dg-505 would you be interested in this issue given that you have already worked with tutorials before?

**Comment by dg-505** [comment]
Yes, I would be.
I also noticed that there are several problems with the other tutorials. E.g. "Landing" should start with engines running, but at least for me, it doesn't. It seems that the startup procedure of the c172p has become that complex that initializing a tutorial with engines running may be very difficult, if not impossible.

- In the first step, the tiedowns, chocks and pitot cover get removed (line 93-112). If they are nevertheless not removed, I don't know the reason. In the first step the switch positions can also be set. The breaker positions are checked in a separate step (line 193-363) so IMHO they don't need to be set at the beginning.

- The "priming"-step is from line 365-404. According to this it should move to the next step when ```/controls/engines/engine[0]/primer``` is **3 or more** and ```/controls/engines/engine[0]/primer-lever``` is **0** i.e. the Primer lever is in. To prime the engine 3 times you have to actuate the primer 6 times: 3 times pull out, 3 times push in.

- Ah, I discovered the mistake in the "throttle-setting"-step. I will correct this right now.

**Comment by dg-505** [comment]
See #629

**Comment by gilbertohasnofb** [comment]
> Yes, I would be.

Great! :smile: 

> In the first step, the tiedowns, chocks and pitot cover get removed (line 93-112). If they are nevertheless not removed, I don't know the reason.

Strange. I loaded the tutorial when I was tied down and it didn't remove the tie-downs by itself.

**Comment by dg-505** [comment]
As #629 is now merged, can this now be closed?

**Comment by gilbertohasnofb** [comment]
Yes, absolutely! I forgot to do so. Thanks again!
