### ISSUE TITLE
improve flaps lever

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#634]
I think our flap lever is not the most common model found in the P model. Most of the images I found are of this model:

![](http://www.flylpas.com/N5314K%20panel.JPG)

Note how it has only two colours (light blue and white) as opposed to ours with three, also note that the numbers inside these colours show the max speed for that flap extension and not the angle. 

I will work on the new texture, but probably the model will have to be slightly adapted. Any volunteers to fix it? (should be some really simple adjustments)

**Comment by gilbertohasnofb** [comment]
Okay, done. Pushed to a new branch `bug-634`. This is the new texture:

![flaps](https://cloud.githubusercontent.com/assets/5700795/12055548/825847d2-af2e-11e5-972c-cf8053ee4a9b.png)

And while the old flap had two textures, one for the panel one for the lever itself, I have everything in a single texture so the lever should be re-UV mapped.

So could anyone give me a hand with the 3D model?

**Comment by gilbertohasnofb** [comment]
Also note that the flap lever and the flap position indicator (the tiny "T" that indicates the current flap position and which is electrically controlled) might need to be a bit repositioned, and also the xml for the flaps will need to be tweaked for the correct positions for each notch.

**Comment by gilbertohasnofb** [comment]
@wlbragg when you have the chance, do you think you could have a look at this? I can fix the xml myself I think, but for the 3D model update I'd need help.

**Comment by wlbragg** [comment]
Yes, I'll look at it.

**Comment by gilbertohasnofb** [comment]
Thank you so much.

**Comment by wlbragg** [comment]
I noticed the ignition switch lighting looked messed up so I fixed it while I was at it.
![ignit](https://cloud.githubusercontent.com/assets/11069680/12214814/b40c7316-b668-11e5-925d-18b52ce4a3b3.jpg)

Unrelated I also moved all the development files to dev folder, I got tired of them cluttering up the models folder.

**Comment by wlbragg** [comment]
![flaps](https://cloud.githubusercontent.com/assets/11069680/12214850/ebe4a94c-b669-11e5-9b61-11dd59a0fce8.jpg)

**Comment by gilbertohasnofb** [comment]
Thank you so much!

> I noticed the ignition switch lighting looked messed up so I fixed it while I was at it.

Looks much better, that switch always had some strange problems (first the green illumination, now this). Now it looks finally fixed :smile: 

About the flaps, thanks for the work, it looks good but it has a problem: the flap lever texture is applied sideways, note the shadow line inside the red circle in the image below, it should have been lengthwise and not sideways (that is, it has to be rotated 90 degrees). See the cockpit photograph on the first post to look how the flap lever looks like and what I tried to do with the texture.

Also I still have to fix the position of the lever and the little "T" object before merging as they should be in the black holes rather than where they are now. So that PR shouldn't be merged yet!

**Comment by gilbertohasnofb** [comment]
Forgot the image, see:
![test](https://cloud.githubusercontent.com/assets/5700795/12215921/d615230a-b6d0-11e5-9592-ee1ad2c25462.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg actually, the position of the levers also has to be fixed in Blender, I can only work on the animation of them in the xml file. The little T is a bit too high and the flap lever is also too high and too much to the right. This should be the new "path" of their animation:

![untitled](https://cloud.githubusercontent.com/assets/5700795/12216486/8983210a-b6e3-11e5-9ef4-14e5c674b940.jpg)

**Comment by onox** [comment]
@wlbragg I had to perform some surgery in branch `bug-634`, so chop off the 4 old commits and then pull:

1. Check your active branch is `bug-634`

2. `git reset --hard HEAD~4`. This should remove the 4 old commits.

3. `git pull` to get the 2 new commits

**Comment by onox** [comment]
@gilbertohasnofb The current animation is a rotation animation, right? Maybe it should be changed to a translate animation using interpolation?

**Comment by gilbertohasnofb** [comment]
> The current animation is a rotation animation, right?

Yep!

> Maybe it should be changed to a translate animation using interpolation?

I need to study how this work as I only worked with very simple animations so far, but indeed we will need some like that in order to create the complex path the lever now should make.

**Comment by wlbragg** [comment]
OK, it may be later tonight or tomorrow before I can get get to this.

**Comment by gilbertohasnofb** [comment]
No rush :smile:

**Comment by wlbragg** [comment]
I just finished rotating the lever texture did you want me to move the indicator over to the right so it starts in the black or are you going to do it all with xml?

**Comment by gilbertohasnofb** [comment]
I'd say it's more elegant to have them in the correct position in the blend file. It's the same amount of work in xml I suppose, but leaving it like this will make it show "wrongly" in Blender while fine in the sim, and I think it may puzzle future developers :wink:

**Comment by wlbragg** [comment]
It's pushed!

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg Please don't kill me, but the flap lever texture is applied upside down! It's a super minor detailed, but:

![untitled](https://cloud.githubusercontent.com/assets/5700795/12223262/83c58722-b7d2-11e5-8311-10f78ca50591.png)

**Comment by wlbragg** [comment]
No, my fault. sorry.

**Comment by gilbertohasnofb** [comment]
No problem at all! :smile:

**Comment by wlbragg** [comment]
Let's try this! :smile:

**Comment by wlbragg** [comment]
I also had not mapped the indicator button. It was just using the white material.

**Comment by gilbertohasnofb** [comment]
Now it looks perfect, thank you so much!

I will take a look at the xml file when I can, but given that this animation will be more complex than before I still need to learn how this can be accomplished. In the next weeks I am super busy with my thesis so I can't promise when I will get this done... :cry:

**Comment by wlbragg** [comment]
If I have time I might get to it. It's not much to do once you know how.

**Comment by gilbertohasnofb** [comment]
Feel free to do so, but if anyone can't do this I will have a look on it later.

**Comment by onox** [comment]
You could focus first on just the vertical translate animation. That should not be too difficult.

**Comment by gilbertohasnofb** [comment]
I will try that when I have more time, onox. I am really super busy with my thesis :sob:

**Comment by gilbertohasnofb** [comment]
@onox Do you think you could give us a hand in the c182 project? Heiko can't find which part of the code makes the lever smoothly move from a position to the next notch, the lever is simply teleporting to the new positions. See: https://github.com/HHS81/c182/issues/33

On the other hand, Heiko used a translation + rotation to animate the lever, maybe something like this could look better in our plane as well. What do you think?
