### ISSUE TITLE
FDM uses wrong type of fuel  --> wrong weight of fuel

### ISSUE THREAD

**Issue by HHS81** [Juanvvc/c172p-detailed#644]
According http://wiki.flightgear.org/JSBSim_Fuel_System    JSBSim calculates 6.6 lbs/ gal fuel weight as standard. This is the density of Jet Fuel. 
But the C172 uses AvGas. So it should be 6.02lbs/ gal. So fuel weight is not correct!

How to Fix:
Standard tank is 43 Gallons for the Cessna 172P , so add <type>  AVGAS</type> btween <tank></tank> tags and change each capacity to 129.43lbs.

**Comment by wkitty42** [comment]
On 01/06/2016 09:04 PM, HHS81 wrote:
> According http://wikiflightgearorg/JSBSim_Fuel_System JSBSim calculates 66
> lbs/ gal fuel weight as standard This is the density of Jet Fuel But the C172
> uses AvGas So it should be 602lbs/ gal So fuel weight is not correct!

something doesn't look right in the above... where'd your periods (.) go???

**Comment by onox** [comment]
According to POH, standard tanks capacity is 43 gallons, long range tanks is 54 gallons, and integral tanks 68 gallons.
