### ISSUE TITLE
Next release and milestones names

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#646]
@onox @Juanvvc @wlbragg @dg-505 and all others: do you guys know when exactly do we need to have a stable model ready for merging into FGDATA in order to make it to the next release? By the discussions in the dev list it seems a next release will come soon. If that's the case, maybe we should start doing what we did for the 3.6 and start moving issues to more future milestones if they are not going to be fixed soon, and also focus some some important bugs that we must solve before this merge (if there are any, I can't remember by heart).

Also, as far as I can tell,  the new release won't be called "FlightGear 4.0" but it will rather use the geeky and horribly confusing "FlightGear 2016.1 San Francisco" typical of open source programs`</rant>`, and so I think we have to rename our milestones accordingly (currently we have 3.8 and 3.9).

Finally, it seems that the concept of release candidates and stable/unstable releases is also being reviewed, and also as far as I could understand there won't be any feature freeze period any longer. If that's right, then I suppose we don't need these double milestones for each version.

**Comment by gilbertohasnofb** [comment]
This is a list of bugs that I think we could have a look once again before the next release, though none of them are as serious as the ones we had to fix before the 3.6 freeze IMO:

https://github.com/Juanvvc/c172p-detailed/issues/607
https://github.com/Juanvvc/c172p-detailed/issues/547
https://github.com/Juanvvc/c172p-detailed/issues/414
https://github.com/Juanvvc/c172p-detailed/issues/399
https://github.com/Juanvvc/c172p-detailed/issues/387
https://github.com/Juanvvc/c172p-detailed/issues/307
https://github.com/Juanvvc/c172p-detailed/issues/306
https://github.com/Juanvvc/c172p-detailed/issues/295
https://github.com/Juanvvc/c172p-detailed/issues/293

**Comment by onox** [comment]
> Finally, it seems that the concept of release candidates and stable/unstable releases is also being reviewed, and also as far as I could understand there won't be any feature freeze period any longer. If that's right, then I suppose we don't need these double milestones for each version.

I think we could still keep the distinction between features and bug fixes, but the deadline of the two milestones will be the same.

> Also, as far as I can tell, the new release won't be called "FlightGear 4.0" but it will rather use the geeky and horribly confusing "FlightGear 2016.1 San Francisco" typical of open source programs

As far as I understand it they're going to use something like yyyy.n.0 for git and yyyy.n.1, yyyy.n.2, etc. for stable releases. What's confusing IMO is that they use .0 for git. Usually .0 is used for a new stable release, and .1, .2, etc. are used for bug fix releases. FlightGear used to have version numbers like 3.5, 3.7, etc. for git, but that doesn't make much sense unless you actually do a release (of the current git repo) (like Gnome does)

**Comment by gilbertohasnofb** [comment]
Sounds good to me.

**Comment by gilbertohasnofb** [comment]
Also, two other things:

- the c172p in FGDATA is from July 2015. I already wrote twice to the mailing list about when and how should we do a merge for 2016.1.1, but I got no answer. Do any of you know anything about it?
- Edward d'Auvergne has made some commits in the c172p in FGDATA, shall we sync them with our repo? See: https://sourceforge.net/p/flightgear/fgdata/ci/next/tree/Aircraft/c172p/

**Comment by onox** [comment]
Which files did he modify? SF says only files in `AI/Aircraft/` were modified.

**Comment by gilbertohasnofb** [comment]
> Which files did he modify? SF says only files in AI/Aircraft/ were modified.

I don't think so, that commit is several pages long but the first page is only about modifications to `AI/Aircraft`. At page 6 ( https://sourceforge.net/p/flightgear/fgdata/ci/3bf57db6b479d0353f2d9f59702a90890ed5c34e/?page=5 ) we see:

```
changed 	Aircraft/c172p
changed 	Aircraft/c172p/Models
changed 	Aircraft/c172p/Models/Interior
changed 	Aircraft/c172p/Models/Interior/Panel
changed 	Aircraft/c172p/Models/Interior/Panel/Flaps
changed 	Aircraft/c172p/Models/Interior/Panel/Flaps/flaps.png
changed 	Aircraft/c172p/Models/Interior/Panel/Flaps/manilla.png
changed 	Aircraft/c172p/Models/Interior/Yoke
changed 	Aircraft/c172p/Models/Interior/Yoke/yoke.png
changed 	Aircraft/c172p/Models/Pedals
changed 	Aircraft/c172p/Models/Pedals/pedal.png 
```

**Comment by gilbertohasnofb** [comment]
So it's basically the yoke, pedals and flaps textures only.

**Comment by onox** [comment]
Yeah I see it now, SF interface is crappy.

**Comment by gilbertohasnofb** [comment]
> SF interface is crappy.

Tell me about it.. :wink:

**Comment by onox** [comment]
I think you should ask him to create a PR, otherwise he doesn't learn that development takes place here :laughing:

**Comment by gilbertohasnofb** [comment]
Yeah, I can do that :smile: But the thing is he used an automatic tool to fix all png files in FGDATA and so I don't think he is even aware that he modified the c172p.

**Comment by onox** [comment]
Yeah, can you do `identify Models/Pedals/pedal.png` and see if you get those `iCCP` errors?

**Comment by gilbertohasnofb** [comment]
I don't know much about those iCCP errors, but in a conversation with Edward apparently the version of the libpng packages that come with Linux Mint (and some Ubuntu distros) are not affected. I remember trying to run a command to identify them myself but there were no error messages at all.

**Comment by gilbertohasnofb** [comment]
But given that the fixed png files open fine here for me, we could simply incorporate them.

**Comment by onox** [comment]
Ok, you can do that, but please tell Edward that he shouldn't modify `Aircraft/c172p/` in fgdata, and instead create a PR here on Github.

**Comment by wkitty42** [comment]
On 01/08/2016 09:34 AM, Gilberto Agostinho wrote:
>     Which files did he modify? SF says only files in AI/Aircraft/ were modified.
[trim]
> changed Aircraft/c172p changed Aircraft/c172p/Models
> changed Aircraft/c172p/Models/Interior
> changed Aircraft/c172p/Models/Interior/Panel
> changed Aircraft/c172p/Models/Interior/Panel/Flaps
> changed Aircraft/c172p/Models/Interior/Panel/Flaps/flaps.png
> changed Aircraft/c172p/Models/Interior/Panel/Flaps/manilla.png
> changed Aircraft/c172p/Models/Interior/Yoke
> changed Aircraft/c172p/Models/Interior/Yoke/yoke.png
> changed Aircraft/c172p/Models/Pedals
> changed Aircraft/c172p/Models/Pedals/pedal.png

these modifications are related to the invalid ICC profiles in PNGs, right? if 
so, how were those PNGs created? they can be recreated without the invalid ICC 
profiles... if they cannot be recreated without the invalid ICC profile, then i 
would likely merge them back into this repo...

pngcrush was used to remove the invalid ICC profiles... i don't know if there's 
a winwhatever version... on linux, one doesn't see this problem with older 
versions of libpng ( <2.0 IIRC )... i can't see it with pngcrush which uses my 
local libpng but FGFS does see it and emit the warning/error to the console and 
log...

it would also be nice to know which software was used and possibly report that 
to the dev list if they are making a list of such software...

**Comment by gilbertohasnofb** [comment]
@onox I will do so then. I just think that since this is the first time he modified something in the c172p folder there, and given it was automatically done via a terminal command and affect tons of others files, then there is no reason to make life annoying to him as to ask him to make an account here and create a PR himself when I can do that easily myself. But I will let him know about it.

@wkitty42 those files are pre-historic, from the original c172p. They might be 10 years old and to track who created them and how they did and in which program is beyond me. None of my textures showed any problems, nor for this project nor for other ones that got merged into FGDATA, so we can sleep well knowing we aren't contributing to the issue :smile:

**Comment by gilbertohasnofb** [comment]
@onox just one more thing, I won't merge his modified `yoke.png` since we have a new yoke texture since the last sync in FGDATA.

**Comment by onox** [comment]
@gilbertohasnofb Maybe it's better to just open the four .png files in Gimp and somehow get rid of the embedded color profile?

**Comment by onox** [comment]
Or use pngcrush if it doesn't modify the picture itself.

**Comment by gilbertohasnofb** [comment]
Why do you think that's better than using his fix? The thing is my system doesn't see any error so pngcrush doesn't seem to do anything about it here.

**Comment by onox** [comment]
I'm not sure about it. I don't know how pngcrush "fixes" the file.

**Comment by gilbertohasnofb** [comment]
Well, me neither... but however he did that, it seems to have fixed the problem for those observing the error messages, while others like me who never had any problems still can open the new files fine (can't tell the difference). So I just don't see why using his fixed png files would be a bad idea.

**Comment by onox** [comment]
> So I just don't see why using his fixed png files would be a bad idea.

You said: "I won't merge his modified yoke.png since we have a new yoke texture" :wink:

**Comment by gilbertohasnofb** [comment]
None of the textures I created or modified myself showed any problems, so I am pretty sure the new `yoke.png` file is fine. The files `flaps.png` and `manilla.png` should hopefully be replaced once someone help me implement the new texture I created for them in the issue https://github.com/Juanvvc/c172p-detailed/issues/634, but in the meantime we do have the old files in our project. As for the `pedal.png`, that file was never touched by any of us and probably won't be since it's a very good texture. So what I propose is to create a PR now containing the fixed versions of `flaps.png`, `manilla.png` and `pedals.png`, while ignoring the fixed-but-old `yoke.png`. Makes sense?

**Comment by onox** [comment]
Sounds good.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Done, see: https://github.com/Juanvvc/c172p-detailed/pull/649

**Comment by gilbertohasnofb** [comment]
Torsten wrote in the mailing list today:

> The discussion ended with a consent and I will release 2016.1.1 in two weeks.

Is anyone aware of how/when/if will we make another merge into FGDATA prior to that release?

**Comment by wlbragg** [comment]
>I just think that since this is the first time he modified something in the c172p folder there, and given it was automatically done via a terminal command and affect tons of others files, then there is no reason to make life annoying to him as to ask him to make an account here and create a PR himself when I can do that easily myself. 

This is the right way to look at this, I was about to make the same comment prior to finishing this thread. What would be nice to know is what causes this "bad" png. Do any changes or new png's we create have this bug? From your prior post @gilbertohasnofb, it sounds like they don't cause problems. Must have been some older program that saved png's poorly or at least differently then others.

>Is anyone aware of how/when/if will we make another merge into FGDATA prior to that release? 

Who did the last one?

**Comment by gilbertohasnofb** [comment]
> Do any changes or new png's we create have this bug? 

None of our new pngs (modified at least by me, you, @thevirtualfer, @tigert and possibly others) have caused these issues, the only bad apple in our repo was a prehistoric file (rudder pedal textures) and that has been fixed. So I think we don't have to worry about this at all.

> Who did the last one?

I believe it was Stuart. I had sent a couple of e-mails about it to the list in the past months, but got no clear answer about it. The current version of the c172p in FGDATA is from August 2015, and I think we **must** have another push soon before the release.

**Comment by wlbragg** [comment]
You might try it again (dev list) or I can post one on there and see if I get any response?

**Comment by gilbertohasnofb** [comment]
I will try one more time, let's see if it works

**Comment by gilbertohasnofb** [comment]
I just wrote an e-mail to the list, let's see how it goes. I suppose that as soon as we have the procedural lights done we are ready for a merge, right? Or do we need to fix something urgently before that? @onox?

**Comment by onox** [comment]
Someone could work on that thermometer.

**Comment by gilbertohasnofb** [comment]
Yes, I also would be happy to have a thermometer, but I ran into a wall with that old style of gauge (the ones that use `<panel>`) and I just don't know how to proceed. To be honest, that thermometer's code will become completely useless and we would only use it's 3D model (which isn't the best either, but acceptable), so effectively we'd need to create the gauge from scratch. And unfortunately I don't know how to do that :cry:

**Comment by onox** [comment]
I told you to take a look at the hobbs meter. It uses the same technique with the textures.

**Comment by onox** [comment]
Or does that require UV mapping or something? :open_mouth:

**Comment by gilbertohasnofb** [comment]
And I replied to that:

> Finally, about the Hobbs, the numbers are displayed on individual 3D objects, and this isn't the case of this thermometer. So to use something similar as the Hobbs, it would involve some work on Blender I suppose.

**Comment by wlbragg** [comment]
This seems on the surface such a simple thing. Don't we simply use an existing temperature property to update a "digital" representation of a digital thermometer screen?
Is it because we need a font sheet or a some kind of a simulated LED interface for a number scheme? 
I am not familiar at all with the tech FG employs to update a surface with text, but would be willing to learn with a couple well placed hints as to some source or docs.
@onox , you beat me to the my post, @gilbertohasnofb  you want me to look at this and see if I can do this.

**Comment by wlbragg** [comment]
oops!

**Comment by gilbertohasnofb** [comment]
>  you want me to look at this and see if I can do this.

If you can, that would be great. I honestly don't think it's likely I would be able to figure all this in the next days, until the merge, so that would be really appreciated!

**Comment by wlbragg** [comment]
Let me try, that is if I get rid of this damn headache. Hopefully I can take a good look this afternoon. I'm out of here for now. Have fun!

**Comment by gilbertohasnofb** [comment]
:+1: thanks a lot and get better soon!

**Comment by gilbertohasnofb** [comment]
Okay, so I got an answer from Stuart and he will do the merge for us. So when exactly shall we do this? I guess we need first to implement the lights, maybe the thermometer as well. When do you guys think it's a realistic deadline?

**Comment by onox** [comment]
I need to finish the lights and then I'll make a branch in a few days which he can merge.

**Comment by onox** [comment]
I have kinda implemented the navigation lights in PR #685.

**Comment by onox** [comment]
@wlbragg I have a request for you. You can delete a bunch of unused `navlight_*` objects (those which were used by damaged wings) :smile:  Don't delete `navlight_left`, `navlight_right`, and `navlight_back` in the main Blender file though. These 3 are still used. See the PR.

**Comment by onox** [comment]
> Okay, so I got an answer from Stuart and he will do the merge for us. So when exactly shall we do this? I guess we need first to implement the lights, maybe the thermometer as well. When do you guys think it's a realistic deadline?

I have set the deadlines to tuesday for now.

**Comment by wlbragg** [comment]
Yes, I'll delete them.

**Comment by gilbertohasnofb** [comment]
> I have set the deadlines to tuesday for now.

Sounds good.
