### ISSUE TITLE
Improve layout of Aircraft Options dialog

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#664]
1. Move "Allow securing aircraft" and indent the related check buttons to show the relationship
2. Re-order bushkit options

![fgfs-screen-438](https://cloud.githubusercontent.com/assets/3361585/12384578/f447661e-bdb3-11e5-9a9c-f5b91353f9dd.png)

**Comment by gilbertohasnofb** [comment]
Looks pretty, I will test the PR now :smile:

**Comment by wkitty42** [comment]
i like this new layout... i do have a thought, though... perhaps the "allow securing aircraft" options could be in a side pop out menu? when you mouse over it, the menu opens? that or when the box is checked, then they appear as shown? i don't have a problem with it but i was thinking that it is getting a little bit long and seeing how some other menus in other craft pop out on certain items, it was just a thought...

**Comment by gilbertohasnofb** [comment]
I don't know what's this pop out menu you are talking about, can you give some examples of planes using it?

**Comment by wkitty42** [comment]
On 01/18/2016 01:15 PM, Gilberto Agostinho wrote:
> I don't know what's this pop out menu you are talking about, can you give
> some examples of planes using it?

i think what i was thinking of it like those that come up in the bluebird hover 
craft... they've even got certain keys set to bring up some of their menus...

what i mean by "pop out" was like you see in most menus where hiliting or 
hovering over an option springs a menu out to the side... that depends on the 
menuing system, though, i guess... i expect that in FGFS they may be being faked 
to look like that's what they are doing and instead they are just a new box with 
options being shown and hidden...

if you haven't looked at the bluebird, it might offer some ideas...

**Comment by wlbragg** [comment]
Very nice indeed!

**Comment by gilbertohasnofb** [comment]
I just tried the Bluebird (sorry for the delay) but I have to say I don't like that style of GUI. Exchanging lots of checkboxes in a single menu by several menus with the same amount of checkboxes doesn't make much sense to me. I don't think our menu is cluttered (at least when compared to X-Plane http://www.x-plane.com/wp/wp-content/uploads/2013/06/location-data-input-output-screen-x-plane.png :wink: ). I think that two or more menus will just make people click more and move the mouse around more to accomplish the same tasks, and that's in my opinion bad design.

**Comment by wlbragg** [comment]
I noticed my comment was out of order and context. I hadn't taken the opportunity to comment on the changes to our GUI, I like the changes that were made. It looks really clean and organized just the way it is.

**Comment by wkitty42** [comment]
@gilbertohasnofb my comment was only about the one section of our menu... nothing more and yes, the bluebird is rougher than i remembered... i can't remember all the craft i've flown and what all their menus looked like...

**Comment by gilbertohasnofb** [comment]
> i can't remember all the craft i've flown and what all their menus looked like...

Well, so try them out before recommending their dialogs! :stuck_out_tongue_winking_eye:

**Comment by wkitty42** [comment]
On 01/22/2016 03:51 AM, Gilberto Agostinho wrote:
>     i can't remember all the craft i've flown and what all their menus looked
>     like...
>
> Well, so try them out before recommending their dialogs!
> :stuck_out_tongue_winking_eye:

i know you're being funny but i should go digging back thru 600+ craft to try to 
find the few dozen or so that i've found with menus like i described? yeah, 
thanks but no thanks :wink:

**Comment by gilbertohasnofb** [comment]
> i know you're being funny but i should go digging back thru 600+ craft to try to find the few dozen or so that i've found with menus like i described?

Not really, but if you are recommending something, it's good that you try it first. Should __I__ test something that crossed your mind and then it turns out you don't remember how the menu looks like? Thanks but no thanks to that :wink:
