### ISSUE TITLE
Copy 3D seat mounts from c182

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#670]
Copy 3D seat mounts from c182: that project has detailed mounts while we are still using a shameless cardboard rectangle :wink:

**Comment by legoboyvdlp** [comment]
Thank goodness; I was trying tof igure out just how to start, and couldn't.
I'll need to be lot's more comfortable with Blender before I 'fix' (break most lkkely) the Cessna.

**Comment by gilbertohasnofb** [comment]
No worries, lego :smile:

**Comment by wlbragg** [comment]
OK, I'm confused, are the seat mounts backwards in my last commit? If so I can rotate them on the horizontal easy enough?

**Comment by gilbertohasnofb** [comment]
I honestly don't know as the model isn't identical to the images we have. IMO the difference is small and it looks fine to me, but maybe you can ask Heiko what his intentions were.
