### ISSUE TITLE
Adjust stall horn volume to start at roughly 5-10 knots above stall speed

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#671]
Stall horn might become audible too late. Adjust pitch and volume a couple of knots above stall speeds in POH.

**Comment by dany93** [comment]
I'd rather say that the criteria should be the Angle of Attack  (say, with no flaps, or depending on flaps). Otherwise, the stall speed depends on the Gross Weight at the moment. Worse, in a turn, the stall speed is much higher due to higher apparent load.

**Comment by onox** [comment]
Yes, I know criteria is AoA, but what this PR does it make sure the stall horn gets hearable when you can still save your plane instead of when it's almost too late. If you look at the [code](https://github.com/Juanvvc/c172p-detailed/pull/672/files) you see I simply lowered the numbers a bit. (Inspired by what HHS81/c182 does)

**Comment by HHS81** [comment]
Correct, onox! All Cessna single engines let their stall horn work about 5-10ktn about indicated stall speed. 
A good landing is when very shortly before the main wheels touches the ground you hear the stall horn. That's what every FI and good pilot will tell you (and you can see on many videos)
