### ISSUE TITLE
Calibrate IAS needed according POH?

### ISSUE THREAD

**Issue by HHS81** [Juanvvc/c172p-detailed#676]
That's a bit difficult to explain, but give me a try:
We know TAS = True Airspeed, which is the speed of the aircraft relative of the surrounding airmass.
And we know IAS = Indicated Airspeed, depending of the air pressure, but very important to the pilot.

But IAS does not only depend on the air pressure. It needs also to be corrected for known instrument and position errors. This is CAS = Calibrated Airspeed. So AoA has an influence on the airflow measured as well like the air "jamming" in front of the extended flaps, which all influence IAS. 
See also: https://en.wikipedia.org/wiki/Indicated_airspeed
So every (Cessna) aircraft has a part in the POH which is called calibrated airspeed, and shows a table  comparing IAS vs CAS. 

On the C182S (derivate of the c172p-fdm) I made the experience that the stall speeds matches 100% the given CAS-values in the POH - but not the IAS-values. 

Looking at it seems to me that unfortunately FlightGear's IAS doesn't show that much error, I even think it never does. It seems this is not reflected by JSBSim or FlightGear in a realistic way, and should be done per aircraft.. 

So I created a table which changes the IAS to values given in the POH, depending on CAS (fdm/jsbsim/velocities/vc-kts)

So the indicated airspeed in the c172p has maybe to be changed as well so that it matches with the table in the POH. 
Especially near stall speeds the difference is quite high and noticeable. 
See https://github.com/HHS81/c182/blob/master/Systems/indicated-airspeed.xml for how it is done.

**Comment by gilbertohasnofb** [comment]
@dany93 maybe you are the right guy to check this out?

**Comment by dany93** [comment]
I'm looking at this.
But please let me some time, I'm not too much used to using these functions.
Neither with these calibrations.

@HHS81: Thanks for your links and your indications.

**Comment by gilbertohasnofb** [comment]
@dany93 no rush, Dany!
