### ISSUE TITLE
External lights aren't visible from certain angles

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#683]
Gijs wrote in the forum:

> The red and green lights should be visible when flying head on towards the aircraft. The table from FAR §23.1391 says that between 0° to 10°, the minimum (!) intensity should be 40 candelas. Below 0° the lights on the c172p are now completely invisible, whereas I would expect a gradual reduction. See for example the following videos:
> 
> https://www.youtube.com/watch?v=KR-Girnjcyg
> 
> https://www.youtube.com/watch?v=0kaXYQb5ko4

**Comment by gilbertohasnofb** [comment]
It looks like he is right, what do you think, @onox @wlbragg ?

**Comment by wlbragg** [comment]
He's right, I thought that was odd that you could not ever see both red and green at te same time.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
First some definitions: 0 deg is from cockpit to nose, -90 deg is from cockpit to right wing, and +90 deg is from cockpit to left wing.

@Gijsrooy I defined the visibility of the red and green navigation lights to have an arc of 110 deg, exactly as is shown in http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2550#p274105 In fact there is a gradual reduction, but it is from about -12 to 0 for the green light on the right wing, and +12 to 0 for the red wing.

We can adjust the range, but it will also probably require modifications to the cone objects in Blender.

For the front limit of the red/green lights:

From that first YouTube video in http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2550#p274113 I estimate the green light starts to dim between +10 to +45 deg.

For the aft limit of the red/green lights: using the red light in the video I estimate +140 to +160 deg?

So the total arc would be for the red light on the left wing: from +160 deg to -45 deg; for the green light on the right wing that would be: -160 deg to +45 deg.

Current arc range is +110 to 0 and -110 to 0.

What do you guys think of that?

**Comment by onox** [comment]
If I'm not mistaken, the current arc is about 157.955 deg wide, and it would need to be increased to 205 deg.

**Comment by gilbertohasnofb** [comment]
I think your proposal sounds reasonable, @onox. We can give it a try and see how it looks I suppose.

**Comment by Gijsrooy** [comment]
Yes please, it'd be nice to see how that works out. I find it remarkable that the regulations only go up to 0 degree. Maybe I missed some subsubsub, as I'm quite sure that you should be able to see both from the front...

Simulating lights correctly is a pain, but you're doing very well so far! Once this issue is sorted I'll probably take and modify them for the 744 :-)

**Comment by wlbragg** [comment]
So for now this is an XML fix?
@onox, are you currently working on this?

**Comment by wlbragg** [comment]
I found info on the beacon light collision with the body.
https://sourceforge.net/p/flightgear/mailman/message/12102066/

**Comment by wlbragg** [comment]
I'm jut about ready to push the nav light changes.

**Comment by wlbragg** [comment]
It would really be nice to document the functions of all the tags available in these animations.
I would consider adding the documentation to the wiki if I understood it at all.

Things like...

axis - what exactly are those numbers doing, all I know is a larger negative value on the x increased the viewable arc.
min, max - appears to be clipping the light at certain angles. min 1 x max 4 seemed to clip the light where we need it, but I have no clue what those numbers mean.

It's really nobodies fault that the documentation is so limited, but none the less, it is extremely frustrating for those of use that are less then genius and is a major factor in productivity. I spend 95% of my time learning how to do something that with a little bit better documentation should have taken about 5% of my time, FRUSTRATING!

**Comment by wlbragg** [comment]
Sorry for the rant, anyway a change has been pushed and can be tested. :smile:

**Comment by wlbragg** [comment]
![crop2](https://cloud.githubusercontent.com/assets/11069680/12591097/ceba019e-c42b-11e5-95ae-451929bb3306.jpg)

**Comment by wlbragg** [comment]
![crop2](https://cloud.githubusercontent.com/assets/11069680/12591204/467018d6-c42c-11e5-8c9f-28e04c404cbf.jpg)

**Comment by wlbragg** [comment]
![crop2](https://cloud.githubusercontent.com/assets/11069680/12591602/3270fd4e-c42e-11e5-8121-9b03a396096a.jpg)

**Comment by wlbragg** [comment]
>min, max - appears to be clipping the light at certain angles. min 1 x max 4 seemed to clip the light where we need it, but I have no clue what those numbers mean.

Is this actually clipping the light brightness from min 1 to max 4 and the cone is responsible for clipping the light completely?
If so then changing the min to 1, which allowed it to be seen down the wing must not be the correct resolution to this issue but instead the range of the arc and the starting and ending point of the arc needs to be adjusted? What part of the XML does this and how?

**Comment by Gijsrooy** [comment]
Yeah, that looks much better!

**Comment by onox** [comment]
@wlbragg This issue requires modifying the cone object in Blender first. After that we can modify the XML.

The info about the "flash" animation can be found [here](http://wiki.flightgear.org/Howto:Animate_models#Flash).

**Comment by onox** [comment]
As I said in https://github.com/Juanvvc/c172p-detailed/issues/683#issuecomment-175067086 the angle of the cone is about 158 deg. But it needs to be increased to about 210. So you need to modify the physical shape of the cones. In Blender :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
>The info about the "flash" animation can be found here.

I sure am glad you can decipher the entire flash code from that short piece of documentation, but like I said, we need doc's for those of us that are not genius!

>the angle of the cone is about 158 deg

It may be somewhat less than that currently because we had to reduce the angle to keep from clipping into the wing.

So how to proceed?

**Comment by onox** [comment]
Move the cone a little bit forward so it can bend around the wing?

**Comment by onox** [comment]
Even better would be if Thorsten can generate lights using GLSL.

**Comment by wlbragg** [comment]
>Even better would be if Thorsten can generate lights using GLSL.

I just posted the same to the c172p thread!

**Comment by wlbragg** [comment]
We can't move the cone or we won't get the light point positioned correctly, it doesn't appear to behave when you try to put it past the cone. Therefor you will get separation from the light.

**Comment by wlbragg** [comment]
We learned this during the last iterations.

**Comment by onox** [comment]
Can't you move the center of the cone (the origin of the light) closer to the leading edge of the wing? And then rotate and increase the width of the cone?

**Comment by wlbragg** [comment]
Maybe!

**Comment by onox** [comment]
So just wrap the cone around the leading edge of the wing tip by moving the vertices (or by pressing a magic sequence of keys, which is something I would love to know about since I'm not fond of using the mouse in Blender)

**Comment by wlbragg** [comment]
I'm a bit confused though because looking at the cone in blender, your saying this angle is not enough, we nee to see farther than this limiting factor?
![cone6](https://cloud.githubusercontent.com/assets/11069680/12593283/e73cfed8-c435-11e5-8eae-6e0683842edb.jpg)

**Comment by HHS81** [comment]
Hmmm... I'm not sure if the idea presenting those lights as cone is good. I don't think that real lights looks like cones from some perspectives. It looks somehow strange when looking at those pictures wlbragg sent one hour ago.

**Comment by onox** [comment]
Press 7 on your numpad (or go to View > Top) to go to top ortho. Then you see the cone needs to widened.

**Comment by onox** [comment]
I think it would be much better to have lights generated in GLSL than having to use cones with a texture.

**Comment by HHS81** [comment]
emitting glsl quads with textures than emitting .ac quads with textures?

**Comment by wlbragg** [comment]
How can the light at the opposite side be seen at the 45deg angle off the nose in the real thing? According to our physical light position, it can't, maybe we need to take a look at that?

**Comment by onox** [comment]
Not necessary, you can use fragment shaders to generate all kinds of stuff: https://www.shadertoy.com/view/XtsSWs

**Comment by wlbragg** [comment]
We would still need a bigger angle but the cone needs to be forward of it's current position, and according to the video the light itself must be?

**Comment by onox** [comment]
> We would still need a bigger angle but the cone needs to be forward of it's current position

Yes and yes :smile:

**Comment by wlbragg** [comment]
Look at the video again, I'm not so sure that is the green light were seeing at 45 deg off nose.
I think 90 deg forward off the same wing tip should be the max angle to see either light. After that it is either a white light or a faint glow of the green mixed with white and that depends on the type of light being used.

**Comment by wlbragg** [comment]
This is if you are using the type of light we are modeling in our c172p. You physically cannot see the light bulb at 45 off nose opposite.

**Comment by onox** [comment]
But in the video you can?

**Comment by wlbragg** [comment]
I'm not so sure that is green, search google for c172 nav light images.

**Comment by wlbragg** [comment]
If that is the green nav then their lights are different than ours. You can't see through the wing! One image I saw the bulb was at the bottom of the edge of the wing, so you might be able to see it from slightly below.

**Comment by onox** [comment]
It's green here:

![nav-lights-172](https://cloud.githubusercontent.com/assets/3361585/12594057/71575dfa-c474-11e5-844b-7deb01db818f.png)

**Comment by wlbragg** [comment]
>I'm not sure if the idea presenting those lights as cone is good. I don't think that real lights looks like cones from some perspectives.

I don't really care for that either.

**Comment by onox** [comment]
Do you think we should just ditch those cones and ask Thorsten very politely to make us some GLSL lights? :open_mouth:

**Comment by onox** [comment]
He can make afterburner flames, so lights should be possible too :smile:

**Comment by wlbragg** [comment]
Then that aircraft has a different light than we do, It simply is physically impossible to see our light at that angle.
We would still nee to get the correct light on the wing to see it at that angle.

But yes, I put the word on the forum, lets see his response.

**Comment by gilbertohasnofb** [comment]
Thorsten had already offered to make some procedural lights, but I had informed him that we were happy with our results here (or so I thought). So my guess is that he would be opened for doing it, so @wlbragg can you clarify the situation with him?

**Comment by wlbragg** [comment]
Yes, I think maybe I already have in the forum. I think he will get the picture, if not I'll PM him.
![nav1](https://cloud.githubusercontent.com/assets/11069680/12594472/e2925fbc-c43b-11e5-93e1-1a4421b07da2.jpg)
![nav2](https://cloud.githubusercontent.com/assets/11069680/12594515/18d83eac-c43c-11e5-8110-0c13289c6c6c.jpg)
![nav3](https://cloud.githubusercontent.com/assets/11069680/12594518/1aa85aa0-c43c-11e5-87d1-da0005f2052a.jpg)

**Comment by wlbragg** [comment]
How do you see the colored light from 45 deg opposite?

**Comment by onox** [comment]
Black hole on the wing tip + gravitational lensing? :laughing:

**Comment by onox** [comment]
Maybe a black hole is too much, just something with lots of mass!

**Comment by onox** [comment]
> How do you see the colored light from 45 deg opposite?

On a more serious note: it's difficult to see what kind of nav lights exactly that 172 in the video has, but with shader lights we can probably have more control over it. I feel that we're currently abusing the "flash" animation a bit.

**Comment by wlbragg** [comment]
>we can probably have more control over it

Assuming we have some ability to control the behavior of the shader. It might be a good idea to list what we would like or need!

**Comment by Gijsrooy** [comment]
Same aircraft as the first video, this time from the other side. Red light is clearly visible.

https://www.youtube.com/watch?v=Ke1pfqxrjSk

And a picture of its wingtip (sorry couldn't find a better picture on my quick search)

https://www.flickr.com/photos/48233656@N00/20248334900

So yes there are obviously dozens of different lights available. But in the end, shouldn't they all be visible from beyond the zero angle? That's part of the whole idea with position lights AFAIK.

**Comment by wlbragg** [comment]
>It might be a good idea to list what we would like or need!

position
intensity
view range
view angle x, y and z

**Comment by onox** [comment]
For the nav lights the inner angle where you have full brightness + outer angle where brightness is zero.

**Comment by wlbragg** [comment]
>But in the end, shouldn't they all be visible from beyond the zero angle? 

Not necessarily, looking at the other drawings, they are not required past the zero? So it depends on the lights installed, the ones you showed don't match the video, IMO.

**Comment by onox** [comment]
@wlbragg @Gijsrooy's video clearly shows that the nav lights are visible past 0 deg, so why not make sure that's also the case in FG?

**Comment by Gijsrooy** [comment]
Well, I don't know the source of that drawing. The regulations mention the 110 degree, so I can see where that's coming from. And I neither understand how you can see a light around a corner, but it just doesn't make sense to me that you would not be able to see those lights when your right in front of the aircraft. Everything I've ever read or seen about position lights match the videos.

Anyhow, that's it for today from my side. It's an interesting subject that's for sure :-) Of you cannot find a definitive answer I'll search some more over the weekend.

**Comment by onox** [comment]
Yeah, I agree with that. I'm signing off as well, need to study for exams a bit more :disappointed:

**Comment by Gijsrooy** [comment]
Just one last comment: in general I trust photographs and videos more than drawings or manuals. That's one thing I've learned by working through thousands of pages of official Boeing manuals :P

**Comment by gilbertohasnofb** [comment]
> Yeah, I agree with that. I'm signing off as well, need to study for exams a bit more :disappointed:

Good studies, @onox!

**Comment by wlbragg** [comment]
I have no issue with making it past zero, my issue would be doing it with the wrong lights.

**Comment by wlbragg** [comment]
You can't see through solid objects, if it can't be explained as to why, then your guessing. From the looks of this picture it may have to do with the position and size of the globe being at the bottom of the wing. Which would still limit it to being seen only from certain angles.
If I'm going to invest any more time beyond what I already have, then I want to know it is appropriate and not guesswork. We've already guessed enough, time to do it right.
We (I) need to know for certain why and how a light on the side of one wing with no clear available line of sight can be seen from an apparently (non-visible) angle.
That's all. The reason we can't do it now is because physics say so. We would have to cheat to do it.

**Comment by wlbragg** [comment]
Here is the video aircraft compared to ours.
![172p](https://cloud.githubusercontent.com/assets/11069680/12595551/869847e8-c441-11e5-9824-760cc93665b8.jpg)

**Comment by HHS81** [comment]
That's how a nav light is looking and constructed. 
http://www.aircraftspruce.com/catalog/pdf/71105-3.pdf
I can see a 110°deg angle. 

What fgfs would need is a billboard animation but which has defined view angles. Instead of always facing the viewer, only in a defined space between two angles.

**Comment by wlbragg** [comment]
Regarding the possible shader work for aircraft lights. Some of the needed definable or adjustable parameters would be...

shape?
color
position
intensity (also influenced automatically with the atmospheric affects and available light)
view range (distance) (also influenced automatically with the atmospheric affects and available light)
view angle x, y and z

>For the nav lights the inner angle where you have full brightness + outer angle where brightness is zero.

I agree with the caveat that we don't know for sure the mechanics of the lights themselves. Is this an effect of partial obstruction by design or engineered to limit brightness at angles or what specifically?

**Comment by HHS81** [comment]
> I agree with the caveat that we don't know for sure the mechanics of the lights themselves. Is this an effect of partial obstruction by design or engineered to limit brightness at angles or what specifically?

That's not correct. We do know it. It is partial obstruction by design as the .pdf above and resultats of a googles search shows. The values Gijs gave us are just requirements  every nav light should reach. How, that depends on the producer.

**Comment by wlbragg** [comment]
>It is partial obstruction by design

If this is true then in the video, if the viewing angle was identical to what is shown in the video, except from above the wing instead of below, you would not see the light. So I submit, to do this right we need to lower our light closer to the bottom edge of the wing and maybe slightly forward, maybe even a size adjustment (larger). I would like to see a video or image from slightly above and/ or on the same plane as the aircraft at the same angles as the current video.

**Comment by wlbragg** [comment]
A closeup of the end of our wing.

![wingend](https://cloud.githubusercontent.com/assets/11069680/12631064/0dfb0d14-c515-11e5-845f-3f8f98e5c5a7.jpg)

**Comment by HHS81** [comment]
Well, that's how a cessna wingtip looks like: http://www.cessna172online.com/conical-wing-tips-0523565/
http://www.weekendcfii.com/photos/c172preflt/C172_right_tip.jpg

With partial obstruction by design I mean  how those 110°deg angle are achieved.

I found another video:
https://www.youtube.com/watch?v=xiHgrarb1nc
https://www.youtube.com/watch?v=OfXcMkh48pw

**Comment by wlbragg** [comment]
It's really hard to tell from looking at the light end-wise (from the tip down the wing) but that bulb housing obviously sticks out enough and is positioned low enough on the wing that it is visible from 20+ degree below the aircraft to 45ish degrees off the nose opposite. These videos pretty much confirm what is going on here.
![wing1](https://cloud.githubusercontent.com/assets/11069680/12654892/d77e119e-c5bb-11e5-850c-587d6f8479a2.jpg)
![wing2](https://cloud.githubusercontent.com/assets/11069680/12654899/dd716f38-c5bb-11e5-987d-e094fc77b511.jpg)

**Comment by wlbragg** [comment]
I think we need to move the light housing lower and maybe a bit forward and maybe a bit larger. Then  eventually we probably need a rework of the wing.

**Comment by wlbragg** [comment]
>>I'm not sure if the idea presenting those lights as cone is good. I don't think that real lights looks like cones from some perspectives.

>I don't really care for that either.

Why are we using cones, the tail beacon light doesn't need it? Is that the only way you can completely hide the light at angles?

**Comment by HHS81** [comment]
> Why are we using cones, the tail beacon light doesn't need it?
You are using cones, because there was an author before you who added them (well, actually that was me) 

> Is that the only way you can completely hide the light at angles?
We didn't have or had any way to completely hide the angles. 

> Is the flash animation shrinking the light at the outside viewing angles, is that how it works?
Yes, that's a very good explanation of what it actually does. That's why I used it, and that's also a good method for old fashioned rotating beacon lights.

> Can it shrink them to into oblivion?
If out of sight it should have a scale of zero, if I understood the animation correct.

**Comment by HHS81** [comment]
This is a C182:
![image](https://cloud.githubusercontent.com/assets/12649375/12684482/8393ebbc-c6bf-11e5-8fc4-64c09a4b3e8f.png)

Not visible here!

btw: http://forum.flightgear.org/viewtopic.php?f=47&t=28645
Nice, but I hate those star effect!

**Comment by wlbragg** [comment]
>Not visible here!

Right, that pretty well confirms what is going on.

I've been experimenting by using a simple plane or planes instead of a cone and it looks better at the edge than the cone I think. I'm not sure how practical it would be but a 3 plane x/y/z each with their own flash animation might be the best visual but would require some precise parameters. Even one plane angled the same as the cone makes the edge flat as opposed to a concave edge and is not quite as unbelievable as the cone. But the point of the cone actually helps positioning the light, it's really hard to get the plane positioned where it is needed. I think with precise params that a 3 plane structure using the physical aircraft wing edge and even the light housing might prove the best visual in the end using existing techniques.

I also experimented with re-configuring the wing tip (recessed it at the lower front like the images you provided. It made a big difference in a "believable" view of the bulb at the lower angle.

**Comment by gilbertohasnofb** [comment]
@wlbragg just in case you didn't notice, Thorsten opened a thread for procedural lights in the forum: http://forum.flightgear.org/viewtopic.php?f=47&t=28645

**Comment by wlbragg** [comment]
Yes, I saw it, we need anyone that is familiar or experienced with lighting to speak up in that thread so we can get everything we need.

@onox, you may want to take a look at that thread and give me any suggestions or comments you might want passed on!

@gilbertohasnofb , you may also have input that I am not aware of.

**Comment by gilbertohasnofb** [comment]
Ok, if anything crosses my mind I will speak up!

**Comment by onox** [comment]
@wlbragg What Erik said (inner/outer angles and gains) in the forum thread would be nice.

**Comment by onox** [comment]
And we should be able to define an axis where the angle is considered 0 degrees. (Which we also do in the "flash" animations)

**Comment by wlbragg** [comment]
Looks like the procedural light code is in place. I am a bit under the weather today and may not start on this until I feel a little more like the "living". Same for #682

**Comment by wlbragg** [comment]
I am not opposed to anyone else working on it if they are so inclined.

**Comment by HHS81** [comment]
I have tried them out on the c182s, and they do work. Will be a nice realistic addition to all aircraft! (beside the star thing....)

**Comment by onox** [comment]
I'll work on it :smile:

**Comment by gilbertohasnofb** [comment]
@HHS81 Great to hear that! (btw, I also hate the star effect... :disappointed: )

**Comment by wlbragg** [comment]
Are we going to try to use the standard lighting as a fallback to procedural?
@onox, have you seen the last iteration of the c182 lights? he used a square plane instead of a cone. I already have a local copy of the cone with the angle changed to something pretty close to 180 and at the extreme angle it looks much better. But to use it or if we change to a square plane, we still need to lower our light to the bottom of the wing and a bit forward.

**Comment by wlbragg** [comment]
>beside the star thing....

I thought Thorsten left us an out with intensity?

**Comment by onox** [comment]
Are you talking about the standard lighting? The procedural just need a quad AFAIK.

**Comment by wlbragg** [comment]
>Are you talking about the standard lighting?

Yes, I was talking about standard lighting.

**Comment by onox** [comment]
@gilbertohasnofb Can you give me the "red" color and "green" color? Currently I use 1,0,0 for red and 0,1,0 for green.

**Comment by wlbragg** [comment]
@HHS81, that wasn't procedural lighting on your latest commit was it?

>we still need to lower our light to the bottom of the wing and a bit forward.

I think this holds true with procedural as well.

**Comment by onox** [comment]
He put it in a different branch.

**Comment by gilbertohasnofb** [comment]
> @gilbertohasnofb Can you give me the "red" color and "green" color? Currently I use 1,0,0 for red and 0,1,0 for green.

Try this:

- green: 0.441, 0.100, 0.477

- red: 1.000, 0.320, 0.320

**Comment by onox** [comment]
Thanks.

**Comment by wlbragg** [comment]
I also noticed on the c182s that the "square plane" (standard lighting) cut into the forward wing tip as our cone used to, yet his didn't appear to have any adverse affect like ours did.

**Comment by onox** [comment]
Personally I would just remove the old lighting: anyone who uses basic renderer is a noob or an idiot. Anyone who uses Rembrandt probably uses some other Rembrandtish lights?

**Comment by onox** [comment]
> green: 0.441, 0.100, 0.477

This is purple.

**Comment by gilbertohasnofb** [comment]
Sorry, that's suppose to be a 1.000 not 0.1000.... fixed values:

    green: 0.441, 1.000, 0.477

    red: 1.000, 0.320, 0.320

**Comment by onox** [comment]
And what should be the center color? It's currently white (1,1,1)

**Comment by onox** [comment]
@HHS81 Is the procedural light "billboarded"? Doesn't look like it.

**Comment by wlbragg** [comment]
No.

**Comment by gilbertohasnofb** [comment]
> And what should be the center color? And what should be the center color? 

Yes, our png file also had 1,1,1 for the centre.

**Comment by onox** [comment]
:+1:

**Comment by wlbragg** [comment]
I don't think 1.1.1 is good, I think it should be a derivative of the primary but extremely light.

**Comment by gilbertohasnofb** [comment]
Well, we have been using 1,1,1 so far, so maybe we can try that first and then tweak it if necessary.

**Comment by wlbragg** [comment]
If it is too much trouble to figure each color out, then I guess I am OK with that, I just never liked that pure white.

**Comment by gilbertohasnofb** [comment]
I think the opposite, to be honest. For instance, I think the latest modifications Thorsten made to the scenery lights in which the centre is now not white anymore look far worse than before.

**Comment by onox** [comment]
It looks like Thorsten limited the direction to be at most 90 deg from center in the fragment shader `Shaders/light-ALS.frag`:

```glsl
float arg = clamp(direction, 0.0, 1.0);
```

Dot product of viewing direction and pointing direction is 1.0 if looking against the pointing direction, 0.0 if orthogonal, -1.0 if looking in same direction as pointing direction (from behind). 

But I want the nav light's arc to be 100 to 110 deg from center.

**Comment by HHS81** [comment]
> But I want the nav light's arc to be 100 to 110 deg from center.

Posssible

This:
[https://github.com/HHS81/c182/blob/add765057195e2da7840b6cbcd2522b5af5774e4/Models/Effects/c182sprocedural-light.eff](url)
gives the red navlight with a full view angle of 200deg
45deg from opposite wing + 110deg (specified by laws) + another 45deg.

**Comment by onox** [comment]
Your link doesn't work.

**Comment by onox** [comment]
> gives the red navlight with a full view angle of 200deg

If I read the shader correctly, that's not possible. The dot product is clamped between 0 and 1. That gives a total range of 180 deg. 200 deg, would mean 10 deg beyond 90 deg on each side. That would mean the dot product is negative, but in the code it is clamped to be always positive.

**Comment by HHS81** [comment]
@onox: billboard effect by shader, not fgfs-animation.
Sorry, new link: https://github.com/HHS81/c182/blob/newlights/Models/Effects/c182sprocedural-light.eff

**Comment by onox** [comment]
I already tried your values, and it gives a range less than 180 deg. Certainly not 200 I think.

**Comment by HHS81** [comment]
@onox: true, somehow I was irritated by wlbragg's calculation of what he saw on the videos.....

**Comment by HHS81** [comment]
I guess you need two procedural lights at the same spot which add their angles.

**Comment by onox** [comment]
Hmm... I'm reading my posts and those video's again, and maybe arc shouldn't be more than 180 deg.

**Comment by onox** [comment]
@gilbertohasnofb @wlbragg So what do we want? +45 to -135 (that's a range of 180) or +45 to -165 (that's a range of 210)?

**Comment by onox** [comment]
In the mean I read the forum and read what I had already just figured out:

>inner, outer, zero angles and outer gain are the beam parameters as outlined in Erik's model - the values are actually the sines of the ange (they're cutoffs for the dot product)

**Comment by onox** [comment]
Seems 180 deg is the maximum:

> (I don't want to fade to zero at 360 deg, light isn't sound, if it's directional there is no backward emission at all, so we have a zero angle beyond which the light is gone).

**Comment by HHS81** [comment]
I wonder how Thorsten propose how we can achieve this: 
![image](https://cloud.githubusercontent.com/assets/12649375/12793908/e1e0ee8a-cab2-11e5-9b13-2c9f0d4435aa.png)

**Comment by onox** [comment]
Any angle less 180 is OK, but that white light with an angle of 225 (> 180) is a problem.

@gilbertohasnofb @wlbragg Using a pointing direction at -45 deg (thus diagonal), I'll set the inner angle to 0 deg (in the direction of the nose) and outer angle to +45 (diagonal over the other wing).

**Comment by onox** [comment]
@gilbertohasnofb What should be the color of the tail light? This https://github.com/Juanvvc/c172p-detailed/issues/683#issuecomment-179354000?

**Comment by onox** [comment]
This is how the tail light looks:

![fgfs-screen-455](https://cloud.githubusercontent.com/assets/3361585/12795616/1e9a4210-cabb-11e5-92e5-0247705415d3.png)

I have set inner angle to 140 and outer to 180. That gives a sharp edge and for the tail light I would like the outer angle to be a bit higher than 180.

**Comment by gilbertohasnofb** [comment]
About the angles, I have no opinions about it because I haven't studied the problem in details like you guys did, and I haven't read through all the conversation. So I really don't know.

> What should be the color of the tail light?

The bluish/whitish light in the tail in our png texture use to have the following values: 0.790, 1.000, 0.790. Your picture looks really good, but maybe the light is too purplish, try these values I am writing here. Also, you may need to check your wings, they seem a bit... broken :wink:

**Comment by onox** [comment]
I know, I was about to test adding a translate animation for the nav lights so that we no longer need tons of `navlight_*` objects.

**Comment by onox** [comment]
It's a bit greenish:

![fgfs-screen-456](https://cloud.githubusercontent.com/assets/3361585/12796203/e279aa02-cabd-11e5-89e3-0b9e138c1217.png)

**Comment by gilbertohasnofb** [comment]
Sorry, one more typo.... the order was wrong, try: 0.790, 0.790, 1.000.

**Comment by gilbertohasnofb** [comment]
And what is that artifact in the light? I see a black dot or something.

**Comment by onox** [comment]
That's probably a vertex of the model intersecting the quad. That's why I asked if the thing was billboarded https://github.com/Juanvvc/c172p-detailed/issues/683#issuecomment-179357630 Maybe it is, but it's not at the front, on top of everything else in the screen.

**Comment by onox** [comment]
I can offset it a little bit, maybe that fixes it.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
Now it looks better:

![fgfs-screen-457](https://cloud.githubusercontent.com/assets/3361585/12796410/deb10f2c-cabe-11e5-8cc8-ea0cc9f36d8a.png)

Intersection still happens at extreme angles though.

**Comment by gilbertohasnofb** [comment]
Looking good!

**Comment by wlbragg** [comment]
If I understand all this I think for the nav lights, in our case, 180 should be more than enough. If we start straight out the wing and call it 0, the opposite wing is 180 we should need no more than a bit over 90 to achieve the nav light practical range (maybe 110-145?). Sounds like the shader does this no problem?
But the tail nav should be what, over 180? I didn't think we we're even using up to 180?

@onox, could you post a branch so I don't have to recreate what you've already done to test?

So far it looks pretty good.

>I wonder how Thorsten propose how we can achieve this (225deg): 

@HHS81, two lights?

**Comment by wlbragg** [comment]
As soon as we are sure of all limitations or know what it is we may still need that we don't have, I can approach Thorsten for clarification and requests! :fearful:

I'm I understanding that the nav light intensity is not producing the star effect but the strobes are? What about landing lights?

**Comment by wlbragg** [comment]
From c182
>ask him to allow also the use textures instead of shader magic?

@HHS81 can you explain, isn't that what we currently do? I want to make sure I am on the same page.

**Comment by HHS81** [comment]
@wlbragg:
- the term "procedural" means, that the shader creates the colors, pattern etc itself so there is no need for textures. 
So in the procedural lights there are absolutely no textures involved, all what you can see is defined by the shaders. This means, we can only change the appearence of those lights by the values and factors Thorsten gave us. 

- The star effect depends on the light intensity and the light color center. The more white the light color center is, the more star effect you have. 

- Currently it seems we can only have <180deg per light. So if we want to have >180deg, we have to add two lights. So if we want, let's say, a light coverage of 240deg, we do need two procedural light quads, and each of them an own procedural-light.eff applied, at the same location (X,Y,Z). Both with an outer angle of 120deg, but different, opposite pointings of 60deg.

**Comment by onox** [comment]
> @onox, could you post a branch so I don't have to recreate what you've already done to test?

I'll push it later, it's called `bug-683` (lowercase :wink:). I need to work on the translate animation. I'm trying to translate a fixed amount if the wing is damaged, but when the animation is disabled (wing is OK) then the light stays where it currently is, it doesn't get reset to its default position. It's like as if simgear reuses the transform matrix, but that's a wild guess.

So I guess I'm gonna need two properties to transmit the translate distance (0.0 for wing OK, 0.59 for wing damaged). Or try something with Nasal in the `<nasal>` block.

> a light coverage of 240deg, we do need two procedural light quads

I'll give that a try.

**Comment by onox** [comment]
Once I figure out the translate animation, @wlbragg can start deleting a lot of the `navlight_*` objects. Because then we only need the two regular ones (not all those for the damaged wings duplicates) and just translate its position.
