### ISSUE TITLE
Create new splash screen for the skis

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#686]
Create new splash screen for the skis since our current splash9 shows the old ski model

**Comment by gilbertohasnofb** [comment]
@wlbragg as you requested, I will replace splash9 with an image of the new skis. I have two shots so far, which one do you like best? The top one is a recreation of splash9, while the bottom one is from another angle. Let me know so I can create the splash and the PR!

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/12859187/cbb5f3f0-cc54-11e5-90b1-c33aa9c77b26.png)

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12859206/ea237db2-cc54-11e5-99fc-692177312814.png)

**Comment by wkitty42** [comment]
FWIW: i like'em both... maybe if one was a different craft than the other? then make both into splash screens :wink:

**Comment by wlbragg** [comment]
I like them both :smile: But if I have to choose one I guess it would be the first one. I really like seeing the top of the skis though and I think that one shows the ski off better than the first image. But I really like the angle of the top image and the entire composition of it.

**Comment by gilbertohasnofb** [comment]
Okay, so let's go with the first shot then! I will prepare it and make a PR soon.

**Comment by gilbertohasnofb** [comment]
Done, please see: https://github.com/Juanvvc/c172p-detailed/pull/688
