### ISSUE TITLE
Improve instrument gauges

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#690]
- fix tachometer's range. The instrument should display a range between 300 and 3500 RPM, and the green arc should be between 2100 and 2700. 

- the VS instrument could be improved as well (no lines after "10") and the numbers "5" and "15" needs to be bigger.

- the black Artificial Horizon looks a bit different than ours in the source images 

- our oil pressure has a green arc and yellow arc. In some photo's the yellow arc is green and they don't have any other arc.

- check for low resolution gauges

For images, see: http://www.airliners.net/search/photo.search?aircraft_genericsearch=%3D%28%22cessna+172+skyhawk%2Fcutlass%2Fhawk+xp+%28t-41%2Fmescalero%29%22+OR+%22reims+f172+skyhawk%2Freims+rocket%2Fhawk+xp%22%29&airlinesearch=&countrysearch=&specialsearch=&keywords=172P+cockpit&sort_order=photo_id+desc&page_limit=15&daterange=&range=&thumbnails=&engine_version=6.0

For the discussion, see: https://github.com/Juanvvc/c172p-detailed/pull/689#issuecomment-180994034

**Comment by gilbertohasnofb** [comment]
I will try to prepare the texture today and also to take a look at the xml code myself. In case I don't manage the second part, I will shout for help here :wink:

**Comment by onox** [comment]
@gilbertohasnofb Our oil pressure has a green arc and yellow arc. In some photo's the yellow arc is green and they don't have any other arc.

**Comment by gilbertohasnofb** [comment]
Yes, most of the images in that link show only the green arc. I will work on it as well.

**Comment by gilbertohasnofb** [comment]
As for all the gauges being in higher resolution, I will check them all today. But as far as I can remember, most looked fine to me. I will leave for lunch soon but when I am back I will work on this issue, hopefully we can close it still today.

**Comment by onox** [comment]
Okay.

**Comment by onox** [comment]
You could take a look at the HD panel. It shows just a green arc as well. (Although most of the instruments of the HD panel are from the 172S)

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Okay, so I decided to not only fix those instruments, but I will try to make ALL our instruments looking better. For starters, our instruments are simply a black background with full white text, which makes them look so unrealistic. This is what I got with the VSI so far:

![fgfs-screen-007](https://cloud.githubusercontent.com/assets/5700795/12873426/91c0159a-cdbc-11e5-97bb-8069270738df.png)

Much better, right? So I will continue here and try to remake everything still today

**Comment by gilbertohasnofb** [comment]
Perhaps @wlbragg could help me fixing https://github.com/Juanvvc/c172p-detailed/issues/373 in this same branch here (`bug-690`). The new texture of the AI is already pushed.

**Comment by gilbertohasnofb** [comment]
Also, the AI now uses png textures instead of the old rgb files. I updates the xml files and ac model, but I now realized we have a blend model for the AI inside `/dev/blender/instruments`. Could anyone update the blender model as well to use the png textures?

**Comment by onox** [comment]
VS looks better, but the background looks a bit as if it has a backlight.

**Comment by gilbertohasnofb** [comment]
I will tone it down a little bit (i.e. make it darker) but I kind of disagree with you, @onox. Often these old planes have an inconsistent "black" colour in the background of the instruments. See for instance this image (this is not because of glass reflection I believe): http://www.airliners.net/photo/Cessna-172P-Skyhawk/2000925/L/

So adding this little differences of brightness and saturation to the background gives us a more realistic look IMO. In the image above the TC stands out for being the only reworked instrument. I will keep working and once this is all done we can discuss these adjustments ok?

@wlbragg I noticed that some instruments aren't being affected by shadows (such as the TC). Is there an easy way to enable it, at least on their backgrounds?

**Comment by gilbertohasnofb** [comment]
TC slightly darker, and now with new ASI, altimeter and AI as well:

![fgfs-screen-009](https://cloud.githubusercontent.com/assets/5700795/12874240/4b5dabf8-cdd0-11e5-9d02-e9ef50648e80.png)

**Comment by wlbragg** [comment]
>Much better, right?

I think so.

>I noticed that some instruments aren't being affected by shadows

I thought all of them had the shadow turned off. We had to because the difference in shader calculations between the air frame and the individual instruments weren't synced and the shadows don't match, it looked really bad. I am afraid we would get the same thing using only the backgrounds
Can we only add the effect to the backgrounds, yes, but you have to find the object names of each one and add it to the effect. Originally I did that in each of the instruments own XML file. That is what we removed. But I added the flashlight code there instead so they would light up with the flashlight.

>Perhaps @wlbragg could help me fixing #373 in this same branch here

Yes, but it won't be until late tonight or Monday.

**Comment by gilbertohasnofb** [comment]
Okay guys, so I pushed new textures for **all** gauges. Personally, I think the results are much better than before, I hope you will all like it :smile:

Some shots:

![fg-3](https://cloud.githubusercontent.com/assets/5700795/12875512/83e02660-cdec-11e5-8d8d-553c54e20ce6.jpg)

![fg-4](https://cloud.githubusercontent.com/assets/5700795/12875511/83dc9432-cdec-11e5-9836-465297c80401.jpg)

![fg-5](https://cloud.githubusercontent.com/assets/5700795/12875513/8462023e-cdec-11e5-85a1-b330d3a46047.jpg)
 
What is still missing though and which I'd need help with is:

1) update some few Blend files and direct them to use the new png and not the deleted rgb textures. All png filenames are the same as the old rgb as well as their location, the only difference is their extension. The affected blend files are: 

- `/dev/blender/instruments/AI.blend`
- `/dev/blender/instruments/hi.blend`
- `/dev/blender/instruments/tc.blend`

2) AI mapping could be improved (see #373 )

3) the tail of the airplane in the turn coordinator is a bit shorter than the texture, compare the texture file `/Models/Interior/Panel/Instruments/tc/tc03.png` with this: 

![fg](https://cloud.githubusercontent.com/assets/5700795/12875595/88930bc6-cdee-11e5-96e2-0528f74ddf93.jpg)

4) two instruments have plain colour backgrounds for which I created new textures, but they aren't applied yet. They are the ADF gauge and the DME part of the radio stack. The new files are `Models/Interior/Panel/Instruments/kr87-adf/adf-background.png` and `Models/Interior/Panel/Instruments/dme/dme-background.png`. This is where the plain backgrounds are:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/12875528/010c78c8-cded-11e5-9a83-a93606f85283.jpg)

5) the needles of the RPM gauge and of the VSI look very ugly since they aren't texturized. I created the files `Models/Interior/Panel/Instruments/RPM/needle.png` and `Models/Interior/Panel/Instruments/VSI/needle.png` but they need to be applied in Blender. This is how the gauges look now:

![fg-1](https://cloud.githubusercontent.com/assets/5700795/12875554/24dea77a-cdee-11e5-89d8-70d99c6c8263.jpg)

@wlbragg So do you think tomorrow you could give me a hand with this, and then we make a PR and merge this in time for 2016.1.1? @onox could you also help by already testing this branch and checking if you don't spot any mistake, as I also had to touch a couple of xml files?

**Comment by onox** [comment]
I'll check the branch.

**Comment by gilbertohasnofb** [comment]
:+1: Thanks!

**Comment by onox** [comment]
I'll create a PR so I can more easily see (on Github) how the png files were changed.

**Comment by wlbragg** [comment]
>So do you think tomorrow you could give me a hand with this, and then we make a PR and merge this in time for 2016.1.1?

Yes, what time Monday do you think you will be on here, I will make a point to be here? I am -6 GMT,  "Central Standard".

**Comment by gilbertohasnofb** [comment]
@onox That makes things easier indeed, thanks!

@wlbragg I live in Prague (GMT +1). Tomorrow I am home until 4pm (so until 9am for you) then I should be back in the evening at around 8 or 9pm (so 1-2 pm for you). During any of these times I will be online. Does that suit you?

**Comment by onox** [comment]
I'll be here after 1800 GMT+1.

**Comment by gilbertohasnofb** [comment]
Ok!

**Comment by onox** [comment]
@gilbertohasnofb The altimeter doesn't light up under the flashlight. It seems you removed the effect in https://github.com/Juanvvc/c172p-detailed/commit/1e3cc4765ceb277ff54341293e21f494fc66594b

**Comment by gilbertohasnofb** [comment]
My bad, I somehow added an old xml file by accident. I will fix it now.

**Comment by onox** [comment]
You also might need to fix that issue with the animation in that same commit.

When I press ctrl+c, the knobs for the altimeter are two squares again. The heading indicator has the same problem.

**Comment by gilbertohasnofb** [comment]
Well, by reverting only the alt.xml I got the flashlight working again as well as the circular knobs. As for the HI, I didn't touch its xml file so I guess this problem was there before. Do you know how to fix it?

**Comment by gilbertohasnofb** [comment]
alt.xml has been reverted.

**Comment by onox** [comment]
Let me check.

**Comment by wlbragg** [comment]
>Does that suit you?

Yes, I'll be here.

**Comment by gilbertohasnofb** [comment]
Cool! Thanks for the help, by the way :smile: :+1:

**Comment by onox** [comment]
I'm fixing the HI knobs. All the instrument look great btw! :clap:

**Comment by gilbertohasnofb** [comment]
I am glad to hear you like them, thanks! :bow:

**Comment by onox** [comment]
Pushed.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
I'm working on this now.
Just finished AI and I am testing.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
Is it just these 3 that need done?


    /dev/blender/instruments/AI.blend
    /dev/blender/instruments/hi.blend
    /dev/blender/instruments/tc.blend

**Comment by wlbragg** [comment]
I'm a bit confused on the hi, it shows that the .ac already refers to the png's and not the rgb's?

**Comment by gilbertohasnofb** [comment]
Yes, those 3 blend files are all you need to worry about 

> I'm a bit confused on the hi, it shows that the .ac already refers to the png's and not the rgb's?

That's really bizarre. until yesterday all textures of the HI were rgb and not png, how come the blend file was already routed to non existent png files?!

**Comment by gilbertohasnofb** [comment]
I manually updated all .ac files of our gauges, so just bother with the .blend files, everything else should be fine :wink:

**Comment by gilbertohasnofb** [comment]
By bothering I mean "replace *.rgb by *.png"

**Comment by wlbragg** [comment]
OK, I am having a problem with the tc, it won't export the blend to an ac (but I get no errors). It looks like tc5.png might be the culprit, but I don't know why.

You didn't push your changes yet? Are you going to push after mine?

If so, why don't you push now and I will re-pull and see if it fixes the tc problem for me.

**Comment by wlbragg** [comment]
In other words pull my last two commits, then push yours, then I will pull again and try to fix the tc again.

**Comment by gilbertohasnofb** [comment]
> You didn't push your changes yet? Are you going to push after mine?
> [...]
> In other words pull my last two commits, then push yours

I didn't push anything today to this branch, all my work was done yesterday and so I have nothing to push. I have no idea why the blend file isn't exporting :cry:

**Comment by gilbertohasnofb** [comment]
@wlbragg I am so sorry but I already must go, it got quite late here... I will come back in the morning (in some 8h from now), and tomorrow I must be most of the day online.

**Comment by wlbragg** [comment]
>That's really bizarre. until yesterday all textures of the HI were rgb and not png, how come the blend file was already routed to non existent png files?

OK, I think I see what happened. You already mapped the AC file by hand, when I tried to export my GIT GUI reported no change in the AC file, that is because you already changed the paths in the AC but not the blend. I have an idea to fix the TC, I'll try again.

**Comment by wlbragg** [comment]
OK, no problem. I think I have it under control. Anything you need me to do before you come back?

**Comment by gilbertohasnofb** [comment]
> OK, I think I see what happened. You already mapped the AC file by hand, when I tried to export my GIT GUI reported no change in the AC file, that is because you already changed the paths in the AC but not the blend. I have an idea to fix the TC, I'll try again.

I guess so. What I did was to open the .ac files and substitute any ".rgb" string for ".png" so I could test my new textures. So I guess everything is fine.

> OK, no problem. I think I have it under control. Anything you need me to do before you come back?

If you can have a look at the comments 3) 4) and 5) from https://github.com/Juanvvc/c172p-detailed/issues/690#issuecomment-181131002 it would be great. Basically they are all related to UV-mapping, all textures are ready and it should be easy to do those without me here.

**Comment by gilbertohasnofb** [comment]
Take care and talk to you all tomorrow!

**Comment by onox** [comment]
@wlbragg Are you still working on (4) and (5)?

**Comment by wlbragg** [comment]
4) two instruments have plain colour backgrounds for which I created new textures, but they aren't applied yet.

The ADF gauge was textured in such a way I am not sure your getting what you hoped for. 
Here is how it is now mapped and as you can see, it may not be what you expected.
![adf1](https://cloud.githubusercontent.com/assets/11069680/12906490/7063a8ae-cea6-11e5-8679-bcec62eafc4b.jpg)
![adf2](https://cloud.githubusercontent.com/assets/11069680/12906495/744b7730-cea6-11e5-8194-9bb845586538.jpg)
![adf3](https://cloud.githubusercontent.com/assets/11069680/12906498/7751deec-cea6-11e5-9539-b2cee6597556.jpg)
And you end up with this.
![adf5](https://cloud.githubusercontent.com/assets/11069680/12906529/c903e4f6-cea6-11e5-9e03-c8a190644d23.jpg)

**Comment by wlbragg** [comment]
Sorry I just noticed your comment.
Yes 4 and 5 are finished.

**Comment by wlbragg** [comment]
Oops, sorry, 3 and 4 are finished, starting on 5 now.

**Comment by wlbragg** [comment]
DME/ki226 was a detailed fix. I used the frame from the auto pilot and added @gilbertohasnofb new texture to it, adjusted everything to fit z. I think it is better than it was but the dme portion needs to have the label texture match the background texture better. Also we should combine dme.ac and ki226.ac and blends together at some point, but not tonight.

**Comment by onox** [comment]
:+1:

**Comment by wlbragg** [comment]
OK, 5 is finished I also noticed a few objects that didn't have the flashlight effect applied to them, so I added them here. I think there may be a few more but I need to take some time to investigate. So probably not before this version is merged.
As far as I am concerned this work is finished and the PR can be merged upon testing and verification.

**Comment by onox** [comment]
@wlbragg I get: `can't find base effect ../../../../Effects/interior/c172p-flashlight`

**Comment by wlbragg** [comment]
OK, let me see if I get it, It all seemed to work but I didn't check for any error output.

**Comment by onox** [comment]
It works when you make the path absolute: `Aircraft/c172p/Models/Effects/interior/c172p-flashlight`

**Comment by onox** [comment]
You can commit the fix.

**Comment by wlbragg** [comment]
It's done.

**Comment by legoboyvdlp** [comment]
My, this all looks wonderful. Nice job.

**Comment by gilbertohasnofb** [comment]
Thanks, @legoboyvdlp
