### ISSUE TITLE
rework rudder

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#7]
3D05 - when moving the rudder, part of the fuselage moves as well. The back of the plane should be redesigned, the rudder should go all the way to the bottom, see: 

http://s3.postimg.org/oy7ao6x6b/image.png

**Comment by wlbragg** [comment]
Can we close this?

**Comment by gilbertohasnofb** [comment]
Yes, Juan has fixed it here: https://github.com/Juanvvc/c172p-detailed/issues/106
