### ISSUE TITLE
New glass reflections look bad at night

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#701]
New glass reflections look bad at night:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12931634/0addadf2-cf7f-11e5-8bb8-d742456b9417.png)

They are really strong. Also, as I discussed previously with @wlbragg, we should recreate the reflection cube using 4X-CHV's cockpit (as it's the default livery) as well as add the instruments to the reflection (see #699 )

**Comment by wlbragg** [comment]
If we want to correct this now and get it include I can try to fix it also.

**Comment by gilbertohasnofb** [comment]
If you can, that would be nice.
