### ISSUE TITLE
ceiling looks black

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#704]
Ceiling looks black while the panel with the speaker doesn't. I don't think the ceiling should be pitch black during day at any circumstances.

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12934924/568bed0a-cf92-11e5-8e42-d4adfb4c85b9.png)

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry but suddenly I am discovering bug after bug :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
It's been there all along, it is the irradiance map. I tried to adjust the strength but it doesn't seem to be working. This one will take some time to fix and may require Thorsten to do some shader work.

Without irradiance map
![norad](https://cloud.githubusercontent.com/assets/11069680/12935390/fdc757fe-cf5a-11e5-83ab-686da482d655.jpg)

With irradiance map
![withrad](https://cloud.githubusercontent.com/assets/11069680/12935394/0451e4ae-cf5b-11e5-8534-4ff7d1f79397.jpg)

**Comment by gilbertohasnofb** [comment]
I think I never looked up after the irradiance map was added :laughing: No problems then, let's add a later milestone to this issue.

**Comment by wlbragg** [comment]
:-1:

**Comment by legoboyvdlp** [comment]
Who's looking at the cieling anyway :laughing:

**Comment by gilbertohasnofb** [comment]
Well, the guy who created that beautiful texture for the speaker, I suppose! :stuck_out_tongue_winking_eye:

**Comment by wlbragg** [comment]
FYI: This is done with the default (built in), however we can do this with a mask and choose where we want it applied and how strong. But we will need someone good at making masks.

**Comment by wlbragg** [comment]
I'm not sure why this wasn't immediately fixed when discovered. If I remember correctly it appeared the strength setting wasn't working before. Well it is now. The simple fix is to change the strength setting.
I'm pushing the fix now.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/730
