### ISSUE TITLE
New pitot tube model undone in model

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#706]
@wlbragg In `bug-492` you added D-ECHO's new pitot tube model, but now it seems that addition has been undone by the work in `bug-633`.

![fgfs-screen-485](https://cloud.githubusercontent.com/assets/3361585/12946755/0de63ba4-cff7-11e5-9959-a6e08cc356cc.png)

**Comment by onox** [comment]
Extract the new pitot tube (the cover is in a separate file, thus OK) from `dev/blender/c172p.blend` in commit 88a7c23df7ce45cb6ae21ec0c1261e07ad90ad24:

1. `git checkout -b bug-706`

2. Download the old [c172p.blend](https://github.com/Juanvvc/c172p-detailed/blob/88a7c23df7ce45cb6ae21ec0c1261e07ad90ad24/dev/blender/c172p.blend?raw=true) file

3. Extract the pitot tube object (`PitotTube`). (Just that pitot tube, nothing else).

4. Add it to current c172p.blend file (`dev/blender/c172p.blend`)

**Comment by onox** [comment]
Write down the Blender coordinates of the improved `PitotTube` object in the old file, so you can easily restore its position.

**Comment by wlbragg** [comment]
OK, number 2 on the list after DME.

**Comment by wlbragg** [comment]
How in the heck did we manage this, unless I did it wrong, 706 has the wrong one?
Investigating.....

**Comment by wlbragg** [comment]
Why can't I find the new tube?

**Comment by gilbertohasnofb** [comment]
I think the old one got merged above it. I suspect you will have to look at the history of `c172p.blend` and find a version with the correct tube

**Comment by gilbertohasnofb** [comment]
Somewhere here https://github.com/Juanvvc/c172p-detailed/commits/master/dev/blender/c172p.blend

**Comment by wlbragg** [comment]
I just found it.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/709

**Comment by onox** [comment]
> Why can't I find the new tube?

In https://github.com/Juanvvc/c172p-detailed/issues/706#issuecomment-182335741 I gave you a direct link to an older file that contains the improved pitot tube :stuck_out_tongue_closed_eyes:

**Comment by wlbragg** [comment]
I don't know what I did wrong, but tell me I finally got the right one?

**Comment by onox** [comment]
I think so, it looked better than what I saw when I files the bug.

**Comment by onox** [comment]
The problem was that `bug-633` was started before `bug-492` got merged. So `bug-633` started with a Blender file that contained still the old pitot tube.

**Comment by onox** [comment]
And `bug-633` was merged after `bug-492`, so we undid the adding in `bug-492`. Hope that explains it.

**Comment by wlbragg** [comment]
Yes, as long as that is the only regression.
