### ISSUE TITLE
Adjust spacing between equipment in radio stack

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#713]
Spacing and alignment between equipment on radio stack could stand to be spaced a little more evenly.

**Comment by wlbragg** [comment]
![stack1](https://cloud.githubusercontent.com/assets/11069680/12964932/57125544-d018-11e5-9209-241229681015.jpg)
Before

![stack2](https://cloud.githubusercontent.com/assets/11069680/12964937/602ec338-d018-11e5-90a3-7cd0d3fab999.jpg)
After

**Comment by gilbertohasnofb** [comment]
I do like it better as well!
