### ISSUE TITLE
Attitude Indicator lack of pitch marker in release 2016.1

### ISSUE THREAD

**Issue by tonghuix** [Juanvvc/c172p-detailed#719]
I just compile and install FlightGear 2016.1 in Linux. I found there is some different in Attitude Indicator from v3.6. Finally I realize the AI lack of pitch marker. Well, the real 172p is normal, see: http://www.airliners.net/photo/Cessna-172P-Skyhawk/1568374/L/&sid=c9c603b628d868eaebc1088476c80d5c

Screenshot for 2016.1
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/423703/13161483/f558679a-d6d8-11e5-93f7-4c7dfdea5c7e.png)

Screenshot for 3.6
![fgfs-screen-022](https://cloud.githubusercontent.com/assets/423703/13161495/13b1c7ea-d6d9-11e5-9fb1-26fc9e440fe0.png)

**Comment by onox** [comment]
@gilbertohasnofb Is this a problem with one of the textures?

**Comment by wlbragg** [comment]
Wow, how did we miss that?

I'm looking at it now..

**Comment by wlbragg** [comment]
Looks like AI2.png is missing the pitch lines or we need to use AI2-2.png?

**Comment by wlbragg** [comment]
This is what the c182 is using.
![ai2](https://cloud.githubusercontent.com/assets/11069680/13166558/cf78bea2-d68e-11e5-996b-dc258f22cf94.png)

**Comment by wlbragg** [comment]
This is the RGB used in the c152, I converted it to a png and we can use it in the c172p?
![ai2](https://cloud.githubusercontent.com/assets/11069680/13166632/7923120e-d68f-11e5-8d04-d5495db2f944.png)

**Comment by wlbragg** [comment]
This is what it looks like now after I finished it.
![newai](https://cloud.githubusercontent.com/assets/11069680/13166750/e94d7b86-d690-11e5-9140-5c44e0e047e4.jpg)

**Comment by tonghuix** [comment]
@wlbragg Good job! However I think it is not as real as it should be, your pitch marker a little bit higher and lager. 

Ref: ![](http://cdn-www.airliners.net/aviation-photos/photos/4/4/2/1995244.jpg)

**Comment by wlbragg** [comment]
Right, I agree.

@gilbertohasnofb, job opportunity! :smile:

**Comment by gilbertohasnofb** [comment]
> Is this a problem with one of the textures?

No, there is not. As they say, this isn't a bug, it's a feature. This type of AI is commonly found in the model P, hence why I decided to use it. See:

![](http://www.airliners.net/photo/Cessna-172P-Skyhawk/2558033/L/&sid=051e145e5929615a6979a29e123970f6)

![](http://www.airliners.net/photo/Cessna-172P-Skyhawk/2558033/L/&sid=051e145e5929615a6979a29e123970f6)

There are several types of AI used by Cessna in these models according to the images I have seen: the one without lines, then two models with lines (one black and one brown). I simply tried to have coherent old styled gauges for all instruments. 

For me this is a won't fix, but if you insist we can add the lines back (but please don't copy the 152 model, I don't think we should use those shadows around it as the 172 model is not spheric at all).

**Comment by wlbragg** [comment]
Oops, I didn't know any of this. I have no problem leaving it as it was.

The only comment I might add is, do pilots rely on the pitch tic marks for any kind of climb reference?

You can all decide and just delete the PR if you decide against the lines.

**Comment by Juanvvc** [comment]
> do pilots rely on the pitch tic marks for any kind of climb reference?

We don't. VS is the important parameter

**Comment by gilbertohasnofb** [comment]
:+1:
