### ISSUE TITLE
Add objects from the c182 (cones, ladder, fuel tank, etc.)

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#725]
Add objects from the c182 (cones, ladder, fuel tank, etc.)

@onox wrote:
>  Does the c172p has a need for that external power unit? If you add the models, you might want to add it to Models/generic/ to indicate they can be re-used by other aircraft.

See: https://github.com/HHS81/c182/issues/55

**Comment by tigert** [comment]
The external power unit not so much. There is the plug socket in the aircraft, but you rarely if ever need to power it through that.

**Comment by HHS81** [comment]
From Cessna 182S/T POH:

>_ When air temperatures are below 20°F (-6"C), use an external
preheater and an external power source whenever possible to
obtain positive starting and to reduce wear and abuse to the engine
and electrical system. _

Not sure about the Cessna 172P...

**Comment by tigert** [comment]
Yeah, preheater yes. I guess each country has their own practices (I remember reading somewhere that in Alaska, some folks have a quick drain valve in the oil reservoir so they can take their engine oil inside for the night and preheat it in the stove before going flying in the morning :-)

We have an internal "Defa" (basically a car interior heater - a hot air blower) both in the cabin via the regular car plug and interior 220V socket, and another one bolted to the firewall, inside the engine cowling. The engine cowling has then a wrap-around insulated cover (basically a "winter jacket") that blocks the holes.

The interior heater keeps moisture away, so you don't get instant fog on windows when you step inside a freezing cabin. And it is good for the avionics too, electronics do not really like condensated water all over themselves.

**Comment by legoboyvdlp** [comment]
That Cessna looks nice and comfortable :)

**Comment by gilbertohasnofb** [comment]
Duplicate of https://github.com/Juanvvc/c172p-detailed/issues/717
