### ISSUE TITLE
flap lever doesn't have hotspots

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#732]
flap lever doesn't have hotspots and cannot be controlled via click or drag.

**Comment by gilbertohasnofb** [comment]
If memory serves me well, before we didn't have the standard hotspots but actually we could grab the flap lever and then drag it up or down, which "felt" realistic. I think the modification which removed this behaviour was in this PR: https://github.com/Juanvvc/c172p-detailed/pull/653/files

**Comment by gilbertohasnofb** [comment]
We can also take a look at the c182 flap lever.

**Comment by onox** [comment]
I'll fix this.
