### ISSUE TITLE
adjust tutorials to use newly moved marker...

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#733]
this just in from the fgfs-dev list...

>From: Torsten Dreyer <torsten@t3r.de>
>Date: Wed, 23 Mar 2016 10:03:39 +0000
>To: FlightGear developers discussions <flightgear-devel@lists.sourceforge.net>
>Subject: Re: [Flightgear-devel] Remove Models
>
>Oh - that one :-/
>
>Probably a much better place woud be Aircraft/Generic.
>I just pushed a fixe to move marker.xml and marker.ac to Aircraft/Generic and adjust all references in FGData.
>Will work on fgaddon now and push the fix.
>
>Attention c172p developers: Please adapt that change upstream!
>
>Torsten
>
>P.S.: thanks for spotting.
>
>Alan Teeder <ajteeder@v-twin.org.uk> schrieb am Mi., 23. März 2016 um 10:27 Uhr:
>
>> Also missing
>> fgdata/Models/Aircraft/marker.xml.
>>
>> I think that this is the marker used in the tutorial system.
>>
>> Without it FGRun complains and will not load aircraft.  Is this a ploy to
>> make us use the aircraft centre? ;-)
>>
>> Alan

effectively, it should be little more than changing

`<path>Models/Aircraft/marker.xml</path>`
to
`<path>Aircraft/Generic/marker.xml</path>`
where ever it is needed... i don't know anything about the tutorial system...

**Comment by gilbertohasnofb** [comment]
I suddenly started getting an error message `Failed to load file: "Aircraft/Generic/marker.xml"`, did the devs decide to move this file yet once again?!

**Comment by wkitty42** [comment]
On 05/15/2016 07:00 AM, Gilberto Agostinho wrote:
>I suddenly started getting an error message |Failed to load file:
"Aircraft/Generic/marker.xml"|, did the devs decide to move this file yet once
again?!
 >

i have one in FGData... there was a commit that was undone which put files back 
into place but the commit for the other half of the move was not undone so there 
are some duplicate files... the marker file is not one of them AFAIK... it was 
mainly pushbacks, towropes and similar that were restored due to apparent 
hardcoding of where they are looked for...

**Comment by gilbertohasnofb** [comment]
@wkitty42 thanks for the info, but as I wrote in my updated message above (maybe you missed it) the problem was that I downgraded my flightgear installation to version 2016.1.1 due to some problems I had with the PPA I use, and forgot that the marker was moved after the release of that version. So there are no problems at all, just my mistake :smile:

**Comment by wkitty42** [comment]
yeah, i missed that because i read the original in email and responded from there... if you downgraded your fgfs, then you apparently also downgraded your fgdata?? that's the problem... you'll have to either manually copy or move the marker file from the old location to the new and either keep two of them or...
