### ISSUE TITLE
Change tutorial airport for FlightGear 2016.2

### ISSUE THREAD

**Issue by ElGaton** [Juanvvc/c172p-detailed#745]
#In line with the new versioning scheme, the default scenery/airport is going to be changed at each release - the tutorials, however, still refer to Livermore Municipal Airport. This may cause the user to experience a "missing scenery" scenario in case TerraSync is not switched on.

Consider moving the tutorial location to LEBL, or a nearby airport in the same tile (e.g. Sabadell), and amending the release process. (Another alternative might be omitting the airport tags from the tutorial files entirely and making it location independent).

**Comment by gilbertohasnofb** [comment]
> This may cause the user to experience a "missing scenery" scenario in case TerraSync is not switched on.

I agree with you, this what you wrote is for me is the key point. Probably changing it to LEBL would be a good idea.

**Comment by gilbertohasnofb** [comment]
@dg-505 what do you think about it?

**Comment by ElGaton** [comment]
Any progress on this? (The 2015.2 release is near. I can move the location or make the tutorial location independent, if needed, but I'd like the fix to land in the new version).

**Comment by onox** [comment]
I'll work on this.

**Comment by onox** [comment]
It seems `<init>` doesn't work in the tutorials. Can anyone confirm?

**Comment by onox** [comment]
I have partially fixed the tutorials in branch `bug-745`. I have changed the taxi locations in the taxiing tutorial, but not updated all the heading checks and messages. Someone else should do that.

Aircraft should start in taxiing and runup tutorials, have not checked other tutorials.

Anyone who wants to test the branch can switch to it if using git or download https://github.com/Juanvvc/c172p-detailed/archive/bug-745.zip (make sure to remove the old c172p in FGDATA)

**Comment by onox** [comment]
@gilbertohasnofb Would you be able to update `taxiing.xml` a bit?

**Comment by gilbertohasnofb** [comment]
I can try having a look at it, but I never dealt with the tutorials before, so I'd need to learn things by scratch. Maybe @dg-505 would be interested in doing it though, since he worked on the tutorials before. If he can't then I can take a look at it myself.

**Comment by gilbertohasnofb** [comment]
@onox after this has been fixed, is there still any other very important issue we must tackle before releasing the aircraft for the next release? I think we should contact stuart as soon as possible about it.

**Comment by onox** [comment]
Not that I can think of.

**Comment by dg-505** [comment]
Hey guys
I'll have a look over the tutorials. Personally I would prefer the tutorials to be at another airport (my suggestion would be Sabadell) because it is more realistic to fly a C172 at a smaller airfield than LEBL.

**Comment by gilbertohasnofb** [comment]
@dg-505 I agree with you, our previous tutorial was also not set at KSFO either. I just checked LELL and it seems to be a nice option indeed, well developed and everything. Given that we will have to change these tutorials every 3 months, I think a good guideline is:

- if the main airport of the next FG edition normally handles GA, then choose it
- else find a smaller airfield that typically handles GA somewhat near the main one
- make sure the airfield is not too close to the borders of the default tiles, so that the scenery won't just simply "finish" for someone without connection

**Comment by dany93** [comment]
GA = "General Aviation?" I would explicit it.

> make sure the airfield is not too close to the borders of the default tiles, so that the scenery won't just simply "finish" for someone without connection

I'd write "....with Terrasync not activated". Although beginners will not understand Terrasync and what or where this tile is... That's the drawback of changing the airport.

**Comment by gilbertohasnofb** [comment]
@dany93 these guidelines I propose are just for us, not for any warning messages or anything like that. I just means that when _we_ select the next tutorial airfields (which should always be in the default tiles), we can use these ideas when picking up one.

>  beginners will not understand Terrasync and what or where this tile is... That's the drawback of changing the airport.

That's exactly why I say it must be well within the default tiles, so even people without internet connection can fly around for a bit without seeing the tile borders.

**Comment by dany93** [comment]
>@dany93 these guidelines I propose are just for us

Right. Sorry for my misunderstanding.

**Comment by gilbertohasnofb** [comment]
No worries! :smile:

**Comment by dg-505** [comment]
Gentlemen, we have a problem. It's about the Radios tutorial.
When the tutorial is located at Sabadell (LELL), one has to listen in on the ATIS of Barcelona-El Prat becaus LELL doesn't have an own ATIS. But when I'm on the ground on LELL, I can't hear the LEBL-ATIS. When I jump in the air with "CTRL-U", then I can hear the ATIS.

What can we do to adress this?

Shall we nevertheless locate the "Radios"-tutorial on LEBL, although all the other tutorials are on LELL?
Or does anyone have another solution?

Cheers
Jonathan

**Comment by gilbertohasnofb** [comment]
Hmm, if this bug is really reproducible then it's something beyond this project of ours. The solutions that come to mind are:

- find other airfield than LELL for all tutorials
- use LEBL for all tutorials
- use LEBL only for the radio tutorial, as you propose

Would you have any other airfield in mind? It doesn't have to be literally in Barcelona, just like our previous wasn't exactly in San Francisco

**Comment by dg-505** [comment]
Well, AFAIK Livermore has an own ATIS, so this wasn't a problem in previous FG versions.

I'm pretty sure that this isn't a bug: In reality, a radio transmitter has limited range along the ground because of obstacles on the ground (buildings, mountains, etc. The higher the reciever is, the longer is the reception range.

**Comment by gilbertohasnofb** [comment]
> Well, AFAIK Livermore has an own ATIS

I am confused. You had previously written that "[...] one has to listen in on the ATIS of Barcelona-El Prat becaus LELL doesn't have an own ATIS."

> so this wasn't a problem in previous FG versions.

If something wasn't a problem before and now is, isn't that a bug?

**Comment by dg-505** [comment]
Well, that was written a little ambiguous....

What I meant:
Our previous tutorial airport for the C172 was Livermore Municipal (KLVK). So, KLVK has it's own ATIS, and therefore the limited range of radio transmitters along the ground wasn't a problem because you easily recieve the ATIS of KLVK

But now our tutorial airport is LELL.
LELL however has no own ATIS, and so you need the ATIS from LEBL to get weather information. The problem is that you can't recieve the ATIS of LEBL in Sabadell.


Was that a bit easier to understand? :wink:

**Comment by gilbertohasnofb** [comment]
Yes, now it's all clear! Thanks :smile: 

> LELL however has no own ATIS, and so you need the ATIS from LEBL to get weather information. The problem is that you can't recieve the ATIS of LEBL in Sabadell.

But what do you think is the reason you can't receive the ATIS there if in RL you are expect to do so? Is it something with our plane? Or with FG?

**Comment by dg-505** [comment]
Sorry, I meant that I assume that it is correct (and I think in real life that's the same) that you can't hear the ATIS of Barcelona-El Prat in Sabadell:
>In reality, a radio transmitter has limited range along the ground because of obstacles on the ground (buildings, mountains, etc.) The higher the reciever is, the longer is the reception range.

And because of that reason you can't hear the ATIS from LEBL on LELL.

**Comment by gilbertohasnofb** [comment]
I see, I see... well, in that case we must start at least this specific tutorial in a different airport. LEBL is the obvious choice; Girona airport (LEGE) also has ATIS, but I think it also doesn't normally handle GA, though I have seen some photos of GA aircraft parked there.

**Comment by dg-505** [comment]
So my suggestion would be to do only the radio tutorial on LEBL and all other tutorials on LELL

**Comment by gilbertohasnofb** [comment]
Yes, I think that's probably the best solution as well.

**Comment by dg-505** [comment]
Okay, than I'll do it that way.

**Comment by dg-505** [comment]
I created a pull request for branch _bug-745_:
https://github.com/Juanvvc/c172p-detailed/pull/755

**Comment by onox** [comment]
@dg-505 Good suggestion to move to that little airport :+1: 

About the tutorials: the taxiing tutorial mentions that the pilot has to turn to heading 320. Perhaps just say something like "Turn left (heading 320) onto the taxiway". Something like that. The phrase is currently also quite long on the screen.

About the altimeter tutorial: it says 30.32 should correspond with 15 ft, but I think the 15 ft is incorrect. (I think that may have been my mistake, but I was a bit clueless). Setting the altimeter correctly resulted in messages like "too low" and "too high". Perhaps widen the upper and lower bound a bit?

**Comment by dg-505** [comment]
I'll take a look

**Comment by onox** [comment]
Btw, can we find the actual QNH for LEBL in the property tree somewhere? Then we could remove that altitude check/msg and just let the pilot adjust the altimeter to the required QNH.

**Comment by onox** [comment]
Or at least just not mention "15 feet" and increase the bounds a bit, like 30.31 and 30.33.

**Comment by onox** [comment]
Can't find the correct QNH in the property tree, so should we write "Pretend the ATIS message said..."?

**Comment by dg-505** [comment]
The QNH property is, AFAIK **metar/pressure-inhg**

See also https://forum.flightgear.org/viewtopic.php?f=69&t=29554

**Comment by ElGaton** [comment]
Yes, it's **metar/pressure-inhg** (which is, however, a double and, thus, suffer from rounding errors).

The ideal way to perform this check would be to test if the actual altimeter setting is in the range [ATIS QNH - 0.099; ATIS QNH + 0.099] or something like that, but the conditions framework (see $FG_ROOT/Docs/README.conditions) seems not to be flexible enough. Another way could be checking the altitude indicated by the altimeter (as the 777 does):

```
<condition>
    <and>
        <greater-than>
            <property>instrumentation/altimeter/indicated-altitude-ft</property>
            <value>60</value>
        </greater-than>
        <lower-than>
            <property>instrumentation/altimeter/indicated-altitude-ft</property>
            <value>70</value>
        </lower-than>
    </and>
</condition>
```
Note, however, that the lower and upper limits almost certainly depend on the terrain (I have performed this test using the LEBL Scenery Pack and the QNH value given by the spoken ATIS, which differed a bit from the one displayed in the Weather dialog).

**Comment by ElGaton** [comment]
Yes, it's **metar/pressure-inhg** (which is, however, a double and, thus, suffers from rounding/machine representation errors).

The ideal way to perform this check would be to test if the actual altimeter setting is in the range [ATIS QNH - 0.099; ATIS QNH + 0.099] or something like that, but the conditions framework (see $FG_ROOT/Docs/README.conditions) seems not to be flexible enough for this purpose. Another way could be checking the altitude indicated by the altimeter (as the 777 does):

```
<condition>
    <and>
        <greater-than>
            <property>instrumentation/altimeter/indicated-altitude-ft</property>
            <value>60</value>
        </greater-than>
        <lower-than>
            <property>instrumentation/altimeter/indicated-altitude-ft</property>
            <value>70</value>
        </lower-than>
    </and>
</condition>
```
Note, however, that the lower and upper limits almost certainly depend on the terrain (I have performed this test using the LEBL Scenery Pack and the QNH value given by the spoken ATIS, which differed a bit from the one displayed in the Weather dialog).
