### ISSUE TITLE
Feature Request: display local time

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#747]
See
https://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2595#p284594
and the potential solution is in the next post.
https://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2595#p284596

**Comment by wkitty42** [comment]
so folks don't have to go to the forum to see what this is all about, it is about the clock in the craft... i, too, would like to see the clock display in my chosen locale... i say it like this because if one has chosen --time-match-real or --time-match-local then the display may be different than expected... plus there's the other options of dawn, morning, noon, afternoon, dusk, evening, midnight and the location you are starting in...

**Comment by gilbertohasnofb** [comment]
I will try to take care of this, but I don't think we need Nasal to solve it as D-ECHO proposes.

**Comment by wlbragg** [comment]
I guess I am not sure what the issue is. I ran a test to see what the clock is doing and it did what I expected it to do. What am I missing?
It appeared to take my local computer time and calculates the time at the chosen location based on my local time (my computer time). What is it others are expecting it to do?

**Comment by wkitty42** [comment]
there were times that i expected the clock and day/night to mimic my locale no matter where i am in the world... that way i could easily tell when it was time to go to bed or eat dinner or something else while a long flight was ongoing... other times, meh, let's see the dark over there while it is light here... my thing, such as it is, is to see the clock with the right time for where i am instead of UTC all the time... these are things for the sim, though... or i dunno... maybe not...

**Comment by gilbertohasnofb** [comment]
Well, right now the clock in the aircraft should matter FG's local time which is done by this filter:
```
    <filter>
        <name>Clock: UTF to local time conversion</name>
        <type>gain</type>
        <input>
            <property>sim/time/utc/day-seconds</property>
            <offset>
                <property>sim/time/local-offset</property>
            </offset>
        </input>
        <output>
            <property>/sim/model/c172p/local-time-seconds</property>
        </output>
    </filter>
```

So the clock should never show system time nor utf time, it should simply reflect the local FG time. If anyone is seeing anything different, please report how to reproduce it.

**Comment by wkitty42** [comment]
i'm maybe 50 miles as the crow flies from KRDU... current local time is 14:53EDT (UTC-0400)... that's 18:53UTC... the clock in the craft is reading 1:53... the ENVIRONMENT->Time is reading 13:53... both of them are one hour off and should be reading 2:53/14:53...  apparently neither the sim nor the craft are taking daylight saving into account at the proper times of the year...

NOTE: i am not using any of the --time-* switches at this time...

**Comment by gilbertohasnofb** [comment]
If the aircraft clock matches the local time in the sim, then there is no bug from our side. Daylight savings should be implemented in the sim side, not ours. @wkitty42 If you are interested in this feature, would you consider to bring it in the mailing list? I personally don't care much, but it would be much nicer if FG took care of daylight savings automatically.

**Comment by wkitty42** [comment]
@gilbertohasnofb agreed on the craft clock matching the sim local time... i will bring this up on the dev list for the sim side to handle it...

as for the report, i'm not sure if it is complete... i've read the topic on the forum and i'm not sure that what has been explained has been fully and clearly explained... it makes my head hurt every time i have to start coding or working with time stuffs ;)

**Comment by gilbertohasnofb** [comment]
@wkitty42 thanks for writing the devs!

> as for the report, i'm not sure if it is complete...

I am not sure either and I can't reproduce here, the clock shows what it's supposed to, i.e. _sim_ local time. Unless someone finds a way for me to reproduce this, then I don't really know what to do.

> it makes my head hurt every time i have to start coding or working with time stuffs ;) 

Same here. And if you have time and interest, check this out: https://www.youtube.com/watch?v=uW6QqcmCfm8

**Comment by gilbertohasnofb** [comment]
@wlbragg by the way, I like Thorsten's suggestion of letting the user adjust the clock. Would you be up to add some dial or button to the clock model so we can add a "user offset" property to the time?

**Comment by gilbertohasnofb** [comment]
Just one more thing: I am for keeping this issue closed (as it is now) unless one of us can reproduce the bug mentioned by the user.

**Comment by wlbragg** [comment]
>add some dial or button to the clock model so we can add a "user offset" property to the time

Yeah, maybe that is the best way to deal with this. OK on keeping it closed, if you want to start a new issue for adding a time set knob, that would be helpful.
