### ISSUE TITLE
rudder pedals moving opposite

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#752]
can someone check the code for this?
[https://forum.flightgear.org/viewtopic.php?p=284786#p284786](url)
DerryUL wrote:
>Just tried a flight in the Cessna and when viewing in the cockpit the rudder pedals move in the wrong sense.
>
When flying in real life if you want to turn left you move your left leg forward. Similarly to turn right you move your right leg forward.
>
The Cessna rudder pedals show the opposite ie to turn left you move your right leg forward.
>
I was using version 2016.1.1
>
Derry.

**Comment by gilbertohasnofb** [comment]
Confirmed. Nice catch.

I will try to fix it myself.
