### ISSUE TITLE
Prop mist while raining

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#762]
From the forum, see
https://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=285877#p285822

Consider spray from morning dew and on water in float or amphibious as well.

Posted from Android tablet.

**Comment by gilbertohasnofb** [comment]
That looks really cool! Love his first shot of the plane engulfed in mist, I'd love to see it from the cockpit! (since we should be able to see the "smoke" effect of the mist besides the water droplets, right?)

**Comment by wlbragg** [comment]
I thought so too, yes we should be able to see it from inside.

**Comment by wlbragg** [comment]
Note: https://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2595#p285942

Just in case anyone starts to work on this.
