### ISSUE TITLE
VOR patch

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#772]
David Megginson posted in the list:

> Some time over the past few weeks, the properties that the VOR indicators in the base package (shared by many aircraft) depend on disappeared from the next branch of FlightGear, so the needles no longer showed any deflection (for some reason, the problem didn't appear in the c172p -- maybe it has some special nasal code, or uses different instruments).  The attached patch makes them work again, at least for the pa28-161.

```
diff --git a/Aircraft/Instruments-3d/vor/vor.xml b/Aircraft/Instruments-3d/vor/vor.xml
index 7270f26..b2bfd3f 100644
--- a/Aircraft/Instruments-3d/vor/vor.xml
+++ b/Aircraft/Instruments-3d/vor/vor.xml
@@ -6,8 +6,8 @@
   <nav-to-flag>/instrumentation/nav[0]/to-flag</nav-to-flag>
   <nav-from-flag>/instrumentation/nav[0]/from-flag</nav-from-flag>
   <nav-radial-selected>/instrumentation/nav[0]/radials/selected-deg</nav-radial-selected>
-  <nav-gs-needle-deflection>/instrumentation/nav[0]/filtered-gsNAV0-deflection</nav-gs-needle-deflection>
-  <nav-heading-needle-deflection>/instrumentation/nav[0]/filtered-cdiNAV0-deflection</nav-heading-needle-deflection>
+  <nav-gs-needle-deflection>/instrumentation/nav[0]/gs-needle-deflection</nav-gs-needle-deflection>
+  <nav-heading-needle-deflection>/instrumentation/nav[0]/heading-needle-deflection</nav-heading-needle-deflection>
   <nav-in-range>/instrumentation/nav[0]/in-range</nav-in-range>
   <gs-in-range>/instrumentation/nav[0]/gs-in-range</gs-in-range>
  </params>
diff --git a/Aircraft/Instruments-3d/vor/vor2.xml b/Aircraft/Instruments-3d/vor/vor2.xml
index b1d39db..7bdad93 100644
--- a/Aircraft/Instruments-3d/vor/vor2.xml
+++ b/Aircraft/Instruments-3d/vor/vor2.xml
@@ -6,8 +6,8 @@
   <nav-to-flag>/instrumentation/nav[1]/to-flag</nav-to-flag>
   <nav-from-flag>/instrumentation/nav[1]/from-flag</nav-from-flag>
   <nav-radial-selected>/instrumentation/nav[1]/radials/selected-deg</nav-radial-selected>
-  <nav-gs-needle-deflection>/instrumentation/nav[1]/filtered-gsNAV1-deflection</nav-gs-needle-deflection>
-  <nav-heading-needle-deflection>/instrumentation/nav[1]/filtered-cdiNAV1-deflection</nav-heading-needle-deflection>
+  <nav-gs-needle-deflection>/instrumentation/nav[1]/gs-needle-deflection</nav-gs-needle-deflection>
+  <nav-heading-needle-deflection>/instrumentation/nav[1]/heading-needle-deflection</nav-heading-needle-deflection>
   <nav-in-range>/instrumentation/nav[1]/in-range</nav-in-range>
   <gs-in-range>/instrumentation/nav[1]/gs-in-range</gs-in-range>
  </params>
```

Indeed our VORs use the properties:

- `/instrumentation/nav[0]/filtered-gsNAV0-deflection`
- `/instrumentation/nav[0]/filtered-cdiNAV0-deflection` 
- `/instrumentation/nav[1]/filtered-gsNAV1-deflection`
- `/instrumentation/nav[1]/filtered-cdiNAV1-deflection` 

as opposed to his patched versions:

- `/instrumentation/nav[0]/gs-needle-deflection`
- `/instrumentation/nav[0]/heading-needle-deflection` 
- `/instrumentation/nav[1]/gs-needle-deflection`
- `/instrumentation/nav[1]/heading-needle-deflection` 

But I can't see any problems with our VORs (2016.1.1). Can anyone reproduce this issue? Would it be any beneficial if we also alter our `vor.xml` and `vor2.xml` files?

**Comment by wkitty42** [comment]
> But I can't see any problems with our VORs. Can anyone reproduce this issue?
> Would it be good if we also alter our |vor.xml| and |vor2.xml| files?


he said the c172p wasn't affected... plus i've searched the commit logs for 
fgdata and not found anything removing or changing those properties...

**Comment by gilbertohasnofb** [comment]
I understand that David wrote that the c172p wasn't affected. My point is that if his patch really fixes the VOR code in the base package, then it means those properties were the problem. And if they were the problem, then it begs the question on how on Earth our VORs are not being affected.

**Comment by wkitty42** [comment]
On 05/30/2016 05:44 AM, Gilberto Agostinho wrote:
> I understand that David wrote that the c172p wasn't affected. My point is
> that if his patch really fixes the VOR code in the base package, then it
> means those properties were the problem. And if they were the problem, then
> it begs the question on how on Earth our VORs are not being affected.

exactly :)

**Comment by gilbertohasnofb** [comment]
Aha, it looks like our `c172p/Systems/instruments.xml` contains a bunch of filters converting the correct properties into the ones that are supposedly causing problems in other aircraft. So maybe this instrument was broken when someone used pushed the VORs from the c172p (in the old times) from the c172p project without realizing that. So I think we are golden and we can close this.

**Comment by wkitty42** [comment]
that's possible... i saw, yesterday while digging about, two files named like c172p-vor1.xml... i don't recall what directory they were in, though...

perhaps the real fix is to either have our filters pushed over there or for us to switch to the new stuff? i don't know and don't have the knowledge to dig into the code for both and compare them with identical test values...
