### ISSUE TITLE
Indicated airspeed needle is not moving

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#774]
Reported on the c172p forum thread.
https://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=287039#p287025

I verified in our master that this is not working.

**Comment by gilbertohasnofb** [comment]
Duplicate, see: https://github.com/Juanvvc/c172p-detailed/issues/773

And I am about to push a PR fixing it

**Comment by gilbertohasnofb** [comment]
Please see https://github.com/Juanvvc/c172p-detailed/pull/775

**Comment by wlbragg** [comment]
:+1:
