### ISSUE TITLE
Key in ignition slot disappears while holding "s" key

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#777]
If you hold the "s" key to start the engine, the key in the ignition slot disappears.

**Comment by gilbertohasnofb** [comment]
Confirmed

**Comment by wkitty42** [comment]
confirmed over here, too... i saw it earlier when testing the start on the rwy at VI66 (13700ft)...

**Comment by wlbragg** [comment]
Wow, that is a regression, I remember fixing this before.
