### ISSUE TITLE
Tire smoke not behaving as originally programmed.

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#778]
Somewhere along the way the behavior of the tire smoke got changed. Originally I had it programmed (by consensus) to behave a very specific way.

The way it used to work had two different behaviors. One was touchdown smoke only when on the runway. I remember it used the fgdata built in tire smoke code which allowed for the tire smoke to only happen right at touchdown. The only other time we allowed tire smoke was "off road". For off road it was really considered dust and it only occurred after the wheel spin was greater than a certain speed.

As  it is programmed now we get tire smoke at a speed greater than X if on a surface type equal to or greater than 1.

Now, I don't really care that much how we decide to do this. I did it the way it was because we actually discussed it before hand and that was the consensus. So i everyone is happy with the way it is just close this issue and we can move on. I only noticed it because I am doing the J3Cub and was surprised to find it had changed. I got the code for the Cub from here.

**Comment by gilbertohasnofb** [comment]
> The way it used to work had two different behaviors. One was touchdown smoke only when on the runway. I remember it used the fgdata built in tire smoke code which allowed for the tire smoke to only happen right at touchdown. The only other time we allowed tire smoke was "off road". For off road it was really considered dust and it only occurred after the wheel spin was greater than a certain speed.

That sounds really reasonable to me. What is the problem with the current status, how is it different than what you wrote?

**Comment by wlbragg** [comment]
>As it is programmed now we get tire smoke at a speed greater than X if on a surface type equal to or greater than 1.

Versus how it was originally
Tire smoke on touchdown only (fast spin, I don't remember exactly). Just a puff. Constant "dust" on greater than 1 surface type at speeds exceeding 20 kts or so.

**Comment by gilbertohasnofb** [comment]
Ok, I think I get it. So isn't this simply the case of reverting to the behaviour your implemented? Are you able to find which commit changed it?

**Comment by wlbragg** [comment]
Unfortunately not that easy. This happened when @onox refactored from nasal to autopilot/fdm code. It will take a bit of effort to figure out exactly how to layout the touchdown portion, but the off road dust is a minor adjustment.

**Comment by wlbragg** [comment]
My mistake, after looking at this a little closer it is still behaving as before. I was operating on a dirt runway, thus I was getting dust at > xspeed. If I go to a paved airport you don't get any dust, only a puff of touchdown smoke upon landing fast and hard.

So I am closing this.
