### ISSUE TITLE
Avionics switch should not affect turn coordinator

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#79]
As reported by the user tigert in the forum thread, the avionics switch should not affect the turn coordinator nor any other gauge. It's sole function is to allow power to the radio stack and autopilot. The gauges are supplied by the master switch. See:

http://s18.postimg.org/n12yt1qk9/Screenshot_from_2015_03_13_17_33_45.png
http://s9.postimg.org/oj3mjft8v/Screenshot_from_2015_03_13_17_34_47.png

**Comment by onox** [comment]
What about the transponder?

**Comment by gilbertohasnofb** [comment]
Yes, the avionics switch controls the transponder indeed (see in the 1st image above, in the Avionics Bus -- bottom right -- we have the circuit breaker named Radio 4 connected to radio or transponder.
