### ISSUE TITLE
Taxi tutorial and secured aircraft

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#792]
An user in the forum was reporting that he/she was following the instructions in the Taxi tutorial but couldn't get the aircraft to move. It turns out his aircraft was secured. See: https://forum.flightgear.org/viewtopic.php?f=25&t=30025

The question is: shouldn't this tutorial cover the securing aircraft elements (chocks, tiedowns, etc.)? Or at least force them to be off? I remember we did some rework relatively recently to these securing elements, so maybe something broke in the tutorials?

**Comment by wkitty42** [comment]
yes, i think the tutorial should be adjusted to cover a secure craft or to force the secure stuff to be off... i suspect that it was simply missed when these were added...

**Comment by gilbertohasnofb** [comment]
@wkitty42 agreed.
@dg-505 do you think you could take a look at this when you have some time?

**Comment by dg-505** [comment]
I'll take a look. This shouldb't be a huge problem

**Comment by gilbertohasnofb** [comment]
:+1: thanks!

**Comment by dg-505** [comment]
PR #794 created.

**Comment by gilbertohasnofb** [comment]
Closed via #794

**Comment by gilbertohasnofb** [comment]
@wkitty42 when you have some time, could you please reply to that thread posting that the problem has been fixed in our repo, and so in the next release it will also be fixed?

**Comment by wkitty42** [comment]
sure... i gotta find it but yeah... i'll try to...

**Comment by gilbertohasnofb** [comment]
Thanks! And the link to the thread is on the first post in this conversation :wink:

**Comment by wkitty42** [comment]
why, so it is :)  posted...

**Comment by gilbertohasnofb** [comment]
:+1: Thanks!
