### ISSUE TITLE
ALS panel shadow

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#797]
@wlbragg the ALS panel shadow has been implemented on the c182, and some of the effects are really stunning. Are we using the same features? If not, we could think of implementing some of these. For instance, see these images:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/16901246/500abe10-4c3e-11e6-8940-7e1c05ef64bf.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/16901247/500ba492-4c3e-11e6-9f92-e3b2e66232f5.jpg)

Note how the shadows are still present at dusk, but the colour becomes softer and bluer. In real time the effect is really beautiful to see...

Now take a look at this:

![fg-2](https://cloud.githubusercontent.com/assets/5700795/16901266/c0887e52-4c3e-11e6-910b-f7d237f31bbc.jpg)

Just before when it's completely evening, there is still a tiny bit of light coming from the window.

It just feels to me that shadow is more detailed than ours.

![fg-3](https://cloud.githubusercontent.com/assets/5700795/16901272/d673cbb8-4c3e-11e6-91a2-7c8ecffb60fc.jpg)

**Comment by gilbertohasnofb** [comment]
@wlbragg would you care to take a spin on the c182 and take a look for yourself? It's difficult to describe these effects with words and still pictures

**Comment by wlbragg** [comment]
Sure, I'll take a closer look and see what if anything is different. I agree with you the c182 is stunning. You two have really put together a great model.

**Comment by wlbragg** [comment]
@gilbertohasnofb, I haven't looked at the maps or his code yet, but just looking at the effect in both crafts I'm not sure I am seeing that much difference. One thing is the color of the dashboard in the c182. Try comparing the shadow on the default c182 livery to the KLM livery in the c172.

I'll still compare the cube maps and code to see if there are noticeable differences.

**Comment by gilbertohasnofb** [comment]
@wlbragg  
> Try comparing the shadow on the default c182 livery to the KLM livery in the c172.

Oh, I see, there is basically no distinction in the effect! Sorry, I have been using the default livery for a while and the effect doesn't show well in the dark panel, but in the others it does. So I would say we can close this and label it as "invalid".

> I agree with you the c182 is stunning. You two have really put together a great model.

Thanks a lot, I really appreciate it (also thanks for the help over there!). What has been cool about working on the two projects is that new features in one makes it easier to implement in the other one and vice-versa.

**Comment by onox** [comment]
Is the effect a light map?

**Comment by gilbertohasnofb** [comment]
I think the panel lights are a light map, but I was talking about the natural light from the environment in the areas without shadow. But I realised that I was not seeing them because the dark panels do not show them very well (or at all).

**Comment by wlbragg** [comment]
>I think the panel lights are a light map,

I'm starting this on the Shuttle, do we have an open issue for panel light on this aircraft? Do we know where they are and what they light up? Now that I have a bit of a clue how a lightmap is created in Blender, I might try doing them for this project while I am in "lighting" mode! :smile:

**Comment by gilbertohasnofb** [comment]
@wlbragg take a look at the discussion here: https://github.com/Juanvvc/c172p-detailed/issues/438

**Comment by gilbertohasnofb** [comment]
I will close this since our panel shadow has no issues and we already have an issue for the lightmap
