### ISSUE TITLE
remapping livery texture

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#8]
3D06 - livery must be discussed. Maybe wing and tail in a single file with all sides (top, bottom, right and left).

  * Gilberto: why? And do you think you can fit wing (top and down), tail (left and right) and stabilizer (top and down) in a single file?!
  *fer: Why ?  : Because there is a waste of space in the tail file and in wing file.
        And you think... : Don't know, yet bro. Will see. 
  * Gilberto: ok, go for it, just careful not to lower too much the resolution (particularly of the tail since it usually has text, colours, etc)

**Comment by wlbragg** [comment]
Can we close this?

**Comment by gilbertohasnofb** [comment]
I guess so, given my last tests and optimization attempts, I don't think we would gain much performance by doing that and it would be a huge amount of work. I don't mind to leave it as it is.
