### ISSUE TITLE
Add a recharge battery button to aircraft menu

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#801]
Add a recharge battery button to aircraft menu. Take a look how this has been implemented in the ~~c182s~~ c150.

**Comment by HHS81** [comment]
you mean c150

**Comment by gilbertohasnofb** [comment]
Yes, my bad. Fixed it.

**Comment by gilbertohasnofb** [comment]
I will give this a shot today.

**Comment by onox** [comment]
Doesn't the battery get recharged when the user clicks the 'Repair' button?

**Comment by gilbertohasnofb** [comment]
Yes it does, but I think it's better to have a button only for the battery. I mean, I would never use the term "repair" to recharging a battery :smile: I actually already finished a huge work on this, I am creating a PR now so you can take a look
