### ISSUE TITLE
Replace splash1.png

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#809]
Since we created the splash screen `splash1.png`, our panel has changed a lot and that image is no longer representative of it. We need to create a new one.

**Comment by gilbertohasnofb** [comment]
I will just wait for the PR https://github.com/Juanvvc/c172p-detailed/pull/805 to be merged before doing it.

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg which one do you prefer?

![fg-0](https://cloud.githubusercontent.com/assets/5700795/17464024/c54dc388-5cd4-11e6-8665-b44b18a0baf5.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/17464025/c54edd7c-5cd4-11e6-920b-1755b9ae17d7.jpg)

The current splash1 shows the panel of the OH-CTL

**Comment by gilbertohasnofb** [comment]
I just updated the images above, it is nicer to show the shadows in the cockpit!

**Comment by wlbragg** [comment]
I like the top one.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
The new yokes make it look like a whole new aircraft.

**Comment by gilbertohasnofb** [comment]
I also prefer the top one, so I will go ahead and make the PR

> The new yokes make it look like a whole new aircraft.

Oh, you flatter me :blush:
