### ISSUE TITLE
apply vent tube texture to 3D object

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#83]
The vent tube textures are located in the panel_parts texture file. It should be wrapped around this object in the top left of the panel: http://s18.postimg.org/jgh3t8hgp/fgfs_screen_002.png

The opening (black rectangle) should point down like this: http://www.cruik.org/blog/ventubes/ventube-out.jpg

related to: https://github.com/Juanvvc/c172p-detailed/issues/23

**Comment by Juanvvc** [comment]
While checking this, I noticed the tubes already have a hole in them! I rotated the tubes to have the holes oriented toward the pilot and copilot's faces. Surfaces are now textured.

**Comment by gilbertohasnofb** [comment]
> I noticed the tubes already have a hole in them!

Great! That will surely look better than a simple black rectangle :)
