### ISSUE TITLE
Use ladders in the pre-flight check tutorial

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#830]
We now have static objects, including ladders, which can be activated in the Ground Equipment dialog. This ladder can be climber by the walker, making it easier to click on the fuel tank caps to add/remove fuel. This could be added to the pre-flight check tutorial.

**Comment by gilbertohasnofb** [comment]
@dg-505 would you like to implement this?

**Comment by dg-505** [comment]
I really *would like* to, just like the C182S tutorials which you mentioned, but at the moment I have no real chance to use FG (or any other sim, game, ...) due to some serious problems with my laptop...

I'm sorry:disappointed:

**Comment by gilbertohasnofb** [comment]
@dg-505 I am sorry to hear about your laptop :crying_cat_face: but look, there is no rush, even if it takes a long time. If this issue will be opened then we would welcome a fix :smile:

**Comment by dg-505** [comment]
Well, I suspect it will result in needing a complete new computer... And that isn't an easy choice.

**Comment by gilbertohasnofb** [comment]
Really? Oh man, that sucks :sob: Good luck over there, and let us know when you are back with FG running!

**Comment by dg-505** [comment]
Thanks :sunglasses: I will let you know :smile:

**Comment by gilbertohasnofb** [comment]
Joined into https://github.com/Juanvvc/c172p-detailed/issues/830
