### ISSUE TITLE
Delay luggage dialog binding

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#833]
Delay the luggage dialog which is automatically opened when clicking on the luggage door, so that the door fully opens before the dialog is presented to the user.

---

Original post:

> Question: is it possible to delay a binding for a pick animation? What I wanted to do is to delay the baggage dialog to open only 1 second after the baggage door has been opened, so that the user could see the animation (right now the dialog pops in the middle of the screen instantaneously). Does anyone know if this is possible? I tried searching on the wiki and forum but I came up with nothing :cry:

**Comment by wkitty42** [comment]
On 08/15/2016 06:34 AM, Gilberto Agostinho wrote:
> Question: is it possible to delay a binding for a pick animation? What I
> wanted to do is to delay the baggage dialog to open only 1 second after the
> baggage door has been opened, so that the user could see the animation (right
> now the dialog pops in the middle of the screen instantaneously). Does anyone
> know if this is possible? I tried searching on the wiki and forum but I came
> up with nothing 😢

wouldn't you use maketimer to open the dialog after the timer runs out?

**Comment by gilbertohasnofb** [comment]
You are right, I could use a `<script>` block in the xml and use Nasal for that, but I was still wondering if there was not a way of doing it without Nasal. Maybe there is an xml solution to this, and if not maybe it would be interesting to ask this features to the devs, as it may have some more uses as well.

**Comment by onox** [comment]
`maketimer()` runs repeatedly, unless you`singleShot` to true. See http://wiki.flightgear.org/Nasal_library#maketimer.28.29

**Comment by wkitty42** [comment]
@gilbertohasnofb yeah, sorry... i forgot that maketimer is nasal stuff... i'm not currently aware of any other way to have some sort of timer, though... but even after 1.5years, i'm still a newbie to fgfs ;)

**Comment by gilbertohasnofb** [comment]
Ok, thanks guys.

**Comment by gilbertohasnofb** [comment]
I updated this issue description, title, labels, etc.
