### ISSUE TITLE
Add fire extinguisher

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#834]
Currently our plane is flying illegally as we are missing the mandatory fire extinguisher! :scream: We could also maybe add a beacon locator to the plane if those are common to the 172. Below are the models from the c150:

![fg-1](https://cloud.githubusercontent.com/assets/5700795/17672747/32f6e226-631e-11e6-831c-4db07425fd60.jpg)

![fg-0](https://cloud.githubusercontent.com/assets/5700795/17672752/365998f0-631e-11e6-96be-1c691d9c271c.jpg)

I would be happy to tackle this myself, but I have two questions about it:

- the fire extinguisher is normally located in between the seats, as in the image below. But we use that space for the amphibian water rudder cord. So what's a better solution, to add the fire extinguisher elsewhere (maybe close to the co-pilot rudders as in the c150 image above) or should I add them in between the seats for all variants except the amphibian?
![](https://farm3.staticflickr.com/2635/4128320459_5a85b28c87_b.jpg)

- what about the beacon locator, is anyone familiar with that sort of equipment?

**Comment by gilbertohasnofb** [comment]
@Juanvvc @tigert maybe one of you is familiar with the questions I wrote above?

**Comment by wlbragg** [comment]
Would it fit attached to the seat back, on the side between the two.

**Comment by Juanvvc** [comment]
> @Juanvvc @tigert maybe one of you is familiar with the questions I wrote above?

If I recall correctly, the fire extinguisher in my c172 was under the pilot's seat, but it was a very long time ago!

Regarding the ELT/distress beacon, it was in the luggage compartment with a simple switch somewhere in the panel to switch it on and off. It has to be always on and there is no reason to switch it off, even if the aircraft is parked.

**Comment by gilbertohasnofb** [comment]
@Juanvvc Thanks for the info! 

So about the fire extinguisher, I suppose there is not a fixed place for it, since you had it at one place (under the pilot's seat), the the picture I posted above had it between the seats, and this picture below show it under the co-pilot's seat. So I will just see where it fits best and where it doesn't conflict with any variant.

![](http://southshore.com/~jaj/interior/Int03.jpg)

About the ELT, I have seen pictures of this model you speak about in which the main box of the ELT is hidden inside the luggage compartment and only the switch is visible outside, but I also found this image which shows a very similar model as the one from the c150:

![](http://2.bp.blogspot.com/-TR-MPHfWnhg/UYb_kwNmhNI/AAAAAAAAOGY/kQjl8LmvyxQ/s1600/image.jpg)

So to make things simpler, I think I will add it similarly to how it's done in the c150, the only difference being that I will add it to the opposite side as our baggage compartment door is on the left-hand side of the airplane.

I will be a quite busy until the end of the month, but I should take care of this as soon as I have some free time.

**Comment by gilbertohasnofb** [comment]
Hmm, I tried tackling this by myself but unfortunately the fire extinguisher and the beacon locator are part of the c150 main model file and are not external `.ac` files. Would anyone be willing to give me a hand to create two individual `.ac` files for them?

**Comment by wkitty42** [comment]
On 09/21/2016 11:11 AM, Gilberto Agostinho wrote:
> Hmm, I tried tackling this by myself but unfortunately the fire extinguisher and
> the beacon locator are part of the c150 main model file and are not external
> |.ac| files. Would anyone be willing to give me a hand to create two individual
> |.ac| files for them?

can you select them in that .ac file and export them as individual ones to use 
elsewhere? i don't know blender well enough to know if that can be done or not...

**Comment by gilbertohasnofb** [comment]
@wkitty42 That's the thing, I don't know Blender very well either. Also, those objects use texture files that include several other textures, so the UV-mapping should be redone. So this is why I am asking for some help.

**Comment by wlbragg** [comment]
I can help you. Where is the source you want separated?

**Comment by gilbertohasnofb** [comment]
It's the `.ac` model of the c150 which you can find at https://github.com/Harald67/c150/. I isolated the necessary textures for the fire extinguisher and for the beacon, you can find it here:

![fire-extenguisher](https://cloud.githubusercontent.com/assets/5700795/18720992/9787aa86-802e-11e6-8be9-d5ae6d4f6137.png)

Would you be able then to extract those two models from the `c150.ac` file, put them inside a same folder (let's say `extinguisher-and-beacon` or something like that), and UV map them to this texture above? Then I can take care of the positioning of them in the cockpit.

**Comment by gilbertohasnofb** [comment]
@wlbragg  Also, please create a `bug-834` branch and work on it, so that I can pick up from where you stop. Thank you so much for the hand! :smile:

**Comment by wlbragg** [comment]
Yes, I jumped the gun and grabbed the elt from fgaddon c150. I also pushed it to elt branch. I'll delete elt branch and follow your instructions, thanks for the details.

**Comment by gilbertohasnofb** [comment]
No problems, you can do it your way as well, just let me know how. It would only be good to have both the extinguisher and ELT in the same branch and same folder, as to use that same png above.

**Comment by wlbragg** [comment]
:+1:

**Comment by wlbragg** [comment]
Pushed to bug-834.  Let me know if you need anything else.

**Comment by gilbertohasnofb** [comment]
@wlbragg thank you so much, I will work on it today

**Comment by gilbertohasnofb** [comment]
@wlbragg there is a small problem, you kept  both the fire extinguisher and the ELT in the same `.ac` model. This way I can't position them freely in the cockpit :cry: Would it be too much trouble to break them down into two `.ac` files, but keeping them in that same folder and using just a single `.png` texture? So the directory would look like this:

```
Models/Interior/FE-ELT/fire.ac
Models/Interior/FE-ELT/fire-elt.png
Models/Interior/FE-ELT/elt.ac
```

Or something like that. What do you think?

**Comment by wlbragg** [comment]
:+1:

**Comment by wlbragg** [comment]
Pushed, I didn't re-position them, they are both in their original locations in the blend.

**Comment by gilbertohasnofb** [comment]
> Pushed

Great, thanks a lot! :smile_cat: 

> I didn't re-position them, they are both in their original locations in the blend.

No problems at all.
