### ISSUE TITLE
"Start with engine running" does not work: Nasal errors

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#838]
When I launch the simulator with "Start with engine running" **checked**, the engine is not running and I get Nasal errors (only when checked).

```
Nasal runtime error: non-objects have no members
 at /home/dany/FG/github/c172p/Nasal/electrical.nas, line 43
  called from: /home/dany/FG/github/c172p/Nasal/c172p.nas, line 12
  called from: /home/dany/FG/github/c172p/Nasal/c172p.nas, line 325
  called from: /home/dany/FG/github/c172p/Nasal/c172p.nas, line 573
  called from: /home/dany/fgfs/install/flightgear/fgdata/Nasal/globals.nas, line 119
```

I get this with the C172P embedded in the current FG 2016.4.0 Pack version and the C172P 95260d7 github version (both from10 sept 2016).

The "Autostart" works well.

**Comment by gilbertohasnofb** [comment]
I will take a look at this today, as I am probably the one that caused it :smile:

**Comment by gilbertohasnofb** [comment]
Bug confirmed, investigating the issue.

**Comment by onox** [comment]
I cannot reproduce this. Do I need to enable/disable certain settings besides "Start with engine running"?

**Comment by onox** [comment]
I can reproduce it now, was in wrong branch.
