### ISSUE TITLE
Improve pitot tube cover logic

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#840]
Given the number of issues we are having with people having a dead AIS and (I guess) no pitot tube cover on, I think we must rethink our code concerning it. If the serviceable property is ever set to `false`, then we must ensure that the pitot tube cover is on by any cost as to allow the user to diagnose the issue. 

Apparently the issues are happening when people install newer versions of our aircraft but keep the same data file.

See: https://forum.flightgear.org/viewtopic.php?f=4&t=30493

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg what you guys think?

**Comment by onox** [comment]
Where is the `serviceable` of the airspeed-indicator being set? Was this happening only in old code? I can only find `systems/asi/pitot-serviceable` being set in `Systems/indicated-airspeed.xml`.

So in other words: this purely a migration issue?

**Comment by onox** [comment]
Why doesn't FG delete the data files when it initializes itself? (it does seem to create a new preferences file when upgrading to a new version)

**Comment by gilbertohasnofb** [comment]
@onox my bad, I am closing this. I completely forgot we have already removed the `serviceable` from our new pitot tube cover code. Sorry about the confusion.

**Comment by onox** [comment]
No problem.
