### ISSUE TITLE
Pedal animation may be reversed

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#842]
See
https://forum.flightgear.org/viewtopic.php?f=4&t=30531
and
https://forum.flightgear.org/viewtopic.php?f=24&t=30467

**Comment by gilbertohasnofb** [comment]
When moving the rudder to the righthand side using the mouse (`Ctrl` + mouse to the right), I see:

- right pedal rudder moves forward, left moves backwards (for both the pilot and copilot seats)
- the nose wheel moves to the right
- the rudder surface moves to the left

As far as I know, this is all correct and how it should be. I also tested using the `0` key which should move the rudder to the left and everything was correct (i.e. opposite of what I described above).

The user apparently sees the same thing, but then adds:

> However, the left GUI-pedal moves back, and the right moves to the front. Which is not the way, a real aircraft works.
> The same behavior is observed when using e.g. CH-rudder pedals.

What is this GUI-pedal? Is it some FG feature I am not aware of?

**Comment by wlbragg** [comment]
I assumed it was the physical pedal in the aircraft.
I didn't test it myself until just now and I am in agreement with you, there is no issue unless the right pedal is supposed to move forward when you yaw or roll left.

**Comment by wlbragg** [comment]
>However, the left GUI-pedal moves back, and the right moves to the front. Which is not the way, a real aircraft works.
The same behavior is observed when using e.g. CH-rudder pedals.

They are saying that the right pedal should move forward when rudder to left.

**Comment by wlbragg** [comment]
An extremely quick search shows this
![rudped](https://cloud.githubusercontent.com/assets/11069680/18848427/f129e036-83f3-11e6-9775-3191967e26e9.png)

**Comment by gilbertohasnofb** [comment]
Ok, so some issues here: first, if the user means the 3D rudder pedals when writing GUI-rudders then there is some confusion, as GUI stands for graphic user interface is used for referring to dialogs, menus, etc., so that's why I didn't understand him/her. If that's the case, then it's all clear now.

> They are saying that the right pedal should move forward when rudder to left.

This is incorrect and our plane's behaviour is correct. Right rudder means pushing the right pedal forwards which yaws the aircraft to the right by moving the rudder surface to the right at the same time as pointing the wheel to the right. 

This is what your image above correctly shows: the pedal in the direction of the turn is moved forwards.

**Comment by gilbertohasnofb** [comment]
Sorry, but re-reading the user post he indeed has a problem, but I can't reproduce it here. See:

> E.g. pressing the "0"-key yaws a Cessna 172p to the left, also the rudder moves to the left, which is correct. The front wheel moves correctly.
> However, the left GUI-pedal moves back, and the right moves to the front. Which is not the way, a real aircraft works.

For me, the left pedal moves _forwards_ as expected when pressing '0'. So there is something wrong with his installation I believe...

**Comment by gilbertohasnofb** [comment]
Or: on the 10th of May I fixed this issue here https://github.com/Juanvvc/c172p-detailed/issues/752 and according to the dates the bug was fixed before 2016.2. So if the user is using 2016.1 or earlier, then the bug is still there, but the solution is simply to upgrade FG or download the newest version of our aircraft.

Could you please confirm it with the user if that's the case so we can close this and label it as invalid?

**Comment by wlbragg** [comment]
No, re-read.
>However, the left GUI-pedal moves back, and the right moves to the front. Which is not the way, a real aircraft works.

That is the correct behavior!

**Comment by wkitty42** [comment]
On 09/26/2016 03:40 PM, Gilberto Agostinho wrote:
> Or: on the 10th of May I fixed this issue here #752
> <https://github.com/Juanvvc/c172p-detailed/issues/752> and according to the
> dates the bug was fixed before 2016.2. So if the user is using 2016.1 or
> earlier, then the bug is still there, but the solution is simply to upgrade FG
> or download the newest version of our aircraft.

i remember this being fixed... my reading of the OPs forum post is that if the 
right pedal goes forward, the left one should go back the same amount... if the 
left one goes forward, the right one should go back the same amount... in other 
words, they are connected like a pushme-pullyou... i haven't looked at the 
pedals in the sim, though... i'm too busy flying to be looking at them ;)

**Comment by wlbragg** [comment]
> like a pushme-pullyou... 

They do!

**Comment by wlbragg** [comment]
Oops, I think I see it now,

>left GUI-pedal moves back, and the right moves to the front. 

Left moves back (as in closer to the pilot) not back as in towards the nose of the aircraft.

Yes, I think they have an old version. I'll pass it on.

**Comment by gilbertohasnofb** [comment]
> Oops, I think I see it now,
> Left moves back (as in closer to the pilot) not back as in towards the nose of the aircraft.

:+1: 

I think it's all clear then:

- the user is indeed seeing a problem
- our plane seems to be fine (i.e. we can't reproduce the report)
- the theory is that the user either has an older version of our plane/FG or (very unlikely) there is something else causing the issue

**Comment by wlbragg** [comment]
Determined to be an old version that was not yet updated.

**Comment by gilbertohasnofb** [comment]
:+1:
