### ISSUE TITLE
Possible incorrect extra weight for 180hp engine

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#845]
Where did this value come from, and is the extra weight added for the 180 hp or the total weight of the 180hp?

~~~xml
 <switch name="extra-weight-180hp">
            <default value="0"/>
            <test logic="AND" value="142">
                /controls/engines/active-engine EQ 1
            </test>
            <output>/fdm/jsbsim/inertia/pointmass-weight-lbs[15]</output>
        </switch>
~~~

Everything I have been reading points to approx 30 lb of extra weight between the two, 150 - 180?

**Comment by wlbragg** [comment]
Lycolm
Lycoming O-360 = 258lb
Lycoming O-320 = 244 lb
Continental IO-360 = 294 lb

Lycoming O-320 to a Continental IO-360 = 294 - 244 = 50lb at best?

**Comment by dany93** [comment]
> Where did this value come from, and is the extra weight added for the 180 hp or the total weight of the 180hp?

It comes from the weight difference between 180 hp and 160hp **aircraft** empty weight.
Not from the engines.
Refs:
Cessna 172P Skyhawk 160hp (1982 POH)
Cessna 172S 552SP POH 180hp (8 july 1998

**c172p.xml FDM file** line 59
`        <emptywt unit="LBS"> 1500 </emptywt>`
(I don't know or don't remember where it comes from, I think it was in the original FDM)
1467 lb may have been better, I read this p. 6-10 (112/357 pdf) of the 160 hp POH.
Anyway, **1500 lb** in the FDM file for the empty weight.

**180 hp, 552SP POH** p. 6-12 (156/384) : basic Empty Weight **1642 lbs**

1642-1500=142 lbs

**Comment by wlbragg** [comment]
OK, thanks!

**Comment by onox** [comment]
See https://github.com/Juanvvc/c172p-detailed/issues/273#issuecomment-113833227.

**Comment by onox** [comment]
> From 552SP POH p. 1-7 (23/384): empty weight 1663 lbs, or p. 6-12 (156/384) 1642 lbs, which would add about 163 or 142 lbs.
