### ISSUE TITLE
Improve stall horn sound

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#85]
improve stall horn sound, use this as reference: https://www.youtube.com/watch?v=4tLWIvnVnCQ#t=42

**Comment by gilbertohasnofb** [comment]
Ok, done on my last commit. Now I just need some help to apply this sound to our plane (I couldn't make it work so far, sorry). The sound is located inside a subfolder named Sounds. I also had to create a Thanks file to comply with the CC license of the youtube video which was the source.

So could anyone please give me a hand with the xml file? Right now it seems to be redirecting all sounds from fgdata and I don't know how to make the path relative to our plane.

**Comment by onox** [comment]
The youtube video doesn't have a CC license?

**Comment by onox** [comment]
Ah, the Thanks file says https://www.youtube.com/watch?v=zTq8Jvoks2U

**Comment by onox** [comment]
I would just add this to the README.md file.

**Comment by gilbertohasnofb** [comment]
Don't you think it's better to have a separate Thanks file just like fgdata does? Actually, once this plane gets incorporated into fgdata, our Thanks can merge together.

**Comment by onox** [comment]
Ok. I can help with the xml

**Comment by gilbertohasnofb** [comment]
Thanks, onox!

**Comment by onox** [comment]
I see the file is stereo. If you want to have it come from a certain position in the cockpit then you should make it mono.

**Comment by gilbertohasnofb** [comment]
Absolutely, my bad. Completely forgot about it. Give me a minute to fix this.

**Comment by onox** [comment]
Do you want to make it a looped sound? (like how an engine sound is looped for example)

**Comment by onox** [comment]
Then you can control pitch and volume and loop the stall sound continuously.

**Comment by onox** [comment]
Btw, you can leave the current sound as it is, so that it can be modified in the future (treat it as a blend/xcf file).

**Comment by gilbertohasnofb** [comment]
Ok, converted it to mono. Yes, please let it be looped. As for pitch and volume, I don't think they need to be changed, just loop this file and that should be enough.

> Btw, you can leave the current sound as it is (treat it as a blend/xcf file).

What do you mean leave it as it is?

**Comment by onox** [comment]
That you leave the stereo file in the repository. Perhaps someone wants to use the stereo version for something else in the future. I'm quite astonished how you managed to extract this from that youtube video :astonished:

**Comment by gilbertohasnofb** [comment]
Thanks for the compliment :) As for keeping it stereo, it may not be a good idea because sound files can become quite large. I probably can upload the stereo version to the livery repository though

**Comment by onox** [comment]
Btw, with looped I mean you take the part between 2.7 seconds and 6.2 seconds.

**Comment by onox** [comment]
Loop it in Audacity and you shouldn't hear any repeats.

**Comment by gilbertohasnofb** [comment]
I understand, but I think it would sound more realistic if the file simply loops itself. I checked several videos and normally the stall warning will not sound constantly for a long period of time, it always has little interruptions (even when holding the yoke back), so I guess the effect is more realistic.

**Comment by onox** [comment]
I think you should also add a finish/stop sound. So you have:

1. A sound that can be looped continuously

2. A very small sound that you can play once when you stop playing the looped sound.

**Comment by onox** [comment]
Otherwise, when you stop playing the looped sound, the stall horn stops abruptly, which sounds weird.

**Comment by onox** [comment]
> I checked several videos and normally the stall warning will not sound constantly for a long period of time, it always has little interruptions (even when holding the yoke back), so I guess the effect is more realistic.

Ok.

**Comment by onox** [comment]
But then you will always here the sound for the full duration.

**Comment by onox** [comment]
Can you create a screenshot and mark the position of the speaker?

**Comment by gilbertohasnofb** [comment]
Hmm, that's a bit tricky: that would work well for a constant looped sound, but as I wrote a realistic stall horn will have some short breaks. Can't we simply play the file until the end? Even if the plane isn't stalling anymore, the file will just continue for a second or two and then naturally finish? Or maybe simply fade out in the sim? Trying to glue an end sound to it won't work IMO.

As for the placement, I don't know where it is. Does it come from the speaker overhead or do we listen to the horn directly from the left wing?

**Comment by gilbertohasnofb** [comment]
For now we can simply place the virtual sound coming from the speaker on the top panel and then we see with @Juanvvc or @tigert

**Comment by onox** [comment]
> Trying to glue an end sound to it won't work IMO.

It will if the stop position in Audacity of the looped sound is the same as the start position of the finish/end sound :smile:

**Comment by gilbertohasnofb** [comment]
No, that is not what I mean. I know how to loop a sound. What I mean is that simply stopping sound a.wav at any position and then playing a sound b.wav and expecting that a and b fit together is not going to work (it very likely will be noticible).

**Comment by onox** [comment]
Ok, maybe the stall sound is not as monotonic as the sound of a gattling gun :wink: I have changed the path to the sound, but I still need to fix the position of the horn.

Do you mean with the "top panel" the position near the compass, or above the pilot's head?

**Comment by gilbertohasnofb** [comment]
Thanks onox! And I meant above the pilot's head. You will find a loudspeaker there :)

**Comment by onox** [comment]
Argh, never seen that before :stuck_out_tongue_closed_eyes: Is the speak that dark grey box?

**Comment by onox** [comment]
Or one of the 3 light grey circles?

**Comment by gilbertohasnofb** [comment]
The dark grey box

**Comment by onox** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
Thank you so much for the help!

**Comment by onox** [comment]
Do you know an `.ac` file that is very small?

**Comment by gilbertohasnofb** [comment]
I think we have tons of small `.ac` files in our project. I found 15 of them under 10 kb. What do you mean exactly?

**Comment by onox** [comment]
Or you could just give me the x,y,z coords of that dray grey box.

**Comment by onox** [comment]
That would be the most easiest :smile:

**Comment by onox** [comment]
x is fore/aft (positive aft)
y is left/right (positive left)
z is up/down (positive up)

**Comment by gilbertohasnofb** [comment]
Ah onox, I don't know how to use blender to find this information! I tried opening the model on it but that program is just too complex for me... if you can't find it by yourself let's then leave the sound at the origin (0,0,0) and wait for someone who knows his way on Blender to help us.

**Comment by onox** [comment]
Can you instead give me a very small .ac file? (I mean that the object is very small)

**Comment by gilbertohasnofb** [comment]
Onox, I never dealt with ac files before and I really don't know how to create them :cry: You are dealing with a complete 3D-ignorant person here.

**Comment by onox** [comment]
I have already a good position. Just need to damp the volume if not internal and doors are closed.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
Fixed! If you can hear the sound well, try to open the door and switch to helicopter view, then you should be able to hear it very softly.

**Comment by gilbertohasnofb** [comment]
Thanks onox, I will give it a try now. And when you have a chance, could you please check https://github.com/Juanvvc/c172p-detailed/issues/117 and https://github.com/Juanvvc/c172p-detailed/issues/238 ? Both should be easy to fix given what you have been doing for this stall sound. Let me know if I can help with anything.

**Comment by wkitty42** [comment]
wow! you guys have been busy on this issue :)  i just wanted to say that there was recent work concerning stereo sound files in the core with fgaddon... basically it comes down to stereo can't be played buy the sounds system... everything should be mono and if you want sound from or more sides, each has to be separate and positioned as needed... the 3D (IIRC) system will then take the mono sounds and blend them as needed for dispersion in the 3D space...

**Comment by onox** [comment]
Yes, that's why @gilbertohasnofb has converted it to mono.

**Comment by wkitty42** [comment]
excellent... the core devs are or were working on fixing all the craft in fgaddon for the problem with stereo files... i learned about it from reading the dev list else i might have made the same mistake... i just wanted to pass on the info as i had learned it ;)

**Comment by gilbertohasnofb** [comment]
@onox @Juanvvc @dany93 @wkitty42 Let's continue that discussion about the stall sound here, as it's by far the most appropriate place. So in the end I believe we decide to go with the synthesized sound route, correct? In forum, Erik has posted several versions of his sounds and then I also posted a synthesized version of mine as well. My sound is based on spectrum analysis of our previous sound (I looked for the strongest nine or ten overtones of the sound and recreate them using oscillators), and so it sounds much closer to what we had in my opinion. You can hear it here: 
https://www.dropbox.com/s/ktk43ldgtzbdunl/stall.wav?dl=0

What do you think? In the forum I had some positive feedback about it (and I personally believe its closer to the real sound than Erik's), but I think most of you might have missed it given the amount of discussion going on there in the past 24 hours. Let me know what you want me to do, if I should exchange our older sound for this one on the master or if you prefer Erik's version. Either way is fine with me.

**Comment by gilbertohasnofb** [comment]
(as a reference, listen to this stall horn at 0:35 of this video. This is the sound I analysed for that synthesis: https://www.youtube.com/watch?v=zTq8Jvoks2U )

**Comment by onox** [comment]
@gilbertohasnofb Yours sound a little bit better, but both sound artificial. If we decide to use this, then we need to make sure we can accurately adjust the volume and pitch during a stall, so that it will sound like a screaming kitty :crying_cat_face: just like in those YouTube video's.

**Comment by onox** [comment]
Please create a branch bug-85 and a PR in that case.

**Comment by gilbertohasnofb** [comment]
> both sound artificial

I agree completely, but that's the route that was decided. So now it's up to the magicians/programmers among us to implement this in a realistic way. I can of course cater to what is needed (e.g., I can create other variations of the stall sound, or a version that is cracking instead of constant, etc.).

> Please create a branch bug-85 and a PR in that case.

Okay, I can do that, but from my part this will be only an upload of a wav file, nothing more. I really can't program in Nasal.

**Comment by onox** [comment]
> Okay, I can do that, but from my part this will be only an upload of a wav file, nothing more. I really can't program in Nasal.

That's ok. As long as it's in a separate branch.

**Comment by gilbertohasnofb** [comment]
Okay, I will do that! Could you please tell me how to create a branch on my local repository?

**Comment by onox** [comment]
1. Check you're in master: `git branch`

2. `git pull`

3. `git branch -b bug-85`

4. Add the .wav file

**Comment by onox** [comment]
The third should use "checkout", not "branch". I've modified my comment.

**Comment by gilbertohasnofb** [comment]
Okay, I did that all, then added, committed and pushed it, but I can't see the branch `bug-85` on our repository using the GitHub webpage.

And by the way, the option `-b` on `git checkout` means what? Does it create a new branch in case it doesn't exist?

**Comment by onox** [comment]
-b means you create the branch and then do a checkout. `git pull` gives me nothing. Can you do `git branch` and tell me what you see?

**Comment by gilbertohasnofb** [comment]
I see:

	andgi-add-water-sounds
		bug-238
		bug-80
	* bug-85
		master

I was reading that I may need to push using `git push -A -u` instead of `git push -A`. Does that make sense to you?

**Comment by onox** [comment]
You need to do: `git push -u origin bug-85`

**Comment by gilbertohasnofb** [comment]
Done.

**Comment by onox** [comment]
Ok, now I get it:

```
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/Juanvvc/c172p-detailed
 * [new branch]      bug-85     -> origin/bug-85
Already up-to-date.
```

**Comment by dany93** [comment]
@wkitty42 has written https://github.com/Juanvvc/c172p-detailed/issues/117#issuecomment-112890435
>the idea is to find the pressures at the two points on the wing related to the stall horn... point A at the front (where you suck on the stall horn to test it) where the air exits the stall horn and point B where the high pressure air enters the stall horn's air scoop to be directed through the reed or valve assembly...

>the idea is if we know the pressures at these two points, we can then calculate (or fake) the speed of the air through the reeds or valves... that speed will determine the pitch of the note..

>if we can get qbar(??) from the front edge of the wing and from the bottom of the wing where the pressure is higher when in a stall, this might work out...

In JSBSim, qbar-psf is the dynamic pressure ```1/2*ro*V^2```. General value, not the detailed values at different locations. I think that these detailed value are not available (I do not know everything from JSBSim, if you find them, please tell me).

Even assuming that you have these differences, 
> we can then calculate (or fake) the speed of the air through the reeds or valves... that speed will determine the pitch of the note..

How?

As I've written here https://github.com/Juanvvc/c172p-detailed/issues/117#issuecomment-112883955
@dany93 wrote
>I rather think you will have to use the AoA. It is the best indicator, admitted by everyone. By a non-linear relation if you prefer, you do all that you want.
Anyway, at best imagine you have the pressure (difference), you have to apply a law to transform it into a note. And you ignore the physical law. Non linear for sure.
The pitch and volume of the note are connected to the pressure by a law that you do not know, and the pressure is connected to the AoA, maybe to the velocity too. As the AoA is directly available, better to use the AoA. In any case you have to guess a law. You can add a velocity contribution if you wish, but with no better knowledge of the physical law. All of that is guess, or preferably comparison with IRL if someone can tell.

**Comment by onox** [comment]
@dany93 Let us say we have a function `f(AoA) = (volume, pitch)`. We'll define how this function works precisely later. First question is: do we need to add more input variables to this function `f`?

**Comment by dany93** [comment]
Not easy to answer because (as I wrote above) we do not know which parameters have an effect on volume and pitch. The velocity may have an effect on the pressure difference. A stall can happen in straight and levelled flight conditions (that is around 45 KIAS) or dynamically, during a steep turn with high roll angle (higher velocity). Also at high g due to a strong pitch up. I completely ignore the possible effect on the volume and pitch. I think you will have to guess something based on the observations and subjective memory of c172 pilots.
The first I would do is increasing pitch and volume with the AoA. Then (maybe) volume with the velocity. Purely guess.
Anyway, it can suffer some approximation with no important loss in realism....

**Comment by onox** [comment]
Currently the volume is controlled by `/sim/alarms/stall-warning` which is controlled in `src/FDM/JSBSim/models/FGAerodynamics.cpp` as follows:

```C++
161   if (alphaclmax != 0) {
162     if (in.Alpha > 0.85*alphaclmax) {
163       impending_stall = 10*(in.Alpha/alphaclmax - 0.85);
164     } else {
165       impending_stall = 0;
166     }
167   }
```

**Comment by dany93** [comment]
That is: volume proportional to AoA only, with a threshold at Alpha/alphaclmax = 0.85.
*(true ?)*

**Comment by onox** [comment]
So I think we could definitely write our own function that increases pitch when the AoA is in certain regions.

**Comment by onox** [comment]
What do you mean with volume?

**Comment by dany93** [comment]
If you want to include pitch, yes. "How to" remains to be seen.

The volume is the intensity of the sound, the power. Like the volume knob on an amplificator.
The pitch is the frequency, the note itself (A, B, ... G)

**Comment by onox** [comment]
I know.

**Comment by onox** [comment]
I think @wkitty42 posted some video somewhere that showed the different musical notes of the stall horn?

**Comment by onox** [comment]
@gilbertohasnofb Shall I update bug-85 to use a property which controls the pitch? You can then set this property to certain number (0.9, 1.0, 1.1, etc.) and give us a list of reasonable number.

**Comment by dany93** [comment]
At least gsagostinho  on the forum http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1995#p247508

**Comment by onox** [comment]
That's not the video I mean. It was a youtube link posted by @wkitty42

**Comment by onox** [comment]
This is the post I'm talking about: https://github.com/Juanvvc/c172p-detailed/issues/117#issuecomment-112844657 :smile

**Comment by onox** [comment]
Can someone compute the angles where the pitch changes from that video?

**Comment by gilbertohasnofb** [comment]
Hi guys, Erik uploaded another version of his stall sound on this address http://www.adalin.com/ehtw.info/html/images/stall.wav . I personally still feel my version is a bit better, it sounds a bit rougher and gritier and more annoying (as it's supposed to be IMO). I also think that spectral analysis and resynthesis is the way to go instead of trying to approximate the sound via saw tooth generators and adding effects (it gets much closer to the sound we want to imitate). Anyway, I leave it up to you to see which sound you prefer. If you like his sound better, then I can exchange it myself in the repository, okay? Just please let me know.

**Comment by onox** [comment]
@gilbertohasnofb I think yours sounds better.

**Comment by onox** [comment]
Can I chop off that commit from @wlbragg in master? It gives the regular pontoons front gear :confused:

**Comment by gilbertohasnofb** [comment]
@onox @dany93 Erik posted a code snippet of how this could be implemented in our forum thread. Could you please have a look on it?

**Comment by onox** [comment]
I have force pushed master and bug-85.

**Comment by onox** [comment]
@gilbertohasnofb I'll take a look at the code snippet.

**Comment by gilbertohasnofb** [comment]
@onox thanks!

**Comment by onox** [comment]
Can you still take a look at the video in https://github.com/Juanvvc/c172p-detailed/issues/117#issuecomment-112844657 and try to estimate the difference in angles?

**Comment by gilbertohasnofb** [comment]
Yes I can do that but only a bit later, right now I have to leave. I will try to do it by tonight, okay?

**Comment by onox** [comment]
Ok.

**Comment by dany93** [comment]
I'd say an angle difference of about 8 to 10 deg between the beginning and the end.

**Comment by onox** [comment]
But currently the horn starts at 13.63 and ends at 16.04.

**Comment by dany93** [comment]
I find that it does not end. I had it up to high values.
More than 20 - 22 deg at idle, 30 - 40 deg by climbing and cutting the throttle.
It has no reason to end.

**Comment by onox** [comment]
Yeah, sorry, you're right about that.

**Comment by onox** [comment]
`/sim/alarms/stall-warning` is 0.0 at 85 % of the alphalimit and 1.5 at 100 %.

**Comment by onox** [comment]
I'm writing two `<fcs_functions>`'s to control volume and pitch because I'm not too happy with the snippet posted by Erik.

**Comment by dany93** [comment]
For the code snippet, http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=2010#p247690
how do you understand it?
I read ```0.745 * log(alpha)```
Which would be a nonsense (alpha can take the value 0)
And where is the threshold?

**Comment by onox** [comment]
This is what I have currently:

```xml
 277    <volume>
 278     <property>/fdm/jsbsim/sounds/stall-horn-volume</property>
 279    </volume>
 280    <pitch>
 281     <property>/fdm/jsbsim/sounds/stall-horn-pitch</property>
 282     <offset>0.0</offset>
 283    </pitch>
```

**Comment by onox** [comment]
Using a pitch between 0.9 and 1.1.

**Comment by dany93** [comment]
What is wrong with the original code https://github.com/Juanvvc/c172p-detailed/issues/85#issuecomment-113135864?

**Comment by onox** [comment]
The volume is linear.

**Comment by dany93** [comment]
And something like 
```if alpha > alpha-theshold```
```log(k * alpha/alpha-threshold)```
?

**Comment by onox** [comment]
I'm trying this right: log((aero/alpha-deg - 13.63 + 0.5) * 2.0) for the volume.

**Comment by onox** [comment]
@dany93 I'll push a commit for you to test in a minute.

**Comment by onox** [comment]
Ok. See branch bug-85.

**Comment by onox** [comment]
@dany93 Note that currently the pitch is shifted linearly between 0.9 and 1.1. But in the video from https://github.com/Juanvvc/c172p-detailed/issues/117#issuecomment-112844657 there's a sudden increase in pitch, so we should use a `<table>` with `<tableData>`.

**Comment by dany93** [comment]
I have no sound. Is it normal?
I can only look at ```/sim/alarms/stall-warning = ```

**Comment by onox** [comment]
Did you get branch bug-85?

**Comment by dany93** [comment]
I did  git fetch upstream
then git checkout bug-85

**Comment by onox** [comment]
I have a fix.

**Comment by dany93** [comment]
What should I do to refresh my download?

**Comment by gilbertohasnofb** [comment]
@onox do you still need the angles from that video or the information @dany93 gave you is already enough? Let me know because I am back home now.

**Comment by onox** [comment]
@dany93 `git pull upstream bug-85`?

**Comment by onox** [comment]
@gilbertohasnofb That would be nice.

**Comment by gilbertohasnofb** [comment]
Okay, will do that!

**Comment by dany93** [comment]
@onox It seems good.
But I'm not a reference, I have never heard a stall warning apart from in FG....

**Comment by onox** [comment]
I have another commit that uses `<tableData>`.

**Comment by onox** [comment]
@gilbertohasnofb When you watch this video at 0:12 https://www.youtube.com/watch?feature=player_detailpage&v=CbtG8KHeMak#t=12 you'll hear the horn is growling a bit. Can you create such a second to a separate .wav file?

**Comment by onox** [comment]
And please pull latest bug-85, then you'll the see in the latest commit the `<tableData>` I'm using.

**Comment by gilbertohasnofb** [comment]
> Can you create such a second to a separate .wav file?

I will try!

**Comment by onox** [comment]
Hopefully that second sound can help the stall horn sound more organic, and less electronic.

**Comment by onox** [comment]
@tigert Is the location of the stall horn near the wind shield to the left of the pilot? I thought I read something like that lately here.

**Comment by gilbertohasnofb** [comment]
@onox have a look on the discussion about how the horn works in #117; the consensus is that it's a mechanical device on the wing, so the sound should come from the left

**Comment by onox** [comment]
I'll update the position of the stall horn.

**Comment by gilbertohasnofb** [comment]
I measured the angles in that video at three different positions when the sound pitch changes:

0:00 seconds - pitch 1 - 19.31 degrees
0:05 seconds - pitch 2 - 23.86 degrees
0:08 seconds - pitch 3 - 27.93 degrees

And now I will start working on that new sound you asked, onox.

**Comment by onox** [comment]
Hmm... not sure that we can handle a difference of about 8 degrees because of the stall near the alpha limit. This is what I currently have:

```xml
<table>
    <independentVar>aero/alpha-deg</independentVar>
    <tableData>
        13.6364    0.9
        15.0000    0.9
        15.0428    1.0
        16.0000    1.0
        16.0428    1.1
    </tableData>
</table>
```

**Comment by gilbertohasnofb** [comment]
@onox about the new sound, I didn't have the time to deal with it today, I'm so sorry. I hope I will have it by tomorrow, okay?

**Comment by wkitty42** [comment]
@dany93 
>> we can then calculate (or fake) the speed of the air through the reeds or valves... that speed
>> will determine the pitch of the note..
>
> How?

this was in response to my thoughts about having the air pressure values from two points on the wing... the idea is (was?) that one of those points would be the low pressure ""trigger"" area of the stall horn (ie: the leading wing edge where you suck to test the horn)... the other point would be the high pressure area of the stall horn.. that's the area where the air enters the horn assembly... once we have those two values, it should be a simply matter of subtracting them to get the ""strength"" of the difference in the two points...

in normal flight, these two numbers should be equal or very close to equal so their subtractive value would be very close to zero... have to see if we can find them and then gather the values... at a low stall AoA, these two numbers should be slightly larger then in normal flight... that will increase the value of subtracting them... as the stall gets worse and the AoA increases, the values will grow further apart which will increase their subtractive value... if we use this value, with a lower limit number, to indicate when a stall is starting, then the low value can be used to start the stall horn at a low pitch and volume... as the stall increases and the number grows larger due to the difference in air pressure between the two points, we increase the pitch of the sound as well as increasing the volume...

i'm imagining having only one sound file that sounds like a low pitch raspy gravelly kazoo sound... with the number increasing, we have the sound system playing the same sound but increasing the pitch which will make it higher in note and we also have the sound system increase the volume... we keep doing this up to an upper limit value where the sound is at its highest pitch tone and volume...

by the same token, as we recover from the stall, the air pressure differences between the two points gets smaller and smaller which would cause our sound to start reducing its tonal pitch and volume all the way back till we return to normal flight and the values are below our lower limit...

this is all based exactly on the descriptive texts i've read on how reed and valve stall horns work... in a stall the lower pressure on the front of the wing leading edge allows the air to enter through the stall horn scoop, pass through the reeds or valve, and exit at the leading edge of the wing... that's why you suck on the hole at the front of the wing... you create low pressure and the normal pressure just brings the air on through...

PS: sorry, too, if this is wordy... it has been a long day and we're just starting to see the end of the recovery after our modem was zapped in a storm at 0500 this morning... we weren't able to find a replacement and get it online until ~1500... these last four hours have been very hectic, trying and tiring... i do hope the above is clear enough in explanation... it would be good to be able to find these values or something like them... the sim knows when we're stalling so we may just have to find that/those value/values that it uses and work from there... i believe the idea is sound... it works in real life... the existing stall horns are proof of that :wink: :smile_cat:

**Comment by onox** [comment]
@wkitty42 The only information that JSBSim has is the current alpha and the alpha limit. See https://github.com/Juanvvc/c172p-detailed/issues/85#issuecomment-113135864

I've changed the computation of the volume to be less linear. You try it yourself by doing `git checkout bug-85`.

**Comment by onox** [comment]
@dany93 Could you take a look at the current code in branch bug-85 and give suggestions if things need to be improved?

**Comment by wkitty42** [comment]
YAY!! i found the numbers i was looking for! the ones we can use to vary the pitch of the stall horn as well as the volume... i found a commit log showing when "/sim/alarms/stall-warning" was changed from a boolean to a double but i can't find it again... anyway, that was one of the triggers for me to log the output from that property to see what it was and when... it is zero until we enter a stall state and then it fluctuates depending on the severity of our stall... *this is the number i've been trying to come up with!* i just need a kazoo sound and someone to show me how to do the pitch changes with the sound system so that i can feed the stall-warning value to the pitch modifier... then we'll have our stall horn like it acts IRL... once that's working, we only need to tweak it for accuracy but it'll be much better than trying to change sounds at different AoA or speeds and such :wink: :angel:

**Comment by onox** [comment]
And guess what `/sim/alarms/stall-warning` uses as input? AoA! See https://github.com/Juanvvc/c172p-detailed/issues/85#issuecomment-113135864

**Comment by wkitty42** [comment]
@onox i didn't understand that when i read it... the variable names didn't mean anything to me at that time... i thought AoA was only about the angle and not about stalling... you can have a high AoA without stalling, can't you? or, wait... AoA is along your direction of travel... hummm... ok...

in that comment above, you say that the volume is controlled by AoA... can we do the same with the pitch of the sound? are you already working on doing that or is it already available and i'm reinventing the wheel? admittedly i am learning some of the internals but the class has just barely been started :wink: :laughing:

**Comment by onox** [comment]
> i'm reinventing the wheel? admittedly i am learning some of the internals but the class has just barely been started

Yes, you're a bit reinventing the wheel. See branch [bug-85](https://github.com/Juanvvc/c172p-detailed/commits/bug-85).

**Comment by wkitty42** [comment]
i haven't played with that branch yet... not since i've been working on this for the last 4 days or so... i will try to take a look at it, though... one thing in my testing that i've found is that using that stall-warning value doesn't seem to be working as i had hoped it would... it seems to be too slow on the count... i mean, i'm at 300 feet with an airspeed of ~42 kts (indicated.. not sure about ground speed)  and a incline of ~13 degrees and before i start to hear the horn but i'm starting to fall out of the sky...

either way, i'm probably going to continue to work on this for my own satisfaction and learning...if you guys want it when i get it done, great... if not, oh well...

**Comment by dany93** [comment]
https://en.wikipedia.org/wiki/Angle_of_attack
https://www.youtube.com/watch?v=5wIq75_BzOQ

**Comment by onox** [comment]
@gilbertohasnofb Do you know if the core devs have made a final decision about (dis)allowing CC-BY sound files? (So we can have a loopable variant of the original stall sound)

**Comment by gilbertohasnofb** [comment]
No, they didn't.... I am also waiting for it, but that thread is just getting bigger and bigger everyday without anything being decided. But given that there seems to be no consensus there by any mean, my guess is that they will settle for not changing anything, meaning no CC-BY. I will update you all about it once that discussion is over.

**Comment by onox** [comment]
I'll ask then.

**Comment by onox** [comment]
@gilbertohasnofb I think we have a green light for a loopable variant of the original stall horn sound:

> So, my apologies for causing confusion, and in particular to the
c172p-detailed team.  I'll get their CC-BY sounds committed as
soon as possible,

> I'll also include this information (along with Edward's suggestion
of a link to the GNU compatible license page) in the next draft of the
Policy document.

> Best regards,

> -Stuart

**Comment by gilbertohasnofb** [comment]
@onox new looped stall sound already uploaded to branch bug-85! Same name as before: `stall2.wav`. I also removed the scratches layer from OH-CTL and ZS-MDF liveries and those have been uploaded directly to master. Hope that now everything is settle :smile:

**Comment by onox** [comment]
@gilbertohasnofb Can you update the `Thanks` file? Please copy, edit and use the file from the master branch.

**Comment by gilbertohasnofb** [comment]
@onox But the `Thanks` file at `bug-85` is the most recent one, I already updated it. It should overwrite the `Thanks` file automatically once we merge this branch.

**Comment by onox** [comment]
In master branch you have written for the parking brake and trim sounds: "which kindly allowed it to be used under under the CC0 license".

Should I use https://github.com/Juanvvc/c172p-detailed/blob/bug-85/Thanks or https://github.com/Juanvvc/c172p-detailed/blob/master/Thanks ? Because currently the two file are conflicting.

**Comment by gilbertohasnofb** [comment]
You are right, onox. In the end it doesn't really matter since we have been allowed to use CC-BY files, but I updated the file on the branches `bug-85` and `master` (so they shouldn't conflict any more) and I will paste those authorizations in the forum thread (something the devs recommended me to do).
