### ISSUE TITLE
Taxiing Tutorial - Engine not running

### ISSUE THREAD

**Issue by alwelsh** [Juanvvc/c172p-detailed#850]
When starting the taxiing tutorial the dialog says the engine is started and running.  However, it isn't and it will not start using the procedure learnt in the engine start tutorial - comes up with an "Engine Flooded" message.  As an alternative I tried the pre-positioned in the air option but again the engine was not running!

**Comment by onox** [comment]
Hi @alwelsh,

Thanks for the report. I have a few questions:

1. Which version of FG are you using exactly?
2. How did you start the taxiing tutorial? Did you just load FG and then immediately start the tutorial or did you try to start it while in/after another tutorial?
3. Could you make a screenshot of the "Aircraft Options" window (accessible via the Cessna 172P menu).

Currently I cannot reproduce your issue of the engine not starting in the beginning of the taxiing tutorial.

About your other issue: you need to prime the engine 3 to 6 times. More than 6 times will result in a "Flooded engine!" message.

**Comment by alwelsh** [comment]
Hi,

Thanks for the reply.  To answer your questions, I was using FG 2016.2.1 when I encountered the problem.  I started the taxiing tutorial after I had done the pre-flight and engine start ones.  However, following advice from the FG forum, I have now downloaded the 2016.3.1 version and the problem seems to have gone away!  I will limit my engine priming a bit and, hopefully, that will solve my other problem.

 

Many thanks for the response

 

Regards

 

Al Welsh

**Comment by gilbertohasnofb** [comment]
Glad to hear the problem has gone away!

**Comment by Astrinus** [comment]
I'm using 2018.2.2 version. In tutorials (start the engine, taxiing) the engine won't start (as in alwesh case), and even autostart fails, however it starts fine with very same procedure if not in tutorial mode.
Starting tutorials one after another or directly, with and without FG restarting, does not change anything.

**Comment by gilbertohasnofb** [comment]
@Astrinus I just tried loading the taxiing tutorial on FG 2018.2.2 and the engine starts as soon as the tutorial is loaded, so I am not sure what is the problem. I think we need more information to understand what is the problem on your side.

**Comment by Astrinus** [comment]
I don't know how or why, but after a couple of restarts it worked.
However, when doing the taxiing tutorial, it tells me that "the taxiway [which I should get to] has a darker ground color", but I am already on the darkest ground!
Going forward, at about half the taxiway, it starts telling me "you're doing curves", even if I go straight, till the end.

**Comment by legoboyvdlp** [comment]
Once 2018.3 is released, could you recheck with the tutorials which will be released with it? Thanks!

**Comment by Astrinus** [comment]
No more problems with 2018.3, although I had a hard way to complete the tutorial. I had to input coordinates from the tutorial XML in GMaps to understand where I should head to and I had to switch to Helicopter View since I could not see the taxiway from Cockpit View (the first three times I did the tutorial I followed the runway instead).

**Comment by legoboyvdlp** [comment]
Great!
