### ISSUE TITLE
add interior effects (cube map)

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#86]
I added what should be considered a test for now of the interior effect. The cube maps are rough and need to be redone. The layout and orientation of the six sides of the cube needs to be verified.

**Comment by wlbragg** [comment]
Final cub map has been added. Will leave issue open for now until we explore cube map per livery or choose generic grayscale for default cube map. As of now, cube map per livery is impractical.

**Comment by gilbertohasnofb** [comment]
I guess this has been more then tested now, right? Maybe we can close this.
