### ISSUE TITLE
Preflight control surfaces check

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#861]
I would like to implement control surfaces check for the preflight. My idea is quite simple: during the preflight, if one click on the ailerons, elevators and rudder they would move up and down a single time, as if the pilot is testing them. This is just eye candy of course, but it's quite a neat feature I have seen in other simulators. The question is how can this be done. I ran into two problems:

- the control surface properties cannot be overridden (e.g. `/surface-positions/elevator-pos-norm`). Is there another property I could use for this?
- how to smoothly change a property in Nasal? How can I make a property go from `0` to `1` in 2 seconds and back to `0` in another 2 seconds, then stop?

Does anyone have ideas or suggestions on how to tackle this?

**Comment by gilbertohasnofb** [comment]
See 1:05 for an example of what I am trying to do: https://www.youtube.com/watch?v=1OAwy-1ZlKo

**Comment by gilbertohasnofb** [comment]
Another option would be after the user clicks on a surface, the mouse controls it while the button is held. Maybe this is even less feasible than what I proposed above, I am just brainstorming here...

**Comment by dany93** [comment]
control/flight/aileron
control/flight/elevator
control/flight/rudder

**Comment by gilbertohasnofb** [comment]
Fantastic, Dany! The `interpolate` command works like a charm!

As for the `/control/flight/<surface>` properties, I am just thinking if a joystick would not override them during the interpolation, but I will test that.

**Comment by dany93** [comment]
`<time>` or `<rate>` in xml
property-interpolate

http://wiki.flightgear.org/Bindings

**Comment by dany93** [comment]
I think the joystick will be quiet if one do not move it.
The last one speaking wins.

**Comment by gilbertohasnofb** [comment]
:+1: thanks a lot!

**Comment by wkitty42** [comment]
On 11/14/2016 07:56 AM, Gilberto Agostinho wrote:
> I would like to implement control surfaces check for the preflight. My idea is
> quite simple: during the preflight, if one click on the ailerons, elevators and
> rudder they would move up and down a single time, as if the pilot is testing
> them. This is just eye candy of course, but it's quite a neat feature I have
> seen in other simulators.


why click on the control surface? why not just have the user wiggle their 
joystick, mouse or use the proper keys on the keyboard? just make sure they are 
in the outside view where they can see them move...

just 2 cents ;)

**Comment by gilbertohasnofb** [comment]
> why click on the control surface? why not just have the user wiggle their joystick, mouse or use the proper keys on the keyboard?

Because in RL you don't have access to the yoke while doing the preflight inspection and you have to literally force the control surfaces up and down with your bare hands. Look, what I am working on will not be obligatory in the sense that it won't punish the user for not doing it -- it's just eye candy as it actually won't do anything, it's just activating animations! -- but it will feel nice for those of us who care about simulating the preflight inspection, and will give you a reason to click on each control surface.

**Comment by dany93** [comment]
@gilbertohasnofb wrote
> Another option would be after the user clicks on a surface, the mouse controls it while the button is held.

Isn't it by the `slider` command, like c172p.xml in Models?
lines 2968 - 2983, 
```
    <animation>
        <type>slider</type>
        <object-name>Throttle</object-name>
        <object-name>ThrottleMount</object-name>
        <visible>true</visible>
        <drag-direction>vertical</drag-direction>
        <!-- no translation, we handle that seperately -->
        <action>
            <binding>
                <command>property-adjust</command>
                <property>/controls/engines/current-engine/throttle</property>
                <factor>0.05</factor>
                <min>0</min>
                <max>1</max>
                <wrap>0</wrap>
            </binding>
        </action>
```

**Comment by gilbertohasnofb** [comment]
@dany93 I decided to go through the route of just clicking for a brief automatic surface check, see:

https://youtu.be/ieVGiAv0ntI

(the video doesn't show my mouse clicking on the surfaces)

I will push a PR soon for testing, just checking some few things still

**Comment by gilbertohasnofb** [comment]
Also, in the video above, when I check the aileron surface you will notice that the front wheel moves, but this is only because I have only my mouse here and so I have auto coordination on, and so any aileron input == rudder input as well.

**Comment by wkitty42** [comment]
@gilbertohasnofb 
> Because in RL you don't have access to the yoke while doing the preflight inspection and you have to literally force the control surfaces up and down with your bare hands.

ohhhh!!! right... stupid me... i don't know what i was thinking of :laughing:

**Comment by gilbertohasnofb** [comment]
:smile_cat:
