### ISSUE TITLE
fix some face loops on the fuselage

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#9]
3D07 - fix some face loops on the fuselage.

**Comment by gilbertohasnofb** [comment]
Can we close this?

**Comment by onox** [comment]
What do you mean with "face loops"?

**Comment by gilbertohasnofb** [comment]
See my comments at #11. This also could be closed IMO.

**Comment by thevirtualfer** [comment]
It is a 3D modeller's nomenclature.

Is related how the faces connects one to other, making loops.

2015-06-16 8:05 GMT-03:00 onox <notifications@github.com>:
