### ISSUE TITLE
Turn coordinator's tube colour

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#91]
The turn coordinator's tube (where the ball moves) should be white, not black. There should be a solid white panel behind it in order for it to show properly. Compare our version...:
https://dl.dropboxusercontent.com/u/2730444/flightgear/devel/tc.png
...with the real thing:
http://www.pilotshop.rs/media/catalog/product/cache/1/image/1280x/040ec09b1e35df139433887a97daa66f/1/3/1394t100-7z.jpg

**Comment by Juanvvc** [comment]
Fixed
