### ISSUE TITLE
Test Dany93's new FDM and see how it compares to default one

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#93]
Test Dany93's new FDM and see how it compares to default one. Dany93's improvements include:

    - forward-slip bank angle (with drop of the higher wing at stall),
    - cross-wind landing (for 20 kt) with decrabbing (by crossing the commands),
    - slip-skid ball response (more sensitive).
    - (Stall and) Spin departure in a turn: more frank
    - Tables for lift and drag supplemented between 20 and 90 deg AoA (were only up to 20 deg)
    - Spiraling propwash effect added (thus, pulls leftwards instead of wrongly rightwards at acceleration to takeoff)

Possibly related to https://github.com/Juanvvc/c172p-detailed/issues/53

**Comment by gilbertohasnofb** [comment]
@dany93 now that you are part of the team, I guess we can close this issue, right? Also, was there any decisions about having a single FDM or are we going to stick to this 2 FDM solution?

**Comment by dany93** [comment]
I agree for closing this issue. Anyway, I think that nobody still reads it.
I've got too involved in this FDM to decide. All that I can do is to explain why it is done, and its differences.
Done here http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1320#p242233
Testing by yourself is the only way to make your mind. Even non-pilot's opinions are valuable, representative of most future users.
The question will inevitably reappear.

**Comment by onox** [comment]
I think we should have 1 FDM. If the contact points of dany93's FDM can be updated then we can go for that one.

**Comment by dany93** [comment]
I do not see why there could a difference in setting the contact points between "my" FDM and the original one.

**Comment by onox** [comment]
`TAIL_SKID`, `LEFT_TIP`, and `RIGHT_TIP` are commented in your FDM and have different values.

**Comment by wlbragg** [comment]
There should be no difference in contact points between the two. I must have forgot to update Dany's FDM. It should match master.

**Comment by wlbragg** [comment]
I agree, let's merge Dany's into master  Unless someone beats me to it, I'll update dany FDM contact points tonight..

**Comment by onox** [comment]
It seems `c172p.xml` also uses a `aero/function/total-wing-damage` property, while dany's FDM uses `wing/broken-both` and `wing/broken-one` versus `wing-damage/right-wing`. So you should take a look at that as well.

**Comment by dany93** [comment]
Where do you see these wing/broken-both, wing/broken-one in c172p-fdm-dany93.xml?
Normally those have been changed everywhere for the proper wing-damage/right-wing, wing-damage/left-wing and aero/function/total-wing-damage.

**Comment by onox** [comment]
@dany93 It's okay now, I was comparing an older version of your FDM :astonished: :smile: 

Btw, do you have some diff tool to compare the FDM's? If you don't have any, you could try [meld](http://meldmerge.org/).

**Comment by dany93** [comment]
I use meld.
Usually good.
It sometimes stumbles over the differences (I recently had this with physics.nas, where it refused to mark some blocks of lines as being similar).

**Comment by onox** [comment]
Fixed in PR #212
