### ISSUE TITLE
add text to panel textures about circuit breakers

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#95]
When circuit breakers are functional, add text to the panel textures writing which circuit breaker is which (see https://lh3.googleusercontent.com/-tye1M809eHU/UXyGmO9aa_I/AAAAAAAAAic/P5ixYmkM4s8/s640/blogger-image--449840105.jpg ).

**Comment by gilbertohasnofb** [comment]
Related to https://github.com/Juanvvc/c172p-detailed/issues/94 and https://github.com/Juanvvc/c172p-detailed/issues/80

**Comment by gilbertohasnofb** [comment]
@Juanvvc Just confirming, the layout of the 3D circuit breakers won't change any more, right? So can I start to hard code the text to all panels?

**Comment by Juanvvc** [comment]
I think no, it won't. Use the tool-tips to identify each breaker. Also, in my opinion, the best solution is if you provide a separated texture with only texts and a transparent background, as a decal to put on the panel.  Do not join this decal to any existing texture.

**Comment by gilbertohasnofb** [comment]
> Do not join this decal to any existing texture

Ok, I can do that, but won't that get a bit messy, since a lot of the other text (all switches, levers, etc.) is already in the panel?

**Comment by Juanvvc** [comment]
I can't decide.

PROS:
1) As suggested by Throsten in the forums, the right thing to do to enhance memory and performance is using a much smaller panel texture and moving details to specific textures. If we agree with this, the sooner we start producing decals, the better.
2) I (or any other contributor) can edit a decal, but only you can edit the panel texture because only you have the .xcf file

CONS:
1) We have currently two themes, dark and clear. They are both using white color for texts, but in the future each theme may prefer different colors for labels. Changing colors is much more difficult to manage if we use decals.
2) Managing decals is a bit of extra work for the manager of the .blend/.ac files.

**Comment by gilbertohasnofb** [comment]
If you'd like, I can push all my xcf files as well, that wouldn't be a problem, but currently I have around 500 MB of xcf and png files related to this project.

Creating smaller files will of course enhance performance, but creating liveries like this would be very annoying (not only for me but for other people in the future). E.g., I think it's easier to deal with a single panel png file than to edit dozens of them, one that has a single texture here, another that has another texture there. It's also more difficult to preview the final result. Lastly, if someone wants to create a decal where there isn't currently one (let's say a non-smoking symbol in the right panel), then with a single png that's trivial.

Anyway, it's up to you guys, but as I don't think our aircraft is having performance issues, I honestly don't see why should we go through this line.

> We have currently two themes, dark and clear
Actually, we have four themes: default, OH-CTL, ZS-MDF, PT-IAO, all of which have their own interior and panels. And I was working on a fourth theme of my own, which would need black text in the panel :(

So let me know what to do, I already have the text of the breakers prepared, it's just a matter of applying it to all panels vs creating a decal png. Here is how it looks: http://s8.postimg.org/74z29piv9/fgfs_screen_001.png

**Comment by Juanvvc** [comment]
It look fantastic, of course. If you has this already fixed, please, push it. We will think again next time!

**Comment by gilbertohasnofb** [comment]
Thanks! I have this applied only to the red/black panel, but give me 10 minutes and I will apply it for all other panels as well and then push it.

**Comment by gilbertohasnofb** [comment]
Ok, applied to all panels and pushed. The only thing that is not completely satisfying to me is that given the low resolution of the default panel the labels are not looking as good on it as they do in the other panels (OH-CTL, ZS-MDF and PT-IAO).

**Comment by onox** [comment]
@gilbertohasnofb Could you add those .xcf files to a different repository? The current repository is already close to 350 MB and more than doubling it would be a bit too much.

**Comment by gilbertohasnofb** [comment]
@onox I was thinking about doing the same. I will do it next time I am at my uni, and I will add the link to the description of this repo and in the thread as well. WARNING: my xcf files are a bit messy, particularly since I work on so many liveries at the same time. This means that one of them usually have very well structured layer groups for a certain feature (e.g., individual text for each breaker), while all others have a flattened version of this layer group.
