### ISSUE TITLE
Better texture for the Hobbs meter

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#97]
Better texture for the Hobbs meter

**Comment by gilbertohasnofb** [comment]
Hmm, I can't find any image with high enough resolution of a Hobbs meter on a 172 (the very high res images I have of a 172 cockpit do not show the Hobbs, and the meter in the images that show it is not very readable). The following image is from a 152, and I think the Hobbs meter should look fairly similar in a 172: http://s27.postimg.org/cexossp3n/hobbs.png

Any opinions on this, @Juanvvc, @onox and everyone else?

The main problem with our current texture is that it consists of a very low resolution and stretched photo. I can simply copy this original one, but I thought it would be better to have a real photo as reference. So should I base myself on this image of the 152 Hobbs above or should I base myself on the FG's default Hobbs texture? Or does anyone have a better image for me?

**Comment by Juanvvc** [comment]
The hobbs meter on "my" c172 was exactly the same than the one your photo shows.

It is sunken into the panel, and modeling this hole is something I'm not sure I'm going to be able to do.

**Comment by gilbertohasnofb** [comment]
Ok, do got now on I can at least make a texture that resembles this Hobbs meter, and later we see if we change the 3D model to have it sinken or not (thevirtualfer should be back online soonish).

**Comment by gilbertohasnofb** [comment]
It's done, see: http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=236113#p236113

Still not pushed to repository though, because it will require a rework of the 3D panel and I don't want to break everybody's Hobbs in the meantime (thus the issue it not closed yet, so I don't forget to upload it)

**Comment by Juanvvc** [comment]
The new hobbs meter is pushed
