### ISSUE TITLE
Remodel Hobbs meter

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#99]
In order to use the new texture created for issue https://github.com/Juanvvc/c172p-detailed/issues/97, a remodelling of the Hobbs meter is necessary. It should look like this: http://s27.postimg.org/cexossp3n/hobbs.png

But currently (with the new texture) it looks like this: http://s12.postimg.org/46ealhch9/fgfs_screen_002.png

**Comment by Juanvvc** [comment]
The new hobbs meter with the updated texture is pushed. Now, it counts hours, not minutes.
